  model = "gpt-5.4"
  model_provider = "patungin02"
  model_reasoning_effort = "low"

  [model_providers.patungin01]
  name = "Patungin01"
  base_url = "https://ai.patungin.id/v1"
  experimental_bearer_token = "patunginXuzSX3bbzETiDFOz"
  wire_api = "responses"

  [model_providers.patungin02]
  name = "Patungin02"
  base_url = "https://ai.patungin.id/v1"
  experimental_bearer_token = "patunginaULdOv23UT2cO16e7D7WZg"
  wire_api = "responses"

  [model_providers.patungin03]
  name = "Patungin03"
  base_url = "https://ai.patungin.id/v1"
  experimental_bearer_token = "patungin_zvGaZcJvdSdIzs48EInkw"
  wire_api = "responses"
