-- m0_report full queries containing prefix m3_
-- total rows: 107

-- RID=196 | MODULE=0 | MENU=0 | ITEM=1 | RQUERY=1 | NAME=Assembly | FILE=assembly
SELECT asd.urutan , sa.asnotransaksi , sa.astgl , sa.asuraian , asd.jml as jmldetail , asd.satuan as satuandetail, asd.hpp , asd.namabarang as namabarangdetail, asd.tipebarang as tipebarangdetail , b.bkode as kodedetail, bj.bsatuan as satuan, sa.asjmljadi , bj.bkode AS bk2 , bj.bnama AS bn2 , bj.btipe as bt2 , g.gnama FROM m3_as sa JOIN m3_as_detail asd on sa.asid = asd.idas JOIN m1_barang b on asd.idbarang = b.bid JOIN m1_barang bj on sa.asidbarangjadi = bj.bid LEFT JOIN m1_gudang g on sa.asgudang = g.gkode;

-- RID=24 | MODULE=3 | MENU=3 | ITEM=1 | RQUERY=1 | NAME=Daftar Permintaan Barang (MR) | FILE=listmaterialrequisition
SELECT mr.mrnotransaksi , mr.mrtgl , mr.mrtgldipakai, kd.knama AS mrdimintaoleh, km.knama AS mrmintake , wa.wnama AS mrgudangasal , wt.wnama AS mrgudangtujuan, mr.mruraian , st.nama AS mrstatus , b.bkode , mrd.namabarang , mrd.jml, mrd.satuan , mrd.catatan FROM m3_mr mr JOIN m1_contact kd ON mr.mrdimintaoleh = kd.kid JOIN m1_contact km ON mr.mrmintake = km.kid JOIN m1_warehouse wa ON mr.mrgudangasal = wa.wkode JOIN m1_warehouse wt ON mr.mrgudangtujuan = wt.wkode JOIN m0_status st on mr.mrstatus = st.kode join m3_mr_detail mrd ON mr.mrid = mrd.idmr JOIN m1_item b ON mrd.idbarang = b.bid ORDER BY mr.mrtgl , mr.mrid , mr.mrnotransaksi, mrd.urutan;

-- RID=25 | MODULE=3 | MENU=3 | ITEM=2 | RQUERY=1 | NAME=Permintaan Barang (MR) | FILE=materialrequisitiondetail_new
SELECT mr.mrnotransaksi , mr.mrtgl , mr.mrtgldipakai, kd.knama AS mrdimintaoleh, km.knama AS mrmintake , wa.wnama AS mrgudangasal , wt.wnama AS mrgudangtujuan, mr.mruraian , st.nama AS mrstatus , b.bkode , mrd.namabarang , mrd.jml, mrd.satuan , mrd.catatan FROM m3_mr mr JOIN m1_contact kd ON mr.mrdimintaoleh = kd.kid JOIN m1_contact km ON mr.mrmintake = km.kid JOIN m1_warehouse wa ON mr.mrgudangasal = wa.wkode JOIN m1_warehouse wt ON mr.mrgudangtujuan = wt.wkode JOIN m0_status st on mr.mrstatus = st.kode join m3_mr_detail mrd ON mr.mrid = mrd.idmr JOIN m1_item b ON mrd.idbarang = b.bid ORDER BY mr.mrtgl , mr.mrid , mr.mrnotransaksi, mrd.urutan;

-- RID=715 | MODULE=3 | MENU=3 | ITEM=3 | RQUERY=1 | NAME=Permintaan Barang (MR) | FILE=materialrequisitiondetail_new2
SELECT mr.mrnotransaksi , mr.mrtgl , mr.mrtgldipakai, kd.knama AS mrdimintaoleh, km.knama AS mrmintake , wa.wnama AS mrgudangasal , wt.wnama AS mrgudangtujuan, mr.mruraian , st.nama AS mrstatus , b.bkode , mrd.namabarang , mrd.jml, mrd.satuan , mrd.catatan FROM m3_mr mr JOIN m1_contact kd ON mr.mrdimintaoleh = kd.kid JOIN m1_contact km ON mr.mrmintake = km.kid JOIN m1_warehouse wa ON mr.mrgudangasal = wa.wkode JOIN m1_warehouse wt ON mr.mrgudangtujuan = wt.wkode JOIN m0_status st on mr.mrstatus = st.kode join m3_mr_detail mrd ON mr.mrid = mrd.idmr JOIN m1_item b ON mrd.idbarang = b.bid ORDER BY mr.mrtgl , mr.mrid , mr.mrnotransaksi, mrd.urutan;

-- RID=330 | MODULE=3 | MENU=3 | ITEM=4 | RQUERY=1 | NAME=Daftar Permintaan Barang (MR) Perproduk | FILE=listmaterialrequisition_Product
SELECT b.bid , b.bkode , mrd.namabarang , mr.mrnotransaksi , mr.mrtgl , mr.mrtgldipakai, kd.knama AS mrdimintaoleh , km.knama AS mrmintake , wa.wnama AS mrgudangasal , wt.wnama AS mrgudangtujuan , st.nama AS mrstatus , SUM(mrd.jml) as jml , mrd.satuan FROM m3_mr mr JOIN m1_contact kd ON mr.mrdimintaoleh = kd.kid JOIN m1_contact km ON mr.mrmintake = km.kid JOIN m1_warehouse wa ON mr.mrgudangasal = wa.wkode JOIN m1_warehouse wt ON mr.mrgudangtujuan = wt.wkode JOIN m0_status st on mr.mrstatus = st.kode join m3_mr_detail mrd ON mr.mrid = mrd.idmr JOIN m1_item b ON mrd.idbarang = b.bid GROUP BY mrd.idbarang , b.bid , b.bkode, mrd.namabarang , mrd.satuan , mrd.idmr ORDER BY mrd.idbarang , b.bid , b.bkode, mrd.namabarang;

-- RID=335 | MODULE=3 | MENU=3 | ITEM=5 | RQUERY=1 | NAME=Daftar Permintaan Barang (MR) Outstanding | FILE=listmaterialrequisitionoutstanding
SELECT mr.mrnotransaksi , mr.mrtgl , kd.knama AS mrdimintaoleh, wa.wnama AS mrgudangasal , wt.wnama AS mrgudangtujuan, mr.mruraian , b.bkode , mrd.namabarang , mrd.jml, mrd.satuan , (mrd.jmlrealisasi / mrd.nilaisatuan) AS jmlrealisasi , (mrd.jml - (mrd.jmlrealisasi / mrd.nilaisatuan)) as jmlsisa , mrd.catatan FROM m3_mr mr JOIN m1_contact kd ON mr.mrdimintaoleh = kd.kid JOIN m1_warehouse wa ON mr.mrgudangasal = wa.wkode JOIN m1_warehouse wt ON mr.mrgudangtujuan = wt.wkode join m3_mr_detail mrd ON mr.mrid = mrd.idmr JOIN m1_item b ON mrd.idbarang = b.bid ORDER BY mr.mrtgl , mr.mrid , mr.mrnotransaksi, mrd.urutan;

-- RID=337 | MODULE=3 | MENU=3 | ITEM=6 | RQUERY=1 | NAME=Daftar Permintaan Barang (MR) Outstanding Sisa | FILE=listmaterialrequisitionoutstandingsisa
SELECT mr.mrnotransaksi, mr.mrtgl, mr.mruraian, ga.wnama AS gudangasal, gt.wnama AS gudangtujuan, b.bkode, (CASE mr.mrstatus WHEN 0 THEN 'Draft' WHEN 1 THEN 'Minta Approve' WHEN 2 THEN 'Approved' WHEN 3 THEN 'Inprogress' WHEN 4 THEN 'Complete' WHEN 5 THEN 'Revisi' WHEN 6 THEN 'Reject' WHEN 7 THEN 'Close' WHEN 8 THEN 'Approve1' WHEN 9 THEN 'Approve2' WHEN 10 THEN 'Approve3' WHEN 11 THEN 'Approve4' WHEN 12 THEN 'Hapus' END) AS status, ((mrd.jml) - IFNULL(mrd.jmlrs,0)) AS jmlrs, ((mrd.jml) - IFNULL(mrd.jmlts,0)) AS jmlts, mrd.namabarang, mrd.tipebarang, mrd.jml, mrd.satuan, mrd.catatan FROM m3_mr mr JOIN m3_mr_detail mrd ON mr.mrid = mrd.idmr JOIN m1_item b ON mrd.idbarang = b.bid LEFT JOIN m1_warehouse ga ON mr.mrgudangasal = ga.wkode LEFT JOIN m1_warehouse gt ON mr.mrgudangtujuan = gt.wkode ORDER BY mr.mrnotransaksi, mrd.urutan;

-- RID=554 | MODULE=3 | MENU=3 | ITEM=7 | RQUERY=1 | NAME=Permintaan Barang (MR) | FILE=materialrequisitiondetail_ud
SELECT mr.mrnotransaksi , mr.mrtgl , mr.mrtgldipakai, kd.knama AS mrdimintaoleh, km.knama AS mrmintake , wa.wnama AS mrgudangasal , wt.wnama AS mrgudangtujuan, mr.mruraian , st.nama AS mrstatus , b.bkode , mrd.namabarang , mrd.jml, mrd.satuan , mrd.catatan FROM m3_mr mr JOIN m1_contact kd ON mr.mrdimintaoleh = kd.kid JOIN m1_contact km ON mr.mrmintake = km.kid JOIN m1_warehouse wa ON mr.mrgudangasal = wa.wkode JOIN m1_warehouse wt ON mr.mrgudangtujuan = wt.wkode JOIN m0_status st on mr.mrstatus = st.kode join m3_mr_detail mrd ON mr.mrid = mrd.idmr JOIN m1_item b ON mrd.idbarang = b.bid ORDER BY mr.mrtgl , mr.mrid , mr.mrnotransaksi, mrd.urutan;

-- RID=1096 | MODULE=3 | MENU=3 | ITEM=8 | RQUERY=1 | NAME=Daftar Permintaan Barang (MR) Stok Global | FILE=MRStokGlobal
SELECT COUNT(*) , wa.wnama AS mrgudangasal , mr.mrnotransaksi , mrd.idbarang , b.bkode AS kodebarang, mrd.namabarang , SUM(mrd.jml) AS jml, mrd.satuan , SUM(mrd.jmlrealisasi / mrd.nilaisatuan) AS jmlrealisasi , SUM(mrd.jml - (mrd.jmlrealisasi / mrd.nilaisatuan)) as jmlsisa , (stok.stok - SUM(mrd.jml - (mrd.jmlrealisasi / mrd.nilaisatuan))) AS sisa , stok.stok FROM m3_mr mr JOIN m1_contact kd ON mr.mrdimintaoleh = kd.kid JOIN m1_warehouse wa ON mr.mrgudangasal = wa.wkode JOIN m1_warehouse wt ON mr.mrgudangtujuan = wt.wkode join m3_mr_detail mrd ON mr.mrid = mrd.idmr JOIN m1_item b ON mrd.idbarang = b.bid JOIN m1_item_stock_warehouse stok ON mrd.idbarang = stok.idbarang AND mr.mrgudangasal = stok.kgudang GROUP BY mr.mrgudangasal , mrd.idbarang ORDER BY mr.mrgudangasal , mrd.idbarang, mrd.idbarang;

-- RID=1097 | MODULE=3 | MENU=3 | ITEM=9 | RQUERY=1 | NAME=Daftar Permintaan Barang (MR) Stok Detail | FILE=MRStokDetail
SELECT COUNT(*) , wa.wnama AS mrgudangasal , mr.mrnotransaksi , mrd.idbarang , b.bkode AS kodebarang, mrd.namabarang , SUM(mrd.jml) AS jml, mrd.satuan , SUM(mrd.jmlrealisasi / mrd.nilaisatuan) AS jmlrealisasi , SUM(mrd.jml - (mrd.jmlrealisasi / mrd.nilaisatuan)) as jmlsisa , stok.stok FROM m3_mr mr JOIN m1_contact kd ON mr.mrdimintaoleh = kd.kid JOIN m1_warehouse wa ON mr.mrgudangasal = wa.wkode JOIN m1_warehouse wt ON mr.mrgudangtujuan = wt.wkode join m3_mr_detail mrd ON mr.mrid = mrd.idmr JOIN m1_item b ON mrd.idbarang = b.bid JOIN m1_item_stock_warehouse stok ON mrd.idbarang = stok.idbarang AND mr.mrgudangasal = stok.kgudang GROUP BY mr.mrgudangasal , mr.mrnotransaksi , mrd.idbarang ORDER BY mr.mrgudangasal , mrd.idbarang, mrd.idbarang ,mr.mrnotransaksi;

-- RID=1636 | MODULE=3 | MENU=3 | ITEM=10 | RQUERY=1 | NAME=Daftar Permintaan Barang (MR) | FILE=listmaterialrequisition2
SELECT mr.mrnotransaksi , mr.mrtgl , mr.mrtgldipakai, kd.knama AS mrdimintaoleh, km.knama AS mrmintake , wa.wnama AS mrgudangasal , wt.wnama AS mrgudangtujuan, mr.mruraian , st.nama AS mrstatus , b.bkode , mrd.namabarang , mrd.jml, mrd.satuan , mrd.catatan FROM m3_mr mr JOIN m1_contact kd ON mr.mrdimintaoleh = kd.kid JOIN m1_contact km ON mr.mrmintake = km.kid JOIN m1_warehouse wa ON mr.mrgudangasal = wa.wkode JOIN m1_warehouse wt ON mr.mrgudangtujuan = wt.wkode JOIN m0_status st on mr.mrstatus = st.kode join m3_mr_detail mrd ON mr.mrid = mrd.idmr JOIN m1_item b ON mrd.idbarang = b.bid ORDER BY mr.mrtgl , mr.mrid , mr.mrnotransaksi, mrd.urutan;

-- RID=50001636 | MODULE=3 | MENU=3 | ITEM=11 | RQUERY=1 | NAME=Transaksi MR | FILE=MaterialRequisition
SELECT mrid , mrcabang , mrlokasi , mrgudangasal , mrgudangtujuan , mrsumber , mrautonotransaksi , mrnotransaksi , mrtgl , mrkodepa , mrdimintaoleh , mrdimintaolehkontak , mrmintake , mrtgldipakai , mruraian , mrcabang , mrnoref , mrtglnoref , mrstatusts , mrstatusrs , mrstatusrealisasi, mrstatus, mrstatussebelumnya, mrjmlrevisi, mrcetakanke, mrinputuser, mrinputuser, mrinputtgl, mrmodifikasiuser , mrmodifikasitgl , mrposting , mrpostingtgl , mrisclose , idmrdetail, idmr , idbarang , namabarang , tipebarang, jml, satuan, nilaisatuan, jmlbarang, satuanbarang, matauang, kurs, hargabeli, hargajual, stokterakhir, cabang, lokasi, gudangasal, gudangtujuan, costcenter, divisi, subdivisi, proyek, catatan, urutan, jmlts, statusts, jmlrs, statusrs, jmlrealisasi, statusrealisasi, isclose FROM m3_mr mr JOIN m3_mr_detail mrd ON mr.mrid = mrd.idmr ORDER BY mr.mrtgl ASC, mr.mrid ASC , mrd.idmrdetail ASC;

-- RID=26 | MODULE=3 | MENU=4 | ITEM=1 | RQUERY=1 | NAME=Daftar Mutasi Barang (TS) | FILE=listtransferstock
SELECT ts.tsid , ts.tsnotransaksi , ts.tstgl , wa.wnama AS tsgudangasal , wt.wnama AS tsgudangtransit, wtu.wnama AS tsgudangtujuan, ts.tsuraian , st.nama AS tsstatus , b.bkode , tsd.namabarang , tsd.jml , tsd.satuan , tsd.catatan , mr.mrnotransaksi FROM m3_ts ts JOIN m1_warehouse wa ON ts.tsgudangasal = wa.wkode JOIN m1_warehouse wt ON ts.tsgudangtransit = wt.wkode JOIN m1_warehouse wtu ON ts.tsgudangtujuan = wtu.wkode JOIN m0_status st ON ts.tsstatus = st.kode JOIN m3_ts_detail tsd ON ts.tsid = tsd.idts JOIN m1_item b ON tsd.idbarang = b.bid LEft JOIN m3_mr_detail mrd ON mrd.idmrdetail = tsd.idmrdetail LEFt JOIN m3_mr mr ON mrd.idmr = mr.mrid ORDER BY ts.tstgl , ts.tsid , ts.tsnotransaksi , tsd.urutan;

-- RID=27 | MODULE=3 | MENU=4 | ITEM=2 | RQUERY=1 | NAME=Mutasi Barang (TS) | FILE=transferstockdetail_new
SELECT ts.tsid , ts.tsnotransaksi , ts.tstgl , wa.wnama AS tsgudangasal , wt.wnama AS tsgudangtransit, wtu.wnama AS tsgudangtujuan, ts.tsuraian , st.nama AS tsstatus , b.bkode , tsd.namabarang , tsd.jml , tsd.satuan , tsd.catatan , mr.mrnotransaksi FROM m3_ts ts LEFT JOIN m1_warehouse wa ON ts.tsgudangasal = wa.wkode LEFT JOIN m1_warehouse wt ON ts.tsgudangtransit = wt.wkode LEFT JOIN m1_warehouse wtu ON ts.tsgudangtujuan = wtu.wkode JOIN m0_status st ON ts.tsstatus = st.kode JOIN m3_ts_detail tsd ON ts.tsid = tsd.idts JOIN m1_item b ON tsd.idbarang = b.bid LEft JOIN m3_mr_detail mrd ON mrd.idmrdetail = tsd.idmrdetail LEFt JOIN m3_mr mr ON mrd.idmr = mr.mrid ORDER BY ts.tstgl , ts.tsid , ts.tsnotransaksi , tsd.urutan;

-- RID=716 | MODULE=3 | MENU=4 | ITEM=3 | RQUERY=1 | NAME=Mutasi Barang (TS) | FILE=transferstockdetail_new2
SELECT ts.tsid , ts.tsnotransaksi , ts.tstgl , wa.wnama AS tsgudangasal , wt.wnama AS tsgudangtransit, wtu.wnama AS tsgudangtujuan, ts.tsuraian , st.nama AS tsstatus , b.bkode , tsd.namabarang , tsd.jml , tsd.satuan , tsd.catatan , mr.mrnotransaksi FROM m3_ts ts LEFT JOIN m1_warehouse wa ON ts.tsgudangasal = wa.wkode LEFT JOIN m1_warehouse wt ON ts.tsgudangtransit = wt.wkode LEFT JOIN m1_warehouse wtu ON ts.tsgudangtujuan = wtu.wkode JOIN m0_status st ON ts.tsstatus = st.kode JOIN m3_ts_detail tsd ON ts.tsid = tsd.idts JOIN m1_item b ON tsd.idbarang = b.bid LEft JOIN m3_mr_detail mrd ON mrd.idmrdetail = tsd.idmrdetail LEFt JOIN m3_mr mr ON mrd.idmr = mr.mrid ORDER BY ts.tstgl , ts.tsid , ts.tsnotransaksi , tsd.urutan;

-- RID=29 | MODULE=3 | MENU=4 | ITEM=4 | RQUERY=1 | NAME=Mutasi Barang (TS)  | FILE=transferstockperlocation
SELECT tsd.urutan, b.bid , LEFT((blg.blgkodelokasi),3) AS lokasi, blg.blgnamalokasi, ts.tsnotransaksi , ts.tsstatus, ts.tstgl, tsd.namabarang, gt.wnama AS 'gudangtujuan', ga.wnama AS 'gudangasal', b.bkode, tsd.tipebarang, sum(tsd.jml), tsd.satuan, ts.tscatatan FROM m3_ts ts JOIN m3_ts_detail tsd ON (ts.tsid = tsd.idts) JOIN m1_item b ON (tsd.idbarang = b.bid) LEFT JOIN m1_warehouse gt ON (tsd.gudangtujuan = gt.wkode) LEFT JOIN m1_warehouse ga ON (tsd.gudangasal = ga.wkode) LEFT JOIN m1_item_location_warehouse blg ON (ts.tsgudangtransit = blg.blggudang AND b.bid = blg.blgidbarang) GROUP BY ts.tsnotransaksi, ifnull(LEFT((blg.blgkodelokasi),3), '-'), b.bkode , tsd.tipebarang , tsd.namabarang , tsd.satuan ORDER BY ts.tsnotransaksi, ifnull(LEFT((blg.blgkodelokasi),3), '-'), tsd.urutan;

-- RID=480 | MODULE=3 | MENU=4 | ITEM=5 | RQUERY=1 | NAME=Mutasi Barang (TS) Serial | FILE=transferstockdetail_serial
SELECT COUNT(*), tsd.idbarang , ts.tsid , ts.tsnotransaksi , ts.tstgl , wa.wnama AS tsgudangasal , wt.wnama AS tsgudangtransit, wtu.wnama AS tsgudangtujuan, ts.tsuraian , st.nama AS tsstatus , b.bkode , tsd.namabarang , Sum(tsd.jml) AS jml , tsd.satuan , tsd.catatan , mr.mrnotransaksi FROM m3_ts ts JOIN m1_warehouse wa ON ts.tsgudangasal = wa.wkode JOIN m1_warehouse wt ON ts.tsgudangtransit = wt.wkode JOIN m1_warehouse wtu ON ts.tsgudangtujuan = wtu.wkode JOIN m0_status st ON ts.tsstatus = st.kode JOIN m3_ts_detail tsd ON ts.tsid = tsd.idts JOIN m1_item b ON tsd.idbarang = b.bid LEft JOIN m3_mr_detail mrd ON mrd.idmrdetail = tsd.idmrdetail LEFt JOIN m3_mr mr ON mrd.idmr = mr.mrid GROUP BY ts.tsid , tsd.idbarang , tsd.namabarang , tsd.satuan ORDER BY ts.tstgl , ts.tsid , ts.tsnotransaksi , tsd.idbarang , tsd.urutan;

-- RID=775 | MODULE=3 | MENU=4 | ITEM=6 | RQUERY=1 | NAME=Mutasi Barang (TS) Batch | FILE=transferstockdetail_batch
SELECT COUNT(*), tsd.idbarang , ts.tsid , ts.tsnotransaksi , ts.tstgl , wa.wnama AS tsgudangasal , wt.wnama AS tsgudangtransit, wtu.wnama AS tsgudangtujuan, ts.tsuraian , st.nama AS tsstatus , b.bkode , tsd.namabarang , Sum(tsd.jml) AS jml , tsd.satuan , tsd.catatan , mr.mrnotransaksi FROM m3_ts ts JOIN m1_warehouse wa ON ts.tsgudangasal = wa.wkode JOIN m1_warehouse wt ON ts.tsgudangtransit = wt.wkode JOIN m1_warehouse wtu ON ts.tsgudangtujuan = wtu.wkode JOIN m0_status st ON ts.tsstatus = st.kode JOIN m3_ts_detail tsd ON ts.tsid = tsd.idts JOIN m1_item b ON tsd.idbarang = b.bid LEft JOIN m3_mr_detail mrd ON mrd.idmrdetail = tsd.idmrdetail LEFt JOIN m3_mr mr ON mrd.idmr = mr.mrid GROUP BY ts.tsid , tsd.idbarang , tsd.namabarang , tsd.satuan ORDER BY ts.tstgl , ts.tsid , ts.tsnotransaksi , tsd.idbarang , tsd.urutan;

-- RID=336 | MODULE=3 | MENU=4 | ITEM=7 | RQUERY=1 | NAME=Daftar Mutasi Barang (TS) Outstanding | FILE=listtransferstockoutstanding
SELECT ts.tsid , ts.tsnotransaksi , ts.tstgl , wa.wnama AS tsgudangasal , wt.wnama AS tsgudangtransit, wtu.wnama AS tsgudangtujuan, ts.tsuraian , st.nama AS tsstatus , b.bkode , tsd.namabarang , tsd.jml , tsd.satuan , tsd.catatan , (tsd.jmlrealisasi / tsd.nilaisatuan) AS jmlrealisasi , (tsd.jml - (tsd.jmlrealisasi / tsd.nilaisatuan)) AS jmlsisa FROM m3_ts ts JOIN m1_warehouse wa ON ts.tsgudangasal = wa.wkode JOIN m1_warehouse wt ON ts.tsgudangtransit = wt.wkode JOIN m1_warehouse wtu ON ts.tsgudangtujuan = wtu.wkode JOIN m0_status st ON ts.tsstatus = st.kode JOIN m3_ts_detail tsd ON ts.tsid = tsd.idts JOIN m1_item b ON tsd.idbarang = b.bid ORDER BY ts.tstgl , ts.tsid , ts.tsnotransaksi , tsd.urutan;

-- RID=338 | MODULE=3 | MENU=4 | ITEM=8 | RQUERY=1 | NAME=Daftar Mutasi Barang (TS) Outstanding Sisa | FILE=listtransferstockoutstanding
SELECT ts.tsnotransaksi , ts.tstgl, tsd.jml, tsd.satuan, tsd.namabarang, (CASE ts.tsstatus WHEN 0 THEN 'Draft' WHEN 1 THEN 'Minta Approve' WHEN 2 THEN 'Approved' WHEN 3 THEN 'Inprogress' WHEN 4 THEN 'Complete' WHEN 5 THEN 'Revisi' WHEN 6 THEN 'Reject' WHEN 7 THEN 'Close' WHEN 8 THEN 'Approve1' WHEN 9 THEN 'Approve2' WHEN 10 THEN 'Approve3' WHEN 11 THEN 'Approve4' WHEN 12 THEN 'Hapus' END) AS status, gt.wnama AS 'gudangtujuan', ga.wnama AS 'gudangasal', ((tsd.jml) - IFNULL(tsd.jmlrs,0)) AS jmlrs, ts.tsuraian, b.bkode, tsd.tipebarang, tsd.urutan FROM m3_ts ts JOIN m3_ts_detail tsd ON (ts.tsid = tsd.idts) JOIN m1_item b ON (tsd.idbarang = b.bid) LEFT JOIN m1_warehouse gt ON (tsd.gudangtujuan = gt.wkode) LEFT JOIN m1_warehouse ga ON (tsd.gudangasal = ga.wkode) ORDER BY ts.tsnotransaksi, tsd.urutan;

-- RID=555 | MODULE=3 | MENU=4 | ITEM=9 | RQUERY=1 | NAME=Mutasi Barang (TS) | FILE=transferstockdetail_ud
SELECT ts.tsid , ts.tsnotransaksi , ts.tstgl , wa.wnama AS tsgudangasal , wt.wnama AS tsgudangtransit, wtu.wnama AS tsgudangtujuan, ts.tsuraian , st.nama AS tsstatus , b.bkode , tsd.namabarang , tsd.jml , tsd.satuan , tsd.catatan , mr.mrnotransaksi FROM m3_ts ts JOIN m1_warehouse wa ON ts.tsgudangasal = wa.wkode JOIN m1_warehouse wt ON ts.tsgudangtransit = wt.wkode JOIN m1_warehouse wtu ON ts.tsgudangtujuan = wtu.wkode JOIN m0_status st ON ts.tsstatus = st.kode JOIN m3_ts_detail tsd ON ts.tsid = tsd.idts JOIN m1_item b ON tsd.idbarang = b.bid LEft JOIN m3_mr_detail mrd ON mrd.idmrdetail = tsd.idmrdetail LEFt JOIN m3_mr mr ON mrd.idmr = mr.mrid ORDER BY ts.tstgl , ts.tsid , ts.tsnotransaksi , tsd.urutan;

-- RID=31 | MODULE=3 | MENU=4 | ITEM=10 | RQUERY=1 | NAME=Mutasi Barang (TS) Perproduk | FILE=listtransferstock_product
SELECT b.bid , b.bkode , tsd.namabarang , ts.tsnotransaksi , ts.tstgl , wa.wnama AS tsgudangasal , wt.wnama AS tsgudangtransit , wtu.wnama AS tsgudangtujuan , st.nama AS tsstatus , mr.mrnotransaksi , SUM(tsd.jml) AS jml , tsd.satuan FROM m3_ts ts JOIN m1_warehouse wa ON ts.tsgudangasal = wa.wkode JOIN m1_warehouse wt ON ts.tsgudangtransit = wt.wkode JOIN m1_warehouse wtu ON ts.tsgudangtujuan = wtu.wkode JOIN m0_status st ON ts.tsstatus = st.kode JOIN m3_ts_detail tsd ON ts.tsid = tsd.idts JOIN m1_item b ON tsd.idbarang = b.bid LEft JOIN m3_mr_detail mrd ON mrd.idmrdetail = tsd.idmrdetail LEFt JOIN m3_mr mr ON mrd.idmr = mr.mrid GROUP BY tsd.idbarang , b.bid , b.bkode, mrd.namabarang , tsd.satuan, tsd.idts, tsd.idmrdetail ORDER BY tsd.idbarang , b.bid , tsd.namabarang;

-- RID=1638 | MODULE=3 | MENU=4 | ITEM=11 | RQUERY=1 | NAME=Daftar Mutasi Barang (TS) | FILE=listtransferstock2
SELECT ts.tsid , ts.tsnotransaksi , ts.tstgl , wa.wnama AS tsgudangasal , wt.wnama AS tsgudangtransit, wtu.wnama AS tsgudangtujuan, ts.tsuraian , st.nama AS tsstatus , b.bkode , tsd.namabarang , tsd.jml , tsd.satuan , tsd.catatan , mr.mrnotransaksi FROM m3_ts ts JOIN m1_warehouse wa ON ts.tsgudangasal = wa.wkode JOIN m1_warehouse wt ON ts.tsgudangtransit = wt.wkode JOIN m1_warehouse wtu ON ts.tsgudangtujuan = wtu.wkode JOIN m0_status st ON ts.tsstatus = st.kode JOIN m3_ts_detail tsd ON ts.tsid = tsd.idts JOIN m1_item b ON tsd.idbarang = b.bid LEft JOIN m3_mr_detail mrd ON mrd.idmrdetail = tsd.idmrdetail LEFt JOIN m3_mr mr ON mrd.idmr = mr.mrid ORDER BY ts.tstgl , ts.tsid , ts.tsnotransaksi , tsd.urutan;

-- RID=5013 | MODULE=3 | MENU=4 | ITEM=12 | RQUERY=1 | NAME=Mutasi Barang (TS) | FILE=transferstockdetail_new_makmur
SELECT ts.tsid , ts.tsnotransaksi , ts.tstgl , wa.wnama AS tsgudangasal , wt.wnama AS tsgudangtransit, wtu.wnama AS tsgudangtujuan, ts.tsuraian , st.nama AS tsstatus , b.bkode , tsd.namabarang , tsd.jml , tsd.satuan , tsd.catatan , mr.mrnotransaksi FROM m3_ts ts LEFT JOIN m1_warehouse wa ON ts.tsgudangasal = wa.wkode LEFT JOIN m1_warehouse wt ON ts.tsgudangtransit = wt.wkode LEFT JOIN m1_warehouse wtu ON ts.tsgudangtujuan = wtu.wkode JOIN m0_status st ON ts.tsstatus = st.kode JOIN m3_ts_detail tsd ON ts.tsid = tsd.idts JOIN m1_item b ON tsd.idbarang = b.bid LEft JOIN m3_mr_detail mrd ON mrd.idmrdetail = tsd.idmrdetail LEFt JOIN m3_mr mr ON mrd.idmr = mr.mrid ORDER BY ts.tstgl , ts.tsid , ts.tsnotransaksi , tsd.urutan;

-- RID=5014 | MODULE=3 | MENU=4 | ITEM=13 | RQUERY=1 | NAME=Mutasi Barang (TS) | FILE=transferstockdetail1_new_makmur
SELECT ts.tsid , ts.tsnotransaksi , ts.tstgl , wa.wnama AS tsgudangasal , wt.wnama AS tsgudangtransit, wtu.wnama AS tsgudangtujuan, ts.tsuraian , st.nama AS tsstatus , b.bkode , tsd.namabarang , tsd.jml , tsd.satuan , tsd.catatan , mr.mrnotransaksi FROM m3_ts ts LEFT JOIN m1_warehouse wa ON ts.tsgudangasal = wa.wkode LEFT JOIN m1_warehouse wt ON ts.tsgudangtransit = wt.wkode LEFT JOIN m1_warehouse wtu ON ts.tsgudangtujuan = wtu.wkode JOIN m0_status st ON ts.tsstatus = st.kode JOIN m3_ts_detail tsd ON ts.tsid = tsd.idts JOIN m1_item b ON tsd.idbarang = b.bid LEft JOIN m3_mr_detail mrd ON mrd.idmrdetail = tsd.idmrdetail LEFt JOIN m3_mr mr ON mrd.idmr = mr.mrid ORDER BY ts.tstgl , ts.tsid , ts.tsnotransaksi , tsd.urutan;

-- RID=50015 | MODULE=3 | MENU=4 | ITEM=14 | RQUERY=1 | NAME=Mutasi Barang (TS) Batch Per Produk  | FILE=listtransferstock_product_batch
SELECT b.bid , b.bkode , tsd.namabarang , ts.tsnotransaksi , ts.tstgl , wa.wnama AS tsgudangasal , wt.wnama AS tsgudangtransit , wtu.wnama AS tsgudangtujuan , st.nama AS tsstatus , mr.mrnotransaksi , SUM(tsd.jml) AS jml , tsd.satuan , tsd.idbarang FROM m3_ts ts JOIN m1_warehouse wa ON ts.tsgudangasal = wa.wkode JOIN m1_warehouse wt ON ts.tsgudangtransit = wt.wkode JOIN m1_warehouse wtu ON ts.tsgudangtujuan = wtu.wkode JOIN m0_status st ON ts.tsstatus = st.kode JOIN m3_ts_detail tsd ON ts.tsid = tsd.idts JOIN m1_item b ON tsd.idbarang = b.bid LEft JOIN m3_mr_detail mrd ON mrd.idmrdetail = tsd.idmrdetail LEFt JOIN m3_mr mr ON mrd.idmr = mr.mrid GROUP BY tsd.idbarang , b.bid , b.bkode, tsd.satuan, tsd.idts, tsd.idmrdetail ORDER BY tsd.idbarang , b.bid , tsd.namabarang;

-- RID=50000574 | MODULE=3 | MENU=4 | ITEM=15 | RQUERY=1 | NAME=Mutasi Barang (TS) | FILE=transferstockdetail_new_denganharga
SELECT ts.tsid , ts.tsnotransaksi , ts.tstgl , wa.wnama AS tsgudangasal , wt.wnama AS tsgudangtransit, wtu.wnama AS tsgudangtujuan, ts.tsuraian , st.nama AS tsstatus , b.bkode , tsd.namabarang , tsd.jml , tsd.satuan , tsd.catatan , mr.mrnotransaksi , b.bhargajual1 AS harga , (tsd.jml * bhargajual1) AS total FROM m3_ts ts LEFT JOIN m1_warehouse wa ON ts.tsgudangasal = wa.wkode LEFT JOIN m1_warehouse wt ON ts.tsgudangtransit = wt.wkode LEFT JOIN m1_warehouse wtu ON ts.tsgudangtujuan = wtu.wkode JOIN m0_status st ON ts.tsstatus = st.kode JOIN m3_ts_detail tsd ON ts.tsid = tsd.idts JOIN m1_item b ON tsd.idbarang = b.bid LEft JOIN m3_mr_detail mrd ON mrd.idmrdetail = tsd.idmrdetail LEFt JOIN m3_mr mr ON mrd.idmr = mr.mrid ORDER BY ts.tstgl , ts.tsid , ts.tsnotransaksi , tsd.urutan;

-- RID=50000575 | MODULE=3 | MENU=4 | ITEM=16 | RQUERY=1 | NAME=Mutasi Barang (TS) | FILE=transferstockdetail_new_denganharga2
SELECT ts.tsid , ts.tsnotransaksi , ts.tstgl , wa.wnama AS tsgudangasal , wt.wnama AS tsgudangtransit, wtu.wnama AS tsgudangtujuan, ts.tsuraian , st.nama AS tsstatus , b.bkode , tsd.namabarang , tsd.jml , tsd.satuan , tsd.catatan , mr.mrnotransaksi , b.bhargajual1 AS harga , (tsd.jml * bhargajual1) AS total FROM m3_ts ts LEFT JOIN m1_warehouse wa ON ts.tsgudangasal = wa.wkode LEFT JOIN m1_warehouse wt ON ts.tsgudangtransit = wt.wkode LEFT JOIN m1_warehouse wtu ON ts.tsgudangtujuan = wtu.wkode JOIN m0_status st ON ts.tsstatus = st.kode JOIN m3_ts_detail tsd ON ts.tsid = tsd.idts JOIN m1_item b ON tsd.idbarang = b.bid LEft JOIN m3_mr_detail mrd ON mrd.idmrdetail = tsd.idmrdetail LEFt JOIN m3_mr mr ON mrd.idmr = mr.mrid ORDER BY ts.tstgl , ts.tsid , ts.tsnotransaksi , tsd.urutan;

-- RID=50001650 | MODULE=3 | MENU=4 | ITEM=17 | RQUERY=1 | NAME=Transaksi TS | FILE=TransferStock
SELECT tsid, tscabang, tslokasi, tsjenis, tsgudangasal, tsgudangtransit, tsgudangtujuan, tssumber, tsautonotransaksi, tsnotransaksi, tstgl, tskodepa, tsbagianmutasi, tsbagianmutasikontak, tsuraian, tscatatan, tsnoref, tstglnoref, tsidmr, tsstatusrs, tsstatusrealisasi, tsstatus, tsstatussebelumnya, tsjmlrevisi, tscetakanke, tsinputuser, tsinputtgl, tsmodifikasiuser, tsmodifikasitgl, tsposting, tspostingtgl, tsisclose, idtsdetail, idts, idbarang, namabarang, tipebarang, jml, satuan, nilaisatuan, jmlbarang, satuanbarang, idhppkhususmasuk, cabang, lokasi, gudangasal, gudangtransit, gudangtujuan, costcenter, divisi, subdivisi, proyek, catatan, urutan, idmrdetail, idgrndetail, jmlrs, statusrs, jmlrealisasi, statusrealisasi, isclose FROM m3_ts ts JOIN m3_ts_detail tsd ON ts.tsid = tsd.idts ORDER BY ts.tstgl ASC, ts.tsid ASC , tsd.idtsdetail ASC;

-- RID=32 | MODULE=3 | MENU=5 | ITEM=1 | RQUERY=1 | NAME=Daftar Terima Mutasi (RS) | FILE=listreceiptstock
SELECT rs.rsid , rs.rsnotransaksi , rs.rstgl , wa.wnama AS rsgudangasal , wt.wnama AS rsgudangtransit, wtu.wnama AS rsgudangtujuan, rs.rsuraian , st.nama AS rsstatus , b.bkode , rsd.namabarang , rsd.jml , rsd.satuan , rsd.catatan , ts.tsnotransaksi FROM m3_rs rs JOIN m1_warehouse wa ON rs.rsgudangasal = wa.wkode JOIN m1_warehouse wt ON rs.rsgudangtransit = wt.wkode JOIN m1_warehouse wtu ON rs.rsgudangtujuan = wtu.wkode JOIN m0_status st ON rs.rsstatus = st.kode JOIN m3_rs_detail rsd ON rs.rsid = rsd.idrs JOIN m1_item b ON rsd.idbarang = b.bid LEFT JOIN m3_ts_detail tsd ON rsd.idtsdetail = tsd.idtsdetail LEFT JOIN m3_ts ts ON tsd.idts = ts.tsid ORDER BY rs.rstgl , rs.rsid , rs.rsnotransaksi , rsd.urutan;

-- RID=33 | MODULE=3 | MENU=5 | ITEM=2 | RQUERY=1 | NAME=Terima Mutasi (RS) | FILE=receiptstockdetail_new
SELECT rs.rsid , rs.rsnotransaksi , rs.rstgl , wa.wnama AS rsgudangasal , wt.wnama AS rsgudangtransit, wtu.wnama AS rsgudangtujuan, rs.rsuraian , st.nama AS rsstatus , b.bkode , rsd.namabarang , rsd.jml , rsd.satuan , rsd.catatan , ts.tsnotransaksi FROM m3_rs rs JOIN m1_warehouse wa ON rs.rsgudangasal = wa.wkode JOIN m1_warehouse wt ON rs.rsgudangtransit = wt.wkode JOIN m1_warehouse wtu ON rs.rsgudangtujuan = wtu.wkode JOIN m0_status st ON rs.rsstatus = st.kode JOIN m3_rs_detail rsd ON rs.rsid = rsd.idrs JOIN m1_item b ON rsd.idbarang = b.bid LEFT JOIN m3_ts_detail tsd ON rsd.idtsdetail = tsd.idtsdetail LEFT JOIN m3_ts ts ON tsd.idts = ts.tsid ORDER BY rs.rstgl , rs.rsid , rs.rsnotransaksi , rsd.urutan;

-- RID=717 | MODULE=3 | MENU=5 | ITEM=3 | RQUERY=1 | NAME=Terima Mutasi (RS) | FILE=receiptstockdetail_new2
SELECT rs.rsid , rs.rsnotransaksi , rs.rstgl , wa.wnama AS rsgudangasal , wt.wnama AS rsgudangtransit, wtu.wnama AS rsgudangtujuan, rs.rsuraian , st.nama AS rsstatus , b.bkode , rsd.namabarang , rsd.jml , rsd.satuan , rsd.catatan , ts.tsnotransaksi FROM m3_rs rs JOIN m1_warehouse wa ON rs.rsgudangasal = wa.wkode JOIN m1_warehouse wt ON rs.rsgudangtransit = wt.wkode JOIN m1_warehouse wtu ON rs.rsgudangtujuan = wtu.wkode JOIN m0_status st ON rs.rsstatus = st.kode JOIN m3_rs_detail rsd ON rs.rsid = rsd.idrs JOIN m1_item b ON rsd.idbarang = b.bid LEFT JOIN m3_ts_detail tsd ON rsd.idtsdetail = tsd.idtsdetail LEFT JOIN m3_ts ts ON tsd.idts = ts.tsid ORDER BY rs.rstgl , rs.rsid , rs.rsnotransaksi , rsd.urutan;

-- RID=478 | MODULE=3 | MENU=5 | ITEM=4 | RQUERY=1 | NAME=Terima Mutasi (RS) Serial | FILE=receiptstockdetail_serial
SELECT COUNT(*) , rs.rsid , rs.rsnotransaksi , rs.rstgl , wa.wnama AS rsgudangasal , wtu.wnama AS rsgudangtujuan, rs.rsuraian , st.nama AS rsstatus , rsd.idbarang , b.bkode , rsd.namabarang , SUM(rsd.jml) AS jml , rsd.satuan , rsd.catatan , ts.tsnotransaksi FROM m3_rs rs JOIN m1_warehouse wa ON rs.rsgudangasal = wa.wkode JOIN m1_warehouse wtu ON rs.rsgudangtujuan = wtu.wkode JOIN m0_status st ON rs.rsstatus = st.kode JOIN m3_rs_detail rsd ON rs.rsid = rsd.idrs JOIN m1_item b ON rsd.idbarang = b.bid LEFT JOIN m3_ts_detail tsd ON rsd.idtsdetail = tsd.idtsdetail LEFT JOIN m3_ts ts ON tsd.idts = ts.tsid GROUP BY rs.rsid , rsd.idbarang , rsd.namabarang , rsd.satuan ORDER BY rs.rstgl , rs.rsid , rs.rsnotransaksi , rsd.idbarang , rsd.urutan;

-- RID=773 | MODULE=3 | MENU=5 | ITEM=5 | RQUERY=1 | NAME=Terima Mutasi (RS) Batch | FILE=receiptstockdetail_batch
SELECT COUNT(*) , rs.rsid , rs.rsnotransaksi , rs.rstgl , wa.wnama AS rsgudangasal , wtu.wnama AS rsgudangtujuan, rs.rsuraian , st.nama AS rsstatus , rsd.idbarang , b.bkode , rsd.namabarang , SUM(rsd.jml) AS jml , rsd.satuan , rsd.catatan , ts.tsnotransaksi FROM m3_rs rs JOIN m1_warehouse wa ON rs.rsgudangasal = wa.wkode JOIN m1_warehouse wtu ON rs.rsgudangtujuan = wtu.wkode JOIN m0_status st ON rs.rsstatus = st.kode JOIN m3_rs_detail rsd ON rs.rsid = rsd.idrs JOIN m1_item b ON rsd.idbarang = b.bid LEFT JOIN m3_ts_detail tsd ON rsd.idtsdetail = tsd.idtsdetail LEFT JOIN m3_ts ts ON tsd.idts = ts.tsid GROUP BY rs.rsid , rsd.idbarang , rsd.namabarang , rsd.satuan ORDER BY rs.rstgl , rs.rsid , rs.rsnotransaksi , rsd.idbarang , rsd.urutan;

-- RID=37 | MODULE=3 | MENU=5 | ITEM=6 | RQUERY=1 | NAME=Terima Mutasi (RS) Perproduk | FILE=listreceiptstock_product
SELECT b.bid , b.bkode , rsd.namabarang , rs.rsnotransaksi , rs.rstgl , wa.wnama AS rsgudangasal , wt.wnama AS rsgudangtransit , wtu.wnama AS rsgudangtujuan, ts.tsnotransaksi , SUM(rsd.jml) AS jml , rsd.satuan FROM m3_rs rs JOIN m1_warehouse wa ON rs.rsgudangasal = wa.wkode JOIN m1_warehouse wt ON rs.rsgudangtransit = wt.wkode JOIN m1_warehouse wtu ON rs.rsgudangtujuan = wtu.wkode JOIN m0_status st ON rs.rsstatus = st.kode JOIN m3_rs_detail rsd ON rs.rsid = rsd.idrs JOIN m1_item b ON rsd.idbarang = b.bid LEFT JOIN m3_ts_detail tsd ON rsd.idtsdetail = tsd.idtsdetail LEFT JOIN m3_ts ts ON tsd.idts = ts.tsid GROUP BY rsd.idbarang , b.bid, b.bkode, rsd.namabarang, rsd.satuan, rsd.idrs, rsd.idtsdetail ORDER BY rsd.idbarang , b.bid , rsd.namabarang;

-- RID=564 | MODULE=3 | MENU=5 | ITEM=7 | RQUERY=1 | NAME=Terima Mutasi (RS) | FILE=receiptstockdetail_ud
SELECT rs.rsid , rs.rsnotransaksi , rs.rstgl , wa.wnama AS rsgudangasal , wt.wnama AS rsgudangtransit, wtu.wnama AS rsgudangtujuan, rs.rsuraian , st.nama AS rsstatus , b.bkode , rsd.namabarang , rsd.jml , rsd.satuan , rsd.catatan , ts.tsnotransaksi FROM m3_rs rs JOIN m1_warehouse wa ON rs.rsgudangasal = wa.wkode JOIN m1_warehouse wt ON rs.rsgudangtransit = wt.wkode JOIN m1_warehouse wtu ON rs.rsgudangtujuan = wtu.wkode JOIN m0_status st ON rs.rsstatus = st.kode JOIN m3_rs_detail rsd ON rs.rsid = rsd.idrs JOIN m1_item b ON rsd.idbarang = b.bid LEFT JOIN m3_ts_detail tsd ON rsd.idtsdetail = tsd.idtsdetail LEFT JOIN m3_ts ts ON tsd.idts = ts.tsid ORDER BY rs.rstgl , rs.rsid , rs.rsnotransaksi , rsd.urutan;

-- RID=35 | MODULE=3 | MENU=5 | ITEM=8 | RQUERY=1 | NAME=Terima Mutasi (RS) | FILE=receiptstockperlocation
SELECT rsd.urutan, rs.rsnotransaksi, LEFT((blg.blgnamalokasi),3) AS lokasi , rs.rstgl, rsd.jml, rsd.tipebarang, rsd.namabarang, rsd.satuan, b.bkode, blg.blgnamalokasi, rsd.catatan, rs.rscatatan FROM m3_rs rs JOIN m3_rs_detail rsd ON (rs.rsid = rsd.idrs) JOIN m1_item b ON (rsd.idbarang = b.bid) LEFT JOIN m1_item_location_warehouse blg ON (rs.rsgudangtransit = blg.blggudang) AND (b.bid = blg.blgidbarang) GROUP BY rs.rsnotransaksi, ifnull(LEFT((blg.blgnamalokasi),3), '-'), b.bkode , rsd.tipebarang , rsd.namabarang , blg.blgnamalokasi, rsd.satuan ORDER BY rs.rsnotransaksi, ifnull(LEFT((blg.blgnamalokasi),3), '-') , rsd.urutan;

-- RID=1640 | MODULE=3 | MENU=5 | ITEM=9 | RQUERY=1 | NAME=Daftar Terima Mutasi (RS) | FILE=listreceiptstock2
SELECT rs.rsid , rs.rsnotransaksi , rs.rstgl , wa.wnama AS rsgudangasal , wt.wnama AS rsgudangtransit, wtu.wnama AS rsgudangtujuan, rs.rsuraian , st.nama AS rsstatus , b.bkode , rsd.namabarang , rsd.jml , rsd.satuan , rsd.catatan , ts.tsnotransaksi FROM m3_rs rs JOIN m1_warehouse wa ON rs.rsgudangasal = wa.wkode JOIN m1_warehouse wt ON rs.rsgudangtransit = wt.wkode JOIN m1_warehouse wtu ON rs.rsgudangtujuan = wtu.wkode JOIN m0_status st ON rs.rsstatus = st.kode JOIN m3_rs_detail rsd ON rs.rsid = rsd.idrs JOIN m1_item b ON rsd.idbarang = b.bid LEFT JOIN m3_ts_detail tsd ON rsd.idtsdetail = tsd.idtsdetail LEFT JOIN m3_ts ts ON tsd.idts = ts.tsid ORDER BY rs.rstgl , rs.rsid , rs.rsnotransaksi , rsd.urutan;

-- RID=16040 | MODULE=3 | MENU=5 | ITEM=10 | RQUERY=1 | NAME=Terima Mutasi (RS) Batch Per Produk | FILE=listreceiptstock_product_batch
SELECT b.bid , b.bkode , rsd.namabarang , rs.rsnotransaksi , rs.rstgl , wa.wnama AS rsgudangasal , wt.wnama AS rsgudangtransit , wtu.wnama AS rsgudangtujuan, ts.tsnotransaksi , SUM(rsd.jml) AS jml , rsd.satuan FROM m3_rs rs JOIN m1_warehouse wa ON rs.rsgudangasal = wa.wkode JOIN m1_warehouse wt ON rs.rsgudangtransit = wt.wkode JOIN m1_warehouse wtu ON rs.rsgudangtujuan = wtu.wkode JOIN m0_status st ON rs.rsstatus = st.kode JOIN m3_rs_detail rsd ON rs.rsid = rsd.idrs JOIN m1_item b ON rsd.idbarang = b.bid LEFT JOIN m3_ts_detail tsd ON rsd.idtsdetail = tsd.idtsdetail LEFT JOIN m3_ts ts ON tsd.idts = ts.tsid GROUP BY rsd.idbarang , b.bid, b.bkode, rsd.namabarang, rsd.satuan, rsd.idrs, rsd.idtsdetail ORDER BY rsd.idbarang , b.bid , rsd.namabarang;

-- RID=50001645 | MODULE=3 | MENU=5 | ITEM=11 | RQUERY=1 | NAME=Transaksi RS | FILE=ReceiptStock
SELECT rsid, rscabang, rslokasi, rsgudangasal, rsgudangtransit, rsgudangtujuan, rssumber, rsautonotransaksi, rsnotransaksi, rstgl, rskodepa, rsbagianterima, rsbagianterimakontak, rsuraian, rscatatan, rsnoref, rstglnoref, rsidmr, rsidts, rsstatus, rsstatussebelumnya, rsjmlrevisi, rscetakanke, rsinputuser, rsinputtgl, rsmodifikasiuser, rsmodifikasitgl, rsposting, rspostingtgl, rsisclose, idrsdetail, idrs, idbarang, namabarang, tipebarang, jml, satuan, nilaisatuan, jmlbarang, satuanbarang, cabang, lokasi, gudangasal, gudangtransit, gudangtujuan, costcenter, divisi, subdivisi, proyek, catatan, urutan, idmrdetail, idtsdetail, isclose FROM m3_rs rs JOIN m3_rs_detail rsd ON rs.rsid = rsd.idrs ORDER BY rs.rstgl ASC, rs.rsid ASC , rsd.idrsdetail ASC;

-- RID=40 | MODULE=3 | MENU=6 | ITEM=1 | RQUERY=1 | NAME=Daftar Transaksi Barang (SA) | FILE=liststockadjustment
SELECT sa.sagudang , w.wnama AS gudang, sa.sanotransaksi , sa.satgl , b.bkode , sad.namabarang , tsa.tsanama AS sajenis , sp.spnotransaksi , sad.satuan , sad.jmlmasuk , sad.jmlkeluar, sad.hpplama, sad.hpp, (sad.jmlmasuk * sad.hpp) AS totalmasuk , (sad.jmlkeluar * sad.hpp) AS totalkeluar FROM m3_sa sa JOIN m1_warehouse w ON sa.sagudang = w.wkode JOIN m3_sa_detail sad ON sa.said = sad.idsa JOIN m1_item b ON sad.idbarang = b.bid JOIN m1_type_sa tsa ON sa.sajenis = tsa.tsakode LEFT JOIN m3_sp_detail spd ON sad.idspdetail = spd.idspdetail LEFT JOIN m3_sp sp ON spd.idsp = sp.spid ORDER BY sa.sagudang , sa.satgl , sa.said, sa.sanotransaksi , sad.urutan;

-- RID=41 | MODULE=3 | MENU=6 | ITEM=2 | RQUERY=1 | NAME=Transaksi Barang (SA) | FILE=stockadjustmentdetail_new
SELECT sa.sagudang , w.wnama AS gudang, sa.sanotransaksi , sa.satgl , sa.sauraian , tsa.tsanama AS sajenis , st.nama AS sastatus, sa.sacatatan , b.bkode , sad.namabarang , sad.satuan , sad.jmlmasuk , sad.jmlkeluar, sad.hpplama, sad.hpp, sad.gudang, sad.catatan , b.bstok, b.bstokminimal, b.bstokmaksimal FROM m3_sa sa JOIN m1_warehouse w ON sa.sagudang = w.wkode JOIN m3_sa_detail sad ON sa.said = sad.idsa JOIN m1_item b ON sad.idbarang = b.bid JOIN m1_type_sa tsa ON sa.sajenis = tsa.tsakode JOIN m0_status st ON sa.sastatus = st.kode ORDER BY sa.sagudang , sa.satgl , sa.said, sa.sanotransaksi , sad.urutan;

-- RID=718 | MODULE=3 | MENU=6 | ITEM=3 | RQUERY=1 | NAME=Transaksi Barang (SA) | FILE=stockadjustmentdetail_new2
SELECT sa.sagudang , w.wnama AS gudang, sa.sanotransaksi , sa.satgl , sa.sauraian , tsa.tsanama AS sajenis , st.nama AS sastatus, sa.sacatatan , b.bkode , sad.namabarang , sad.satuan , sad.jmlmasuk , sad.jmlkeluar, sad.hpplama, sad.hpp, sad.catatan FROM m3_sa sa JOIN m1_warehouse w ON sa.sagudang = w.wkode JOIN m3_sa_detail sad ON sa.said = sad.idsa JOIN m1_item b ON sad.idbarang = b.bid JOIN m1_type_sa tsa ON sa.sajenis = tsa.tsakode JOIN m0_status st ON sa.sastatus = st.kode ORDER BY sa.sagudang , sa.satgl , sa.said, sa.sanotransaksi , sad.urutan;

-- RID=479 | MODULE=3 | MENU=6 | ITEM=4 | RQUERY=1 | NAME=Transaksi Barang (SA) Serial | FILE=stockadjustmentdetail_serial
SELECT sa.said , COUNT(*), sa.sagudang , w.wnama AS gudang, sa.sanotransaksi , sa.satgl , sa.sauraian , sa.sacatatan , tsa.tsanama AS sajenis , st.nama AS sastatus, b.bkode , sad.namabarang , sad.satuan , SUM(sad.jmlmasuk) as jmlmasuk , SUM(sad.jmlkeluar) as jmlkeluar, sad.hpplama, sad.hpp, sad.idbarang , sad.catatan FROM m3_sa sa JOIN m1_warehouse w ON sa.sagudang = w.wkode JOIN m3_sa_detail sad ON sa.said = sad.idsa JOIN m1_item b ON sad.idbarang = b.bid JOIN m1_type_sa tsa ON sa.sajenis = tsa.tsakode JOIN m0_status st ON sa.sastatus = st.kode GROUP BY sa.satgl , sa.said , sad.idbarang , sad.namabarang , sad.satuan , sad.hpp, sad.hpplama ORDER BY sa.sagudang , sa.satgl , sa.said, sa.sanotransaksi , sad.idbarang, sad.urutan;

-- RID=774 | MODULE=3 | MENU=6 | ITEM=5 | RQUERY=1 | NAME=Transaksi Barang (SA) Batch | FILE=stockadjustmentdetail_batch
SELECT sa.said , COUNT(*), sa.sagudang, sa.sanotransaksi , sa.satgl , sa.sauraian , sa.sacatatan , tsa.tsanama AS sajenis , st.nama AS sastatus, b.bkode , sad.namabarang , sad.satuan , SUM(sad.jmlmasuk) as jmlmasuk , SUM(sad.jmlkeluar) as jmlkeluar, sad.hpplama, sad.hpp, sad.idbarang , sad.catatan, sad.gudang FROM m3_sa sa JOIN m1_warehouse w ON sa.sagudang = w.wkode JOIN m3_sa_detail sad ON sa.said = sad.idsa JOIN m1_item b ON sad.idbarang = b.bid JOIN m1_type_sa tsa ON sa.sajenis = tsa.tsakode JOIN m0_status st ON sa.sastatus = st.kode GROUP BY sa.satgl , sa.said , sad.idbarang , sad.namabarang , sad.satuan , sad.hpp, sad.hpplama, sad.gudang ORDER BY sad.urutan , sa.sagudang , sa.satgl , sa.said, sa.sanotransaksi , sad.idbarang;

-- RID=201 | MODULE=3 | MENU=6 | ITEM=6 | RQUERY=1 | NAME=Daftar Transaksi Barang (SA) Per Produk | FILE=liststockadjustment_product
SELECT w.wnama AS gudang , b.bid , b.bkode , sad.namabarang , sa.satgl, sa.sanotransaksi , tsa.tsanama AS sajenis , sp.spnotransaksi , sad.satuan , SUM(sad.jmlmasuk) AS jmlkeluar , SUM(sad.jmlkeluar) AS jmlkeluar, SUM(sad.hpplama) AS hpplama, SUM(sad.hpp) AS hpp FROM m3_sa sa JOIN m1_warehouse w ON sa.sagudang = w.wkode JOIN m3_sa_detail sad ON sa.said = sad.idsa JOIN m1_item b ON sad.idbarang = b.bid JOIN m1_type_sa tsa ON sa.sajenis = tsa.tsakode LEFT JOIN m3_sp_detail spd ON sad.idspdetail = spd.idspdetail LEFT JOIN m3_sp sp ON spd.idsp = sp.spid GROUP BY sad.idbarang, b.bid, b.bkode, sad.namabarang, sad.satuan, sad.hpplama, sad.hpp ORDER BY sa.sagudang , sad.idbarang , b.bid , sad.namabarang;

-- RID=566 | MODULE=3 | MENU=6 | ITEM=7 | RQUERY=1 | NAME=Transaksi Barang (SA) | FILE=stockadjustmentdetail_ud
SELECT sa.sagudang , w.wnama AS gudang, sa.sanotransaksi , sa.satgl , sa.sauraian , tsa.tsanama AS sajenis , st.nama AS sastatus, sa.sacatatan , b.bkode , sad.namabarang , sad.satuan , sad.jmlmasuk , sad.jmlkeluar, sad.hpplama, sad.hpp, sad.catatan FROM m3_sa sa JOIN m1_warehouse w ON sa.sagudang = w.wkode JOIN m3_sa_detail sad ON sa.said = sad.idsa JOIN m1_item b ON sad.idbarang = b.bid JOIN m1_type_sa tsa ON sa.sajenis = tsa.tsakode JOIN m0_status st ON sa.sastatus = st.kode ORDER BY sa.sagudang , sa.satgl , sa.said, sa.sanotransaksi , sad.urutan;

-- RID=200 | MODULE=3 | MENU=6 | ITEM=8 | RQUERY=1 | NAME=Transaksi Barang (SA) | FILE=liststockadjustmentperakun
SELECT sad.reklawan, c.cnama, sa.sanotransaksi, sa.satgl, sa.sauraian, sad.hpp, sad.jmlmasuk, sad.jmlkeluar, sa.sacatatan, sad.satuan, b.bkode, sad.namabarang, sad.tipebarang, tsa.tsanama AS jenis FROM m3_sa sa JOIN m3_sa_detail sad ON sa.said = sad.idsa JOIN m1_item b ON sad.idbarang = b.bid JOIN m1_coa c ON sad.reklawan = c.cnomor LEFT JOIN m1_type_sa tsa ON sa.sajenis = tsa.tsakode ORDER BY sad.reklawan , sa.sanotransaksi , sad.urutan;

-- RID=790 | MODULE=3 | MENU=6 | ITEM=9 | RQUERY=1 | NAME=Transaksi Barang (SA) | FILE=stockadjustmentdetail_newvolume
SELECT sa.sagudang , w.wnama AS gudang, sa.sanotransaksi , sa.satgl , sa.sauraian , tsa.tsanama AS sajenis , st.nama AS sastatus, sa.sacatatan , b.bkode , sad.namabarang , sad.satuan , sad.jmlmasuk , sad.jmlkeluar, sad.hpplama, sad.hpp, sad.catatan , b.balebar , b.bapanjang , b.batinggi , CASE sad.jmlkeluar when 0 then (sad.jmlmasuk * b.balebar * b.bapanjang * b.batinggi) else (sad.jmlkeluar * b.balebar * b.bapanjang * b.batinggi) END as volume FROM m3_sa sa JOIN m1_warehouse w ON sa.sagudang = w.wkode JOIN m3_sa_detail sad ON sa.said = sad.idsa JOIN m1_item b ON sad.idbarang = b.bid JOIN m1_type_sa tsa ON sa.sajenis = tsa.tsakode JOIN m0_status st ON sa.sastatus = st.kode ORDER BY sa.sagudang , sa.satgl , sa.said, sa.sanotransaksi , sad.urutan;

-- RID=791 | MODULE=3 | MENU=6 | ITEM=10 | RQUERY=1 | NAME=Transaksi Barang (SA) | FILE=stockadjustmentdetail_newvolume2
SELECT sa.sagudang , w.wnama AS gudang, sa.sanotransaksi , sa.satgl , sa.sauraian , tsa.tsanama AS sajenis , st.nama AS sastatus, sa.sacatatan , b.bkode , sad.namabarang , sad.satuan , sad.jmlmasuk , sad.jmlkeluar, sad.hpplama, sad.hpp, sad.catatan , b.balebar , b.bapanjang , b.batinggi , CASE sad.jmlkeluar when 0 then (sad.jmlmasuk * b.balebar * b.bapanjang * b.batinggi) else (sad.jmlkeluar * b.balebar * b.bapanjang * b.batinggi) END as volume FROM m3_sa sa JOIN m1_warehouse w ON sa.sagudang = w.wkode JOIN m3_sa_detail sad ON sa.said = sad.idsa JOIN m1_item b ON sad.idbarang = b.bid JOIN m1_type_sa tsa ON sa.sajenis = tsa.tsakode JOIN m0_status st ON sa.sastatus = st.kode ORDER BY sa.sagudang , sa.satgl , sa.said, sa.sanotransaksi , sad.urutan;

-- RID=1572 | MODULE=3 | MENU=6 | ITEM=11 | RQUERY=1 | NAME=Transaksi Barang (Detail) | FILE=DaftarPenyesuaianDetail
SELECT tsa.tsanama AS sajenis , sa.satgl , sa.sanotransaksi , k.knama AS sabagiansa, sa.sauraian , sad.namabarang , sad.jmlbarangmasuk as jmlmasuk , sad.satuanbarang , sad.hpp , (sad.jmlbarangmasuk * sad.hpp) as nilai FROM m3_sa sa JOIN m3_sa_detail sad ON sa.said = sad.idsa JOIN m1_contact k ON sa.sabagiansa = k.kid JOIN m1_type_sa tsa ON sa.sajenis = tsa.tsakode ORDER BY sa.satgl;

-- RID=1593 | MODULE=3 | MENU=6 | ITEM=12 | RQUERY=1 | NAME=Daftar Transaksi Barang (SA) Per Jenis | FILE=liststockadjustment_perjenis
SELECT br.bnama AS sacabang , l.lnama AS salokasi , sa.sagudang , w.wnama AS gudang, sa.sanotransaksi , sa.satgl , b.bkode , sad.namabarang , tsa.tsanama AS sajenis , sp.spnotransaksi , sad.satuan , sad.jmlmasuk , sad.jmlkeluar, sad.hpplama, sad.hpp, (sad.jmlmasuk * sad.hpp) AS totalmasuk , (sad.jmlkeluar * sad.hpp) AS totalkeluar FROM m3_sa sa LEFT JOIN m1_branch br ON sa.sacabang = br.bkode LEFT JOIN m1_location l ON sa.salokasi = l.lkode AND sa.sacabang = l.lcabang JOIN m1_warehouse w ON sa.sagudang = w.wkode JOIN m3_sa_detail sad ON sa.said = sad.idsa JOIN m1_item b ON sad.idbarang = b.bid JOIN m1_type_sa tsa ON sa.sajenis = tsa.tsakode LEFT JOIN m3_sp_detail spd ON sad.idspdetail = spd.idspdetail LEFT JOIN m3_sp sp ON spd.idsp = sp.spid ORDER BY br.bnama , l.lnama , sa.sagudang , sa.satgl , sa.said, sa.sanotransaksi , sad.urutan;

-- RID=1592 | MODULE=3 | MENU=6 | ITEM=13 | RQUERY=1 | NAME=Daftar Transaksi Barang (SA) Per Kontak | FILE=liststockadjustment_perkontak
SELECT k.knama AS sabagiansa, sa.sagudang , w.wnama AS gudang, sa.sanotransaksi , sa.satgl , b.bkode , sad.namabarang , sa.sabagiansa AS grup , tsa.tsanama AS sajenis , sp.spnotransaksi , sad.satuan , sad.jmlmasuk , sad.jmlkeluar, sad.hpplama, sad.hpp , IF(((sad.jmlmasuk - sad.jmlkeluar) * sad.hpp) < 0,((sad.jmlmasuk - sad.jmlkeluar) * sad.hpp) * -1,((sad.jmlmasuk - sad.jmlkeluar) * sad.hpp) * 1) as total FROM m3_sa sa JOIN m1_warehouse w ON sa.sagudang = w.wkode JOIN m3_sa_detail sad ON sa.said = sad.idsa JOIN m1_item b ON sad.idbarang = b.bid JOIN m1_type_sa tsa ON sa.sajenis = tsa.tsakode LEFT JOIN m3_sp_detail spd ON sad.idspdetail = spd.idspdetail LEFT JOIN m3_sp sp ON spd.idsp = sp.spid JOIN m1_contact k ON sa.sabagiansa = k.kid ORDER BY sa.sagudang , sa.sabagiansa, sa.satgl, sa.said, sa.sanotransaksi , sad.urutan;

-- RID=1603 | MODULE=3 | MENU=6 | ITEM=14 | RQUERY=1 | NAME=Daftar Transaksi Barang (SA) | FILE=liststockadjustment_2
SELECT sa.sagudang , w.wnama AS gudang, sa.sanotransaksi , sa.satgl , b.bkode , sad.namabarang , tsa.tsanama AS sajenis , sp.spnotransaksi , sad.satuan , sad.jmlmasuk , sad.jmlkeluar, sad.hpplama, sad.hpp, (sad.jmlmasuk * sad.hpp) AS totalmasuk , (sad.jmlkeluar * sad.hpp) AS totalkeluar FROM m3_sa sa JOIN m1_warehouse w ON sa.sagudang = w.wkode JOIN m3_sa_detail sad ON sa.said = sad.idsa JOIN m1_item b ON sad.idbarang = b.bid JOIN m1_type_sa tsa ON sa.sajenis = tsa.tsakode LEFT JOIN m3_sp_detail spd ON sad.idspdetail = spd.idspdetail LEFT JOIN m3_sp sp ON spd.idsp = sp.spid ORDER BY sa.sagudang , sa.satgl , sa.said, sa.sanotransaksi , sad.urutan;

-- RID=1686 | MODULE=3 | MENU=6 | ITEM=15 | RQUERY=1 | NAME=Daftar Transaksi Barang (SA) Global | FILE=liststockadjustmentglobal
SELECT sa.said, sa.sanotransaksi , sa.satgl , k.knama AS sabagiansa, sa.sagudang , w.wnama AS gudang, tsa.tsanama AS sajenis , sa.sauraian, s.nama AS sastatus, b.bkode , sad.namabarang , sp.spnotransaksi , sad.satuan , sad.jmlmasuk , sad.jmlkeluar, sad.hpplama, sad.hpp, (sad.jmlmasuk * sad.hpp) AS totalmasuk , (sad.jmlkeluar * sad.hpp) AS totalkeluar , sa.samodifikasitgl FROM m3_sa sa JOIN m1_warehouse w ON sa.sagudang = w.wkode JOIN m3_sa_detail sad ON sa.said = sad.idsa JOIN m1_item b ON sad.idbarang = b.bid JOIN m1_type_sa tsa ON sa.sajenis = tsa.tsakode JOIN m1_contact k ON sa.sabagiansa = k.kid JOIN m0_status s ON sa.sastatus = s.kode LEFT JOIN m3_sp_detail spd ON sad.idspdetail = spd.idspdetail LEFT JOIN m3_sp sp ON spd.idsp = sp.spid ORDER BY sa.sagudang , sa.satgl , sa.said, sa.sanotransaksi , sad.urutan;

-- RID=1687 | MODULE=3 | MENU=6 | ITEM=16 | RQUERY=1 | NAME=Daftar Transaksi Barang (SA) Detail | FILE=liststockadjustmentdetail
SELECT sa.said, sa.sanotransaksi , sa.satgl , k.knama AS sabagiansa, sa.sagudang , w.wnama AS gudang, tsa.tsanama AS sajenis , sa.sauraian, s.nama AS sastatus, b.bkode , sad.namabarang , sp.spnotransaksi , sad.satuanbarang as satuan , sad.jmlbarangmasuk as jmlmasuk , sad.jmlbarangkeluar as jmlkeluar, sad.hpplama, sad.hpp, (sad.jmlbarangmasuk * sad.hpp) AS totalmasuk , (sad.jmlbarangkeluar * sad.hpp) AS totalkeluar, b.bkategori as kategoribarang, ic.icnama as namakategoribarang FROM m3_sa sa JOIN m1_warehouse w ON sa.sagudang = w.wkode JOIN m3_sa_detail sad ON sa.said = sad.idsa JOIN m1_item b ON sad.idbarang = b.bid JOIN m1_type_sa tsa ON sa.sajenis = tsa.tsakode JOIN m1_contact k ON sa.sabagiansa = k.kid JOIN m0_status s ON sa.sastatus = s.kode LEFT JOIN m3_sp_detail spd ON sad.idspdetail = spd.idspdetail LEFT JOIN m3_sp sp ON spd.idsp = sp.spid left join m1_item_category ic on b.bkategori = ic.ickode ORDER BY sa.sagudang , sa.satgl , sa.said, sa.sanotransaksi , sad.urutan;

-- RID=50001654 | MODULE=3 | MENU=6 | ITEM=17 | RQUERY=1 | NAME=Tansaksi SA | FILE=StockAdjustment
SELECT said, sacabang, salokasi, sagudang, sasumber, sajenis, saautonotransaksi, sanotransaksi, satgl, sakodepa, sabagiansa, sabagiansakontak, sauraian, sacatatan, sanoref, satglnoref, said, sastatus, sastatussebelumnya, sajmlrevisi, sacetakanke, sainputuser, sainputtgl, samodifikasiuser, samodifikasitgl, saposting, sapostingtgl, satutupperiode, saisclose, sauploaded, idsadetail, idsa, idbarang, namabarang, tipebarang, jmlmasuk, jmlkeluar, satuan, nilaisatuan, jmlbarangmasuk, jmlbarangkeluar, satuanbarang, idhppkhususmasuk, hpplama, hpp, rekpersediaan, reklawan, idspdetail, cabang, lokasi, gudang, costcenter,divisi,subdivisi, proyek, catatan, urutan, isclose FROM FROM m3_sa sa JOIN m3_sa_detail sad ON sa.said = sad.idsa ORDER BY sa.satgl ASC, sa.said ASC , sad.idsadetail ASC;

-- RID=43 | MODULE=3 | MENU=7 | ITEM=1 | RQUERY=1 | NAME=Daftar Stok Opname (SP) | FILE=liststockopname
SELECT sp.spnotransaksi , sp.sptgl , w.wnama AS spgudang , sp.spuraian , st.nama AS spstatus , il.ilnama as lokasibarang , b.bkode , spd.namabarang , spd.satuan , spd.jmlsistem, spd.jmlfisik , spd.jmlbagus , spd.jmlrusak, (spd.jmlsistem - spd.jmlfisik ) AS jmlselisih FROM m3_sp sp JOIN m1_warehouse w ON sp.spgudang = w.wkode JOIN m0_status st ON sp.spstatus = st.kode JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang ORDER BY sp.sptgl , sp.spid , sp.spnotransaksi , spd.urutan;

-- RID=48 | MODULE=3 | MENU=7 | ITEM=2 | RQUERY=1 | NAME=Daftar Stok Opname (SP) Outstanding | FILE=liststockopnameoutstanding
SELECT sp.spnotransaksi , sp.sptgl , w.wnama AS spgudang , sp.spuraian , st.nama AS spstatus , il.ilnama as lokasibarang , b.bkode , spd.namabarang , spd.satuan , spd.jmlsistem, spd.jmlsa, (spd.jmlsistem - spd.jmlsa) AS sisa FROM m3_sp sp JOIN m1_warehouse w ON sp.spgudang = w.wkode JOIN m0_status st ON sp.spstatus = st.kode JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang ORDER BY sp.sptgl , sp.spid , sp.spnotransaksi , spd.urutan;

-- RID=44 | MODULE=3 | MENU=7 | ITEM=3 | RQUERY=1 | NAME=Stok Opname (SP) | FILE=stockopnamedetail
SELECT sp.spnotransaksi , sp.sptgl , w.wnama AS spgudang , sp.spuraian , st.nama AS spstatus , il.ilnama as lokasibarang , b.bkode , spd.namabarang , spd.satuan , spd.jmlsistem, spd.jmlfisik , spd.jmlbagus , spd.jmlrusak, (spd.jmlsistem - spd.jmlfisik ) AS jmlselisih FROM m3_sp sp JOIN m1_warehouse w ON sp.spgudang = w.wkode JOIN m0_status st ON sp.spstatus = st.kode JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang ORDER BY sp.sptgl , sp.spid , sp.spnotransaksi , spd.urutan;

-- RID=719 | MODULE=3 | MENU=7 | ITEM=4 | RQUERY=1 | NAME=Stok Opname (SP) | FILE=stockopnamedetail2
SELECT sp.spnotransaksi , sp.sptgl , w.wnama AS spgudang , sp.spuraian , st.nama AS spstatus , il.ilnama as lokasibarang , b.bkode , spd.namabarang , spd.satuan , spd.jmlsistem, spd.jmlfisik , spd.jmlbagus , spd.jmlrusak, (spd.jmlsistem - spd.jmlfisik ) AS jmlselisih FROM m3_sp sp JOIN m1_warehouse w ON sp.spgudang = w.wkode JOIN m0_status st ON sp.spstatus = st.kode JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang ORDER BY sp.sptgl , sp.spid , sp.spnotransaksi , spd.urutan;

-- RID=498 | MODULE=3 | MENU=7 | ITEM=5 | RQUERY=1 | NAME=Stok Opname (SP) Blangko | FILE=stockopnamedetail_blk
SELECT sp.spnotransaksi , sp.sptgl , w.wnama AS spgudang , sp.spuraian , st.nama AS spstatus , il.ilnama as lokasibarang , b.bkode , spd.namabarang , spd.satuan , spd.jmlsistem, spd.jmlfisik , spd.jmlbagus , spd.jmlrusak, (spd.jmlsistem - spd.jmlfisik ) AS jmlselisih FROM m3_sp sp JOIN m1_warehouse w ON sp.spgudang = w.wkode JOIN m0_status st ON sp.spstatus = st.kode JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang ORDER BY sp.sptgl , sp.spid , sp.spnotransaksi , spd.urutan;

-- RID=501 | MODULE=3 | MENU=7 | ITEM=6 | RQUERY=1 | NAME=Stok Opname (SP) Selisih | FILE=stockopnamedetail_selisih
SELECT sp.spnotransaksi , sp.sptgl , w.wnama AS spgudang , sp.spuraian , st.nama AS spstatus , il.ilnama as lokasibarang , b.bkode , spd.namabarang , spd.satuan , spd.jmlsistem, (spd.jmlsistem - spd.jmlfisik ) AS jmlselisih FROM m3_sp sp JOIN m1_warehouse w ON sp.spgudang = w.wkode JOIN m0_status st ON sp.spstatus = st.kode JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang WHERE (spd.jmlsistem - spd.jmlfisik ) <> 0 ORDER BY sp.sptgl , sp.spid , sp.spnotransaksi , spd.urutan;

-- RID=1023 | MODULE=3 | MENU=7 | ITEM=7 | RQUERY=1 | NAME=Stok Opname (SP) Per Produk | FILE=liststockopname_product
SELECT b.bid, b.bkode, spd.namabarang, il.ilnama AS lokasi , sp.spnotransaksi , sp.sptgl , w.wnama AS spgudang, spd.satuan , SUM(spd.jmlsistem) AS jmlsistem, SUM(spd.jmlfisik) AS jmlfisik , SUM(spd.jmlbagus) AS jmlbagus , SUM(spd.jmlrusak) AS jmlrusak, SUM(spd.jmlsistem - spd.jmlfisik ) AS jmlselisih FROM m3_sp sp JOIN m1_warehouse w ON sp.spgudang = w.wkode JOIN m0_status st ON sp.spstatus = st.kode JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang GROUP BY spd.idbarang , b.bid, b.bkode, spd.namabarang, spd.satuan, spd.idsp ORDER BY spd.idbarang , b.bid , spd.namabarang;

-- RID=46 | MODULE=3 | MENU=7 | ITEM=8 | RQUERY=1 | NAME=Stok Opaname (SP) Dengan Saldo | FILE=liststockopnamewithbalance
SELECT spd.urutan, sp.spnotransaksi, sp.sptgl, spd.jmlfisik, spd.jmlbagus, spd.jmlsistem, spd.jmlrusak, b.btipe, b.bnama, b.bkode, b.bsatuan, blg.blgnamalokasi FROM m3_sp sp JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid LEFT JOIN m1_item_location_warehouse blg ON spd.idbarang = blg.blgidbarang AND sp.spgudang = blg.blggudang;

-- RID=47 | MODULE=3 | MENU=7 | ITEM=9 | RQUERY=1 | NAME=Stok Opname (SP) Perproduk | FILE=liststockopnameperproduct
SELECT sp.spnotransaksi, sp.sptgl, sp.spuraian, SUM(spd.jmlsistem) AS jumlahbuku, SUM(spd.jmlfisik) AS jumlahfisik, b.bkode, b.btipe, b.bnama, b.bsatuan, g.wnama, blg.blgnamalokasi, SUM((spd.jmlsistem - spd.jmlfisik)) AS selisih FROM m3_sp sp JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid LEFT JOIN m1_item_location_warehouse blg ON (spd.idbarang = blg.blgidbarang AND sp.spgudang = blg.blggudang) LEFT JOIN m1_warehouse g ON sp.spgudang = g.wkode GROUP BY b.bkode, b.btipe, b.bnama, b.bsatuan, sp.spnotransaksi ORDER BY b.bkode, spd.urutan, sp.spnotransaksi;

-- RID=49 | MODULE=3 | MENU=7 | ITEM=10 | RQUERY=1 | NAME=Stok Opname (SP) Outstanding Sisa | FILE=liststockopnameoutstandingsisa
SELECT sp.spnotransaksi, sp.sptgl, sp.spcatatan, spd.jmlrusak, spd.jmlsa, (CASE sp.spstatus WHEN 0 THEN 'Draft' WHEN 1 THEN 'Minta Approve' WHEN 2 THEN 'Approved' WHEN 3 THEN 'Inprogress' WHEN 4 THEN 'Complete' WHEN 5 THEN 'Revisi' WHEN 6 THEN 'Reject' WHEN 7 THEN 'Close' WHEN 8 THEN 'Approve1' WHEN 9 THEN 'Approve2' WHEN 10 THEN 'Approve3' WHEN 11 THEN 'Approve4' WHEN 12 THEN 'Hapus' END) AS spstatus, b.bkode AS kodebarang, b.bnama AS namabarang, b.btipe, b.bsatuan, g.wnama, sp.spuraian, blg.blgnamalokasi FROM m3_sp sp JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid JOIN m1_warehouse g ON sp.spgudang = g.wkode LEFT JOIN m1_item_location_warehouse blg ON (spd.idbarang = blg.blgidbarang AND sp.spgudang = blg.blggudang) WHERE (sp.spstatussa <> 'S' AND spd.statussa <> 'S') ORDER BY sp.spnotransaksi, spd.urutan;

-- RID=565 | MODULE=3 | MENU=7 | ITEM=11 | RQUERY=1 | NAME=Stok Opname (SP) | FILE=stockopnamedetail_ud
SELECT sp.spnotransaksi , sp.sptgl , w.wnama AS spgudang , sp.spuraian , st.nama AS spstatus , il.ilnama as lokasibarang , b.bkode , spd.namabarang , spd.satuan , spd.jmlsistem, spd.jmlfisik , spd.jmlbagus , spd.jmlrusak, (spd.jmlsistem - spd.jmlfisik ) AS jmlselisih FROM m3_sp sp JOIN m1_warehouse w ON sp.spgudang = w.wkode JOIN m0_status st ON sp.spstatus = st.kode JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang ORDER BY sp.sptgl , sp.spid , sp.spnotransaksi , spd.urutan;

-- RID=1343 | MODULE=3 | MENU=7 | ITEM=12 | RQUERY=1 | NAME=Blanko Stok Opname Dengan Saldo | FILE=BlankoStokOpnameDenganSaldo
SELECT sp.sptgl , sp.spnotransaksi , il.ilnama , b.bkode , spd.namabarang , spd.satuan , spd.jmlsistem, (spd.jmlbagus + spd.jmlrusak)AS jmlfisik, spd.jmlbagus , spd.jmlrusak FROM m3_sp sp JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang ORDER BY sp.sptgl , sp.spnotransaksi , il.ilkode;

-- RID=1344 | MODULE=3 | MENU=7 | ITEM=13 | RQUERY=1 | NAME=Blanko Stok Opname Tanpa Saldo | FILE=BlankoStokOpnameTanpaSaldo
SELECT sp.sptgl , sp.spnotransaksi , il.ilnama , b.bkode , spd.namabarang , spd.satuan, spd.jmlsistem FROM m3_sp sp JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang ORDER BY sp.sptgl , sp.spnotransaksi , spd.idbarang , il.ilkode;

-- RID=1345 | MODULE=3 | MENU=7 | ITEM=14 | RQUERY=1 | NAME=Hasil Stok Opname | FILE=HasilStokOpname
SELECT sp.sptgl , sp.spnotransaksi , w.wnama AS gudang , il.ilnama , b.bkode , spd.namabarang , spd.satuan , spd.jmlsistem, spd.jmlfisik , spd.jmlbagus , spd.jmlrusak , spd.selisih FROM m3_sp sp JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid JOIN m1_warehouse w ON sp.spgudang = w.wkode LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang ORDER BY sp.sptgl , sp.spnotransaksi , il.ilkode;

-- RID=1346 | MODULE=3 | MENU=7 | ITEM=15 | RQUERY=1 | NAME=Blanko Stok Opname Selisih Tanpa Saldo | FILE=BlankoStokOpanameSelisihTanpaSaldo
SELECT w.wnama AS gudang , il.ilnama , b.bkode , spd.namabarang , spd.satuan , SUM(spd.jmlsistem) AS jmlsistem, SUM(spd.jmlfisik) AS jmlfisik , SUM(spd.jmlbagus) AS jmlbagus , SUM(spd.jmlrusak) AS jmlrusak , SUM(spd.selisih) AS selisih FROM m3_sp sp JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid JOIN m1_warehouse w ON sp.spgudang = w.wkode LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang WHERE spd.selisih <> 0 GROUP BY sp.spgudang , b.bkode , il.ilkode ORDER BY sp.spgudang , b.bkode , il.ilkode;

-- RID=1347 | MODULE=3 | MENU=7 | ITEM=16 | RQUERY=1 | NAME=Blanko Stok Opname Selisih Dengan Saldo | FILE=BlankoStokOpanameSelisihDenganSaldo
SELECT w.wnama AS gudang , il.ilnama , b.bkode , spd.namabarang , spd.satuan , SUM(spd.jmlsistem) AS jmlsistem, SUM(spd.jmlfisik) AS jmlfisik , SUM(spd.jmlbagus) AS jmlbagus , SUM(spd.jmlrusak) AS jmlrusak , SUM(spd.selisih) AS selisih FROM m3_sp sp JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid JOIN m1_warehouse w ON sp.spgudang = w.wkode LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang WHERE spd.selisih <> 0 GROUP BY sp.spgudang , il.ilkode, b.bkode , spd.namabarang ORDER BY sp.spgudang , il.ilkode, b.bkode , spd.namabarang;

-- RID=1644 | MODULE=3 | MENU=7 | ITEM=17 | RQUERY=1 | NAME=Daftar Stok Opname (SP) | FILE=liststockopname2
SELECT sp.spnotransaksi , sp.sptgl , w.wnama AS spgudang , sp.spuraian , st.nama AS spstatus , il.ilnama as lokasibarang , b.bkode , spd.namabarang , spd.satuan , spd.jmlsistem, spd.jmlfisik , spd.jmlbagus , spd.jmlrusak, (spd.jmlsistem - spd.jmlfisik ) AS jmlselisih FROM m3_sp sp JOIN m1_warehouse w ON sp.spgudang = w.wkode JOIN m0_status st ON sp.spstatus = st.kode JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang;

-- RID=1653 | MODULE=3 | MENU=7 | ITEM=18 | RQUERY=1 | NAME=Laporan Hasil Stock Opname Pertahap  | FILE=liststockopname_step
SELECT sp.spid , sp.spnotransaksi , sp.sptgl , w.wnama AS spgudang , sp.spuraian , st.nama AS spstatus , spd.idsp , spd.idspdetail , spd.idbarang , il.ilnama as lokasibarang , b.bkode , spd.namabarang , spd.satuan , spd.jmlsistem, spd.jmlfisik , spd.jmlbagus , spd.jmlrusak, (spd.jmlsistem - spd.jmlfisik ) AS jmlselisih FROM m3_sp sp JOIN m1_warehouse w ON sp.spgudang = w.wkode JOIN m0_status st ON sp.spstatus = st.kode JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang ORDER BY sp.sptgl , sp.spid , sp.spnotransaksi , spd.idbarang , spd.urutan;

-- RID=1654 | MODULE=3 | MENU=7 | ITEM=19 | RQUERY=1 | NAME=Stok Opname (SP) Blanko Selisih | FILE=stockopnamedetail_selisih_blanko
SELECT sp.spnotransaksi , sp.sptgl , w.wnama AS spgudang , sp.spuraian , st.nama AS spstatus , il.ilnama as lokasibarang , b.bkode , spd.namabarang , spd.satuan , spd.jmlsistem, (spd.jmlsistem - spd.jmlfisik ) AS jmlselisih FROM m3_sp sp JOIN m1_warehouse w ON sp.spgudang = w.wkode JOIN m0_status st ON sp.spstatus = st.kode JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang WHERE (spd.jmlsistem - spd.jmlfisik ) <> 0 ORDER BY sp.sptgl , sp.spid , sp.spnotransaksi , spd.urutan;

-- RID=1658 | MODULE=3 | MENU=7 | ITEM=20 | RQUERY=1 | NAME=Blanko Stok Opname Selisih Dengan Saldo Penjualan | FILE=BlankoStokOpanameSelisihDenganSaldo_jual
SELECT sp.spid, sp.spnotransaksi, sp.sptgl, w.wnama AS spgudang, st.nama AS spstatus , sp.spuraian , spd.idspdetail, spd.idbarang, il.ilnama as lokasibarang , b.bkode , spd.namabarang, spd.satuan , spd.jmlbarangsistem, spd.jmlbarangfisik, spd.jmlbarangbagus, spd.jmlbarangrusak, SUM((CASE LENGTH(IFNULL(si.siid,'')) WHEN 0 THEN 0 ELSE sid.jmlbarang END) ) as jmlbarangjual, spd.jmlbarangsistem - SUM((CASE LENGTH(IFNULL(si.siid,'')) WHEN 0 THEN 0 ELSE sid.jmlbarang END) ) - spd.jmlbarangfisik as selisihbarangfix FROM m3_sp sp JOIN m3_sp_detail spd ON sp.spid = spd.idsp LEFT JOIN m5_si_detail sid ON spd.idbarang = sid.idbarang LEFT JOIN m5_si si ON sid.idsi = si.siid AND sp.sptgl = si.sitgl AND sp.spgudang = si.sigudang AND si.sistatus IN(2,3,4,7) JOIN m0_status st ON sp.spstatus = st.kode JOIN m1_warehouse w ON spgudang = w.wkode LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang JOIN m1_item b ON spd.idbarang = b.bid GROUP BY spd.idspdetail HAVING selisihbarangfix <> 0 ORDER BY sp.spgudang , il.ilkode, b.bkode , spd.namabarang;

-- RID=1659 | MODULE=3 | MENU=7 | ITEM=21 | RQUERY=1 | NAME=Stok Opname (SP) Blanko Selisih Penjualan | FILE=stockopnamedetail_jual
SELECT sp.spid, sp.spnotransaksi, sp.sptgl, w.wnama AS spgudang, st.nama AS spstatus , sp.spuraian , spd.idspdetail, spd.idbarang, il.ilnama as lokasibarang , b.bkode , spd.namabarang, spd.satuan , spd.jmlbarangsistem, spd.jmlbarangfisik, spd.jmlbarangbagus, spd.jmlbarangrusak, SUM((CASE LENGTH(IFNULL(si.siid,'')) WHEN 0 THEN 0 ELSE sid.jmlbarang END) ) as jmlbarangjual, spd.jmlbarangsistem - SUM((CASE LENGTH(IFNULL(si.siid,'')) WHEN 0 THEN 0 ELSE sid.jmlbarang END) ) - spd.jmlbarangfisik as selisihbarangfix FROM m3_sp sp JOIN m3_sp_detail spd ON sp.spid = spd.idsp LEFT JOIN m5_si_detail sid ON spd.idbarang = sid.idbarang LEFT JOIN m5_si si ON sid.idsi = si.siid AND sp.sptgl = si.sitgl AND sp.spgudang = si.sigudang AND si.sistatus IN(2,3,4,7) JOIN m0_status st ON sp.spstatus = st.kode JOIN m1_warehouse w ON spgudang = w.wkode LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang JOIN m1_item b ON spd.idbarang = b.bid GROUP BY spd.idspdetail HAVING selisihbarangfix <> 0 ORDER BY sp.spid, spd.idspdetail;

-- RID=1665 | MODULE=3 | MENU=7 | ITEM=22 | RQUERY=1 | NAME=Daftar Stok Opname (SP) Dengan Harga | FILE=liststockopnamedenganharga
SELECT sp.spnotransaksi , sp.sptgl , w.wnama AS spgudang , sp.spuraian , st.nama AS spstatus , il.ilnama as lokasibarang , b.bkode , spd.namabarang , spd.satuan , spd.jmlsistem, spd.jmlfisik , spd.jmlbagus , spd.jmlrusak, (spd.jmlsistem - spd.jmlfisik ) AS jmlselisih, b.bhargajual1 AS hargajual FROM m3_sp sp JOIN m1_warehouse w ON sp.spgudang = w.wkode JOIN m0_status st ON sp.spstatus = st.kode JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang ORDER BY sp.sptgl , sp.spid , sp.spnotransaksi , spd.urutan;

-- RID=1667 | MODULE=3 | MENU=7 | ITEM=23 | RQUERY=1 | NAME=Daftar Stok Opname (SP) Tanpa Harga | FILE=liststockopnametanpaharga
SELECT sp.spnotransaksi , sp.sptgl , w.wnama AS spgudang , sp.spuraian , st.nama AS spstatus , il.ilnama as lokasibarang , b.bkode , spd.namabarang , spd.satuan , spd.jmlsistem, spd.jmlfisik , spd.jmlbagus , spd.jmlrusak, (spd.jmlsistem - spd.jmlfisik ) AS jmlselisih FROM m3_sp sp JOIN m1_warehouse w ON sp.spgudang = w.wkode JOIN m0_status st ON sp.spstatus = st.kode JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang ORDER BY sp.sptgl , sp.spid , sp.spnotransaksi , spd.urutan;

-- RID=2014 | MODULE=3 | MENU=7 | ITEM=24 | RQUERY=1 | NAME=Stok Opname Selisih  | FILE=SP_1
SELECT sp.spnotransaksi , sp.sptgl , w.wnama AS spgudang , sp.spuraian , st.nama AS spstatus , il.ilnama as lokasibarang , b.bkode , spd.namabarang , spd.satuan , spd.jmlsistem, spd.jmlfisik , (spd.jmlfisik - spd.jmlsistem) AS jmlselisih FROM m3_sp sp JOIN m1_warehouse w ON sp.spgudang = w.wkode JOIN m0_status st ON sp.spstatus = st.kode JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang WHERE (spd.jmlfisik - spd.jmlsistem) <> 0 ORDER BY sp.sptgl , sp.spid , sp.spnotransaksi , spd.urutan;

-- RID=2015 | MODULE=3 | MENU=7 | ITEM=25 | RQUERY=1 | NAME=Stok Opname Selisih  | FILE=SP_2
SELECT sp.spnotransaksi , sp.sptgl , w.wnama AS spgudang , sp.spuraian , st.nama AS spstatus , il.ilnama as lokasibarang , b.bkode , spd.namabarang , spd.satuan , spd.jmlsistem, spd.jmlfisik , (spd.jmlfisik - spd.jmlsistem) AS jmlselisih FROM m3_sp sp JOIN m1_warehouse w ON sp.spgudang = w.wkode JOIN m0_status st ON sp.spstatus = st.kode JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang WHERE (spd.jmlfisik - spd.jmlsistem) <> 0 ORDER BY sp.sptgl , sp.spid , sp.spnotransaksi , spd.urutan;

-- RID=30001 | MODULE=3 | MENU=7 | ITEM=26 | RQUERY=1 | NAME=Blanko Stok Opname | FILE=Blanko_Stok_Opname
SELECT ic.icnama , sp.spnotransaksi , sp.sptgl , w.wnama AS spgudang , sp.spuraian , b.bkode , spd.namabarang , spd.satuan , spd.jmlsistem, spd.jmlfisik , spd.jmlbagus , spd.jmlrusak, (spd.jmlsistem - spd.jmlfisik ) AS jmlselisih FROM m3_sp sp JOIN m1_warehouse w ON sp.spgudang = w.wkode JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid JOIN m1_item_category ic ON b.bkategori = ic.ickode ORDER BY sp.spnotransaksi , sp.spgudang , b.bkategori;

-- RID=30030 | MODULE=3 | MENU=7 | ITEM=27 | RQUERY=1 | NAME=Daftar Stok Opname (SP) Dengan Harga | FILE=liststockopnamedenganharga2
SELECT sp.spnotransaksi , sp.sptgl , w.wnama AS spgudang , sp.spuraian , st.nama AS spstatus , il.ilnama as lokasibarang , b.bkode , spd.namabarang , spd.satuan , spd.jmlsistem, spd.jmlfisik , spd.jmlbagus , spd.jmlrusak, (spd.jmlsistem - spd.jmlfisik) AS jmlselisih, b.bhppaverage , ((spd.jmlsistem - spd.jmlfisik) * b.bhppaverage) AS hargajual FROM m3_sp sp JOIN m1_warehouse w ON sp.spgudang = w.wkode JOIN m0_status st ON sp.spstatus = st.kode JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang ORDER BY sp.sptgl , sp.spid , sp.spnotransaksi , spd.urutan;

-- RID=42443 | MODULE=3 | MENU=7 | ITEM=29 | RQUERY=1 | NAME=Laporan Total Stok Opname Selisih | FILE=stockopnamedetail_selisih_dgnHarga[OK]
SELECT w.wnama AS spgudang , b.bkode , spd.namabarang , spd.satuan , (spd.jmlsistem) AS jmlsistem, (spd.jmlsistem - SUM(spd.jmlfisik) ) AS jmlselisih , b.bhppaverage , ((spd.jmlsistem - SUM(spd.jmlfisik) ) * b.bhppaverage) AS total FROM m3_sp sp JOIN m1_warehouse w ON sp.spgudang = w.wkode JOIN m0_status st ON sp.spstatus = st.kode JOIN m3_sp_detail spd ON sp.spid = spd.idsp JOIN m1_item b ON spd.idbarang = b.bid GROUP BY sp.spgudang , spd.idbarang HAVING jmlselisih <> 0 ORDER BY sp.spgudang , b.bkode;

-- RID=42445 | MODULE=3 | MENU=7 | ITEM=30 | RQUERY=1 | NAME=Laporan Total Selisih Stok Opname | FILE=Laporan_Total_selisih_SP
SELECT sp.spnotransaksi , sp.sptgl , w.wnama AS spgudang , sp.spuraian , st.nama AS spstatus , il.ilnama as lokasibarang , b.bkode , spd.namabarang , spd.satuan , spd.jmlsistem, SUM(spd.jmlsistem - spd.jmlfisik ) AS jmlselisih , b.bhppaverage , SUM((spd.jmlsistem - spd.jmlfisik ) * b.bhppaverage) AS total FROM m3_sp sp JOIN m1_warehouse w ON sp.spgudang = w.wkode JOIN m0_status st ON sp.spstatus = st.kode JOIN m3_sp_detail spd ON sp.spid = spd.idsp AND sp.spstatus IN(2,3,4,7) LEFT JOIN m1_item_location il ON spd.lokasibarang = il.ilkode AND sp.spgudang = il.ilgudang JOIN m1_item b ON spd.idbarang = b.bid WHERE ((spd.jmlsistem - spd.jmlfisik ) <> 0 ) GROUP BY spd.idbarang ORDER BY spd.idbarang;

-- RID=50001653 | MODULE=3 | MENU=7 | ITEM=33 | RQUERY=1 | NAME=Transaksi SP | FILE=StockOpname
SELECT spid, spcabang, splokasi, spgudang, spsumber, spautonotransaksi, spnotransaksi, sptgl, spkodepa, spbagiansp, spbagianspkontak, spuraian, spcatatan, spnoref, sptglnoref, spstatussa, spstatus, spstatussebelumnya, spjmlrevisi, spcetakanke, spinputuser, spinputtgl, spmodifikasiuser, spmodifikasitgl, spposting, sppostingtgl, sptutupperiode, spisclose, spstepke, spuploaded, idspdetail, idsp, idbarang, namabarang, tipebarang, jmlsistem, jmlfisik, jmlbagus, jmlrusak, selisih, satuan, nilaisatuan, jmlbarangsistem, jmlbarangfisik, jmlbarangbagus, jmlbarangrusak, selisihbarang, satuanbarang, cabang, lokasi, gudang, lokasibarang, jmlsa, statussa, costcenter, divisi, subdivisi, proyek, catatan, urutan, isclose FROM m3_sp sp JOIN m3_sp_detail spd ON sp.spid = spd.idsp ORDER BY sp.sptgl ASC, sp.spid ASC , spd.idspdetail ASC;

-- RID=50 | MODULE=3 | MENU=8 | ITEM=1 | RQUERY=1 | NAME=   | FILE=listpricelistadjustment
SELECT pa.paid , pa.panotransaksi, pa.patgl , pa.patglberlakusampai , pa.pamatauang , pa.pakurs, pa.pauraian , st.nama AS pastatus, b.bkode , b.bnama AS namabarang , pad.satuan, pad.hargajual1lama , pad.hargajual1 , pad.diskonjual1lama, pad.diskonjual1 FROM m3_pa pa JOIN m0_status st ON pa.pastatus = st.kode JOIN m3_pa_detail pad ON pa.paid = pad.idpa JOIN m1_item b ON pad.idbarang = b.bid ORDER BY pa.patgl, pa.paid , pa.panotransaksi , pad.urutan;

-- RID=51 | MODULE=3 | MENU=8 | ITEM=2 | RQUERY=1 | NAME=Set Harga Jual (PA) | FILE=pricelistadjustmentdetail
SELECT pa.paid , pa.panotransaksi, pa.patgl , pa.patglberlakusampai , pa.pamatauang , pa.pakurs, pa.pauraian , st.nama AS pastatus, b.bkode , b.bnama AS namabarang , pad.satuan, pad.hargajual1lama , pad.hargajual1 , pad.diskonjual1lama, pad.diskonjual1 FROM m3_pa pa JOIN m0_status st ON pa.pastatus = st.kode JOIN m3_pa_detail pad ON pa.paid = pad.idpa JOIN m1_item b ON pad.idbarang = b.bid ORDER BY pa.patgl, pa.paid , pa.panotransaksi , pad.urutan;

-- RID=720 | MODULE=3 | MENU=8 | ITEM=3 | RQUERY=1 | NAME=Set Harga Jual (PA) | FILE=pricelistadjustmentdetail2
SELECT pa.paid , pa.panotransaksi, pa.patgl , pa.patglberlakusampai , pa.pamatauang , pa.pakurs, pa.pauraian , st.nama AS pastatus, b.bkode , b.bnama AS namabarang , pad.satuan, pad.hargajual1lama , pad.hargajual1 , pad.diskonjual1lama, pad.diskonjual1 FROM m3_pa pa JOIN m0_status st ON pa.pastatus = st.kode JOIN m3_pa_detail pad ON pa.paid = pad.idpa JOIN m1_item b ON pad.idbarang = b.bid ORDER BY pa.patgl, pa.paid , pa.panotransaksi , pad.urutan;

-- RID=206 | MODULE=3 | MENU=8 | ITEM=4 | RQUERY=1 | NAME=Set Harga Jual (PA) Per Produk | FILE=listpricelistadjustment_product
SELECT b.bid , b.bkode , b.bnama , pa.panotransaksi , pa.patgl , pa.patglberlakusampai , pad.satuan, pad.hargajual1lama , pad.hargajual1 , pad.diskonjual1lama, pad.diskonjual1 FROM m3_pa pa JOIN m0_status st ON pa.pastatus = st.kode JOIN m3_pa_detail pad ON pa.paid = pad.idpa JOIN m1_item b ON pad.idbarang = b.bid GROUP BY pad.idbarang, b.bid, b.bkode, b.bnama, pad.satuan, pad.hargajual1lama , pad.hargajual1 , pad.diskonjual1lama, pad.diskonjual1 ORDER BY pad.idbarang , b.bid, b.bnama;

-- RID=567 | MODULE=3 | MENU=8 | ITEM=5 | RQUERY=1 | NAME=Set Harga Jual (PA) | FILE=pricelistadjustmentdetail_ud
SELECT pa.paid , pa.panotransaksi, pa.patgl , pa.patglberlakusampai , pa.pamatauang , pa.pakurs, pa.pauraian , st.nama AS pastatus, b.bkode , b.bnama AS namabarang , pad.satuan, pad.hargajual1lama , pad.hargajual1 , pad.diskonjual1lama, pad.diskonjual1 FROM m3_pa pa JOIN m0_status st ON pa.pastatus = st.kode JOIN m3_pa_detail pad ON pa.paid = pad.idpa JOIN m1_item b ON pad.idbarang = b.bid ORDER BY pa.patgl, pa.paid , pa.panotransaksi , pad.urutan;

-- RID=1645 | MODULE=3 | MENU=8 | ITEM=6 | RQUERY=1 | NAME=Daftar Set Harga Jual (PA) | FILE=listpricelistadjustment2
SELECT pa.paid , pa.panotransaksi, pa.patgl , pa.patglberlakusampai , pa.pamatauang , pa.pakurs, pa.pauraian , st.nama AS pastatus, b.bkode , b.bnama AS namabarang , pad.satuan, pad.hargajual1lama , pad.hargajual1 , pad.diskonjual1lama, pad.diskonjual1 FROM m3_pa pa JOIN m0_status st ON pa.pastatus = st.kode JOIN m3_pa_detail pad ON pa.paid = pad.idpa JOIN m1_item b ON pad.idbarang = b.bid;

-- RID=50001638 | MODULE=3 | MENU=8 | ITEM=7 | RQUERY=1 | NAME=Transaksi PA | FILE=PriceListAdjustment
SELECT paid, pacabang, palokasi, pagudang, pakategori, pakategoriharga, pasumber, paautonotransaksi, panotransaksi, patgl, patglberlakusampai, pakodepa, pabagianpa, pabagianpakontak, pamatauang, pakurs, pauraian, pacatatan, panoref, patglnoref, pastatus, pastatussebelumnya, pajmlrevisi, pacetakanke, painputuser, painputtgl, pamodifikasiuser, pamodifikasitgl, paposting, papostingtgl, patutupperiode, paisclose, idpadetail, idpa, idbarang, satuan, nilaisatuan, kontak, matauang, kurs, hargajual1lama, hargajual2lama, hargajual3lama, hargajual4lama, hargajual5lama, hargajual1, hargajual2, hargajual3, hargajual4, hargajual5, diskonjual1lama, diskonjual2lama, diskonjual3lama, diskonjual4lama, diskonjual5lama, diskonjual1, diskonjual2, diskonjual3, diskonjual4, diskonjual5, cabang, lokasi, gudang, costcenter, divisi, subdivisi, proyek, catatan, urutan, statusberlaku, isclose, hargajual6lama, hargajual7lama, hargajual8lama, hargajual9lama, hargajual10lama, hargajual6, hargajual7, hargajual8, hargajual9, hargajual10, diskonjual6, diskonjual7, diskonjual8, diskonjual9, diskonjual10 FROM m3_pa pa JOIN m3_pa_detail pad ON pa.paid = pad.idpa ORDER BY m3_pa pa pa.patgl ASC, pa.paid ASC , pad.idpadetail ASC;

-- RID=467 | MODULE=3 | MENU=23 | ITEM=1 | RQUERY=1 | NAME=Daftar Saldo Awal Barang (IB) | FILE=saldoawalbarang
SELECT ib.ibid, ib.ibnotransaksi , ib.ibtgl , w.wnama AS ibgudang , ib.iburaian , st.nama AS ibstatus , b.bkode , ibd.namabarang , ibd.jml, ibd.satuan , ibd.hpplama, ibd.hpp , ibd.catatan FROM m3_ib ib JOIN m1_warehouse w ON ib.ibgudang = w.wkode JOIN m0_status st ON ib.ibstatus = st.kode JOIN m3_ib_detail ibd ON ib.ibid = ibd.idib JOIN m1_item b ON ibd.idbarang = b.bid ORDER BY ib.ibtgl, ib.ibid , ib.ibnotransaksi , ibd.urutan;

-- RID=468 | MODULE=3 | MENU=23 | ITEM=2 | RQUERY=1 | NAME=Saldo Awal Barang (IB) | FILE=saldoawalbarangdetail
SELECT ib.ibid, ib.ibnotransaksi , ib.ibtgl , w.wnama AS ibgudang , ib.iburaian , st.nama AS ibstatus , b.bkode , ibd.namabarang , ibd.jml, ibd.satuan , ibd.hpplama, ibd.hpp , ibd.catatan FROM m3_ib ib JOIN m1_warehouse w ON ib.ibgudang = w.wkode JOIN m0_status st ON ib.ibstatus = st.kode JOIN m3_ib_detail ibd ON ib.ibid = ibd.idib JOIN m1_item b ON ibd.idbarang = b.bid ORDER BY ib.ibtgl, ib.ibid , ib.ibnotransaksi , ibd.urutan;

-- RID=721 | MODULE=3 | MENU=23 | ITEM=3 | RQUERY=1 | NAME=Saldo Awal Barang (IB) | FILE=saldoawalbarangdetail2
SELECT ib.ibid, ib.ibnotransaksi , ib.ibtgl , w.wnama AS ibgudang , ib.iburaian , st.nama AS ibstatus , b.bkode , ibd.namabarang , ibd.jml, ibd.satuan , ibd.hpplama, ibd.hpp , ibd.catatan FROM m3_ib ib JOIN m1_warehouse w ON ib.ibgudang = w.wkode JOIN m0_status st ON ib.ibstatus = st.kode JOIN m3_ib_detail ibd ON ib.ibid = ibd.idib JOIN m1_item b ON ibd.idbarang = b.bid ORDER BY ib.ibtgl, ib.ibid , ib.ibnotransaksi , ibd.urutan;

-- RID=568 | MODULE=3 | MENU=23 | ITEM=4 | RQUERY=1 | NAME=Saldo Awal Barang (IB) | FILE=saldoawalbarangdetail_ud
SELECT ib.ibid, ib.ibnotransaksi , ib.ibtgl , w.wnama AS ibgudang , ib.iburaian , st.nama AS ibstatus , b.bkode , ibd.namabarang , ibd.jml, ibd.satuan , ibd.hpplama, ibd.hpp , ibd.catatan FROM m3_ib ib JOIN m1_warehouse w ON ib.ibgudang = w.wkode JOIN m0_status st ON ib.ibstatus = st.kode JOIN m3_ib_detail ibd ON ib.ibid = ibd.idib JOIN m1_item b ON ibd.idbarang = b.bid ORDER BY ib.ibtgl, ib.ibid , ib.ibnotransaksi , ibd.urutan;

-- RID=1646 | MODULE=3 | MENU=23 | ITEM=5 | RQUERY=1 | NAME=Daftar Saldo Awal Barang (IB) | FILE=saldoawalbarang2
SELECT ib.ibid, ib.ibnotransaksi , ib.ibtgl , w.wnama AS ibgudang , ib.iburaian , st.nama AS ibstatus , b.bkode , ibd.namabarang , ibd.jml, ibd.satuan , ibd.hpplama, ibd.hpp , ibd.catatan FROM m3_ib ib JOIN m1_warehouse w ON ib.ibgudang = w.wkode JOIN m0_status st ON ib.ibstatus = st.kode JOIN m3_ib_detail ibd ON ib.ibid = ibd.idib JOIN m1_item b ON ibd.idbarang = b.bid;

-- RID=50001648 | MODULE=3 | MENU=23 | ITEM=6 | RQUERY=1 | NAME=Transaksi IB | FILE=SaldoAwalBarang
SELECT ibid, ibcabang, iblokasi, ibgudang, ibsumber, ibjenis, ibautonotransaksi, ibnotransaksi, ibtgl, ibkodepa, ibbagianib, ibbagianibkontak, ibmatauang, ibkurs, iburaian, ibcatatan, ibnoref, ibtglnoref, ibstatus, ibstatussebelumnya, ibjmlrevisi, ibcetakanke, ibinputuser, ibinputtgl, ibmodifikasiuser, ibmodifikasitgl, ibposting, ibpostingtgl, ibtutupperiode, ibisclose, idibdetail, idib, idbarang, namabarang, tipebarang, jml, satuan, nilaisatuan, jmlbarang, satuanbarang, matauang, kurs, hpplama, hpp, rekpersediaan, cabang, lokasi, gudang, costcenter, divisi, subdivisi, proyek, catatan, urutan, isclose FROM m3_ib ib JOIN m3_ib_detail ibd ON ib.ibid = ibd.idib ORDER BY ib.ibtgl ASC, ib.ibid ASC , ibd.idibdetail ASC;

-- RID=822 | MODULE=3 | MENU=40 | ITEM=1 | RQUERY=1 | NAME=Daftar Pengisian Bahan Bakar (RF) | FILE=listpengisianbahanbakar
SELECT rf.rfdimintaoleh, k.knama AS dimintaoleh, ih.bkode AS kodebarang, rf.rfnotransaksi, rf.rftgl, rfd.catatan, rf.rfcustomtext1 AS jampengisian, rf.rfuraian, rfd.namabarang, rfd.satuan, rfd.jml, rfd.stokterakhir AS hourmeter, st.nama AS statusrf FROM m3_rf rf JOIN m3_rf_detail rfd ON rf.rfid = rfd.idrf JOIN m1_item_hauling ih ON rfd.idbarang = ih.bid JOIN m1_contact k ON rf.rfdimintaoleh = k.kid JOIN m0_status st ON rf.rfstatus = st.kode ORDER BY rf.rfnotransaksi, ih.bkode, rf.rftgl, k.knama;

-- RID=826 | MODULE=3 | MENU=40 | ITEM=2 | RQUERY=1 | NAME=Laporan Pengisian Bahan Bakar (RF)  | FILE=PemakaianSolar3
SELECT rf.rfdimintaoleh, k.knama AS dimintaoleh, ih.bkode AS kodebarang, rf.rfnotransaksi, rf.rftgl, rfd.catatan, rf.rfcustomtext1 AS jampengisian, rf.rfuraian, rfd.namabarang, rfd.satuan, rfd.jml, rfd.stokterakhir AS hourmeter, st.nama AS statusrf FROM m3_rf rf JOIN m3_rf_detail rfd ON rf.rfid = rfd.idrf JOIN m1_item_hauling ih ON rfd.idbarang = ih.bid JOIN m1_contact k ON rf.rfdimintaoleh = k.kid JOIN m0_status st ON rf.rfstatus = st.kode ORDER BY rf.rfnotransaksi, ih.bkode, rf.rftgl, k.knama;

-- RID=806 | MODULE=3 | MENU=40 | ITEM=3 | RQUERY=1 | NAME=Laporan Pengisian Bahan Bakar (RF) | FILE=PemakaianSolar
SELECT rf.rfdimintaoleh, k.knama AS dimintaoleh, ih.bkode AS kodebarang, rf.rfnotransaksi, rf.rftgl, rfd.catatan, rf.rfcustomtext1 AS jampengisian, rf.rfuraian, rfd.namabarang, rfd.satuan, rfd.jml, rfd.stokterakhir AS hourmeter, st.nama AS statusrf FROM m3_rf rf JOIN m3_rf_detail rfd ON rf.rfid = rfd.idrf JOIN m1_item_hauling ih ON rfd.idbarang = ih.bid JOIN m1_contact k ON rf.rfdimintaoleh = k.kid JOIN m0_status st ON rf.rfstatus = st.kode ORDER BY rf.rfnotransaksi, ih.bkode, rf.rftgl, k.knama;

-- RID=823 | MODULE=3 | MENU=40 | ITEM=4 | RQUERY=1 | NAME=Pengisian Bahan Bakar (RF) | FILE=pengisianbahanbakardetail
SELECT rf.rfdimintaoleh, k.knama AS dimintaoleh, ih.bkode AS kodebarang, rf.rfnotransaksi, rf.rftgl, rfd.catatan, rf.rfcustomtext1 AS jampengisian, rf.rfuraian, rfd.namabarang, rfd.satuan, rfd.jml, rfd.stokterakhir AS hourmeter, st.nama AS statusrf FROM m3_rf rf JOIN m3_rf_detail rfd ON rf.rfid = rfd.idrf JOIN m1_item_hauling ih ON rfd.idbarang = ih.bid JOIN m1_contact k ON rf.rfdimintaoleh = k.kid JOIN m0_status st ON rf.rfstatus = st.kode ORDER BY rf.rfnotransaksi, ih.bkode, rf.rftgl, k.knama;

-- RID=824 | MODULE=3 | MENU=40 | ITEM=5 | RQUERY=1 | NAME=Pengisian Bahan Bakar (RF) | FILE=pengisianbahanbakardetail2
SELECT rf.rfdimintaoleh, k.knama AS dimintaoleh, ih.bkode AS kodebarang, rf.rfnotransaksi, rf.rftgl, rfd.catatan, rf.rfcustomtext1 AS jampengisian, rf.rfuraian, rfd.namabarang, rfd.satuan, rfd.jml, rfd.stokterakhir AS hourmeter, st.nama AS statusrf FROM m3_rf rf JOIN m3_rf_detail rfd ON rf.rfid = rfd.idrf JOIN m1_item_hauling ih ON rfd.idbarang = ih.bid JOIN m1_contact k ON rf.rfdimintaoleh = k.kid JOIN m0_status st ON rf.rfstatus = st.kode ORDER BY rf.rfnotransaksi, ih.bkode, rf.rftgl, k.knama;

-- RID=830 | MODULE=3 | MENU=41 | ITEM=1 | RQUERY=1 | NAME=Daftar Time Sheet / Daily Check (DC) | FILE=ListTimeSheet
SELECT dc.dcid , kk.knama AS dcmintake , dc.dcnotransaksi, dc.dctgl, CASE dc.dcshift WHEN 1 THEN "Night" WHEN 0 THEN "DAY" END AS dcshift , (CASE dc.dcstatus WHEN 0 THEN 'Draft' WHEN 1 THEN 'Minta Approve' WHEN 2 THEN 'Approved' WHEN 3 THEN 'Inprogress' WHEN 4 THEN 'Complete' WHEN 5 THEN 'Revisi' WHEN 6 THEN 'Reject' WHEN 7 THEN 'Close' WHEN 8 THEN 'Approve1' WHEN 9 THEN 'Approve2' WHEN 10 THEN 'Approve3' WHEN 11 THEN 'Approve4' WHEN 12 THEN 'Hapus' END) AS dcstatus, k.knama AS dcdimintaoleh , b.bkode , dc.dcnamabarang , dc.dchmstart , dc.dchmstop , (dc.dchmstop - dc.dchmstart) as total , dcd.opstart, dcd.opend , dcd.sbstart, dcd.sbend, dcd.spstart, dcd.spend, dcd.rfstart , dcd.rfend, dcd.bdstart, dcd.bdend, dcd.catatan FROM m3_dc dc JOIN m1_contact kk ON dc.dcmintake = kk.kid JOIN m1_item b ON dc.dcidbarang = b.bid JOIN m3_dc_detail dcd ON dc.dcid = dcd.iddc LEFT JOIN m1_contact k ON dc.dcdimintaoleh = k.kid LEFT JOIN m1_location l ON dc.dclokasi = l.lkode ORDER BY dc.dcid, dc.dcnotransaksi, dcd.urutan;

-- RID=825 | MODULE=3 | MENU=41 | ITEM=2 | RQUERY=1 | NAME=Time Sheet / Daily Check (DC) | FILE=TimeSheet
SELECT dc.dcid , kk.knama AS dcmintake , dc.dcnotransaksi, dc.dctgl, CASE dc.dcshift WHEN 1 THEN "Night" WHEN 0 THEN "DAY" END AS dcshift , (CASE dc.dcstatus WHEN 0 THEN 'Draft' WHEN 1 THEN 'Minta Approve' WHEN 2 THEN 'Approved' WHEN 3 THEN 'Inprogress' WHEN 4 THEN 'Complete' WHEN 5 THEN 'Revisi' WHEN 6 THEN 'Reject' WHEN 7 THEN 'Close' WHEN 8 THEN 'Approve1' WHEN 9 THEN 'Approve2' WHEN 10 THEN 'Approve3' WHEN 11 THEN 'Approve4' WHEN 12 THEN 'Hapus' END) AS dcstatus, k.knama AS dcdimintaoleh , b.bkode , dc.dcnamabarang , dc.dchmstart , dc.dchmstop , (dc.dchmstop - dc.dchmstart) as total , dcd.opstart, dcd.opend , dcd.sbstart, dcd.sbend, dcd.spstart, dcd.spend, dcd.rfstart , dcd.rfend, dcd.bdstart, dcd.bdend, dcd.catatan FROM m3_dc dc LEFT JOIN m1_location l ON dc.dclokasi = l.lkode JOIN m1_contact kk ON dc.dcmintake = kk.kid JOIN m1_item b ON dc.dcidbarang = b.bid JOIN m3_dc_detail dcd ON dc.dcid = dcd.iddc LEFT JOIN m1_contact k ON dc.dcdimintaoleh = k.kid ORDER BY dc.dcid, dc.dcnotransaksi, dcd.urutan;

