-- m0_report full queries for rmoduleid = 11
-- total rows: 69

-- RID=1447 | MENU=3 | ITEM=1 | RQUERY=1 | NAME=Laporan Daftar Kunjungan | FILE=kunjunganglobal
SELECT kj.kjtgl, kj.kjnotransaksi , kj.kjnopasien, YEAR(kj.kjtglkeluar) AS a , kj.kjtglkeluar , YEAR(kj.kjtglmeninggal) AS b , kj.kjtglmeninggal , CASE kj.kjcarakunjungan WHEN 1 THEN 'Datang Sendiri' WHEN 2 THEN 'Rujukan' END AS kjcarakunjungan , r.rnama AS kjdirujukoleh , i.inama AS kjditanggungoleh , st.nama AS kjstatus , p.pnama AS namapasien , p.palamat AS alamatpasien , CONCAT(p.pkeluargalain," ",p.pnoteleponlain) AS keluargapasien, p.ptgllahir , CASE p.pjeniskelamin WHEN "P" THEN "Perempuan" WHEN "L" THEN "Laki - Laki" END AS pjeniskelamin, p.pnohp FROM m_11_kj kj JOIN m0_status st ON kj.kjstatus = st.kode LEFT JOIN m1_reference r ON kj.kjdirujukoleh = r.rid LEFT JOIN m1_insurer i ON kj.kjditanggungoleh = i.iid LEFT JOIN m1_patient p ON kj.kjnopasien = p.pkode ORDER BY kj.kjnotransaksi;

-- RID=1396 | MENU=3 | ITEM=3 | RQUERY=1 | NAME=Kwitansi | FILE=kunjungankwitansi
SELECT kj.kjnotransaksi , p.pnama , p.pprefix , u.ukode AS ukode, u.unama AS unama FROM m_11_kj kj JOIN m1_patient p ON kj.kjnopasien = p.pkode JOIN m0_user u ON kj.kjinputuser = u.userid ORDER BY kj.kjnotransaksi;

-- RID=1684 | MENU=3 | ITEM=5 | RQUERY=1 | NAME=Daftar Asuransi Kunjungan | FILE=kunjungan
SELECT kj.kjtgl , kj.kjnotransaksi , kj.kjnopasien , kj.kjnama , kj.kjditanggungoleh , i.inama AS asuransi , kj.kjtglkeluar , YEAR(kj.kjtglkeluar) AS tahun FROM m_11_kj kj LEFT JOIN m1_insurer i ON kj.kjditanggungoleh = i.iid ORDER BY kj.kjtgl ASC;

-- RID=1397 | MENU=4 | ITEM=1 | RQUERY=1 | NAME=Daftar Layanan Umum | FILE=layananumumglobal
SELECT kj.kjnotransaksi , kj.kjtgl , lu.lunotransaksi , lu.lutgl , st.nama , kj.kjnopasien, kj.kjnama , ic.icnama AS jenis , b.bkode , lud.namalayanan, lud.jml , lud.satuan , lud.diskon , lud.harga , ((lud.jml * lud.harga) - lud.jmldiskon) AS total , userr.ukode AS usernama , lud.namadokter FROM m_11_lu lu JOIN m_11_kj kj ON lu.luidkj = kj.kjid JOIN m0_status st ON lu.lustatus = st.kode JOIN m_11_lu_detail lud ON lu.luid = lud.idlu JOIN m1_item_category ic ON lud.jenis = ic.ickode JOIN m1_item b ON lud.idlayanan = b.bid JOIN m0_user userr ON lu.luinputuser = userr.userid ORDER BY lu.luid , lud.urutan;

-- RID=1398 | MENU=4 | ITEM=2 | RQUERY=1 | NAME=Layanan Umum | FILE=layananumum
SELECT kj.kjnotransaksi , kj.kjtgl , lu.lunotransaksi , lu.lutgl , st.nama , kj.kjnopasien, kj.kjnama , ic.icnama AS jenis , b.bkode , lud.namalayanan, lud.jml , lud.satuan , lud.diskon , lud.harga , ((lud.jml * lud.harga) - lud.jmldiskon) AS total , userr.ukode AS usernama , lud.namadokter FROM m1_room r JOIN m1_bed b ON r.rnama = b.bkamar ORDER BY lu.luid , lud.urutan;

-- RID=1399 | MENU=5 | ITEM=1 | RQUERY=1 | NAME=Daftar Laboraturium | FILE=laboraturiumglobal
SELECT userrr.ukode AS usrenama , lb.lbnotransaksi , lb.lbtgl , kj.kjnotransaksi , kj.kjtgl , st.nama , p.pkode , p.pnama , ic.icnama , b.bkode , lbd.namalayanan , lbd.jml , lbd.satuan , lbd.diskon , lbd.harga , ((lbd.jml * lbd.harga) - lbd.jmldiskon) AS total , lbd.namadokter FROM m_11_lb lb JOIN m_11_kj kj ON lb.lbidkj = kj.kjid JOIN m1_patient p ON kj.kjnopasien = p.pkode JOIN m0_status st ON lb.lbstatus = st.kode JOIN m_11_lb_detail lbd ON lb.lbid = lbd.idlb JOIN m1_item b ON lbd.idlayanan = b.bid JOIN m0_user userrr ON lb.lbinputuser = userrr.userid LEFT JOIN m1_item_category ic ON lbd.jenis = ic.ickode ORDER BY lb.lbidkj , lb.lbid , lbd.urutan;

-- RID=1400 | MENU=5 | ITEM=2 | RQUERY=1 | NAME=Laboratorium | FILE=laboraturium
SELECT userrr.ukode AS usrenama , lb.lbnotransaksi , lb.lbtgl , kj.kjnotransaksi , kj.kjtgl , st.nama , p.pkode , p.pnama , ic.icnama , b.bkode , lbd.namalayanan , lbd.jml , lbd.satuan , lbd.diskon , lbd.harga , ((lbd.jml * lbd.harga) - lbd.jmldiskon) AS total , lbd.namadokter FROM m_11_lb lb JOIN m_11_kj kj ON lb.lbidkj = kj.kjid JOIN m1_patient p ON kj.kjnopasien = p.pkode JOIN m0_status st ON lb.lbstatus = st.kode JOIN m_11_lb_detail lbd ON lb.lbid = lbd.idlb JOIN m1_item_category ic ON lbd.jenis = ic.ickode JOIN m1_item b ON lbd.idlayanan = b.bid JOIN m0_user userrr ON lb.lbinputuser = userrr.userid ORDER BY lb.lbidkj , lb.lbid , lbd.urutan;

-- RID=1401 | MENU=5 | ITEM=3 | RQUERY=1 | NAME=Hasil Laboraturium | FILE=laboraturium2
SELECT lb.lbid , pc.pcnama AS lbkategoripasien , kj.kjnopasien , kj.kjnama , CASE lb.lbjenislab WHEN "LL" THEN "Lab Luar" WHEN "LD" THEN "Lab Dalam" END AS lbjenislab , CASE lb.lbperawatan WHEN "RJ" THEN "Rawat Jalan" WHEN "RI" THEN "Rawat Inap" END AS lbperawatan , lb.lbtgl , lb.lbnotransaksi , kj.kjnotransaksi , k.knama AS lbdokter , lb.lbkamar FROM m_11_lb lb JOIN m1_patient_category pc ON lb.lbkategoripasien = pc.pckode LEFT JOIN m_11_kj kj ON lb.lbidkj = kj.kjid LEFT JOIN m1_contact k ON lb.lbdokter = k.kkode ORDER BY lb.lbid;

-- RID=1570 | MENU=5 | ITEM=4 | RQUERY=1 | NAME=Daftar Laboraturium  | FILE=DaftarLaboraturium
SELECT lb.lbtgl , lb.lbnotransaksi , kj.kjnopasien , kj.kjnama , SUM(lbd.jml * lbd.harga) AS total , (SUM(lbd.jml * lbd.harga) * 0.1 ) AS JP, CASE lb.lbperawatan WHEN "RI" THEN "Rawat Inap" WHEN "RJ" THEN "Rawat Jalan" END AS lbperawatan , pc.pcnama AS lbkategoripasien FROM m_11_lb lb JOIN m_11_lb_detail lbd on lb.lbid = lbd.idlb LEFT JOIN m_11_kj kj ON lb.lbidkj = kj.kjid LEFT JOIN m1_patient_category pc ON lb.lbkategoripasien = pc.pckode WHERE (lb.lbstatus = 2 OR lb.lbstatus = 3 OR lb.lbstatus = 4 OR lb.lbstatus = 7) GROUP BY lb.lbid ORDER BY lb.lbid;

-- RID=1571 | MENU=5 | ITEM=5 | RQUERY=1 | NAME=Pemerikasaan Laboratorium | FILE=PemerikasaanLaboratorium
SELECT b.bid , b.bkode , b.bnama , lbd.namalayanan , lb.lbtgl , YEAR(lb.lbtgl) AS tahun , day(lb.lbtgl) AS tanggal , CASE lb.lbperawatan WHEN "RI" THEN "Rawat Inap" WHEN "RJ" THEN "Rawat Jalan" END AS lbperawatan , pc.pcnama AS lbkategoripasien FROM m1_item b LEFT JOIN m_11_lb_detail lbd ON lbd.idlayanan = b.bid LEFT JOIN m_11_lb lb ON lbd.idlb = lb.lbid LEFT JOIN m1_patient_category pc ON lb.lbkategoripasien = pc.pckode WHERE b.bkategori = "Lab" ORDER BY b.bid , day(lb.lbtgl) ASC;

-- RID=1573 | MENU=5 | ITEM=6 | RQUERY=1 | NAME=CN | FILE=CN
SELECT lb.lbtgl , lb.lbnotransaksi , CASE lb.lbpenjualanlangsung WHEN 0 THEN p.pnama WHEN 1 THEN k.knama END AS pnama, lb.lbtotaltransaksi , kd.knama AS lbdokter FROM m_11_lb lb LEFT JOIN m1_patient p ON p.pid = lb.lbcustomer AND lb.lbpenjualanlangsung = 0 LEFT JOIN m1_contact k ON k.kid = lb.lbcustomer AND lb.lbpenjualanlangsung = 1 LEFT JOIN m1_contact kd ON lb.lbdokter = kd.kkode ORDER BY lb.lbid;

-- RID=1402 | MENU=6 | ITEM=1 | RQUERY=1 | NAME=Laporan Apotek  | FILE=apotek
SELECT ak.aknotransaksi , ak.aktgl , kj.kjnotransaksi, kj.kjtgl , kj.kjnopasien , kj.kjnama, b.bkode , akd.namalayanan , akd.jml , akd.satuan , akd.harga , akd.diskon , ((akd.jml * akd.harga) - akd.jmldiskon) AS total , ic.icnama AS jenis , u.ukode as usernama FROM m_11_ak ak JOIN m_11_ak_detail akd ON ak.akid = akd.idak JOIN m_11_kj kj ON akd.idkjdetail = kj.kjid JOIN m1_item_category ic ON akd.jenis = ic.ickode JOIN m1_item b ON akd.idlayanan = b.bid JOIN m0_user u ON ak.akinputuser = u.userid ORDER BY ak.aknotransaksi , kj.kjnotransaksi;

-- RID=1404 | MENU=6 | ITEM=2 | RQUERY=1 | NAME=Laporan Apotek  | FILE=apotekdetail2
SELECT ak.aknotransaksi , ak.aktgl , kj.kjnotransaksi, kj.kjtgl , kj.kjnopasien , kj.kjnama, b.bkode , akd.namalayanan , akd.jml , akd.satuan , akd.harga , akd.diskon , ((akd.jml * akd.harga) - akd.jmldiskon) AS total , ic.icnama AS jenis , u.ukode as usernama FROM m_11_ak ak JOIN m_11_ak_detail akd ON ak.akid = akd.idak LEFT JOIN m_11_kj kj ON ak.akidkj = kj.kjid JOIN m1_item b ON akd.idlayanan = b.bid LEFT JOIN m1_contact k ON ak.akpetugas = k.kid LEFT JOIN m1_contact kd ON ak.akdokter = kd.kkode LEFT JOIN m1_patient_category pc ON kj.kjkategoripasien = pc.pckode ORDER BY ak.aknotransaksi , kj.kjnotransaksi;

-- RID=1403 | MENU=6 | ITEM=3 | RQUERY=1 | NAME=BON PENJUALAN OBAT | FILE=apoteknota
SELECT ak.akid , ak.aktgl , ak.aknoref , kj.kjnopasien , kj.kjnama , akd.idlayanan , (akd.jml * akd.harga) AS total , ak.akresep , ak.akracik, ak.akembalase FROM m_11_lu lu JOIN m_11_kj kj ON lu.luidkj = kj.kjid JOIN m0_status st ON lu.lustatus = st.kode JOIN m_11_lu_detail lud ON lu.luid = lud.idlu JOIN m1_item_category ic ON lud.jenis = ic.ickode JOIN m1_item b ON lud.idlayanan = b.bid JOIN m0_user userr ON lu.luinputuser = userr.userid ORDER BY ak.akid , ak.aktgl , akd.urutan;

-- RID=1416 | MENU=6 | ITEM=4 | RQUERY=1 | NAME=NOTA PENJUALAN RAWAT INAP BPJS | FILE=notapenjualanrawatinap
SELECT ak.akid , ak.aknoref AS noresep , kj.kjnopasien , kj.kjnama , kj.kjumur , ak.akkategoripasien , ak.akkamar , kd.knama AS akdokter , ak.aktgl , ak.aknotransaksi , b.bkode , akd.namalayanan, akd.jml , akd.satuan , akd.harga , (akd.jml * akd.harga) AS total , k.knama AS akpetugas , ak.akresep , ak.akracik, ak.akembalase FROM m_11_ak ak JOIN m_11_ak_detail akd ON ak.akid = akd.idak JOIN m1_item b ON akd.idlayanan = b.bid LEFT JOIN m_11_kj kj ON ak.akidkj = kj.kjid LEFT JOIN m1_contact k ON ak.akpetugas = k.kid LEFT JOIN m1_contact kd ON ak.akdokter = kd.kkode WHERE (ak.akperawatan = "RI") AND (ak.akkategoripasien = "BPJS") ORDER BY ak.akid , ak.aktgl , akd.urutan;

-- RID=1417 | MENU=6 | ITEM=5 | RQUERY=1 | NAME=PENJUALAN PERLENGKAPAN PERAWATAN | FILE=penjualanperlengkapanperawatan
SELECT kj.kjnopasien , kj.kjnama , ak.akkamar , ak.akcatatan , ak.aktgl , ak.aknotransaksi , ak.aknoref AS noresep , b.bkode , akd.namalayanan, akd.jml , akd.satuan , akd.harga , (akd.jml * akd.harga) AS total , k.knama AS akpetugas , ak.akresep , ak.akracik, ak.akembalase FROM m_11_ak ak JOIN m_11_ak_detail akd ON ak.akid = akd.idak JOIN m_11_kj kj ON ak.akidkj = kj.kjid JOIN m1_item b ON akd.idlayanan = b.bid LEFT JOIN m1_contact k ON ak.akpetugas = k.kid ORDER BY ak.akid , ak.aktgl , akd.urutan;

-- RID=1406 | MENU=6 | ITEM=6 | RQUERY=1 | NAME=PENJUALAN OBAT RAWAT INAP | FILE=PenjualanObatRI
SELECT ak.akid , ak.aktgl , ak.aknoref , kj.kjnopasien , kj.kjnama , akd.idlayanan , (akd.jml * akd.harga) AS total , ak.akresep , ak.akracik, ak.akembalase FROM m_11_ak ak JOIN m_11_ak_detail akd ON ak.akid = akd.idak LEFT JOIN m_11_kj kj ON ak.akidkj = kj.kjid WHERE ak.akperawatan = "RI" ORDER BY ak.aktgl , ak.akid;

-- RID=1407 | MENU=6 | ITEM=7 | RQUERY=1 | NAME=PENJUALAN OBAT RAWAT INAP SUDAH TERBAYAR | FILE=PenjualanObatRI_sudahterbayar
SELECT ak.akid , ak.aktgl , ak.aknoref , kj.kjnopasien , kj.kjnama , akd.idlayanan , (akd.jml * akd.harga) AS total , ak.akresep , ak.akracik, ak.akembalase FROM m_11_ak ak JOIN m_11_ak_detail akd ON ak.akid = akd.idak LEFT JOIN m_11_kj kj ON ak.akidkj = kj.kjid WHERE ak.akperawatan = "RI" ORDER BY ak.aktgl , ak.akid;

-- RID=1408 | MENU=6 | ITEM=8 | RQUERY=1 | NAME=PENJUALAN OBAT RAWAT INAP BELUM TERBAYAR | FILE=PenjualanObatRI_blmterbayar
SELECT ak.akid , ak.aktgl , ak.aknoref , kj.kjnopasien , kj.kjnama , akd.idlayanan , (akd.jml * akd.harga) AS total , ak.akresep , ak.akracik, ak.akembalase FROM m_11_ak ak JOIN m_11_ak_detail akd ON ak.akid = akd.idak LEFT JOIN m_11_kj kj ON ak.akidkj = kj.kjid WHERE ak.akperawatan = "RI" ORDER BY ak.aktgl , ak.akid;

-- RID=1409 | MENU=6 | ITEM=9 | RQUERY=1 | NAME=PENJUALAN OBAT RAWAT INAP BPJS | FILE=PenjualanObatRI_BPJS
SELECT ak.akid , ak.aktgl , ak.aknoref , kj.kjnopasien , kj.kjnama , akd.idlayanan , (akd.jml * akd.harga) AS total , ak.akresep , ak.akracik, ak.akembalase FROM m_11_ak ak JOIN m_11_ak_detail akd ON ak.akid = akd.idak LEFT JOIN m_11_kj kj ON ak.akidkj = kj.kjid WHERE (ak.akperawatan = "RI") AND (ak.akkategoripasien = "BPJS") ORDER BY ak.aktgl , ak.akid;

-- RID=1410 | MENU=6 | ITEM=10 | RQUERY=1 | NAME=PENJUALAN OBAT RAWAT INAP BPJS SUDAH TERBAYAR | FILE=PenjualanObatRI_BPJSSudahTerbayar
SELECT ak.akid , ak.aktgl , ak.aknoref , kj.kjnopasien , kj.kjnama , akd.idlayanan , (akd.jml * akd.harga) AS total , ak.akresep , ak.akracik, ak.akembalase FROM m_11_ak ak JOIN m_11_ak_detail akd ON ak.akid = akd.idak LEFT JOIN m_11_kj kj ON ak.akidkj = kj.kjid WHERE (ak.akperawatan = "RI") AND (ak.akkategoripasien = "BPJS") ORDER BY ak.aktgl , ak.akid;

-- RID=1411 | MENU=6 | ITEM=11 | RQUERY=1 | NAME=PENJUALAN OBAT RAWAT INAP BPJS BELUM TERBAYAR | FILE=PenjualanObatRI_BPJSBelumTerbayar
SELECT ak.akid , ak.aktgl , ak.aknoref , kj.kjnopasien , kj.kjnama , akd.idlayanan , (akd.jml * akd.harga) AS total , ak.akresep , ak.akracik, ak.akembalase FROM m_11_ak ak JOIN m_11_ak_detail akd ON ak.akid = akd.idak LEFT JOIN m_11_kj kj ON ak.akidkj = kj.kjid WHERE (ak.akperawatan = "RI") AND (ak.akkategoripasien = "BPJS") ORDER BY ak.aktgl , ak.akid;

-- RID=1412 | MENU=6 | ITEM=12 | RQUERY=1 | NAME=PENJUALAN OBAT RAWAT JALAN  | FILE=PenjualanObatRJ
SELECT ak.akid , ak.aktgl , ak.aknoref , kj.kjnopasien , kj.kjnama , akd.idlayanan , (akd.jml * akd.harga) AS total , ak.akresep , ak.akracik, ak.akembalase FROM m_11_ak ak JOIN m_11_ak_detail akd ON ak.akid = akd.idak LEFT JOIN m_11_kj kj ON ak.akidkj = kj.kjid WHERE ak.akperawatan = "RJ" ORDER BY ak.aktgl , ak.akid;

-- RID=1413 | MENU=6 | ITEM=13 | RQUERY=1 | NAME=PENJUALAN OBAT RAWAT JALAN SUDAH TERBAYAR | FILE=PenjualanObatRJ_sudahterbayar
SELECT ak.akid , ak.aktgl , ak.aknoref , kj.kjnopasien , kj.kjnama , akd.idlayanan , (akd.jml * akd.harga) AS total , ak.akresep , ak.akracik, ak.akembalase FROM m_11_ak ak JOIN m_11_ak_detail akd ON ak.akid = akd.idak LEFT JOIN m_11_kj kj ON ak.akidkj = kj.kjid WHERE ak.akperawatan = "RJ" ORDER BY ak.aktgl , ak.akid;

-- RID=1414 | MENU=6 | ITEM=14 | RQUERY=1 | NAME=PENJUALAN OBAT RAWAT JALAN BELUM TERBAYAR | FILE=PenjualanObatRJ_belumterbayar
SELECT ak.akid , ak.aktgl , ak.aknoref , kj.kjnopasien , kj.kjnama , akd.idlayanan , (akd.jml * akd.harga) AS total , ak.akresep , ak.akracik, ak.akembalase FROM m_11_ak ak JOIN m_11_ak_detail akd ON ak.akid = akd.idak LEFT JOIN m_11_kj kj ON ak.akidkj = kj.kjid WHERE ak.akperawatan = "RJ" ORDER BY ak.aktgl , ak.akid;

-- RID=1415 | MENU=6 | ITEM=17 | RQUERY=1 | NAME=PENJUALAN PEMAKAIAN SENDIRI UNIT IGD | FILE=PenjualanPemakaian_SendiriUnitIGD
SELECT ak.aktgl , ak.aknoref , ak.aknotransaksi , "KONTAK" AS dimintaoleh , akd.namalayanan , SUM(akd.jml) AS jml , akd.satuan , akd.harga , SUM(akd.jml * akd.harga) AS total , akd.catatan FROM m_11_ak ak JOIN m_11_ak_detail akd ON ak.akid = akd.idak GROUP BY ak.aktgl , ak.aknoref , ak.aknotransaksi , akd.idlayanan ORDER BY ak.aktgl , ak.aknoref , ak.aknotransaksi;

-- RID=1405 | MENU=6 | ITEM=18 | RQUERY=1 | NAME=BON PENJUALAN OBAT | FILE=apoteknota2
SELECT f_nominal(ak.aktotaltransaksi, ak.akmatauang) AS terbilang , ak.aktotaltransaksi , kj.kjnopasien , kj.kjnama , CASE kj.kjperawatan WHEN "RI" THEN "Rawat Inap" WHEN "RJ" THEN "Rawat Jalan" END AS kjperawatan , pc.pcnama AS kjkategoripasien , ak.akkamar , ak.akcatatan , ak.aktgl , ak.aknotransaksi , ak.aknoref AS noresep , kd.knama AS akdokter , b.bkode , akd.namalayanan, akd.jml , akd.satuan , akd.harga , (akd.jml * akd.harga) AS total , k.knama AS akpetugas , ak.akresep , ak.akracik, ak.akembalase , (ak.akresep + ak.akracik + ak.akembalase ) AS bagi FROM m_11_ak ak JOIN m_11_ak_detail akd ON ak.akid = akd.idak JOIN m1_item b ON akd.idlayanan = b.bid LEFT JOIN m_11_kj kj ON ak.akidkj = kj.kjid LEFT JOIN m1_contact k ON ak.akpetugas = k.kid LEFT JOIN m1_contact kd ON ak.akdokter = kd.kkode LEFT JOIN m1_patient_category pc ON kj.kjkategoripasien = pc.pckode ORDER BY ak.akid , ak.aktgl , akd.urutan;

-- RID=1467 | MENU=6 | ITEM=19 | RQUERY=1 | NAME=Daftar Penjualan Apotek  | FILE=DaftarPenjualanApotek
SELECT ak.aknotransaksi , ak.akid , ak.aktgl , ak.aknoref , kj.kjnopasien , kj.kjnama , akd.idlayanan , SUM(akd.jml * akd.harga) AS total , ak.akresep , ak.akracik, ak.akembalase, CASE ak.akperawatan WHEN "RI" THEN "Rawat Inap" WHEN "RJ" THEN "Rawat Jalan" END AS akperawatan , pc.pcnama AS kjkategoripasien , ak.akuraian FROM m_11_ak ak JOIN m_11_ak_detail akd ON ak.akid = akd.idak LEFT JOIN m_11_kj kj ON ak.akidkj = kj.kjid LEFT JOIN m1_patient_category pc ON ak.akkategoripasien = pc.pckode WHERE (ak.akstatus = 2 or ak.akstatus = 3 or ak.akstatus = 4 or ak.akstatus = 7) GROUP BY ak.akid;

-- RID=1569 | MENU=6 | ITEM=20 | RQUERY=1 | NAME=Daftar Penjualan Obat Terlaris | FILE=DaftarPenjualanObatTerlaris
SELECT akd.idlayanan , b.bkode , b.bnama , SUM(akd.jml) AS jml , akd.satuan, CASE ak.akperawatan WHEN "RI" THEN "Rawat Inap" WHEN "RJ" THEN "Rawat Jalan" END AS akperawatan , pc.pcnama AS akkategoripasien FROM m_11_ak ak JOIN m_11_ak_detail akd ON ak.akid = akd.idak JOIN m1_item b ON akd.idlayanan = b.bid LEFT JOIN m1_patient_category pc ON ak.akkategoripasien = pc.pckode GROUP BY akd.idlayanan ORDER BY SUM(akd.jml) DESC;

-- RID=50000569 | MENU=6 | ITEM=30 | RQUERY=1 | NAME=Laporan Penggunaan Obat | FILE=laporan_penggunaan_obat
SELECT ak.akdokter , k.knama AS akdokternama, namadokter , MONTH(ak.aktgl) AS bulan , YEAR(ak.aktgl) AS tahun , b.bkode , b.bnama , b.bcustom1 , ak.akperawatan , akd.jml FROM m_11_ak ak JOIN m_11_ak_detail akd ON ak.akid = akd.idak JOIN m1_item b ON akd.idlayanan = b.bid LEFT JOIN m1_contact k ON ak.akdokter = k.kid ORDER BY ak.aktgl ASC , ak.akdokter ASC , akd.idlayanan ASC;

-- RID=1418 | MENU=7 | ITEM=1 | RQUERY=1 | NAME=Daftar Kamar dan Kasur | FILE=kamarglobal
SELECT kj.kjnotransaksi , kj.kjtgl, kj.kjnopasien , kj.kjnama , st.nama AS kmstatus , km.kmnotransaksi , km.kmtgl , km.kmtglmasuk, km.kmkamar , km.kmkasur , km.kmtglkeluar, km.kmjmlhari , km.kmcatatan FROM m_11_km km JOIN m_11_kj kj ON km.kmidkj = kj.kjid JOIN m0_status st ON km.kmstatus = st.kode ORDER BY kj.kjnotransaksi , kj.kjnopasien , km.kmnotransaksi;

-- RID=1419 | MENU=20 | ITEM=1 | RQUERY=1 | NAME=Daftar Rekanan  | FILE=rekananDetailGlobal
SELECT kj.kjnotransaksi , c.cnama AS rekanan, rk.rknorek, coa.cnama AS akunD, rk.rkuraian, rk.rknotransaksi , rk.rktgl , rk.rkmatauang , st.nama AS rkstatus , pm.nama AS carabayar , rkp.rekbank, coaa.cnama AS namaakun, rkp.bank , rkp.noacbank , rkp.jumlah , rkp.nogiro , rkp.tgljt FROM m_11_rk rk LEFT JOIN m_11_kj kj ON rk.rkidkj = kj.kjid LEFT JOIN m1_colleague c ON rk.rkkontak = c.cid LEFT JOIN m1_coa coa ON rk.rknorek = coa.cnomor LEFT JOIN m0_status st ON rk.rkstatus = st.kode LEFT JOIN m_11_rk_pay rkp ON rk.rkid = rkp.idrk LEFT JOIN m0_payment_method pm ON rkp.carabayar = pm.kode LEFT JOIN m1_coa coaa ON rkp.rekbank = coaa.cnomor ORDER BY rk.rkid , rkp.urutan;

-- RID=1420 | MENU=20 | ITEM=2 | RQUERY=1 | NAME=Rekanan | FILE=rekananDetail1
SELECT rk.rkid , rkp.idrkcarabayar , kj.kjnotransaksi , c.cnama AS rekanan, rk.rknorek, coa.cnama AS akunD, rk.rkuraian, rk.rknotransaksi , rk.rktgl , rk.rkmatauang , st.nama AS rkstatus , pm.nama AS carabayar , rkp.rekbank, coaa.cnama AS namaakun, rkp.bank , rkp.noacbank , rkp.jumlah , rkp.nogiro , rkp.tgljt FROM m_11_rk rk LEFT JOIN m_11_kj kj ON rk.rkidkj = kj.kjid LEFT JOIN m1_colleague c ON rk.rkkontak = c.cid LEFT JOIN m1_coa coa ON rk.rknorek = coa.cnomor LEFT JOIN m0_status st ON rk.rkstatus = st.kode LEFT JOIN m_11_rk_pay rkp ON rk.rkid = rkp.idrk LEFT JOIN m0_payment_method pm ON rkp.carabayar = pm.kode LEFT JOIN m1_coa coaa ON rkp.rekbank = coaa.cnomor ORDER BY rk.rkid , rkp.urutan;

-- RID=1421 | MENU=20 | ITEM=3 | RQUERY=1 | NAME=Rekanan | FILE=rekananDetail2
SELECT kj.kjnotransaksi , c.cnama AS rekanan, rk.rknorek, coa.cnama AS akunD, rk.rkuraian, rk.rknotransaksi , rk.rktgl , rk.rkmatauang , st.nama AS rkstatus , pm.nama AS carabayar , rkp.rekbank, coaa.cnama AS namaakun, rkp.bank , rkp.noacbank , rkp.jumlah , rkp.nogiro , rkp.tgljt FROM m_11_rk rk JOIN m_11_kj kj ON rk.rkidkj = kj.kjid JOIN m1_colleague c ON rk.rkkontak = c.cid JOIN m1_coa coa ON rk.rknorek = coa.cnomor JOIN m0_status st ON rk.rkstatus = st.kode JOIN m_11_rk_pay rkp ON rk.rkid = rkp.idrk JOIN m0_payment_method pm ON rkp.carabayar = pm.kode JOIN m1_coa coaa ON rkp.rekbank = coaa.cnomor ORDER BY rk.rkid , rkp.urutan;

-- RID=1568 | MENU=20 | ITEM=4 | RQUERY=1 | NAME=Daftar Rekanan | FILE=DaftarRekanan
SELECT rk.rktgl , rk.rknotransaksi , kj.kjnama , rk.rkuraian , SUM(rkp.jumlah) AS jumlah , case rk.rkkategori WHEN 0 THEN "Apotek Luar" WHEN 1 THEN "Labe Luar" WHEN 2 THEN "Lain - Lain" END AS rkkategori , CASE rk.rkperawatan WHEN "RI" THEN "Rawat Inap" WHEN "RJ" THEN "Rawat Jalan" END AS rkperawatan , pc.pcnama AS kjkategoripasien , c.cnama FROM m_11_rk rk LEFT JOIN m_11_kj kj ON rk.rkidkj = kj.kjid LEFT JOIN m_11_rk_pay rkp ON rk.rkid = rkp.idrk LEFT JOIN m1_patient_category pc ON kj.kjkategoripasien = pc.pckode LEFT JOIN m1_colleague c ON rk.rkkontak = c.cid GROUP BY rk.rkid ORDER BY rk.rktgl , rk.rkid , rkp.urutan;

-- RID=1422 | MENU=22 | ITEM=1 | RQUERY=1 | NAME=Daftar Pembayaran Tagihan | FILE=PembayaranTagihanGlobal
SELECT kj.kjnotransaksi, pb.pbnorek , c.cnama , pb.pburaian , pb.pbtgl , pb.pbnotransaksi, pb.pbmatauang, st.nama , pm.nama AS carabayar , pbp.rekbank AS noakun, cc.cnama AS namaakun, pbp.bank, pbp.noacbank , pbp.jumlah, pbp.nogiro, pbp.tgljt FROM m_11_pb pb JOIN m_11_kj kj ON pb.pbidkj = kj.kjid LEFT JOIN m1_coa c ON pb.pbnorek = c.cnomor JOIN m_11_pb_pay pbp ON pb.pbid = pbp.idpb JOIN m0_status st ON pb.pbstatus = st.kode JOIN m0_payment_method pm ON pbp.carabayar = pm.kode JOIN m1_coa cc ON pbp.rekbank = cc.cnomor ORDER BY pb.pbid , pbp.urutan;

-- RID=1423 | MENU=22 | ITEM=2 | RQUERY=1 | NAME=Pembayaran Tagihan  | FILE=PembayaranTagihan
SELECT kj.kjnotransaksi, pb.pbnorek , c.cnama , pb.pburaian , pb.pbtgl , pb.pbnotransaksi, pb.pbmatauang, st.nama , pm.nama AS carabayar , pbp.rekbank AS noakun, cc.cnama AS namaakun, pbp.bank, pbp.noacbank , pbp.jumlah, pbp.nogiro, pbp.tgljt FROM m_11_pb pb JOIN m_11_kj kj ON pb.pbidkj = kj.kjid LEFT JOIN m1_coa c ON pb.pbnorek = c.cnomor JOIN m_11_pb_pay pbp ON pb.pbid = pbp.idpb JOIN m0_status st ON pb.pbstatus = st.kode JOIN m0_payment_method pm ON pbp.carabayar = pm.kode JOIN m1_coa cc ON pbp.rekbank = cc.cnomor ORDER BY pb.pbid , pbp.urutan;

-- RID=1424 | MENU=22 | ITEM=3 | RQUERY=1 | NAME=Pembayaran Tagihan | FILE=PembayaranTagihan2
SELECT rm.rmperawatan, rm.rmlayanan, l.lnama , rm.rmkasus , SUM((SELECT COUNT(*) FROM m_11_rm rms WHERE rms.rmkasus = 1 AND rms.rmid = rm.rmid )) as Baru , SUM((SELECT COUNT(*) FROM m_11_rm rms1 WHERE rms1.rmkasus = 2 AND rms1.rmid = rm.rmid )) as Lama FROM m_11_rm rm JOIN m1_layanan l ON rm.rmlayanan = l.lkode ORDER BY pb.pbid , pbp.urutan;

-- RID=14223 | MENU=22 | ITEM=4 | RQUERY=1 | NAME=Laporan Rekap Pembayaran | FILE=rekap_pb
SELECT pb.pvtgl , pbd.rekhutangpiutang , c.cnama , SUM(pbd.jmlbayar) AS jmlbayar FROM m_11_pb pb JOIN m_11_pb_detail pbd ON pb.pvid = pbd.idpv LEFT JOIN m1_coa c ON pbd.rekhutangpiutang = c.cnomor GROUP BY pb.pvtgl ASC , pbd.rekhutangpiutang ASC ORDER BY pb.pvtgl ASC , pbd.rekhutangpiutang ASC;

-- RID=1425 | MENU=25 | ITEM=1 | RQUERY=1 | NAME=Laporan Daftar Pasien | FILE=patient
SELECT p.pkode , p.pnama , p.pkategoripasiennama , p.palamat , p.pkota, p.pprovinsi , p.pnegara, p.pnotelepon , p.pnohp , p.pkeluargalain , p.pnoteleponlain FROM m1_patient p ORDER BY p.pkode;

-- RID=1426 | MENU=26 | ITEM=1 | RQUERY=1 | NAME=Laporan Daftar Kamar | FILE=kamar
SELECT r.rkode , r.rnama , r.rhargajual1 , r.rjmlkasur , r.rcatatan FROM m1_room r ORDER BY r.rkode;

-- RID=1427 | MENU=27 | ITEM=1 | RQUERY=1 | NAME=Laporan Daftar Kasur | FILE=kasur
SELECT r.rnama , b.bkode , b.bnama , b.bcatatan FROM m1_room r JOIN m1_bed b ON r.rnama = b.bkamar ORDER BY r.rkode , b.bkode;

-- RID=1428 | MENU=28 | ITEM=1 | RQUERY=1 | NAME=Laporan Daftar Rujukan | FILE=rujukan
SELECT r.rkode , r.rnama , r.rcatatan FROM m1_reference r ORDER BY r.rkode;

-- RID=1429 | MENU=29 | ITEM=1 | RQUERY=1 | NAME=Laporan Daftar Asuransi | FILE=penanggung
SELECT i.ikode , i.inama , i.icatatan FROM m1_insurer i ORDER BY i.ikode;

-- RID=1430 | MENU=30 | ITEM=1 | RQUERY=1 | NAME=Laporan Daftar Kategori Pasien | FILE=kategoripasien
SELECT pc.pckode , pc.pcnama , pc.pctingkatjual , pc.pccatatan FROM m1_patient_category pc ORDER BY pc.pckode;

-- RID=1431 | MENU=31 | ITEM=1 | RQUERY=1 | NAME=Laporan Daftar Rekanan | FILE=rekanan
SELECT c.ckode, c.cnama , c.cnotelepon , c.cnofax , c.cemail , c.cnohp , c.calamat , c.ckota , c.cprovinsi, c.ckodepos FROM m1_colleague c ORDER BY c.ckode;

-- RID=1432 | MENU=41 | ITEM=1 | RQUERY=1 | NAME=Daftar Retur Apotek | FILE=returapotek
SELECT ro.ronotransaksi , ro.rotgl , kj.kjnotransaksi , kj.kjtgl , kj.kjnopasien , p.pnama , ic.icnama AS jenis , b.bkode , rod.namalayanan , rod.jml , rod.satuan , rod.harga , rod.diskon , ((rod.jml * rod.harga) - rod.jmldiskon) AS total FROM m_11_ro ro JOIN m_11_ro_detail rod ON ro.roid = rod.idro JOIN m_11_kj kj ON ro.roidkj = kj.kjid JOIN m1_patient p ON kj.kjnopasien = p.pkode JOIN m1_item_category ic ON rod.jenis = ic.ickode JOIN m1_item b ON rod.idlayanan = b.bid ORDER BY ro.rotgl , ro.ronotransaksi , rod.urutan;

-- RID=1433 | MENU=41 | ITEM=2 | RQUERY=1 | NAME=Retur Apotek | FILE=returapotekdetail2
SELECT userr.ukode AS unama , ro.ronotransaksi , ro.rotgl , kj.kjnotransaksi , kj.kjtgl , kj.kjnopasien , p.pnama , ic.icnama AS jenis , b.bkode , rod.namalayanan , rod.jml , rod.satuan , rod.harga , rod.diskon , ((rod.jml * rod.harga) - rod.jmldiskon) AS total FROM m_11_ro ro JOIN m_11_ro_detail rod ON ro.roid = rod.idro JOIN m_11_kj kj ON ro.roidkj = kj.kjid JOIN m1_patient p ON kj.kjnopasien = p.pkode JOIN m1_item_category ic ON rod.jenis = ic.ickode JOIN m1_item b ON rod.idlayanan = b.bid JOIN m0_user userr ON ro.roinputuser = userr.userid ORDER BY ro.rotgl , ro.ronotransaksi , rod.urutan;

-- RID=1435 | MENU=41 | ITEM=3 | RQUERY=1 | NAME=RETUR PENJUALAN OBAT RAWAT INAP | FILE=returapotek_RI
SELECT ro.rotgl , ro.ronoref , ro.ronotransaksi , kj.kjnama , rod.namalayanan , rod.jml , rod.satuan , rod.harga , (rod.jml * rod.harga) AS total FROM m_11_ro ro JOIN m_11_ro_detail rod ON ro.roid = rod.idro JOIN m_11_kj kj ON ro.roidkj = kj.kjid JOIN m1_item b ON rod.idlayanan = b.bid WHERE ro.roperawatan = "RI" ORDER BY ro.rotgl , ro.ronotransaksi , rod.urutan;

-- RID=1436 | MENU=41 | ITEM=4 | RQUERY=1 | NAME=RETUR PENJUALAN OBAT RAWAT INAP BPJS | FILE=returapotek_RI_BPJS
SELECT ro.rotgl , ro.ronoref , ro.ronotransaksi , kj.kjnama , rod.namalayanan , rod.jml , rod.satuan , rod.harga , (rod.jml * rod.harga) AS total FROM m_11_ro ro JOIN m_11_ro_detail rod ON ro.roid = rod.idro JOIN m_11_kj kj ON ro.roidkj = kj.kjid JOIN m1_item b ON rod.idlayanan = b.bid WHERE (ro.roperawatan = "RI") AND (ro.rokategoripasien = "BPJS") ORDER BY ro.rotgl , ro.ronotransaksi , rod.urutan;

-- RID=1567 | MENU=41 | ITEM=5 | RQUERY=1 | NAME=Daftar Retur Apotek  | FILE=DaftarReturApotek
SELECT ro.roid , ro.ronotransaksi , ro.rotgl , ro.ronoref , kj.kjnama , SUM(rod.jml * rod.harga) AS total , CASE kj.kjperawatan WHEN "RI" THEN "Rawat Inap" WHEN "RJ" THEN "Rawat Jalan" END AS kjperawatan , pc.pcnama AS kjkategoripasien , ro.rouraian FROM m_11_ro ro JOIN m_11_ro_detail rod ON ro.roid = rod.idro JOIN m_11_kj kj ON ro.roidkj = kj.kjid LEFT JOIN m1_patient_category pc ON kj.kjkategoripasien = pc.pckode GROUP BY ro.roid ORDER BY ro.rotgl , ro.ronotransaksi , rod.urutan;

-- RID=1441 | MENU=45 | ITEM=1 | RQUERY=1 | NAME=DATA STATUS IMUNISASI | FILE=RLC2
SELECT rm.rmlayanan , kj.kjnotransaksi , p.pjeniskelamin , p.pumur , icd.inama AS rmicd, rm.rmtindaklanjut, rm.rmkrs , rm.rmstatusimunisasi FROM m_11_rm rm JOIN m_11_kj kj ON kj.kjid = rm.rmidkj JOIN m1_patient p ON rm.rmnorm = p.pkode JOIN m1_icd icd ON rm.rmicd = icd.ikode WHERE rm.rmlayanan LIKE '%IMUNISASI%' ORDER BY rm.rmnotransaksi;

-- RID=1442 | MENU=45 | ITEM=2 | RQUERY=1 | NAME=DATA KEADAAN MORBIDITAS RAWAT INAP SURVEILANS TERPADU RUMAH SAKIT | FILE=RL2a1
SELECT kj.kjnotransaksi, rm.rmlayanan, l.lnama , p.pumur , p.pjeniskelamin , SUM((SELECT COUNT(*) FROM m_11_rm rms JOIN m1_patient ps ON rms.rmnorm = ps.pkode WHERE (rms.rmperawatan = "RI") AND (rm.rmid = rms.rmid) AND (ps.pumur BETWEEN 1 AND 4) )) AS "1sampai4" , SUM((SELECT COUNT(*) FROM m_11_rm rms1 JOIN m1_patient ps1 ON rms1.rmnorm = ps1.pkode WHERE (rms1.rmperawatan = "RI") AND (rm.rmid = rms1.rmid) AND (ps1.pumur BETWEEN 5 AND 14) )) as "5sampai14", SUM((SELECT COUNT(*) FROM m_11_rm rms2 JOIN m1_patient ps2 ON rms2.rmnorm = ps2.pkode WHERE (rms2.rmperawatan = "RI") AND (rm.rmid = rms2.rmid) AND (ps2.pumur BETWEEN 15 AND 24) )) as "15sampai24", SUM((SELECT COUNT(*) FROM m_11_rm rms3 JOIN m1_patient ps3 ON rms3.rmnorm = ps3.pkode WHERE (rms3.rmperawatan = "RI") AND (rm.rmid = rms3.rmid) AND (ps3.pumur BETWEEN 25 AND 44) )) as "25sampai44", SUM((SELECT COUNT(*) FROM m_11_rm rms4 JOIN m1_patient ps4 ON rms4.rmnorm = ps4.pkode WHERE (rms4.rmperawatan = "RI") AND (rm.rmid = rms4.rmid) AND (ps4.pumur BETWEEN 45 AND 64) )) as "45sampai64", SUM((SELECT COUNT(*) FROM m_11_rm rms5 JOIN m1_patient ps5 ON rms5.rmnorm = ps5.pkode WHERE (rms5.rmperawatan = "RI") AND (rm.rmid = rms5.rmid) AND (ps5.pumur > 65) )) as "lebihdari65" , SUM((SELECT COUNT(*) FROM m_11_rm rms6 JOIN m1_patient ps6 ON rms6.rmnorm = ps6.pkode WHERE (rms6.rmperawatan = "RI") AND (rm.rmid = rms6.rmid) AND (ps6.pjeniskelamin = "L") )) AS "laki", SUM((SELECT COUNT(*) FROM m_11_rm rms7 JOIN m1_patient ps7 ON rms7.rmnorm = ps7.pkode WHERE (rms7.rmperawatan = "RI") AND (rm.rmid = rms7.rmid) AND (ps7.pjeniskelamin = "P") )) AS "perempuan", SUM((SELECT COUNT(*) FROM m_11_rm rms8 JOIN m1_patient ps8 ON rms8.rmnorm = ps8.pkode WHERE (rms8.rmperawatan = "RI") AND (rm.rmid = rms8.rmid) AND (rms8.rmtindaklanjut = 2) )) AS "mati", SUM((SELECT COUNT(*) FROM m_11_rm rms9 JOIN m1_patient ps9 ON rms9.rmnorm = ps9.pkode WHERE (rms9.rmperawatan = "RI") AND (rm.rmid = rms9.rmid) AND (rms9.rmkrs = 1) )) AS "hidup" FROM m_11_rm rm JOIN m_11_kj kj ON kj.kjid = rm.rmidkj JOIN m1_patient p ON rm.rmnorm = p.pkode JOIN m1_layanan l ON rm.rmlayanan = l.lkode WHERE rm.rmperawatan = "RI" GROUP BY rm.rmlayanan ORDER BY rm.rmlayanan;

-- RID=1443 | MENU=45 | ITEM=3 | RQUERY=1 | NAME=DATA KEGIATAN RUMAH SAKIT | FILE=RL1
SELECT COUNT(*) , rm.rmlayanan , SUM((SELECT COUNT(*) FROM m_11_rm rms JOIN m_11_kj kjk1 ON rms.rmidkj = kjk1.kjid WHERE (rms.rmtindaklanjut = 1 OR rms.rmtindaklanjut = 3 OR rms.rmtindaklanjut = 7) AND (rms.rmid = rm.rmid) AND (kjk1.kjjeniskelamin = "L") )) AS hidupL , SUM((SELECT COUNT(*) FROM m_11_rm rms JOIN m_11_kj kjk1 ON rms.rmidkj = kjk1.kjid WHERE (rms.rmtindaklanjut = 1 OR rms.rmtindaklanjut = 3 OR rms.rmtindaklanjut = 7) AND (rms.rmid = rm.rmid) AND (kjk1.kjjeniskelamin = "P") )) AS hidupP , SUM((SELECT COUNT(*) FROM m_11_rm rms JOIN m_11_kj kjk1 ON rms.rmidkj = kjk1.kjid WHERE rms.rmkrs = 3 AND (rms.rmid = rm.rmid) AND kjk1.kjjeniskelamin = "L" )) AS kurang48L , SUM((SELECT COUNT(*) FROM m_11_rm rms JOIN m_11_kj kjk1 ON rms.rmidkj = kjk1.kjid WHERE rms.rmkrs = 3 AND (rms.rmid = rm.rmid) AND kjk1.kjjeniskelamin = "P" )) AS kurang48P , SUM((SELECT COUNT(*) FROM m_11_rm rms JOIN m_11_kj kjk1 ON rms.rmidkj = kjk1.kjid WHERE rms.rmkrs = 4 AND (rms.rmid = rm.rmid) AND kjk1.kjjeniskelamin = "L" )) AS lebih48L , SUM((SELECT COUNT(*) FROM m_11_rm rms JOIN m_11_kj kjk1 ON rms.rmidkj = kjk1.kjid WHERE rms.rmkrs = 4 AND (rms.rmid = rm.rmid) AND kjk1.kjjeniskelamin = "P" )) AS lebih48P , IFNULL(SUM((SELECT DATEDIFF(kjs2.kjtglkeluar,kjs2.kjtgl) FROM m_11_rm rms2 JOIN m_11_kj kjs2 ON rms2.rmidkj = kjs2.kjid WHERE rms2.rmid = rm.rmid )),0) AS jmllamadirawat , IFNULL(SUM((SELECT DATEDIFF(kjs2.kjtglkeluar,kjs2.kjtgl)+1 FROM m_11_rm rms2 JOIN m_11_kj kjs2 ON rms2.rmidkj = kjs2.kjid WHERE rms2.rmid = rm.rmid )),0) AS jmlhariperawatan , SUM((SELECT COUNT(*) FROM m_11_rm rms3 JOIN m_11_kj kjs3 ON rms3.rmidkj = kjs3.kjid WHERE rms3.rmrehabmedik = "Kelas Utama" AND (rms3.rmid = rm.rmid) )) as kelasutama , SUM((SELECT COUNT(*) FROM m_11_rm rms4 JOIN m_11_kj kjs4 ON rms4.rmidkj = kjs4.kjid WHERE rms4.rmrehabmedik = "Kelas I" AND (rms4.rmid = rm.rmid) )) as kelas1 , SUM((SELECT COUNT(*) FROM m_11_rm rms5 JOIN m_11_kj kjs5 ON rms5.rmidkj = kjs5.kjid WHERE rms5.rmrehabmedik = "Kelas II" AND (rms5.rmid = rm.rmid) )) as kelas2, SUM((SELECT COUNT(*) FROM m_11_rm rms6 JOIN m_11_kj kjs6 ON rms6.rmidkj = kjs6.kjid WHERE rms6.rmrehabmedik = "Kelas III A" AND (rms6.rmid = rm.rmid) )) as kelas3, SUM((SELECT COUNT(*) FROM m_11_rm rms7 JOIN m_11_kj kjs7 ON rms7.rmidkj = kjs7.kjid WHERE rms7.rmrehabmedik = "Kelas III B" AND (rms7.rmid = rm.rmid) )) as kelas4, SUM((SELECT COUNT(*) FROM m_11_rm rms8 JOIN m_11_kj kjs8 ON rms8.rmidkj = kjs8.kjid WHERE (rms8.rmrehabmedik <> "Kelas Utama" AND rms8.rmrehabmedik <> "Kelas I" AND rms8.rmrehabmedik <> "Kelas II" AND rms8.rmrehabmedik <> "Kelas III A" AND rms8.rmrehabmedik <> "Kelas III B" ) AND (rms8.rmid = rm.rmid) )) as tanpakelas FROM m_11_rm rm WHERE rm.rmlayanan <> "IMUNI" GROUP BY rm.rmlayanan ORDER BY rm.rmlayanan;

-- RID=1444 | MENU=45 | ITEM=4 | RQUERY=1 | NAME=s | FILE=RL1_2_3KUNJUNGANRAWATJALAN
SELECT rm.rmperawatan, rm.rmlayanan, l.lnama , rm.rmkasus , SUM((SELECT COUNT(*) FROM m_11_rm rms WHERE rms.rmkasus = 1 AND rms.rmid = rm.rmid )) as Baru , SUM((SELECT COUNT(*) FROM m_11_rm rms1 WHERE rms1.rmkasus = 2 AND rms1.rmid = rm.rmid )) as Lama FROM m_11_rm rm JOIN m1_layanan l ON rm.rmlayanan = l.lkode WHERE rm.rmperawatan = "RJ" GROUP BY rm.rmlayanan ORDER BY rm.rmlayanan, rm.rmkasus;

-- RID=1437 | MENU=45 | ITEM=5 | RQUERY=1 | NAME=DATA KEADAAN MORDIBILITAS PASIEN RAWAT INAP RUMAH SAKIT | FILE=RL2A
SELECT rm.rmid , icd.ikode , icd.inama , p.pjeniskelamin , p.pumur , SUM((SELECT COUNT(*) FROM m_11_rm rms1 JOIN m1_patient p1 ON rms1.rmnorm = p1.pkode WHERE (rm.rmid = rms1.rmid) AND (p1.pumur BETWEEN 1 AND 4) )) AS "1sampai4" , SUM((SELECT COUNT(*) FROM m_11_rm rms2 JOIN m1_patient p2 ON rms2.rmnorm = p2.pkode WHERE (rm.rmid = rms2.rmid) AND (p2.pumur BETWEEN 5 AND 14) )) AS "5sampai14" , SUM((SELECT COUNT(*) FROM m_11_rm rms3 JOIN m1_patient p3 ON rms3.rmnorm = p3.pkode WHERE (rm.rmid = rms3.rmid) AND (p3.pumur BETWEEN 15 AND 24) )) AS "15sampai24" , SUM((SELECT COUNT(*) FROM m_11_rm rms4 JOIN m1_patient p4 ON rms4.rmnorm = p4.pkode WHERE (rm.rmid = rms4.rmid) AND (p4.pumur BETWEEN 25 AND 44) )) AS "25sampai44" , SUM((SELECT COUNT(*) FROM m_11_rm rms5 JOIN m1_patient p5 ON rms5.rmnorm = p5.pkode WHERE (rm.rmid = rms5.rmid) AND (p5.pumur BETWEEN 45 AND 64) )) AS "45sampai64" , SUM((SELECT COUNT(*) FROM m_11_rm rms6 JOIN m1_patient p6 ON rms6.rmnorm = p6.pkode WHERE (rm.rmid = rms6.rmid) AND (p6.pumur > 64) )) AS "lebihdari65" , SUM((SELECT COUNT(*) FROM m_11_rm rms7 JOIN m1_patient p7 ON rms7.rmnorm = p7.pkode WHERE (rm.rmid = rms7.rmid) AND (p7.pjeniskelamin = "L") )) AS "L" , SUM((SELECT COUNT(*) FROM m_11_rm rms8 JOIN m1_patient p8 ON rms8.rmnorm = p8.pkode WHERE (rm.rmid = rms8.rmid) AND (p8.pjeniskelamin = "P") )) AS "P" , rm.rmtindaklanjut , SUM((SELECT COUNT(*) FROM m_11_rm rms9 WHERE (rm.rmid = rms9.rmid) AND (rms9.rmtindaklanjut = 2 ) )) AS "Mati" FROM m1_icd icd LEFT JOIN m_11_rm rm ON icd.ikode = rm.rmicd LEFT JOIN m_11_kj kj on rm.rmidkj = kj.kjid LEFT JOIN m1_patient p ON rm.rmnorm = p.pkode GROUP BY icd.ikode ORDER BY icd.ikode , rm.rmid;

-- RID=1438 | MENU=45 | ITEM=6 | RQUERY=1 | NAME=DAFTAR PERSALINAN | FILE=KIA23
SELECT l.lkode , l.lnama , rm.rmtgl , kj.kjnama , p.psuamiistri, p.pumur , rm.rmhamilke , p.palamat, CASE rm.rmpersalinan WHEN 1 THEN "SC" WHEN 2 THEN "Normal" END AS rmpersalinan , rm.rmkeadaanbayi , /*WHEN 1 THEN "Hidup" WHEN 2 THEN "Mati <7 Hr" WHEN 3 THEN "Mati >1 Bln" */ rm.rmjeniskelamin , rm.rmberat FROM m_11_rm rm JOIN m1_layanan l ON rm.rmlayanan = l.lkode JOIN m_11_kj kj ON rm.rmidkj = kj.kjid JOIN m1_patient p ON kj.kjnopasien = p.pkode WHERE l.lkode LIKE "PERSALINAN" ORDER BY rm.rmtgl;

-- RID=1439 | MENU=45 | ITEM=7 | RQUERY=1 | NAME=Cek Kelengkapan Status Pasien | FILE=rm_cekkelengkapan_st_pasien
SELECT userr.unama , kj.kjnotransaksi , rm.rmnorm, kj.kjnama , CASE rm.rmperawatan WHEN "RI" THEN "Rawat Inap" WHEN "RJ" THEN "Rawat Jalan" END AS rmperawatan , pc.pcnama AS rmkategoripasien , rm.rmtgl , rm.rmnotransaksi , st.nama AS rmstatus , rm.rmtpip11 , rm.rmtpip12 , rm.rmtpip13 , rm.rmtpip4 , rm.rmtpip5 , rm.rmigd21 , rm.rmigd22, rm.rmigd18a , rm.rmigd31, rm.rmigd32, rm.rmigd33, rm.rmigd34 , rm.rmigd35 , rm.rmigd6 , rm.rmigd7 , rm.rmvk10 , rm.rmvk10b , rm.rmvk22bayi , rm.rmrawat36, rm.rmrawat37, rm.rmrawat38, rm.rmrawat9, rm.rmrawat10, rm.rmrawat14, rm.rmrawat15, rm.rmrawat16, rm.rmrawat20, rm.rmrawat21a, rm.rmrawat21b , rm.rmrawat22, rm.rmfp16oral , rm.rmgizi17, rm.rmoklapanastesi, rm.rmok19 FROM m_11_rm rm JOIN m_11_kj kj ON rm.rmidkj = kj.kjid JOIN m1_patient_category pc ON rm.rmkategoripasien = pc.pckode JOIN m0_status st ON rm.rmstatus = st.kode JOIN m0_user userr ON userr.userid = rm.rminputuser ORDER BY rm.rmid;

-- RID=1440 | MENU=45 | ITEM=8 | RQUERY=1 | NAME=Rekam Medis | FILE=rm_transaksi
SELECT userr.unama , kj.kjnotransaksi , rm.rmnorm, kj.kjnama , CASE rm.rmperawatan WHEN "RI" THEN "Rawat Inap" WHEN "RJ" THEN "Rawat Jalan" END AS rmperawatan , pc.pcnama AS rmkategoripasien , rm.rmtgl , rm.rmnotransaksi , st.nama AS rmstatus , rm.rmlayanan , rm.rmstatusimunisasi, k.knama AS rmdokter , acc.anama AS rmkecelakaan , CASE rm.rmkasus WHEN 1 THEN "Baru" WHEN 2 THEN "Lama" END AS rmkasus , icd.inama AS rmicd , icdd.inama AS rmicd10 , CASE rm.rmtindaklanjut WHEN 0 THEN "" WHEN 1 THEN "Rujuk" WHEN 2 THEN "Mati" WHEN 3 THEN "Pulang APS" WHEN 4 THEN "MR" WHEN 5 THEN "SVK" WHEN 6 THEN "OK" WHEN 7 THEN "Sembuh" END AS rmtindaklanjut , CASE rm.rmkrs WHEN 0 THEN "" WHEN 1 THEN "Sembuh" WHEN 2 THEN "Belum Sembuh" WHEN 3 THEN "Meninggal < 48 Jam" WHEN 4 THEN "Meninggal >= 48 Jam" END AS rmkrs, CASE rm.rmcarakrs WHEN 0 THEN "" WHEN 1 THEN "Dipulangkan" WHEN 2 THEN "Dirujuk" WHEN 3 THEN "Pulang Paksa" WHEN 4 THEN "Lain - Lain" END AS rmcarakrs, CASE rm.rmrujukan WHEN 0 THEN "" WHEN 1 THEN "Rujukan Dari Bawah" WHEN 2 THEN "Dirujuk Ke Atas" WHEN 3 THEN "Dikembalikan Ke RS Awal" END AS rmrujukan , CASE rm.rmrujukan WHEN 0 THEN "" WHEN 1 THEN (CASE rm.rmrujukandetail WHEN 0 THEN "" WHEN 1 THEN "Diterima Dari Puskesmas" WHEN 2 THEN "Diterima Dari Fasilitas Kes. Lain" WHEN 3 THEN "Diterima Dari RS Lain" WHEN 4 THEN "Dikembalikan Ke Puskesmas" WHEN 5 THEN "Dikembalikan Ke Fasilitas Kes. Lain" END) WHEN 2 THEN (CASE rm.rmrujukandetail WHEN 0 THEN "" WHEN 1 THEN "Pasien Rujukan" WHEN 2 THEN "Pasien Datang Sendiri" WHEN 3 THEN "Diterima Kembali" END) WHEN 3 THEN "" END AS rmrujukandetail, trm.trmnama AS rmrehabmedik, CASE rm.rmdokumen WHEN 0 THEN "" WHEN 1 THEN "Lengkap" WHEN 2 THEN "Tidak Lengkap" END AS rmdokumen , rm.rmhamilke , CASE rm.rmpersalinan WHEN 0 THEN "" WHEN 1 THEN "CS" WHEN 2 THEN "Normal" END AS rmpersalinan , CASE rm.rmkeadaanbayi WHEN 0 THEN "" WHEN 1 THEN "Hidup" WHEN 2 THEN "Mati < 7 Hari" WHEN 3 THEN "Mati >= 1 Bln" END AS rmkeadaanbayi , CASE rm.rmjeniskelamin WHEN "L" THEN "Laki-Laki" WHEN "P" THEN "Perempuan" END AS rmjeniskelamin , rm.rmpanjang , rm.rmberat, rm.rmketerangan FROM m_11_rm rm JOIN m_11_kj kj ON rm.rmidkj = kj.kjid JOIN m1_patient_category pc ON rm.rmkategoripasien = pc.pckode JOIN m0_status st ON rm.rmstatus = st.kode JOIN m0_user userr ON userr.userid = rm.rminputuser LEFT JOIN m1_accident acc ON rm.rmkecelakaan = acc.akode LEFT JOIN m1_contact k on rm.rmdokter = k.kkode LEFT JOIN m1_icd icd ON icd.ikode = rm.rmicd LEFT JOIN m1_icd icdd ON icdd.ikode = rm.rmicd10 LEFT JOIN m1_trm trm ON rm.rmrehabmedik = trm.trmkode ORDER BY rm.rmid;

-- RID=1580 | MENU=45 | ITEM=9 | RQUERY=1 | NAME=REKAM MEDIS 1 | FILE=RM1
SELECT CASE rm.rmperawatan WHEN "RI" THEN "Rawat Inap" WHEN "RJ" THEN "Rawat Jalan" END AS kjperawatan, CASE MONTH(rm.rmtgl) WHEN 1 THEN "Januari" WHEN 2 THEN "Februari" WHEN 3 THEN "Maret" WHEN 4 THEN "April" WHEN 5 THEN "Mei" WHEN 6 THEN "Juni" WHEN 7 THEN "Juli" WHEN 8 THEN "Agustus" WHEN 8 THEN "September" WHEN 10 THEN "Oktober" WHEN 11 THEN "November" WHEN 12 THEN "Desember" END AS bulan , YEAR(rm.rmtgl) AS tahun , COUNT(*) , k.kkode , k.knama , rm.rmdokter FROM m1_contact k LEFT JOIN m_11_rm rm ON k.kkode = rm.rmdokter WHERE k.kkategori = "D" GROUP BY k.kkode ORDER BY k.kkode;

-- RID=1581 | MENU=45 | ITEM=10 | RQUERY=1 | NAME=REKAM MEDIS 2 | FILE=RM2
SELECT CASE kj.kjperawatan WHEN "RI" THEN "Rawat Inap" WHEN "RJ" THEN "Rawat Jalan" END AS kjperawatan , CASE MONTH(rm.rmtgl) WHEN 1 THEN "Januari" WHEN 2 THEN "Februari" WHEN 3 THEN "Maret" WHEN 4 THEN "April" WHEN 5 THEN "Mei" WHEN 6 THEN "Juni" WHEN 7 THEN "Juli" WHEN 8 THEN "Agustus" WHEN 8 THEN "September" WHEN 10 THEN "Oktober" WHEN 11 THEN "November" WHEN 12 THEN "Desember" END AS bulan , YEAR(rm.rmtgl) AS tahun , COUNT(*) , kj.kjstatuspasien , CASE kj.kjstatuspasien WHEN 0 THEN "Pasien Baru" WHEN 1 THEN "Pasien Lama" END AS statuspasien FROM m_11_rm rm JOIN m_11_kj kj ON rm.rmidkj = kj.kjid GROUP BY kj.kjstatuspasien ORDER BY kj.kjstatuspasien;

-- RID=1582 | MENU=45 | ITEM=11 | RQUERY=1 | NAME=Form STP | FILE=STP
SELECT IF(rm.rmketumur = "Hari",IF(rm.rmumur BETWEEN 0 AND 27,"0-28hr", IF(rm.rmumur > 28,"28-<1th","More")) ,IF(rm.rmumur BETWEEN 1 AND 4,"1-4th" ,IF(rm.rmumur BETWEEN 5 AND 14,"5-14th" ,IF(rm.rmumur BETWEEN 15 AND 24,"15-24th" ,IF(rm.rmumur BETWEEN 25 AND 44,"25-44th" ,IF(rm.rmumur BETWEEN 45 AND 64,"45-64th" ,"65+th")))))) AS "umur", rm.rmumur , rm.rmketumur , kj.kjprovinsi , kj.kjkota , CASE rm.rmperawatan WHEN "RI" THEN "Rawat Inap" WHEN "RJ" THEN "Rawat Jalan" END AS kjperawatan, CASE MONTH(rm.rmtgl) WHEN 1 THEN "Januari" WHEN 2 THEN "Februari" WHEN 3 THEN "Maret" WHEN 4 THEN "April" WHEN 5 THEN "Mei" WHEN 6 THEN "Juni" WHEN 7 THEN "Juli" WHEN 8 THEN "Agustus" WHEN 8 THEN "September" WHEN 10 THEN "Oktober" WHEN 11 THEN "November" WHEN 12 THEN "Desember" END AS bulan , YEAR(rm.rmtgl) AS tahun , d.dkode , d.dnama , rm.rmjeniskelamin , rm.rmtindaklanjut , CASE rm.rmtindaklanjut WHEN 2 THEN "Mati" ELSE "Tdk Mati" END AS statuss FROM m_11_rm rm LEFT JOIN m1_diagnosis d ON rm.rmdiagnosa = d.dkode JOIN m_11_kj kj ON rm.rmidkj = kj.kjid ORDER BY rm.rmdiagnosa;

-- RID=1583 | MENU=45 | ITEM=12 | RQUERY=1 | NAME=Pelayanan | FILE=PR
SELECT CASE rm.rmperawatan WHEN "RI" THEN "Rawat Inap" WHEN "RJ" THEN "Rawat Jalan" END AS kjperawatan , CASE MONTH(rm.rmtgl) WHEN 1 THEN "Januari" WHEN 2 THEN "Februari" WHEN 3 THEN "Maret" WHEN 4 THEN "April" WHEN 5 THEN "Mei" WHEN 6 THEN "Juni" WHEN 7 THEN "Juli" WHEN 8 THEN "Agustus" WHEN 8 THEN "September" WHEN 10 THEN "Oktober" WHEN 11 THEN "November" WHEN 12 THEN "Desember" END AS bulan , YEAR(rm.rmtgl) AS tahun , rm.rmlayanan , l.lkode , l.lnama , rm.rmjeniskelamin , rm.rmkrs , CASE rm.rmkrs WHEN 1 THEN "Sembuh" WHEN 2 THEN "Belum Sembuh" WHEN 3 THEN "Meninggal < 48 Jam" WHEN 4 THEN "Meninggal >= 48 Jam" END AS ketkrs , CASE rm.rmkrs WHEN 1 THEN "hidup" WHEN 2 THEN "hidup" WHEN 3 THEN "mati" WHEN 4 THEN "mati" END AS kds , DATEDIFF(kj.kjtglkeluar , kj.kjtgl) AS lamadirawat , (DATEDIFF(kj.kjtglkeluar , kj.kjtgl) + 1) AS haridirawat , kj.kjkamar , r.rkode , r.rnama , r.rkelas , kj.kjtglkeluar , kj.kjtgl FROM m_11_rm rm LEFT JOIN m1_layanan l ON rm.rmlayanan = l.lkode JOIN m_11_kj kj ON rm.rmidkj = kj.kjid LEFT JOIN m1_room r ON kj.kjkamar = r.rkode ORDER BY rm.rmlayanan ASC;

-- RID=1446 | MENU=50 | ITEM=1 | RQUERY=1 | NAME=Kwitansi | FILE=kunjungankwitansi2
/*kjjenistransaksi = 0 (dengan kunjungan , >> pasien) ------------------- 1 (kontak) */ SELECT kw.kwnotransaksi , kw.kwtgl , kwd.idtransaksi , kw.kwjenistransaksi , kw.kwcustomer , CASE kw.kwjenistransaksi WHEN 0 THEN p.pnama WHEN 1 THEN k.knama END AS pnama , CASE kw.kwjenistransaksi WHEN 0 THEN p.pprefix WHEN 1 THEN "-" END AS pprefix , CASE kw.kwjenistransaksi WHEN 0 THEN p.pkode WHEN 1 THEN k.kkode END AS kode , kw.kwtotalar , kw.kwmatauang , f_nominal(kw.kwtotalar, kw.kwmatauang) AS terbilang , kk.knama AS unama , kk.kkode AS ukode FROM m_11_kw kw JOIN m_11_kw_detail kwd ON kw.kwid = kwd.idkw JOIN m1_contact kk ON kw.kwpetugas = kk.kid LEFT JOIN m1_patient p ON p.pid = kw.kwcustomer AND kw.kwjenistransaksi = 0 LEFT JOIN m1_contact k ON k.kid = kw.kwcustomer AND kw.kwjenistransaksi = 1 GROUP BY kw.kwid ORDER BY kw.kwid;

-- RID=1445 | MENU=50 | ITEM=2 | RQUERY=1 | NAME=Perincian Biaya Kunjungan | FILE=kunjungandetail
SELECT kw.kwnotransaksi , kw.kwtgl, kj.kjtgl, kj.kjnotransaksi , kj.kjnopasien, kj.kjtglkeluar , kj.kjtglmeninggal , CASE kj.kjcarakunjungan WHEN 1 THEN 'Datang Sendiri' WHEN 2 THEN 'Rujukan' END AS kjcarakunjungan , r.rnama AS kjdirujukoleh , i.inama AS kjditanggungoleh , st.nama AS kjstatus , p.pnama AS namapasien , p.palamat AS alamatpasien , CONCAT(p.pkeluargalain," ",p.pnoteleponlain) AS keluargapasien, p.ptgllahir , CASE p.pjeniskelamin WHEN "P" THEN "Perempuan" WHEN "L" THEN "Laki - Laki" END AS pjeniskelamin, p.pnohp FROM m_11_kw kw JOIN m_11_kw_detail kwd ON kwd.idkw = kw.kwid JOIN m_11_kj kj ON kwd.idtransaksi = kj.kjid AND kwd.sumber = kj.kjsumber JOIN m0_status st ON kj.kjstatus = st.kode LEFT JOIN m1_reference r ON kj.kjdirujukoleh = r.rid LEFT JOIN m1_insurer i ON kj.kjditanggungoleh = i.iid LEFT JOIN m1_patient p ON kj.kjnopasien = p.pkode ORDER BY kw.kwnotransaksi , kj.kjnotransaksi;

-- RID=1448 | MENU=50 | ITEM=3 | RQUERY=1 | NAME=Rekap Biaya Kunjungan | FILE=kunjungandetail2
SELECT kw.kwnotransaksi , kw.kwtgl, kj.kjtgl, kj.kjnotransaksi , kj.kjnopasien, kj.kjtglkeluar , kj.kjtglmeninggal , CASE kj.kjcarakunjungan WHEN 1 THEN 'Datang Sendiri' WHEN 2 THEN 'Rujukan' END AS kjcarakunjungan , r.rnama AS kjdirujukoleh , i.inama AS kjditanggungoleh , st.nama AS kjstatus , p.pnama AS namapasien , p.palamat AS alamatpasien , CONCAT(p.pkeluargalain," ",p.pnoteleponlain) AS keluargapasien, p.ptgllahir , CASE p.pjeniskelamin WHEN "P" THEN "Perempuan" WHEN "L" THEN "Laki - Laki" END AS pjeniskelamin, p.pnohp FROM m_11_kw kw JOIN m_11_kw_detail kwd ON kwd.idkw = kw.kwid JOIN m_11_kj kj ON kwd.idtransaksi = kj.kjid AND kwd.sumber = kj.kjsumber JOIN m0_status st ON kj.kjstatus = st.kode LEFT JOIN m1_reference r ON kj.kjdirujukoleh = r.rid LEFT JOIN m1_insurer i ON kj.kjditanggungoleh = i.iid LEFT JOIN m1_patient p ON kj.kjnopasien = p.pkode ORDER BY kw.kwnotransaksi , kj.kjnotransaksi;

-- RID=1597 | MENU=50 | ITEM=4 | RQUERY=1 | NAME=Daftar Rekap Biaya Kunjungan | FILE=daftar_kunjungandetail
SELECT kw.kwnotransaksi , kw.kwtgl, kj.kjtgl, kj.kjnotransaksi , kj.kjnopasien, kj.kjtglkeluar , kj.kjtglmeninggal , CASE kj.kjcarakunjungan WHEN 1 THEN 'Datang Sendiri' WHEN 2 THEN 'Rujukan' END AS kjcarakunjungan , r.rnama AS kjdirujukoleh , i.inama AS kjditanggungoleh , st.nama AS kjstatus , p.pnama AS namapasien , p.palamat AS alamatpasien , CONCAT(p.pkeluargalain," ",p.pnoteleponlain) AS keluargapasien, p.ptgllahir , CASE p.pjeniskelamin WHEN "P" THEN "Perempuan" WHEN "L" THEN "Laki - Laki" END AS pjeniskelamin, p.pnohp FROM m_11_kw kw JOIN m_11_kw_detail kwd ON kwd.idkw = kw.kwid JOIN m_11_kj kj ON kwd.idtransaksi = kj.kjid AND kwd.sumber = kj.kjsumber JOIN m0_status st ON kj.kjstatus = st.kode LEFT JOIN m1_reference r ON kj.kjdirujukoleh = r.rid LEFT JOIN m1_insurer i ON kj.kjditanggungoleh = i.iid LEFT JOIN m1_patient p ON kj.kjnopasien = p.pkode ORDER BY kw.kwnotransaksi , kj.kjnotransaksi;

-- RID=50000551 | MENU=54 | ITEM=1 | RQUERY=1 | NAME=Daftar Pengeluaran Cream | FILE=daftar_pengeluaran_cream
SELECT YEAR(it.tgl) AS tahun , MONTH(it.tgl) AS bulan , DAY(tgl) AS tanggal, it.tgl , u.ugrup , b.bkode , b.bnama , SUM(it.jmlbarang) AS jml , CONCAT(DAY(it.tgl),'-',ugrup) AS grup FROM m1_item_transaction it JOIN m0_nomor nom ON nom.transaksihpp = 1 AND nom.kodetabel = it.sumber AND it.jenismutasi = 0 JOIN m1_item b ON it.idbarang = b.bid JOIN m0_user u ON it.inputuser = u.userid GROUP BY it.tgl ASC , b.bkode ASC , u.ugrup ASC ORDER BY it.tgl ASC , b.bkode ASC , u.ugrup ASC;

-- RID=50000552 | MENU=54 | ITEM=2 | RQUERY=1 | NAME=Laporan perolehan dan pendapatan  | FILE=laporan_perolehan_dan_pendapatan
SELECT CASE u.ugrup WHEN 1 THEN "Pagi" WHEN 2 THEN "Sore" END AS shift , ak.aktgl , u.ugrup , COUNT(ak.aknotransaksi) AS nota , SUM(ak.aktotaltransaksi) AS totaltransaksi , ak.akkategoripasien , pc.pcnama FROM m_11_ak ak JOIN m0_user u ON ak.akinputuser = userid JOIN m1_patient_category pc ON ak.akkategoripasien = pc.pckode WHERE ak.akstatus IN(2,3,4,7) GROUP BY ak.akkategoripasien ASC, ak.aktgl ASC , u.ugrup ASC ORDER BY ak.akkategoripasien ASC, ak.aktgl ASC , u.ugrup ASC;

