import { PrismaService } from '../prisma/prisma.service';
export declare class AlertingMetricService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    alertingBusinessMetrics(moduleKey?: string): Promise<{
        success: boolean;
        data: {
            metric_id: number;
            metric_key: unknown;
            label: unknown;
            short_label: unknown;
            module_key: unknown;
            description: unknown;
            business_definition: unknown;
            unit: unknown;
            value_type: unknown;
            comparison_type: unknown;
            source_type: unknown;
            source_ref: unknown;
            semantic_ref: unknown;
            system_metric_ref: unknown;
            supported_dimensions: never[];
            default_filters: {};
            tags: never[];
            owner_name: unknown;
            review_status: unknown;
        }[];
    }>;
    alertingSystemMetrics(moduleKey?: string): Promise<{
        success: boolean;
        data: {
            system_metric_id: number;
            metric_key: unknown;
            label: unknown;
            module_key: unknown;
            description: unknown;
            source_table: unknown;
            source_type: unknown;
            resolver_key: unknown;
            aggregation_type: unknown;
            value_type: unknown;
            supported_dimensions: never[];
            supported_filters: never[];
            default_filters: {};
            tags: never[];
            owner_name: unknown;
            review_status: unknown;
        }[];
    }>;
    alertingMetricBuilderContext(moduleKey?: string, metricKey?: string): Promise<{
        success: boolean;
        data: {
            metric_id: number;
            metric_key: unknown;
            label: unknown;
            short_label: unknown;
            module_key: unknown;
            description: unknown;
            business_definition: unknown;
            unit: unknown;
            value_type: unknown;
            comparison_type: unknown;
            semantic_ref: unknown;
            canonical_semantic_key: unknown;
            semantic_label: unknown;
            semantic_entity_key: unknown;
            semantic_measure_key: unknown;
            semantic_definition: unknown;
            semantic_calculation_summary: unknown;
            system_metric_ref: unknown;
            system_metric_label: unknown;
            system_source_table: unknown;
            system_aggregation_type: unknown;
            source_type: unknown;
            source_ref: unknown;
            supported_dimensions: never[];
            default_filters: {};
            tags: never[];
            owner_name: unknown;
            review_status: unknown;
            goal_count: number;
            goals: never[];
            condition_mapping_count: number;
            condition_mappings: never[];
        }[];
    }>;
    private mapAlertingBusinessMetricRow;
    private mapAlertingSystemMetricRow;
    private mapAlertingMetricBuilderContextRow;
}
