/* eslint-disable @typescript-eslint/no-unused-vars */
import {
  AlertCircle,
  Award,
  Badge,
  Bell,
  Bitcoin,
  Bot,
  Book,
  Briefcase,
  Building,
  CalendarCheck,
  Captions,
  CheckCircle,
  Code,
  Coffee,
  File as DocumentIcon,
  Euro,
  Eye,
  FileQuestion,
  FileText,
  Flag,
  Ghost,
  Gift,
  Grid,
  Heart,
  HelpCircle,
  Kanban,
  Key,
  Layout,
  LayoutGrid,
  LifeBuoy,
  MessageSquare,
  Monitor,
  Network,
  Users as PeopleIcon,
  Plug,
  Share2,
  ShieldOff,
  SquareMousePointer,
  Star,
  ThumbsUp,
  TrendingUp,
  UserCheck,
  Users,
  Briefcase as WorkIcon,
  Zap,
} from 'lucide-react';
import { MenuConfig } from '@/config/types';

export const MENU_SIDEBAR: MenuConfig = [
  {
    title: 'Dashboard',
    icon: LayoutGrid,
    children: [
      {
        title: 'Overview',
        path: '/app/overview',
      },
      {
        title: 'Dashboard M1',
        path: '/app/overview?domain=m1',
      },
      {
        title: 'Dashboard M',
        path: '/app/overview?domain=m',
      },
      {
        title: 'Dashboard M2R',
        path: '/app/overview?domain=m2r',
      },
    ],
  },
  {
    title: 'Administrator',
    icon: Users,
    children: [
      {
        title: 'Notification',
        icon: Bell,
        path: '/app/administrator/notification',
      },
      {
        title: 'Test Workflow',
        icon: Bot,
        path: '/app/administrator/test-workflow',
      },
    ],
  },
];
