-- web-hr Fase 2 — Cuti / PTO (additive, 0 DROP)
-- Live hr_* tables are NOT Prisma-managed; applied via psql (db execute).
-- Conventions mirror existing hr_ tables: integer id, plain timestamp,
-- audit quartet, soft-delete, status CHECK, indexed (FKs not enforced — same
-- decoupled style as hr_attendance_sessions).
-- Apply: docker exec sentient-postgres-core psql -U root -d sentient_factory -f <this>

CREATE TABLE IF NOT EXISTS public.hr_leave_types (
  id                 integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  code               text NOT NULL,
  name               text NOT NULL,
  is_paid            boolean NOT NULL DEFAULT true,
  default_quota_days numeric(6,2),
  is_active          boolean NOT NULL DEFAULT true,
  created_at         timestamp without time zone NOT NULL DEFAULT now(),
  created_by         integer,
  updated_at         timestamp without time zone,
  updated_by         integer,
  deleted_at         timestamp without time zone,
  deleted_by         integer
);

CREATE UNIQUE INDEX IF NOT EXISTS hr_leave_types_code_active_key
  ON public.hr_leave_types (code) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS hr_leave_types_is_active_idx
  ON public.hr_leave_types (is_active);

CREATE TABLE IF NOT EXISTS public.hr_leave_requests (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id       integer NOT NULL,          -- hr_users.id
  leave_type_id integer NOT NULL,          -- hr_leave_types.id
  start_date    date NOT NULL,
  end_date      date NOT NULL,
  total_days    numeric(6,2) NOT NULL DEFAULT 0,
  reason        text,
  status        text NOT NULL DEFAULT 'pending',
  reviewed_by   integer,
  reviewed_at   timestamp without time zone,
  review_note   text,
  created_at    timestamp without time zone NOT NULL DEFAULT now(),
  created_by    integer,
  updated_at    timestamp without time zone,
  updated_by    integer,
  deleted_at    timestamp without time zone,
  deleted_by    integer,
  CONSTRAINT hr_leave_requests_status_chk
    CHECK (status IN ('pending','approved','rejected','cancelled')),
  CONSTRAINT hr_leave_requests_dates_chk CHECK (end_date >= start_date)
);

CREATE INDEX IF NOT EXISTS hr_leave_requests_user_idx ON public.hr_leave_requests (user_id);
CREATE INDEX IF NOT EXISTS hr_leave_requests_status_idx ON public.hr_leave_requests (status);
CREATE INDEX IF NOT EXISTS hr_leave_requests_type_idx ON public.hr_leave_requests (leave_type_id);
CREATE INDEX IF NOT EXISTS hr_leave_requests_dates_idx ON public.hr_leave_requests (start_date, end_date);

-- Seed a couple of default leave types (idempotent).
INSERT INTO public.hr_leave_types (code, name, is_paid, default_quota_days)
SELECT v.code, v.name, v.is_paid, v.quota
FROM (VALUES
  ('ANNUAL', 'Cuti Tahunan', true, 12),
  ('SICK',   'Cuti Sakit',   true, NULL),
  ('UNPAID', 'Cuti Tanpa Bayar', false, NULL)
) AS v(code, name, is_paid, quota)
WHERE NOT EXISTS (
  SELECT 1 FROM public.hr_leave_types t WHERE t.code = v.code AND t.deleted_at IS NULL
);
