-- web-hr Fase 2 — Jadwal/Shift + Proyek/Aktivitas (additive, 0 DROP)
-- Same conventions as 0001 (integer id, plain timestamp, audit quartet, soft-delete).

-- ── Shifts ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.hr_shifts (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  code          text NOT NULL,
  name          text NOT NULL,
  start_time    time NOT NULL,
  end_time      time NOT NULL,
  break_minutes integer NOT NULL DEFAULT 0,
  is_active     boolean NOT NULL DEFAULT true,
  created_at    timestamp without time zone NOT NULL DEFAULT now(),
  created_by    integer, updated_at timestamp without time zone, updated_by integer,
  deleted_at    timestamp without time zone, deleted_by integer
);
CREATE UNIQUE INDEX IF NOT EXISTS hr_shifts_code_active_key
  ON public.hr_shifts (code) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.hr_shift_assignments (
  id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id    integer NOT NULL,        -- hr_users.id
  shift_id   integer NOT NULL,        -- hr_shifts.id
  work_date  date NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  created_by integer, updated_at timestamp without time zone, updated_by integer,
  deleted_at timestamp without time zone, deleted_by integer
);
CREATE UNIQUE INDEX IF NOT EXISTS hr_shift_assignments_user_date_key
  ON public.hr_shift_assignments (user_id, work_date) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS hr_shift_assignments_date_idx ON public.hr_shift_assignments (work_date);
CREATE INDEX IF NOT EXISTS hr_shift_assignments_shift_idx ON public.hr_shift_assignments (shift_id);

INSERT INTO public.hr_shifts (code, name, start_time, end_time, break_minutes)
SELECT v.code, v.name, v.s::time, v.e::time, v.b
FROM (VALUES
  ('PAGI','Shift Pagi','08:00','16:00',60),
  ('SIANG','Shift Siang','14:00','22:00',60),
  ('MALAM','Shift Malam','22:00','06:00',60)
) AS v(code,name,s,e,b)
WHERE NOT EXISTS (SELECT 1 FROM public.hr_shifts t WHERE t.code = v.code AND t.deleted_at IS NULL);

-- ── Projects & activities ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.hr_projects (
  id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  code        text NOT NULL,
  name        text NOT NULL,
  client_name text,
  is_billable boolean NOT NULL DEFAULT false,
  is_active   boolean NOT NULL DEFAULT true,
  created_at  timestamp without time zone NOT NULL DEFAULT now(),
  created_by  integer, updated_at timestamp without time zone, updated_by integer,
  deleted_at  timestamp without time zone, deleted_by integer
);
CREATE UNIQUE INDEX IF NOT EXISTS hr_projects_code_active_key
  ON public.hr_projects (code) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.hr_project_time_entries (
  id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id     integer NOT NULL,       -- hr_users.id
  project_id  integer NOT NULL,       -- hr_projects.id
  work_date   date NOT NULL,
  minutes     integer NOT NULL DEFAULT 0,
  activity    text,
  note        text,
  created_at  timestamp without time zone NOT NULL DEFAULT now(),
  created_by  integer, updated_at timestamp without time zone, updated_by integer,
  deleted_at  timestamp without time zone, deleted_by integer,
  CONSTRAINT hr_project_time_entries_minutes_chk CHECK (minutes >= 0)
);
CREATE INDEX IF NOT EXISTS hr_project_time_entries_user_idx ON public.hr_project_time_entries (user_id);
CREATE INDEX IF NOT EXISTS hr_project_time_entries_project_idx ON public.hr_project_time_entries (project_id);
CREATE INDEX IF NOT EXISTS hr_project_time_entries_date_idx ON public.hr_project_time_entries (work_date);

INSERT INTO public.hr_projects (code, name, client_name, is_billable)
SELECT v.code, v.name, v.client, v.bill
FROM (VALUES
  ('INTERNAL','Operasional Internal', NULL, false),
  ('PROJ-A','Implementasi Klien A','Klien A', true)
) AS v(code,name,client,bill)
WHERE NOT EXISTS (SELECT 1 FROM public.hr_projects t WHERE t.code = v.code AND t.deleted_at IS NULL);
