-- web-hr Fase 2 lanjutan — Kalender Libur (additive, 0 DROP)
-- Live hr_* tables are NOT Prisma-managed; applied via psql (db execute).
-- Conventions mirror existing hr_ tables: integer id, plain timestamp,
-- audit quartet, soft-delete, indexed (FKs not enforced — same decoupled style
-- as hr_attendance_sessions / hr_leave_requests).
-- Apply: docker exec sentient-postgres-core psql -U root -d sentient_factory -f <this>

CREATE TABLE IF NOT EXISTS public.hr_holidays (
  id           integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  holiday_date date NOT NULL,
  name         text NOT NULL,
  is_recurring boolean NOT NULL DEFAULT false,   -- recurs annually on the same month/day
  region       text,                             -- optional regional scope (e.g. 'Nasional', 'Jawa Barat')
  is_active    boolean NOT NULL DEFAULT true,
  created_at   timestamp without time zone NOT NULL DEFAULT now(),
  created_by   integer,
  updated_at   timestamp without time zone,
  updated_by   integer,
  deleted_at   timestamp without time zone,
  deleted_by   integer
);

-- One holiday per date (live rows). Recurring entries store a reference year.
CREATE UNIQUE INDEX IF NOT EXISTS hr_holidays_date_key
  ON public.hr_holidays (holiday_date) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS hr_holidays_active_idx ON public.hr_holidays (is_active);
CREATE INDEX IF NOT EXISTS hr_holidays_date_idx ON public.hr_holidays (holiday_date);

-- Seed a few 2026 Indonesian national holidays (idempotent).
INSERT INTO public.hr_holidays (holiday_date, name, is_recurring, region)
SELECT v.d::date, v.name, v.recurring, 'Nasional'
FROM (VALUES
  ('2026-01-01', 'Tahun Baru Masehi',        true),
  ('2026-05-01', 'Hari Buruh Internasional', true),
  ('2026-06-01', 'Hari Lahir Pancasila',     true),
  ('2026-08-17', 'Hari Kemerdekaan RI',      true),
  ('2026-12-25', 'Hari Raya Natal',          true)
) AS v(d, name, recurring)
WHERE NOT EXISTS (
  SELECT 1 FROM public.hr_holidays h
  WHERE h.holiday_date = v.d::date AND h.deleted_at IS NULL
);
