-- web-hr Fase 2 lanjutan — RBAC eksplisit (additive, 0 DROP)
-- Live hr_* tables are NOT Prisma-managed; applied via psql (db execute).
-- hr_roles = catalog of HR roles; hr_user_roles = assignment to hr_users.
-- Conventions mirror existing hr_ tables: integer id, plain timestamp, audit
-- quartet, soft-delete, indexed (FKs not enforced — decoupled style).
-- Apply: docker exec sentient-postgres-core psql -U root -d sentient_factory -f <this>

CREATE TABLE IF NOT EXISTS public.hr_roles (
  id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  code        text NOT NULL,
  name        text NOT NULL,
  description text,
  is_system   boolean NOT NULL DEFAULT false,  -- system roles cannot be deleted
  is_active   boolean NOT NULL DEFAULT true,
  created_at  timestamp without time zone NOT NULL DEFAULT now(),
  created_by  integer,
  updated_at  timestamp without time zone,
  updated_by  integer,
  deleted_at  timestamp without time zone,
  deleted_by  integer
);

CREATE UNIQUE INDEX IF NOT EXISTS hr_roles_code_key
  ON public.hr_roles (code) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS hr_roles_active_idx ON public.hr_roles (is_active);

CREATE TABLE IF NOT EXISTS public.hr_user_roles (
  id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id    integer NOT NULL,   -- hr_users.id
  role_id    integer NOT NULL,   -- hr_roles.id
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  created_by integer,
  updated_at timestamp without time zone,
  updated_by integer,
  deleted_at timestamp without time zone,
  deleted_by integer
);

CREATE UNIQUE INDEX IF NOT EXISTS hr_user_roles_user_role_key
  ON public.hr_user_roles (user_id, role_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS hr_user_roles_user_idx ON public.hr_user_roles (user_id);
CREATE INDEX IF NOT EXISTS hr_user_roles_role_idx ON public.hr_user_roles (role_id);

-- Seed system roles (idempotent). Mirror platform privilege tiers.
INSERT INTO public.hr_roles (code, name, description, is_system)
SELECT v.code, v.name, v.descr, true
FROM (VALUES
  ('HR_ADMIN',    'HR Admin',    'Akses penuh modul HR: kelola karyawan, kebijakan, dan tinjauan.'),
  ('HR_MANAGER',  'HR Manager',  'Menyetujui kehadiran, cuti, dan timesheet tim.'),
  ('HR_EMPLOYEE', 'HR Employee', 'Karyawan: clock in/out, ajukan cuti, lihat riwayat sendiri.')
) AS v(code, name, descr)
WHERE NOT EXISTS (
  SELECT 1 FROM public.hr_roles r WHERE r.code = v.code AND r.deleted_at IS NULL
);
