-- web-hr Fase 0 — Menu HR (additive, 0 DROP)
-- Live hr_* tables are NOT Prisma-managed; applied via psql (db execute).
-- hr_menus = catalog menu sidebar HR (mirror field ERP sys_menus, namespace hr_).
-- hr_role_menus = grant role→menu (mirror ERP adm_role_menus, style HR junction).
-- Sidebar web-hr dikonsumsi dari GET /api/hr/sys-menus/my-menus (hr-sys-menus module).
-- Tree: MODULE (3 grup) → ITEM (17 route). MODULE selalu dipertahankan renderer;
-- hanya ITEM yang difilter by hr_role_menus.can_view (non-privileged user).
-- path kanonik = tanpa prefix /app (shell menambah base /app saat render URL),
-- persis konvensi ERP sys_menus.path.
-- Conventions mirror existing hr_ tables: integer id, plain timestamp, audit
-- quartet, soft-delete, indexed (FKs not enforced — decoupled style).
-- Apply: docker exec sentient-postgres-core psql -U root -d sentient_factory -f <this>

CREATE TABLE IF NOT EXISTS public.hr_menus (
  id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  code        text NOT NULL,
  title       text NOT NULL,
  path        text,                                   -- canonical route id (tanpa /app)
  icon        text,                                   -- lucide icon name
  type        text NOT NULL CHECK (type IN ('MODULE', 'GROUP', 'ITEM')),
  parent_id   integer,                                -- hr_menus.id (MODULE untuk ITEM)
  sort_order  integer NOT NULL DEFAULT 0,
  is_active   boolean NOT NULL DEFAULT true,
  created_at  timestamp without time zone NOT NULL DEFAULT now(),
  created_by  integer,
  updated_at  timestamp without time zone,
  updated_by  integer,
  deleted_at  timestamp without time zone,
  deleted_by  integer
);

CREATE UNIQUE INDEX IF NOT EXISTS hr_menus_code_key
  ON public.hr_menus (code) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS hr_menus_parent_idx ON public.hr_menus (parent_id);
CREATE INDEX IF NOT EXISTS hr_menus_active_idx ON public.hr_menus (is_active);

-- Grant junction (style = hr_user_roles: surrogate id + unique partial + audit
-- quartet + soft-delete). can_* flags mirror ERP adm_role_menus; hanya can_view
-- yang dipakai filter my-menus saat ini, sisanya tersedia untuk per-action RBAC.
CREATE TABLE IF NOT EXISTS public.hr_role_menus (
  id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  role_id     integer NOT NULL,                       -- hr_roles.id
  menu_id     integer NOT NULL,                       -- hr_menus.id
  can_view    boolean NOT NULL DEFAULT false,
  can_create  boolean NOT NULL DEFAULT false,
  can_edit    boolean NOT NULL DEFAULT false,
  can_delete  boolean NOT NULL DEFAULT false,
  can_approve boolean NOT NULL DEFAULT false,
  can_print   boolean NOT NULL DEFAULT false,
  can_export  boolean NOT NULL DEFAULT false,
  can_import  boolean NOT NULL DEFAULT false,
  is_favorite boolean NOT NULL DEFAULT false,
  created_at  timestamp without time zone NOT NULL DEFAULT now(),
  created_by  integer,
  updated_at  timestamp without time zone,
  updated_by  integer,
  deleted_at  timestamp without time zone,
  deleted_by  integer
);

CREATE UNIQUE INDEX IF NOT EXISTS hr_role_menus_role_menu_key
  ON public.hr_role_menus (role_id, menu_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS hr_role_menus_role_idx ON public.hr_role_menus (role_id);
CREATE INDEX IF NOT EXISTS hr_role_menus_menu_idx ON public.hr_role_menus (menu_id);

-- ─── Seed: 3 MODULE (grup sidebar) ────────────────────────────────────────────
INSERT INTO public.hr_menus (code, title, path, icon, type, parent_id, sort_order, is_active)
SELECT v.code, v.title, v.path, v.icon, v.type, v.parent_id, v.sort_order, true
FROM (VALUES
  ('mod-attendance', 'Kehadiran',              NULL::text, 'Clock4',          'MODULE', NULL::int, 1),
  ('mod-workforce',  'Manajemen Tenaga Kerja', NULL::text, 'Users',           'MODULE', NULL::int, 2),
  ('mod-insight',    'Laporan & Lainnya',      NULL::text, 'BarChart3',       'MODULE', NULL::int, 3)
) AS v(code, title, path, icon, type, parent_id, sort_order)
WHERE NOT EXISTS (
  SELECT 1 FROM public.hr_menus m WHERE m.code = v.code AND m.deleted_at IS NULL
);

-- ─── Seed: 17 ITEM (route) ───────────────────────────────────────────────────
-- parent_id di-resolve dari kode MODULE via subquery (id auto-generated).
INSERT INTO public.hr_menus (code, title, path, icon, type, parent_id, sort_order, is_active)
SELECT v.code, v.title, v.path, v.icon, 'ITEM',
       (SELECT m.id FROM public.hr_menus m WHERE m.code = v.mod AND m.deleted_at IS NULL LIMIT 1),
       v.sort_order, true
FROM (VALUES
  -- mod-attendance (Kehadiran)
  ('dashboard',            'Dashboard',           '/dashboard',           'LayoutDashboard',  'mod-attendance', 1),
  ('attendance',           'Absensi Saya',        '/attendance',          'Fingerprint',      'mod-attendance', 2),
  ('attendance-history',   'Riwayat Absensi',     '/attendance-history',  'History',          'mod-attendance', 3),
  ('attendance-reviews',   'Tinjauan Absensi',    '/attendance-reviews',  'ClipboardCheck',   'mod-attendance', 4),
  ('worksites',            'Lokasi & Geofence',   '/worksites',           'MapPin',           'mod-attendance', 5),
  ('face-enrollments',     'Pendaftaran Wajah',   '/face-enrollments',    'ScanFace',         'mod-attendance', 6),
  ('employees',            'Karyawan',            '/employees',           'Users',            'mod-attendance', 7),
  ('roles',                'Akses & Peran',       '/roles',               'ShieldCheck',      'mod-attendance', 8),
  -- mod-workforce (Manajemen Tenaga Kerja)
  ('timesheets',           'Timesheet',           '/timesheets',          'CalendarClock',    'mod-workforce',  1),
  ('schedules',            'Jadwal & Shift',      '/schedules',           'CalendarDays',     'mod-workforce',  2),
  ('leave',                'Cuti',                '/leave',               'Plane',            'mod-workforce',  3),
  ('holidays',             'Kalender Libur',      '/holidays',            'CalendarX',        'mod-workforce',  4),
  ('projects',             'Proyek & Aktivitas',  '/projects',            'FolderKanban',     'mod-workforce',  5),
  -- mod-insight (Laporan & Lainnya)
  ('reports',              'Laporan',             '/reports',             'BarChart3',        'mod-insight',    1),
  ('kiosk',                'Mode Kiosk',          '/kiosk',               'MonitorSmartphone','mod-insight',    2),
  ('overtime',             'Aturan Lembur',       '/overtime',            'Timer',            'mod-insight',    3),
  ('settings',             'Pengaturan',          '/settings',            'Settings',         'mod-insight',    4)
) AS v(code, title, path, icon, mod, sort_order)
WHERE NOT EXISTS (
  SELECT 1 FROM public.hr_menus m WHERE m.code = v.code AND m.deleted_at IS NULL
);

-- ─── Seed: role→menu grants ──────────────────────────────────────────────────
-- Privileged user (platform admin/manager ATAU HR_ADMIN/HR_MANAGER via
-- resolveHrPrivilege) melihat semua menu tanpa filter, jadi grant di bawah hanya
-- fungsional bagi user non-privileged (HR_EMPLOYEE). Grant eksplisit untuk
-- HR_ADMIN/HR_MANAGER ditulis juga demi kelengkapan/paritas ERP.

-- HR_ADMIN: semua ITEM, full flags.
INSERT INTO public.hr_role_menus (role_id, menu_id, can_view, can_create, can_edit, can_delete, can_approve, can_export)
SELECT r.id, m.id, true, true, true, true, true, true
FROM public.hr_roles r, public.hr_menus m
WHERE r.code = 'HR_ADMIN' AND r.deleted_at IS NULL
  AND m.type = 'ITEM' AND m.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM public.hr_role_menus rm
    WHERE rm.role_id = r.id AND rm.menu_id = m.id AND rm.deleted_at IS NULL
  );

-- HR_MANAGER: semua ITEM (approve/review/leave/timesheet).
INSERT INTO public.hr_role_menus (role_id, menu_id, can_view, can_approve, can_edit)
SELECT r.id, m.id, true, true, true
FROM public.hr_roles r, public.hr_menus m
WHERE r.code = 'HR_MANAGER' AND r.deleted_at IS NULL
  AND m.type = 'ITEM' AND m.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM public.hr_role_menus rm
    WHERE rm.role_id = r.id AND rm.menu_id = m.id AND rm.deleted_at IS NULL
  );

-- HR_EMPLOYEE: subset self-service.
INSERT INTO public.hr_role_menus (role_id, menu_id, can_view)
SELECT r.id, m.id, true
FROM public.hr_roles r, public.hr_menus m
WHERE r.code = 'HR_EMPLOYEE' AND r.deleted_at IS NULL
  AND m.code IN ('dashboard', 'attendance', 'attendance-history', 'leave', 'timesheets', 'projects')
  AND m.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM public.hr_role_menus rm
    WHERE rm.role_id = r.id AND rm.menu_id = m.id AND rm.deleted_at IS NULL
  );
