-- m0_report full queries for rmoduleid = 6
-- total rows: 103

-- RID=217 | MENU=3 | ITEM=1 | RQUERY=1 | NAME=Daftar Formula Produksi (BOM) | FILE=ListBillOfMaterial
SELECT bom.bomnotransaksi, bom.bomtgl, k.knama AS bompembuat, bomuraian, pc.pcnama AS bomjenis, st.nama AS bomstatus , bom.bomid FROM m6_bom bom JOIN m1_production_category pc ON bom.bomjenis = pc.pckode JOIN m0_status st on bom.bomstatus = st.kode LEFT JOIN m1_contact k ON bom.bompembuat = k.kid ORDER BY bom.bomtgl, bom.bomid, bom.bomnotransaksi;

-- RID=219 | MENU=3 | ITEM=2 | RQUERY=1 | NAME=Formula Produksi (BOM) | FILE=BillOfMaterial1
SELECT bom.bomnotransaksi, bom.bomtgl, k.knama AS bompembuat, bomuraian, pc.pcnama AS bomjenis, st.nama AS bomstatus , bom.bomid FROM m6_bom bom JOIN m1_production_category pc ON bom.bomjenis = pc.pckode JOIN m0_status st on bom.bomstatus = st.kode LEFT JOIN m1_contact k ON bom.bompembuat = k.kid ORDER BY bom.bomtgl, bom.bomid, bom.bomnotransaksi;

-- RID=551 | MENU=3 | ITEM=3 | RQUERY=1 | NAME=Formula Produksi (BOM) | FILE=BillOfMaterial1_UD
SELECT bom.bomnotransaksi, bom.bomtgl, k.knama AS bompembuat, bomuraian, pc.pcnama AS bomjenis, st.nama AS bomstatus , bom.bomid FROM m6_bom bom JOIN m1_production_category pc ON bom.bomjenis = pc.pckode JOIN m0_status st on bom.bomstatus = st.kode LEFT JOIN m1_contact k ON bom.bompembuat = k.kid ORDER BY bom.bomtgl, bom.bomid, bom.bomnotransaksi;

-- RID=344 | MENU=3 | ITEM=4 | RQUERY=1 | NAME=Daftar Formula Produksi (BOM) Per Produk | FILE=ListBillOfMaterial_perproduk[CB]
SELECT bid, bkode, namabarang , bomstatus , bomtgl, bomnotransaksi, bominputuser, knama, kkode FROM (SELECT b.bid, b.bkode, bomin.namabarang , bom.bomstatus , bom.bomtgl, bom.bomnotransaksi, bom.bominputuser, k.knama, kkode FROM m6_bom_in bomin JOIN m6_bom bom ON bomin.idbom = bom.bomid JOIN m1_item b ON bomin.idbarang = b.bid JOIN m1_contact k ON bom.bompembuat = k.kid UNION SELECT bb.bid, bb.bkode , bomout.namabarang , bom.bomstatus , bom.bomtgl, bom.bomnotransaksi, bom.bominputuser, k.knama, kkode FROM m6_bom_out bomout JOIN m6_bom bom ON bomout.idbom = bom.bomid JOIN m1_item bb ON bomout.idbarang = bb.bid JOIN m1_contact k ON bom.bompembuat = k.kid ) as a GROUP BY bid, bkode , namabarang ORDER BY bid, bkode , namabarang;

-- RID=255 | MENU=3 | ITEM=5 | RQUERY=1 | NAME=Daftar BOM terkait MRS dan MRN | FILE=BOMMRSMRN
SELECT bom.bomnotransaksi , bom.bomtgl , k.kkode , k.knama , bom.bomid FROM m6_bom bom JOIN m1_contact k ON bom.bompembuat = k.kid ORDER BY bom.bomid;

-- RID=256 | MENU=3 | ITEM=6 | RQUERY=1 | NAME=Daftar BOM terkait MRS dan PD | FILE=BOMMRSPD
SELECT bom.bomnotransaksi , bom.bomid FROM m6_bom bom JOIN m1_contact k ON bom.bompembuat = k.kid ORDER BY bom.bomid;

-- RID=257 | MENU=3 | ITEM=7 | RQUERY=1 | NAME=Daftar BOM terkait PDR dan WO | FILE=BOMPDRWO
SELECT bom.bomnotransaksi , bom.bomid FROM m6_bom bom JOIN m1_contact k ON bom.bompembuat = k.kid ORDER BY bom.bomid;

-- RID=258 | MENU=3 | ITEM=8 | RQUERY=1 | NAME=Daftar BOM terkait WO dan MRS | FILE=BOMWOMRS
SELECT bom.bomnotransaksi , bom.bomid FROM m6_bom bom JOIN m1_contact k ON bom.bompembuat = k.kid ORDER BY bom.bomid;

-- RID=755 | MENU=3 | ITEM=9 | RQUERY=1 | NAME=Formula Produksi (BOM) | FILE=BillOfMaterial2
SELECT bom.bomnotransaksi, bom.bomtgl, k.knama AS bompembuat, bomuraian, pc.pcnama AS bomjenis, st.nama AS bomstatus , bom.bomid FROM m6_bom bom JOIN m1_production_category pc ON bom.bomjenis = pc.pckode JOIN m0_status st on bom.bomstatus = st.kode LEFT JOIN m1_contact k ON bom.bompembuat = k.kid ORDER BY bom.bomtgl, bom.bomid, bom.bomnotransaksi;

-- RID=1608 | MENU=3 | ITEM=10 | RQUERY=1 | NAME=Daftar Formula Produksi (BOM) | FILE=-
SELECT bomid, bomnotransaksi, bomtgl, b.btipe, bomin.idbarang as idhasil, b.bkode as kodehasil, bomin.namabarang, bomout.idbarang as idbahan, bbahan.bkode as kodebahan, bomout.namabarang, bomin.jml as jmljadi,bomout.jml as jmlbahan, 100-(bomin.jml/bomout.jml*100) AS persentasesusut FROM m6_bom bom JOIN (select * from m6_bom_in GROUP BY idbomin) AS bomin ON bomin.idbom = bom.bomid join m1_item b ON b.bid = bomin.idbarang JOIN (SELECT * from m6_bom_out WHERE jml > 0 GROUP BY idbom) AS bomout ON bomid = bomout.idbom join m1_item bbahan ON bbahan.bid = bomout.idbarang GROUP BY bom.bomid ORDER BY bom.bomtgl, bom.bomid, bom.bomnotransaksi;

-- RID=1666 | MENU=3 | ITEM=11 | RQUERY=1 | NAME=Daftar Formula Produksi (BOM) | FILE=ListBillOfMaterial2
SELECT bom.bomnotransaksi, bom.bomtgl, k.knama AS bompembuat, bomuraian, pc.pcnama AS bomjenis, st.nama AS bomstatus , bom.bomid FROM m6_bom bom JOIN m1_production_category pc ON bom.bomjenis = pc.pckode JOIN m0_status st on bom.bomstatus = st.kode LEFT JOIN m1_contact k ON bom.bompembuat = k.kid ORDER BY bom.bomtgl, bom.bomid, bom.bomnotransaksi;

-- RID=1671 | MENU=3 | ITEM=12 | RQUERY=1 | NAME=Formula Produksi (BOM) | FILE=BillOfMaterial3
SELECT bom.bomnotransaksi, bom.bomtgl, k.knama AS bompembuat, bomuraian, pc.pcnama AS bomjenis, st.nama AS bomstatus , bom.bomid FROM m6_bom bom JOIN m1_production_category pc ON bom.bomjenis = pc.pckode JOIN m0_status st on bom.bomstatus = st.kode LEFT JOIN m1_contact k ON bom.bompembuat = k.kid ORDER BY bom.bomtgl, bom.bomid, bom.bomnotransaksi;

-- RID=1676 | MENU=3 | ITEM=13 | RQUERY=1 | NAME=Formula Produksi (BOM) | FILE=BillOfMaterial4
SELECT bom.bomnotransaksi, bom.bomtgl, k.knama AS bompembuat, bomuraian, pc.pcnama AS bomjenis, st.nama AS bomstatus , bom.bomid FROM m6_bom bom JOIN m1_production_category pc ON bom.bomjenis = pc.pckode JOIN m0_status st on bom.bomstatus = st.kode LEFT JOIN m1_contact k ON bom.bompembuat = k.kid ORDER BY bom.bomtgl, bom.bomid, bom.bomnotransaksi;

-- RID=2024 | MENU=3 | ITEM=14 | RQUERY=1 | NAME=Formula Produksi (BOM) | FILE=BillOfMaterial5
SELECT bom.bomnotransaksi, bom.bomtgl, k.knama AS bompembuat, bomuraian, pc.pcnama AS bomjenis, st.nama AS bomstatus , bom.bomid FROM m6_bom bom JOIN m1_production_category pc ON bom.bomjenis = pc.pckode JOIN m0_status st on bom.bomstatus = st.kode LEFT JOIN m1_contact k ON bom.bompembuat = k.kid ORDER BY bom.bomtgl, bom.bomid, bom.bomnotransaksi;

-- RID=2025 | MENU=3 | ITEM=15 | RQUERY=1 | NAME=Formula Produksi (BOM) | FILE=BillOfMaterial6
SELECT bom.bomnotransaksi, bom.bomtgl, k.knama AS bompembuat, bomuraian, pc.pcnama AS bomjenis, st.nama AS bomstatus , bom.bomid FROM m6_bom bom JOIN m1_production_category pc ON bom.bomjenis = pc.pckode JOIN m0_status st on bom.bomstatus = st.kode LEFT JOIN m1_contact k ON bom.bompembuat = k.kid ORDER BY bom.bomtgl, bom.bomid, bom.bomnotransaksi;

-- RID=50001633 | MENU=3 | ITEM=16 | RQUERY=1 | NAME=BILL OF MATERIAL  | FILE=BILL OF MATERIAL KAWATA
SELECT bom.bomid , bom.bomnotransaksi , bom.bomuraian , b.bkode , b.bnama , bomin.jml , bomin.satuan , bb.bkode AS kodebarang , bb.bnama AS namabarang , bomout.jml AS jumlah , bomout.satuan AS sat FROM m6_bom bom JOIN m6_bom_in bomin ON bom.bomid = bomin.idbom JOIN m1_item b ON bomin.idbarang = b.bid JOIN m6_bom_out bomout ON bom.bomid = bomout.idbom JOIN m1_item bb ON bomout.idbarang = bb.bid ORDER BY bom.bomtgl ASC , bom.bomid ASC , bom.bomnotransaksi ASC;

-- RID=222 | MENU=4 | ITEM=1 | RQUERY=1 | NAME=Daftar Permintaan Produksi (PDR) | FILE=ListProductionRequest
SELECT pdr.pdrid, pdr.pdrnotransaksi , pdr.pdrtgl, k.knama AS pdrdimintaoleh , pdr.pdrtgldipakai, pdr.pdruraian , pc.pcnama AS pdrjenis , st.nama AS pdrstatus FROM m6_pdr pdr JOIN m1_production_category pc ON pdr.pdrjenis = pc.pckode JOIN m0_status st ON pdr.pdrstatus = st.kode LEFT JOIN m1_contact k ON pdr.pdrdimintaoleh = k.kid ORDER BY pdr.pdrtgl, pdr.pdrid , pdr.pdrnotransaksi;

-- RID=223 | MENU=4 | ITEM=2 | RQUERY=1 | NAME=Daftar Permintaan Produksi (PDR) Outstanding | FILE=PDROutstanding
SELECT pdr.pdrid, pdr.pdrnotransaksi , pdr.pdrtgl, k.knama AS pdrdimintaoleh , pdr.pdrtgldipakai, pdr.pdruraian , pc.pcnama AS pdrjenis , st.nama AS pdrstatus FROM m6_pdr pdr JOIN m1_production_category pc ON pdr.pdrjenis = pc.pckode JOIN m0_status st ON pdr.pdrstatus = st.kode LEFT JOIN m1_contact k ON pdr.pdrdimintaoleh = k.kid ORDER BY pdr.pdrtgl, pdr.pdrid , pdr.pdrnotransaksi;

-- RID=234 | MENU=4 | ITEM=3 | RQUERY=1 | NAME=Permintaan Produksi (PDR) | FILE=ProductionRequest1
SELECT pdr.pdrid, pdr.pdrnotransaksi , pdr.pdrtgl, k.knama AS pdrdimintaoleh , pdr.pdrtgldipakai, pdr.pdruraian , pc.pcnama AS pdrjenis , st.nama AS pdrstatus FROM m6_pdr pdr JOIN m1_production_category pc ON pdr.pdrjenis = pc.pckode JOIN m0_status st ON pdr.pdrstatus = st.kode LEFT JOIN m1_contact k ON pdr.pdrdimintaoleh = k.kid ORDER BY pdr.pdrtgl, pdr.pdrid , pdr.pdrnotransaksi;

-- RID=254 | MENU=4 | ITEM=4 | RQUERY=1 | NAME=Permintaan Produksi (PDR) | FILE=ProductionRequest1_UD
SELECT pdr.pdrid, pdr.pdrnotransaksi , pdr.pdrtgl, k.knama AS pdrdimintaoleh , pdr.pdrtgldipakai, pdr.pdruraian , pc.pcnama AS pdrjenis , st.nama AS pdrstatus FROM m6_pdr pdr JOIN m1_production_category pc ON pdr.pdrjenis = pc.pckode JOIN m0_status st ON pdr.pdrstatus = st.kode LEFT JOIN m1_contact k ON pdr.pdrdimintaoleh = k.kid ORDER BY pdr.pdrtgl, pdr.pdrid , pdr.pdrnotransaksi;

-- RID=272 | MENU=4 | ITEM=5 | RQUERY=1 | NAME=Daftar Permintaan Produksi (PDR) Outstanding Sisa | FILE=PDROutstandingSisa
SELECT pdr.pdrnotransaksi , pdr.pdrid , pdr.pdrtgl , ks.knama AS pdrmintake , kc.knama AS pdrdimintaoleh , pdr.pdrcatatan , CASE pdr.pdrstatus WHEN 0 THEN "Draft" WHEN 1 THEN "Minta Approve" WHEN 2 THEN "Approved" WHEN 3 THEN "Inprogress" WHEN 4 THEN "Complete" WHEN 5 THEN "Revisi" WHEN 6 THEN "Reject" WHEN 7 THEN "Close" WHEN 8 THEN "Approve 1" WHEN 9 THEN "Approve 2" WHEN 10 THEN "Approve 3" WHEN 11 THEN "Approve 4" WHEN 12 THEN "Hapus" END AS pdrstatus FROM m6_pdr pdr JOIN m1_contact ks ON pdr.pdrmintake = ks.kid JOIN m1_contact kc ON pdr.pdrdimintaoleh = kc.kid ORDER BY pdr.pdrid;

-- RID=260 | MENU=4 | ITEM=6 | RQUERY=1 | NAME=Daftar PDR terkait MRS dan MRN | FILE=PDRMRSMRN
SELECT pdr.pdrautonotransaksi , pdr.pdrid FROM m6_pdr pdr ORDER BY pdr.pdrid;

-- RID=261 | MENU=4 | ITEM=7 | RQUERY=1 | NAME=Daftar PDR terkait MRS dan PD | FILE=PDRMRSPD
SELECT pdr.pdrautonotransaksi , pdr.pdrid FROM m6_pdr pdr ORDER BY pdr.pdrid;

-- RID=262 | MENU=4 | ITEM=8 | RQUERY=1 | NAME=Daftar PDR terkait WO dan MRS | FILE=PDRWOMRS
SELECT pdr.pdrautonotransaksi , pdr.pdrid FROM m6_pdr pdr ORDER BY pdr.pdrid;

-- RID=400 | MENU=4 | ITEM=9 | RQUERY=1 | NAME=Daftar Permintaan Produksi (PDR) Per Produk | FILE=ListProductionRequest_perproduk
SELECT bid, bkode, namabarang, kkode, pdrnotransaksi, pdrtgl FROM (SELECT b.bid, b.bkode , pdrin.namabarang , k.kkode, pdr.pdrnotransaksi, pdr.pdrtgl FROM m6_pdr_in pdrin JOIN m1_item b ON pdrin.idbarang = b.bid JOIN m6_pdr pdr ON pdrin.idpdr = pdr.pdrid JOIN m1_contact k ON pdr.pdrdimintaoleh UNION SELECT b.bid , b.bkode , pdrout.namabarang , k.kkode, pdr.pdrnotransaksi, pdr.pdrtgl FROM m6_pdr_out pdrout JOIN m1_item b ON pdrout.idbarang = b.bid JOIN m6_pdr pdr ON pdrout.idpdr = pdr.pdrid JOIN m1_contact k ON pdr.pdrdimintaoleh ) as a GROUP BY bid, bkode , namabarang ORDER BY bid, bkode , namabarang;

-- RID=756 | MENU=4 | ITEM=10 | RQUERY=1 | NAME=Permintaan Produksi (PDR) | FILE=ProductionRequest2
SELECT pdr.pdrid, pdr.pdrnotransaksi , pdr.pdrtgl, k.knama AS pdrdimintaoleh , pdr.pdrtgldipakai, pdr.pdruraian , pc.pcnama AS pdrjenis , st.nama AS pdrstatus FROM m6_pdr pdr JOIN m1_production_category pc ON pdr.pdrjenis = pc.pckode JOIN m0_status st ON pdr.pdrstatus = st.kode LEFT JOIN m1_contact k ON pdr.pdrdimintaoleh = k.kid ORDER BY pdr.pdrtgl, pdr.pdrid , pdr.pdrnotransaksi;

-- RID=1678 | MENU=4 | ITEM=11 | RQUERY=1 | NAME=Daftar Permintaan Produksi (PDR) | FILE=ListProductionRequest2
SELECT pdr.pdrid, pdr.pdrnotransaksi , pdr.pdrtgl, k.knama AS pdrdimintaoleh , pdr.pdrtgldipakai, pdr.pdruraian , pc.pcnama AS pdrjenis , st.nama AS pdrstatus FROM m6_pdr pdr JOIN m1_production_category pc ON pdr.pdrjenis = pc.pckode JOIN m0_status st ON pdr.pdrstatus = st.kode LEFT JOIN m1_contact k ON pdr.pdrdimintaoleh = k.kid ORDER BY pdr.pdrtgl, pdr.pdrid , pdr.pdrnotransaksi;

-- RID=1677 | MENU=4 | ITEM=12 | RQUERY=1 | NAME=Permintaan Produksi (PDR) | FILE=ProductionRequest3
SELECT pdr.pdrid, pdr.pdrnotransaksi , pdr.pdrtgl, k.knama AS pdrdimintaoleh , pdr.pdrtgldipakai, pdr.pdruraian , pc.pcnama AS pdrjenis , st.nama AS pdrstatus FROM m6_pdr pdr JOIN m1_production_category pc ON pdr.pdrjenis = pc.pckode JOIN m0_status st ON pdr.pdrstatus = st.kode LEFT JOIN m1_contact k ON pdr.pdrdimintaoleh = k.kid ORDER BY pdr.pdrtgl, pdr.pdrid , pdr.pdrnotransaksi;

-- RID=1679 | MENU=4 | ITEM=13 | RQUERY=1 | NAME=Permintaan Produksi (PDR) | FILE=ProductionRequest4
SELECT pdr.pdrid, pdr.pdrnotransaksi , pdr.pdrtgl, k.knama AS pdrdimintaoleh , pdr.pdrtgldipakai, pdr.pdruraian , pc.pcnama AS pdrjenis , st.nama AS pdrstatus FROM m6_pdr pdr JOIN m1_production_category pc ON pdr.pdrjenis = pc.pckode JOIN m0_status st ON pdr.pdrstatus = st.kode LEFT JOIN m1_contact k ON pdr.pdrdimintaoleh = k.kid ORDER BY pdr.pdrtgl, pdr.pdrid , pdr.pdrnotransaksi;

-- RID=50003779 | MENU=4 | ITEM=14 | RQUERY=1 | NAME=Machine Production Planning | FILE=MachineProductionPlanning
SELECT p.*, @zsaldo := CASE WHEN @zmesin = p.mesin AND @ztgl = p.tgl THEN @zsaldo - p.jmlpd ELSE p.kapasitasmesin - p.jmlpd END as zsaldo, @zmesin := p.mesin as zmesin, @ztgl := p.tgl as ztgl FROM (SELECT idmsmq, mesin, tgl, kapasitasmesin, idpdrin, pdrnotransaksi, pdrtgl, pdrtgldipakai, kkode, knama, idsodetail, sonotransaksi, sotgl, sotglkirim, idbarang, bkode, namabarang, bkelasproduk, kapasitasperhari, jmlbarang, backorder, jmlpd, satuanbarang, idlogin, userid FROM m2r_machinepdplanning ORDER BY mesin ASC, tgl ASC, bkode ASC, sotglkirim ASC, jmlpd DESC, idpdrin ASC) as p , (SELECT @ztgl := "") as VariableInit1 , (SELECT @zsaldo := 0) as VariableInit2 , (SELECT @zmesin := "") as VariableInit3;

-- RID=237 | MENU=5 | ITEM=1 | RQUERY=1 | NAME=Daftar Perintah Kerja (WO) | FILE=ListWorkOrder
SELECT wo.woid, wo.wonotransaksi, wo.wotgl, k.knama AS wodimintaoleh , wo.wotgldipakai, wo.wouraian , pc.pcnama AS wojenis , st.nama AS wostatus FROM m6_wo wo JOIN m1_production_category pc ON wo.wojenis = pc.pckode JOIN m0_status st ON wo.wostatus = st.kode LEFT JOIN m1_contact k ON wo.wodimintaoleh = k.kid ORDER BY wo.wotgl, wo.woid, wo.wonotransaksi;

-- RID=238 | MENU=5 | ITEM=2 | RQUERY=1 | NAME=Daftar Perintah Kerja (WO) Outstanding | FILE=WOOutstanding
SELECT wo.woid, wo.wonotransaksi, wo.wotgl, k.knama AS wodimintaoleh , wo.wotgldipakai, wo.wouraian , pc.pcnama AS wojenis , st.nama AS wostatus FROM m6_wo wo JOIN m1_production_category pc ON wo.wojenis = pc.pckode JOIN m0_status st ON wo.wostatus = st.kode LEFT JOIN m1_contact k ON wo.wodimintaoleh = k.kid ORDER BY wo.wotgl, wo.woid, wo.wonotransaksi;

-- RID=239 | MENU=5 | ITEM=3 | RQUERY=1 | NAME=Perintah Kerja (WO)  | FILE=WorkOrder1
SELECT wo.woid, wo.wonotransaksi, wo.wotgl, k.knama AS wodimintaoleh , wo.wotgldipakai, wo.wouraian , pc.pcnama AS wojenis , st.nama AS wostatus FROM m6_wo wo JOIN m1_production_category pc ON wo.wojenis = pc.pckode JOIN m0_status st ON wo.wostatus = st.kode LEFT JOIN m1_contact k ON wo.wodimintaoleh = k.kid ORDER BY wo.wotgl, wo.woid, wo.wonotransaksi;

-- RID=553 | MENU=5 | ITEM=4 | RQUERY=1 | NAME=Perintah Kerja (WO) | FILE=WorkOrder1_UD
SELECT wo.woid, wo.wonotransaksi, wo.wotgl, k.knama AS wodimintaoleh , wo.wotgldipakai, wo.wouraian , pc.pcnama AS wojenis , st.nama AS wostatus FROM m6_wo wo JOIN m1_production_category pc ON wo.wojenis = pc.pckode JOIN m0_status st ON wo.wostatus = st.kode LEFT JOIN m1_contact k ON wo.wodimintaoleh = k.kid ORDER BY wo.wotgl, wo.woid, wo.wonotransaksi;

-- RID=263 | MENU=5 | ITEM=5 | RQUERY=1 | NAME=Daftar WO terkait MRS dan MRN | FILE=WOMRSMRN
SELECT wo.woid , wo.wonotransaksi FROM m6_wo wo LEFT JOIN m1_contact ks ON wo.womintake = ks.kid LEFT JOIN m1_contact kc ON wo.wodimintaoleh = kc.kid LEFT JOIN m1_production_category pc ON wo.wojenis = pc.pckode left JOIN m1_warehouse wa ON wo.wogudangasal = wa.wkode LEFT JOIN m1_warehouse wp ON wo.wogudangproduksi = wp.wkode LEFT JOIN m1_warehouse wt ON wo.wogudangtujuan = wt.wkode ORDER BY wo.woid;

-- RID=264 | MENU=5 | ITEM=6 | RQUERY=1 | NAME=Daftar WO terkait MRS dan PD | FILE=WOMRSPD
SELECT wo.woid , wo.wonotransaksi FROM m6_wo wo LEFT JOIN m1_contact ks ON wo.womintake = ks.kid LEFT JOIN m1_contact kc ON wo.wodimintaoleh = kc.kid LEFT JOIN m1_production_category pc ON wo.wojenis = pc.pckode left JOIN m1_warehouse wa ON wo.wogudangasal = wa.wkode LEFT JOIN m1_warehouse wp ON wo.wogudangproduksi = wp.wkode LEFT JOIN m1_warehouse wt ON wo.wogudangtujuan = wt.wkode ORDER BY wo.woid;

-- RID=267 | MENU=5 | ITEM=7 | RQUERY=1 | NAME=Daftar Perintah Kerja (WO) Outstanding Sisa | FILE=WOOutstandingSIsa
SELECT /* WO (WO>MRS>MRN>PD)*/ wo.wonotransaksi , wo.woid , wo.wotgl, ks.knama AS womintake , kc.knama AS wodimintaoleh , wo.wocatatan , CASE wo.wostatus WHEN 0 THEN "Draft" WHEN 1 THEN "Minta Approve" WHEN 2 THEN "Approved" WHEN 3 THEN "Inprogress" WHEN 4 THEN "Complete" WHEN 5 THEN "Revisi" WHEN 6 THEN "Reject" WHEN 7 THEN "Close" WHEN 8 THEN "Approve 1" WHEN 9 THEN "Approve 2" WHEN 10 THEN "Approve 3" WHEN 11 THEN "Approve 4" WHEN 12 THEN "Hapus" END AS wostatus FROM m6_wo wo JOIN m1_contact ks ON wo.womintake = ks.kid JOIN m1_contact kc ON wo.wodimintaoleh = kc.kid ORDER BY wo.woid;

-- RID=401 | MENU=5 | ITEM=8 | RQUERY=1 | NAME=Daftar Perintah Kerja (WO) Per Produk | FILE=ListWorkOrder_perproduk
SELECT bid, bkode, namabarang , wonotransaksi, wotgl , wotgldipakai FROM (SELECT b.bid, b.bkode , woin.namabarang , wo.wonotransaksi, wo.wotgl, wo.wotgldipakai FROM m6_wo_in woin JOIN m1_item b ON woin.idbarang = b.bid JOIN m6_wo wo ON woin.idwo = wo.woid UNION SELECT bb.bid, bb.bkode , woout.namabarang , wo.wonotransaksi, wo.wotgl , wo.wotgldipakai FROM m6_wo_out woout JOIN m1_item bb ON woout.idbarang = bb.bid JOIN m6_wo wo ON woout.idwo = wo.woid ) as a GROUP BY bid, bkode , namabarang ORDER BY bid, bkode , namabarang;

-- RID=757 | MENU=5 | ITEM=9 | RQUERY=1 | NAME=Perintah Kerja (WO) | FILE=WorkOrder2
SELECT wo.woid, wo.wonotransaksi, wo.wotgl, k.knama AS wodimintaoleh , wo.wotgldipakai, wo.wouraian , pc.pcnama AS wojenis , st.nama AS wostatus FROM m6_wo wo JOIN m1_production_category pc ON wo.wojenis = pc.pckode JOIN m0_status st ON wo.wostatus = st.kode LEFT JOIN m1_contact k ON wo.wodimintaoleh = k.kid ORDER BY wo.wotgl, wo.woid, wo.wonotransaksi;

-- RID=1681 | MENU=5 | ITEM=10 | RQUERY=1 | NAME=Daftar Perintah Kerja (WO) | FILE=ListWorkOrder2
SELECT wo.woid, wo.wonotransaksi, wo.wotgl, k.knama AS wodimintaoleh , wo.wotgldipakai, wo.wouraian , pc.pcnama AS wojenis , st.nama AS wostatus FROM m6_wo wo JOIN m1_production_category pc ON wo.wojenis = pc.pckode JOIN m0_status st ON wo.wostatus = st.kode LEFT JOIN m1_contact k ON wo.wodimintaoleh = k.kid ORDER BY wo.wotgl, wo.woid, wo.wonotransaksi;

-- RID=1682 | MENU=5 | ITEM=11 | RQUERY=1 | NAME=Perintah Kerja (WO) | FILE=WorkOrder3
SELECT wo.woid, wo.wonotransaksi, wo.wotgl, k.knama AS wodimintaoleh , wo.wotgldipakai, wo.wouraian , pc.pcnama AS wojenis , st.nama AS wostatus, wo.wonoref FROM m6_wo wo JOIN m1_production_category pc ON wo.wojenis = pc.pckode JOIN m0_status st ON wo.wostatus = st.kode LEFT JOIN m1_contact k ON wo.wodimintaoleh = k.kid ORDER BY wo.wotgl, wo.woid, wo.wonotransaksi;

-- RID=1683 | MENU=5 | ITEM=12 | RQUERY=1 | NAME=Perintah Kerja (WO) | FILE=WorkOrder4
SELECT wo.woid, wo.wonotransaksi, wo.wotgl, k.knama AS wodimintaoleh , wo.wotgldipakai, wo.wouraian , pc.pcnama AS wojenis , st.nama AS wostatus, wo.wonoref FROM m6_wo wo JOIN m1_production_category pc ON wo.wojenis = pc.pckode JOIN m0_status st ON wo.wostatus = st.kode LEFT JOIN m1_contact k ON wo.wodimintaoleh = k.kid ORDER BY wo.wotgl, wo.woid, wo.wonotransaksi;

-- RID=50001632 | MENU=5 | ITEM=13 | RQUERY=1 | NAME=MATERIAL SLIP  | FILE=MaterialRelease KAWATA
SELECT wo.wodimintaolehkontak , wo.woid , wo.wonotransaksi , wo.wotgl , wo.wotgldipakai , wo.wouraian , wo.woidbom, bom.bomnotransaksi , b.bnama, woin.jml , woin.jmlbarang, woin.satuan , wo.wojenis , bb.bkode AS kodebarang , bb.bnama AS namabarang , woout.jml AS jumlah , woout.satuan AS sat FROM m6_wo wo JOIN m6_wo_in woin ON wo.woid = woin.idwo LEFT JOIN m6_bom bom ON wo.woidbom = bom.bomid JOIN m1_item b ON woin.idbarang = b.bid JOIN m6_wo_out woout ON wo.woid = woout.idwo JOIN m1_item bb ON woout.idbarang = bb.bid ORDER BY wo.wotgl ASC , wo.woid ASC , wo.wonotransaksi ASC;

-- RID=50001634 | MENU=5 | ITEM=14 | RQUERY=1 | NAME=MATERIAL SLIP | FILE=MaterialRelease KAWATA 2
SELECT wo.wodimintaolehkontak , wo.woid , wo.wonotransaksi , wo.wotgl , wo.wotgldipakai , wo.wouraian , wo.woidbom, bom.bomnotransaksi , b.bnama, woin.jml , woin.jmlbarang, woin.satuan , wo.wojenis , bb.bkode AS kodebarang , bb.bnama AS namabarang , woout.jml AS jumlah , woout.satuan AS sat FROM m6_wo wo JOIN m6_wo_in woin ON wo.woid = woin.idwo LEFT JOIN m6_bom bom ON wo.woidbom = bom.bomid JOIN m1_item b ON woin.idbarang = b.bid JOIN m6_wo_out woout ON wo.woid = woout.idwo JOIN m1_item bb ON woout.idbarang = bb.bid ORDER BY wo.wotgl ASC , wo.woid ASC , wo.wonotransaksi ASC;

-- RID=50003790 | MENU=5 | ITEM=15 | RQUERY=1 | NAME=Route Card | FILE=route card br
SELECT woo.wonotransaksi FROM m6_wo woo ORDER BY woo.wotgl, woo.wonotransaksi;

-- RID=242 | MENU=6 | ITEM=1 | RQUERY=1 | NAME=Daftar Pengeluaran Bahan Baku (MRS) | FILE=ListMaterialRelease
SELECT mrs.mrsid , mrs.mrsnotransaksi , mrs.mrstgl, mrs.mrstgldipakai, wa.wnama AS mrsgudangasal , wp.wnama AS mrsgudangproduksi, pc.pcnama AS mrsjenis, mrs.mrsuraian , st.nama AS mrsstatus, wo.wonotransaksi , b.bkode, mrsout.namabarang , mrsout.jml, mrsout.satuan , mrsout.harga , (mrsout.jml * mrsout.harga) as total FROM m6_mrs mrs JOIN m1_warehouse wa ON mrs.mrsgudangasal = wa.wkode JOIN m1_warehouse wp ON mrs.mrsgudangproduksi = wp.wkode JOIN m1_production_category pc ON mrs.mrsjenis = pc.pckode JOIN m0_status st ON mrs.mrsstatus = st.kode JOIN m6_mrs_out mrsout ON mrs.mrsid = mrsout.idmrs JOIN m1_item b ON mrsout.idbarang = b.bid LEFT JOIN m6_wo wo ON mrs.mrsidwo = wo.woid ORDER BY mrs.mrstgl , mrs.mrsid, mrs.mrsnotransaksi , mrsout.urutan;

-- RID=243 | MENU=6 | ITEM=2 | RQUERY=1 | NAME=Daftar Pengeluaran Bahan Baku (MRS) Outstanding | FILE=MRSOutstanding
SELECT mrs.mrsid , mrs.mrsnotransaksi , mrs.mrstgl, mrs.mrstgldipakai, wa.wnama AS mrsgudangasal , wp.wnama AS mrsgudangproduksi, pc.pcnama AS mrsjenis, mrs.mrsuraian , st.nama AS mrsstatus, wo.wonotransaksi , b.bkode, mrsout.namabarang , mrsout.jml, mrsout.satuan, (mrsout.jmlrealisasi / mrsout.nilaisatuan) AS jmlrealisasi , (mrsout.jml - (mrsout.jmlrealisasi / mrsout.nilaisatuan)) as jmlsisa FROM m6_mrs mrs JOIN m1_warehouse wa ON mrs.mrsgudangasal = wa.wkode JOIN m1_warehouse wp ON mrs.mrsgudangproduksi = wp.wkode JOIN m1_production_category pc ON mrs.mrsjenis = pc.pckode JOIN m0_status st ON mrs.mrsstatus = st.kode JOIN m6_mrs_out mrsout ON mrs.mrsid = mrsout.idmrs JOIN m1_item b ON mrsout.idbarang = b.bid LEFT JOIN m6_wo wo ON mrs.mrsidwo = wo.woid ORDER BY mrs.mrstgl , mrs.mrsid, mrs.mrsnotransaksi , mrsout.urutan;

-- RID=244 | MENU=6 | ITEM=3 | RQUERY=1 | NAME=Pengeluaran Bahan Baku (MRS) | FILE=MaterialRelease1
SELECT mrs.mrsid , mrs.mrsnotransaksi , mrs.mrstgl, mrs.mrstgldipakai, wa.wnama AS mrsgudangasal , wp.wnama AS mrsgudangproduksi, pc.pcnama AS mrsjenis, mrs.mrsuraian , st.nama AS mrsstatus, wo.wonotransaksi , b.bkode, mrsout.namabarang , mrsout.jml, mrsout.satuan , mrsout.harga , (mrsout.jml * mrsout.harga) as total FROM m6_mrs mrs JOIN m1_warehouse wa ON mrs.mrsgudangasal = wa.wkode JOIN m1_warehouse wp ON mrs.mrsgudangproduksi = wp.wkode JOIN m1_production_category pc ON mrs.mrsjenis = pc.pckode JOIN m0_status st ON mrs.mrsstatus = st.kode JOIN m6_mrs_out mrsout ON mrs.mrsid = mrsout.idmrs JOIN m1_item b ON mrsout.idbarang = b.bid LEFT JOIN m6_wo wo ON mrs.mrsidwo = wo.woid ORDER BY mrs.mrstgl , mrs.mrsid, mrs.mrsnotransaksi , mrsout.urutan;

-- RID=499 | MENU=6 | ITEM=4 | RQUERY=1 | NAME=Pengeluaran Bahan Baku (MRS) | FILE=MaterialRelease1_tanpaharga
SELECT mrs.mrsid , mrs.mrsnotransaksi , mrs.mrstgl, mrs.mrstgldipakai, wa.wnama AS mrsgudangasal , wp.wnama AS mrsgudangproduksi, pc.pcnama AS mrsjenis, mrs.mrsuraian , st.nama AS mrsstatus, wo.wonotransaksi , b.bkode, mrsout.namabarang , mrsout.jml, mrsout.satuan , mrsout.catatan FROM m6_mrs mrs JOIN m1_warehouse wa ON mrs.mrsgudangasal = wa.wkode JOIN m1_warehouse wp ON mrs.mrsgudangproduksi = wp.wkode JOIN m1_production_category pc ON mrs.mrsjenis = pc.pckode JOIN m0_status st ON mrs.mrsstatus = st.kode JOIN m6_mrs_out mrsout ON mrs.mrsid = mrsout.idmrs JOIN m1_item b ON mrsout.idbarang = b.bid LEFT JOIN m6_wo wo ON mrs.mrsidwo = wo.woid ORDER BY mrs.mrstgl , mrs.mrsid, mrs.mrsnotransaksi , mrsout.urutan;

-- RID=490 | MENU=6 | ITEM=5 | RQUERY=1 | NAME=Pengeluaran Bahan Baku (MRS) Serial | FILE=MaterialRelease1_serial
SELECT COUNT(*) , mrsout.idbarang , mrs.mrsid , mrs.mrsnotransaksi , mrs.mrstgl, mrs.mrstgldipakai, wa.wnama AS mrsgudangasal , wp.wnama AS mrsgudangproduksi, pc.pcnama AS mrsjenis, mrs.mrsuraian , st.nama AS mrsstatus, wo.wonotransaksi , b.bkode, mrsout.namabarang , SUM(mrsout.jml) AS jml, mrsout.satuan , mrsout.harga , (SUM(mrsout.jml) * mrsout.harga) as total FROM m6_mrs mrs JOIN m1_warehouse wa ON mrs.mrsgudangasal = wa.wkode JOIN m1_warehouse wp ON mrs.mrsgudangproduksi = wp.wkode JOIN m1_production_category pc ON mrs.mrsjenis = pc.pckode JOIN m0_status st ON mrs.mrsstatus = st.kode JOIN m6_mrs_out mrsout ON mrs.mrsid = mrsout.idmrs JOIN m1_item b ON mrsout.idbarang = b.bid LEFT JOIN m6_wo wo ON mrs.mrsidwo = wo.woid GROUP BY mrs.mrsid, mrsout.idbarang , mrsout.namabarang , mrsout.satuan , mrsout.harga ORDER BY mrs.mrstgl , mrs.mrsid, mrs.mrsnotransaksi , mrsout.urutan;

-- RID=556 | MENU=6 | ITEM=6 | RQUERY=1 | NAME=Pengeluaran Bahan Baku (MRS)  | FILE=MaterialRelease1_UD
SELECT mrs.mrsid , mrs.mrsnotransaksi , mrs.mrstgl, mrs.mrstgldipakai, wa.wnama AS mrsgudangasal , wp.wnama AS mrsgudangproduksi, pc.pcnama AS mrsjenis, mrs.mrsuraian , st.nama AS mrsstatus, wo.wonotransaksi , b.bkode, mrsout.namabarang , mrsout.jml, mrsout.satuan , mrsout.harga , (mrsout.jml * mrsout.harga) as total FROM m6_mrs mrs JOIN m1_warehouse wa ON mrs.mrsgudangasal = wa.wkode JOIN m1_warehouse wp ON mrs.mrsgudangproduksi = wp.wkode JOIN m1_production_category pc ON mrs.mrsjenis = pc.pckode JOIN m0_status st ON mrs.mrsstatus = st.kode JOIN m6_mrs_out mrsout ON mrs.mrsid = mrsout.idmrs JOIN m1_item b ON mrsout.idbarang = b.bid LEFT JOIN m6_wo wo ON mrs.mrsidwo = wo.woid ORDER BY mrs.mrstgl , mrs.mrsid, mrs.mrsnotransaksi , mrsout.urutan;

-- RID=259 | MENU=6 | ITEM=7 | RQUERY=1 | NAME=Daftar MRS terkait MRN dan PD | FILE=MRSMRNPD
SELECT mrs.mrsid, mrs.mrsnotransaksi FROM m6_mrs mrs LEFT JOIN m1_contact ks on mrs.mrsbagianmrs = ks.kid LEFT JOIN m1_production_category pc ON mrs.mrsjenis = pc.pckode ORDER BY mrs.mrsid;

-- RID=275 | MENU=6 | ITEM=8 | RQUERY=1 | NAME=Daftar Pengeluaran Bahan Baku (MRS) Outstanding Sisa | FILE=MRSOutstandingSisa
SELECT /*MRS(MRS>MRN>PD)*/ mrs.mrsnotransaksi , mrs.mrsid , mrs.mrstgl , ks.knama AS mrsbagianmrs , mrs.mrscatatan , CASE mrs.mrsstatus WHEN 0 THEN "Draft" WHEN 1 THEN "Minta Approve" WHEN 2 THEN "Approved" WHEN 3 THEN "Inprogress" WHEN 4 THEN "Complete" WHEN 5 THEN "Revisi" WHEN 6 THEN "Reject" WHEN 7 THEN "Close" WHEN 8 THEN "Approve 1" WHEN 9 THEN "Approve 2" WHEN 10 THEN "Approve 3" WHEN 11 THEN "Approve 4" WHEN 12 THEN "Hapus" END AS mrsstatus FROM m6_mrs mrs LEFT JOIN m1_contact ks on mrs.mrsbagianmrs = ks.kid LEFT JOIN m1_production_category pc ON mrs.mrsjenis = pc.pckode ORDER BY mrs.mrsid;

-- RID=402 | MENU=6 | ITEM=9 | RQUERY=1 | NAME=Daftar Pengeluaran Bahan Baku (MRS) Per Produk | FILE=ListMaterialRelease_perproduk
SELECT b.bid , b.bkode , mrsout.namabarang , mrs.mrsnotransaksi , mrs.mrstgl, mrs.mrstgldipakai , wa.wnama AS mrsgudangasal , wp.wnama AS mrsgudangproduksi , SUM(mrsout.jml) AS jml, mrsout.satuan , mrsout.harga , SUM(mrsout.jml * mrsout.harga) as total FROM m6_mrs mrs JOIN m1_warehouse wa ON mrs.mrsgudangasal = wa.wkode JOIN m1_warehouse wp ON mrs.mrsgudangproduksi = wp.wkode JOIN m1_production_category pc ON mrs.mrsjenis = pc.pckode JOIN m0_status st ON mrs.mrsstatus = st.kode JOIN m6_mrs_out mrsout ON mrs.mrsid = mrsout.idmrs JOIN m1_item b ON mrsout.idbarang = b.bid GROUP BY mrsout.idbarang , b.bid, b.bkode, mrsout.namabarang , mrsout.satuan , mrsout.harga, mrsout.idmrs ORDER BY mrsout.idbarang, b.bid , b.bkode , mrsout.namabarang;

-- RID=758 | MENU=6 | ITEM=10 | RQUERY=1 | NAME=Pengeluaran Bahan Baku (MRS) | FILE=MaterialRelease2
SELECT mrs.mrsid , mrs.mrsnotransaksi , mrs.mrstgl, mrs.mrstgldipakai, wa.wnama AS mrsgudangasal , wp.wnama AS mrsgudangproduksi, pc.pcnama AS mrsjenis, mrs.mrsuraian , st.nama AS mrsstatus, wo.wonotransaksi , b.bkode, mrsout.namabarang , mrsout.jml, mrsout.satuan , mrsout.harga , (mrsout.jml * mrsout.harga) as total FROM m6_mrs mrs JOIN m1_warehouse wa ON mrs.mrsgudangasal = wa.wkode JOIN m1_warehouse wp ON mrs.mrsgudangproduksi = wp.wkode JOIN m1_production_category pc ON mrs.mrsjenis = pc.pckode JOIN m0_status st ON mrs.mrsstatus = st.kode JOIN m6_mrs_out mrsout ON mrs.mrsid = mrsout.idmrs JOIN m1_item b ON mrsout.idbarang = b.bid LEFT JOIN m6_wo wo ON mrs.mrsidwo = wo.woid ORDER BY mrs.mrstgl , mrs.mrsid, mrs.mrsnotransaksi , mrsout.urutan;

-- RID=759 | MENU=6 | ITEM=11 | RQUERY=1 | NAME=Pengeluaran Bahan Baku (MRS) | FILE=MaterialRelease1_tanpaharga2
SELECT mrs.mrsid , mrs.mrsnotransaksi , mrs.mrstgl, mrs.mrstgldipakai, wa.wnama AS mrsgudangasal , wp.wnama AS mrsgudangproduksi, pc.pcnama AS mrsjenis, mrs.mrsuraian , st.nama AS mrsstatus, wo.wonotransaksi , b.bkode, mrsout.namabarang , mrsout.jml, mrsout.satuan , mrsout.catatan FROM m6_mrs mrs JOIN m1_warehouse wa ON mrs.mrsgudangasal = wa.wkode JOIN m1_warehouse wp ON mrs.mrsgudangproduksi = wp.wkode JOIN m1_production_category pc ON mrs.mrsjenis = pc.pckode JOIN m0_status st ON mrs.mrsstatus = st.kode JOIN m6_mrs_out mrsout ON mrs.mrsid = mrsout.idmrs JOIN m1_item b ON mrsout.idbarang = b.bid LEFT JOIN m6_wo wo ON mrs.mrsidwo = wo.woid ORDER BY mrs.mrstgl , mrs.mrsid, mrs.mrsnotransaksi , mrsout.urutan;

-- RID=1685 | MENU=6 | ITEM=12 | RQUERY=1 | NAME=Daftar Pengeluaran Bahan Baku (MRS) | FILE=ListMaterialRelease2
SELECT mrs.mrsid , mrs.mrsnotransaksi , mrs.mrstgl, mrs.mrstgldipakai, wa.wnama AS mrsgudangasal , wp.wnama AS mrsgudangproduksi, pc.pcnama AS mrsjenis, mrs.mrsuraian , st.nama AS mrsstatus, wo.wonotransaksi , b.bkode, mrsout.namabarang , mrsout.jml, mrsout.satuan , mrsout.harga , (mrsout.jml * mrsout.harga) as total FROM m6_mrs mrs JOIN m1_warehouse wa ON mrs.mrsgudangasal = wa.wkode JOIN m1_warehouse wp ON mrs.mrsgudangproduksi = wp.wkode JOIN m1_production_category pc ON mrs.mrsjenis = pc.pckode JOIN m0_status st ON mrs.mrsstatus = st.kode JOIN m6_mrs_out mrsout ON mrs.mrsid = mrsout.idmrs JOIN m1_item b ON mrsout.idbarang = b.bid LEFT JOIN m6_wo wo ON mrs.mrsidwo = wo.woid ORDER BY mrs.mrstgl , mrs.mrsid, mrs.mrsnotransaksi , mrsout.urutan;

-- RID=2020 | MENU=6 | ITEM=13 | RQUERY=1 | NAME=Pengeluaran Bahan Baku (MRS) Batch | FILE=MaterialRelease1_batch
SELECT COUNT(*) , mrsout.idbarang , mrs.mrsid , mrs.mrsnotransaksi , mrs.mrstgl, mrs.mrstgldipakai, wa.wnama AS mrsgudangasal , wp.wnama AS mrsgudangproduksi, pc.pcnama AS mrsjenis, mrs.mrsuraian , st.nama AS mrsstatus, wo.wonotransaksi , b.bkode, mrsout.namabarang , SUM(mrsout.jml) AS jml, mrsout.satuan , mrsout.harga , (SUM(mrsout.jml) * mrsout.harga) as total FROM m6_mrs mrs JOIN m1_warehouse wa ON mrs.mrsgudangasal = wa.wkode JOIN m1_warehouse wp ON mrs.mrsgudangproduksi = wp.wkode JOIN m1_production_category pc ON mrs.mrsjenis = pc.pckode JOIN m0_status st ON mrs.mrsstatus = st.kode JOIN m6_mrs_out mrsout ON mrs.mrsid = mrsout.idmrs JOIN m1_item b ON mrsout.idbarang = b.bid LEFT JOIN m6_wo wo ON mrs.mrsidwo = wo.woid GROUP BY mrs.mrsid, mrsout.idbarang , mrsout.namabarang , mrsout.satuan , mrsout.harga ORDER BY mrs.mrstgl , mrs.mrsid, mrs.mrsnotransaksi , mrsout.urutan;

-- RID=247 | MENU=7 | ITEM=1 | RQUERY=1 | NAME=Daftar Retur Bahan Baku (MRN) | FILE=ListMaterialReturrn
SELECT mrn.mrnid , mrn.mrnnotransaksi , mrn.mrntgl , pc.pcnama AS mrnjenis , wp.wnama AS mrngudangproduksi, wt.wnama AS mrngudangtujuan, mrnuraian , st.nama AS mrnstatus, b.bkode , mrnout.namabarang , mrs.mrsnotransaksi , mrnout.jml , mrnout.satuan , mrnout.harga , (mrnout.jml * mrnout.harga ) AS total FROM m6_mrn mrn JOIN m1_production_category pc ON mrn.mrnjenis = pc.pckode JOIN m1_warehouse wp ON mrn.mrngudangproduksi = wp.wkode JOIN m1_warehouse wt ON mrn.mrngudangtujuan = wt.wkode JOIN m0_status st ON mrn.mrnstatus = st.kode JOIN m6_mrn_out mrnout ON mrn.mrnid = mrnout.idmrn JOIN m1_item b ON mrnout.idbarang = b.bid LEFT JOIN m6_mrs_out mrsout ON mrnout.idmrsout = mrsout.idmrsout LEFT JOIN m6_mrs mrs ON mrsout.idmrs = mrs.mrsid ORDER BY mrn.mrntgl , mrn.mrnid, mrn.mrnnotransaksi, mrnout.urutan;

-- RID=249 | MENU=7 | ITEM=2 | RQUERY=1 | NAME=Retur Bahan Baku (MRN) | FILE=MaterialReturrn1
SELECT mrn.mrnid , mrn.mrnnotransaksi , mrn.mrntgl , pc.pcnama AS mrnjenis , wp.wnama AS mrngudangproduksi, wt.wnama AS mrngudangtujuan, mrnuraian , st.nama AS mrnstatus, b.bkode , mrnout.namabarang , mrs.mrsnotransaksi , mrnout.jml , mrnout.satuan , mrnout.harga , (mrnout.jml * mrnout.harga ) AS total FROM m6_mrn mrn JOIN m1_production_category pc ON mrn.mrnjenis = pc.pckode JOIN m1_warehouse wp ON mrn.mrngudangproduksi = wp.wkode JOIN m1_warehouse wt ON mrn.mrngudangtujuan = wt.wkode JOIN m0_status st ON mrn.mrnstatus = st.kode JOIN m6_mrn_out mrnout ON mrn.mrnid = mrnout.idmrn JOIN m1_item b ON mrnout.idbarang = b.bid LEFT JOIN m6_mrs_out mrsout ON mrnout.idmrsout = mrsout.idmrsout LEFT JOIN m6_mrs mrs ON mrsout.idmrs = mrs.mrsid ORDER BY mrn.mrntgl , mrn.mrnid, mrn.mrnnotransaksi, mrnout.urutan;

-- RID=500 | MENU=7 | ITEM=3 | RQUERY=1 | NAME=Retur Bahan Baku (MRN) | FILE=MaterialReturrn1_tanpaharga
SELECT mrn.mrnid , mrn.mrnnotransaksi , mrn.mrntgl , pc.pcnama AS mrnjenis , wp.wnama AS mrngudangproduksi, wt.wnama AS mrngudangtujuan, mrnuraian , st.nama AS mrnstatus, b.bkode , mrnout.namabarang , mrs.mrsnotransaksi , mrnout.jml , mrnout.satuan , mrsout.catatan FROM m6_mrn mrn JOIN m1_production_category pc ON mrn.mrnjenis = pc.pckode JOIN m1_warehouse wp ON mrn.mrngudangproduksi = wp.wkode JOIN m1_warehouse wt ON mrn.mrngudangtujuan = wt.wkode JOIN m0_status st ON mrn.mrnstatus = st.kode JOIN m6_mrn_out mrnout ON mrn.mrnid = mrnout.idmrn JOIN m1_item b ON mrnout.idbarang = b.bid LEFT JOIN m6_mrs_out mrsout ON mrnout.idmrsout = mrsout.idmrsout LEFT JOIN m6_mrs mrs ON mrsout.idmrs = mrs.mrsid ORDER BY mrn.mrntgl , mrn.mrnid, mrn.mrnnotransaksi, mrnout.urutan;

-- RID=489 | MENU=7 | ITEM=4 | RQUERY=1 | NAME=Retur Bahan Baku (MRN) Serial | FILE=MaterialReturrn1_serial
SELECT COUNT(*), mrnout.idbarang, mrn.mrnid , mrn.mrnnotransaksi , mrn.mrntgl , pc.pcnama AS mrnjenis , wp.wnama AS mrngudangproduksi, wt.wnama AS mrngudangtujuan, mrnuraian , st.nama AS mrnstatus, b.bkode , mrnout.namabarang , mrs.mrsnotransaksi , SUM(mrnout.jml) AS jml , mrnout.satuan , mrnout.harga , (SUM(mrnout.jml) * mrnout.harga ) AS total FROM m6_mrn mrn JOIN m1_production_category pc ON mrn.mrnjenis = pc.pckode JOIN m1_warehouse wp ON mrn.mrngudangproduksi = wp.wkode JOIN m1_warehouse wt ON mrn.mrngudangtujuan = wt.wkode JOIN m0_status st ON mrn.mrnstatus = st.kode JOIN m6_mrn_out mrnout ON mrn.mrnid = mrnout.idmrn JOIN m1_item b ON mrnout.idbarang = b.bid LEFT JOIN m6_mrs_out mrsout ON mrnout.idmrsout = mrsout.idmrsout LEFT JOIN m6_mrs mrs ON mrsout.idmrs = mrs.mrsid GROUP BY mrn.mrnid, mrnout.idbarang , mrnout.namabarang , mrnout.satuan , mrnout.harga ORDER BY mrn.mrntgl , mrn.mrnid, mrn.mrnnotransaksi, mrnout.urutan;

-- RID=557 | MENU=7 | ITEM=5 | RQUERY=1 | NAME=Retur Bahan Baku (MRN)  | FILE=MaterialReturrn1_UD
SELECT mrn.mrnid , mrn.mrnnotransaksi , mrn.mrntgl , pc.pcnama AS mrnjenis , wp.wnama AS mrngudangproduksi, wt.wnama AS mrngudangtujuan, mrnuraian , st.nama AS mrnstatus, b.bkode , mrnout.namabarang , mrs.mrsnotransaksi , mrnout.jml , mrnout.satuan , mrnout.harga , (mrnout.jml * mrnout.harga ) AS total FROM m6_mrn mrn JOIN m1_production_category pc ON mrn.mrnjenis = pc.pckode JOIN m1_warehouse wp ON mrn.mrngudangproduksi = wp.wkode JOIN m1_warehouse wt ON mrn.mrngudangtujuan = wt.wkode JOIN m0_status st ON mrn.mrnstatus = st.kode JOIN m6_mrn_out mrnout ON mrn.mrnid = mrnout.idmrn JOIN m1_item b ON mrnout.idbarang = b.bid LEFT JOIN m6_mrs_out mrsout ON mrnout.idmrsout = mrsout.idmrsout LEFT JOIN m6_mrs mrs ON mrsout.idmrs = mrs.mrsid ORDER BY mrn.mrntgl , mrn.mrnid, mrn.mrnnotransaksi, mrnout.urutan;

-- RID=403 | MENU=7 | ITEM=6 | RQUERY=1 | NAME=Daftar Retur Bahan Baku (MRN) Per Produk | FILE=ListMaterialReturrn_perproduk
SELECT b.bid, b.bkode , mrnout.namabarang, mrn.mrnnotransaksi , mrn.mrntgl , pc.pcnama AS mrnjenis , wp.wnama AS mrngudangproduksi, wt.wnama AS mrngudangtujuan, mrnout.jml , mrnout.satuan , mrnout.harga , (mrnout.jml * mrnout.harga ) AS total FROM m6_mrn mrn JOIN m1_production_category pc ON mrn.mrnjenis = pc.pckode JOIN m1_warehouse wp ON mrn.mrngudangproduksi = wp.wkode JOIN m1_warehouse wt ON mrn.mrngudangtujuan = wt.wkode JOIN m0_status st ON mrn.mrnstatus = st.kode JOIN m6_mrn_out mrnout ON mrn.mrnid = mrnout.idmrn JOIN m1_item b ON mrnout.idbarang = b.bid LEFT JOIN m6_mrs_out mrsout ON mrnout.idmrsout = mrsout.idmrsout LEFT JOIN m6_mrs mrs ON mrsout.idmrs = mrs.mrsid GROUP BY mrnout.idbarang , b.bid, b.bkode, mrnout.namabarang, mrnout.satuan ,mrnout.harga , mrnout.idmrn, pc.pcnama ,wp.wnama ,wt.wnama ORDER BY mrnout.idbarang , b.bid, b.bkode, mrnout.namabarang;

-- RID=760 | MENU=7 | ITEM=7 | RQUERY=1 | NAME=Retur Bahan Baku (MRN) | FILE=MaterialReturrn2
SELECT mrn.mrnid , mrn.mrnnotransaksi , mrn.mrntgl , pc.pcnama AS mrnjenis , wp.wnama AS mrngudangproduksi, wt.wnama AS mrngudangtujuan, mrnuraian , st.nama AS mrnstatus, b.bkode , mrnout.namabarang , mrs.mrsnotransaksi , mrnout.jml , mrnout.satuan , mrnout.harga , (mrnout.jml * mrnout.harga ) AS total FROM m6_mrn mrn JOIN m1_production_category pc ON mrn.mrnjenis = pc.pckode JOIN m1_warehouse wp ON mrn.mrngudangproduksi = wp.wkode JOIN m1_warehouse wt ON mrn.mrngudangtujuan = wt.wkode JOIN m0_status st ON mrn.mrnstatus = st.kode JOIN m6_mrn_out mrnout ON mrn.mrnid = mrnout.idmrn JOIN m1_item b ON mrnout.idbarang = b.bid LEFT JOIN m6_mrs_out mrsout ON mrnout.idmrsout = mrsout.idmrsout LEFT JOIN m6_mrs mrs ON mrsout.idmrs = mrs.mrsid ORDER BY mrn.mrntgl , mrn.mrnid, mrn.mrnnotransaksi, mrnout.urutan;

-- RID=761 | MENU=7 | ITEM=8 | RQUERY=1 | NAME=Retur Bahan Baku (MRN) | FILE=MaterialReturrn1_tanpaharga2
SELECT mrn.mrnid , mrn.mrnnotransaksi , mrn.mrntgl , pc.pcnama AS mrnjenis , wp.wnama AS mrngudangproduksi, wt.wnama AS mrngudangtujuan, mrnuraian , st.nama AS mrnstatus, b.bkode , mrnout.namabarang , mrs.mrsnotransaksi , mrnout.jml , mrnout.satuan , mrsout.catatan FROM m6_mrn mrn JOIN m1_production_category pc ON mrn.mrnjenis = pc.pckode JOIN m1_warehouse wp ON mrn.mrngudangproduksi = wp.wkode JOIN m1_warehouse wt ON mrn.mrngudangtujuan = wt.wkode JOIN m0_status st ON mrn.mrnstatus = st.kode JOIN m6_mrn_out mrnout ON mrn.mrnid = mrnout.idmrn JOIN m1_item b ON mrnout.idbarang = b.bid LEFT JOIN m6_mrs_out mrsout ON mrnout.idmrsout = mrsout.idmrsout LEFT JOIN m6_mrs mrs ON mrsout.idmrs = mrs.mrsid ORDER BY mrn.mrntgl , mrn.mrnid, mrn.mrnnotransaksi, mrnout.urutan;

-- RID=1991 | MENU=7 | ITEM=9 | RQUERY=1 | NAME=Daftar Retur Bahan Baku (MRN) | FILE=ListMaterialReturrn2
SELECT mrn.mrnid , mrn.mrnnotransaksi , mrn.mrntgl , pc.pcnama AS mrnjenis , wp.wnama AS mrngudangproduksi, wt.wnama AS mrngudangtujuan, mrnuraian , st.nama AS mrnstatus, b.bkode , mrnout.namabarang , mrs.mrsnotransaksi , mrnout.jml , mrnout.satuan , mrnout.harga , (mrnout.jml * mrnout.harga ) AS total FROM m6_mrn mrn JOIN m1_production_category pc ON mrn.mrnjenis = pc.pckode JOIN m1_warehouse wp ON mrn.mrngudangproduksi = wp.wkode JOIN m1_warehouse wt ON mrn.mrngudangtujuan = wt.wkode JOIN m0_status st ON mrn.mrnstatus = st.kode JOIN m6_mrn_out mrnout ON mrn.mrnid = mrnout.idmrn JOIN m1_item b ON mrnout.idbarang = b.bid LEFT JOIN m6_mrs_out mrsout ON mrnout.idmrsout = mrsout.idmrsout LEFT JOIN m6_mrs mrs ON mrsout.idmrs = mrs.mrsid ORDER BY mrn.mrntgl , mrn.mrnid, mrn.mrnnotransaksi, mrnout.urutan;

-- RID=2026 | MENU=7 | ITEM=10 | RQUERY=1 | NAME=Retur Bahan Baku (MRN) Batch | FILE=MaterialReturrn1_batch
SELECT COUNT(*), mrnout.idbarang, mrn.mrnid , mrn.mrnnotransaksi , mrn.mrntgl , pc.pcnama AS mrnjenis , wp.wnama AS mrngudangproduksi, wt.wnama AS mrngudangtujuan, mrnuraian , st.nama AS mrnstatus, b.bkode , mrnout.namabarang , mrs.mrsnotransaksi , SUM(mrnout.jml) AS jml , mrnout.satuan , mrnout.harga , (SUM(mrnout.jml) * mrnout.harga ) AS total FROM m6_mrn mrn JOIN m1_production_category pc ON mrn.mrnjenis = pc.pckode JOIN m1_warehouse wp ON mrn.mrngudangproduksi = wp.wkode JOIN m1_warehouse wt ON mrn.mrngudangtujuan = wt.wkode JOIN m0_status st ON mrn.mrnstatus = st.kode JOIN m6_mrn_out mrnout ON mrn.mrnid = mrnout.idmrn JOIN m1_item b ON mrnout.idbarang = b.bid LEFT JOIN m6_mrs_out mrsout ON mrnout.idmrsout = mrsout.idmrsout LEFT JOIN m6_mrs mrs ON mrsout.idmrs = mrs.mrsid GROUP BY mrn.mrnid, mrnout.idbarang , mrnout.namabarang , mrnout.satuan , mrnout.harga ORDER BY mrn.mrntgl , mrn.mrnid, mrn.mrnnotransaksi, mrnout.urutan;

-- RID=38 | MENU=8 | ITEM=1 | RQUERY=1 | NAME=Daftar Produksi (PD) | FILE=ListProduction
SELECT pd.pdid , pd.pdnotransaksi , pd.pdtgl, wo.wonotransaksi, pd.pdtgldipakai, pc.pcnama AS pdjenis , pd.pduraian , st.nama AS pdstatus FROM m6_pd pd JOIN m1_production_category pc ON pd.pdjenis = pc.pckode JOIN m0_status st ON pd.pdstatus = st.kode LEFT JOIN m6_wo wo ON pd.pdidwo = wo.woid ORDER BY pd.pdtgl , pd.pdid , pd.pdnotransaksi;

-- RID=253 | MENU=8 | ITEM=2 | RQUERY=1 | NAME=Produksi (PD) | FILE=ProductionDetail1
SELECT pd.pdid , pd.pdnotransaksi , pd.pdtgl, wo.wonotransaksi, pd.pdtgldipakai, pc.pcnama AS pdjenis , pd.pduraian , st.nama AS pdstatus FROM m6_pd pd JOIN m1_production_category pc ON pd.pdjenis = pc.pckode JOIN m0_status st ON pd.pdstatus = st.kode LEFT JOIN m6_wo wo ON pd.pdidwo = wo.woid ORDER BY pd.pdtgl , pd.pdid , pd.pdnotransaksi;

-- RID=512 | MENU=8 | ITEM=3 | RQUERY=1 | NAME=Produksi (PD) | FILE=ProductionDetail2
SELECT pd.pdid , pd.pdnotransaksi , pd.pdtgl, wo.wonotransaksi, pd.pdtgldipakai, pc.pcnama AS pdjenis , pd.pduraian , st.nama AS pdstatus FROM m6_pd pd JOIN m1_production_category pc ON pd.pdjenis = pc.pckode JOIN m0_status st ON pd.pdstatus = st.kode LEFT JOIN m6_wo wo ON pd.pdidwo = wo.woid ORDER BY pd.pdtgl , pd.pdid , pd.pdnotransaksi;

-- RID=491 | MENU=8 | ITEM=4 | RQUERY=1 | NAME=Produksi (PD) Serial  | FILE=ProductionDetail1_serial
SELECT pd.pdid , pd.pdnotransaksi , pd.pdtgl, wo.wonotransaksi, pd.pdtgldipakai, pc.pcnama AS pdjenis , pd.pduraian , st.nama AS pdstatus FROM m6_pd pd JOIN m1_production_category pc ON pd.pdjenis = pc.pckode JOIN m0_status st ON pd.pdstatus = st.kode LEFT JOIN m6_wo wo ON pd.pdidwo = wo.woid ORDER BY pd.pdtgl , pd.pdid , pd.pdnotransaksi;

-- RID=558 | MENU=8 | ITEM=5 | RQUERY=1 | NAME=Produksi (PD) | FILE=ProductionDetail1_UD
SELECT pd.pdid , pd.pdnotransaksi , pd.pdtgl, wo.wonotransaksi, pd.pdtgldipakai, pc.pcnama AS pdjenis , pd.pduraian , st.nama AS pdstatus FROM m6_pd pd JOIN m1_production_category pc ON pd.pdjenis = pc.pckode JOIN m0_status st ON pd.pdstatus = st.kode LEFT JOIN m6_wo wo ON pd.pdidwo = wo.woid ORDER BY pd.pdtgl , pd.pdid , pd.pdnotransaksi;

-- RID=1024 | MENU=8 | ITEM=6 | RQUERY=1 | NAME=Daftar Produksi (PD) Per Produk | FILE=ListProduction_perproduk
SELECT bid, bkode, namabarang, pdnotransaksi, pdtgl ,pdtgldipakai FROM (SELECT b.bid , b.bkode , pdin.namabarang , pd.pdnotransaksi, pd.pdtgl ,pd.pdtgldipakai FROM m6_pd_in pdin JOIN m1_item b ON pdin.idbarang = b.bid JOIN m6_pd pd ON pdin.idpd = pd.pdid UNION SELECT bb.bid , bb.bkode , pdout.namabarang, pd.pdnotransaksi, pd.pdtgl ,pd.pdtgldipakai FROM m6_pd_out pdout JOIN m1_item bb ON pdout.idbarang = bb.bid JOIN m6_pd pd ON pdout.idpd = pd.pdid ) as a GROUP BY bid, bkode, namabarang ORDER BY bid, bkode, namabarang;

-- RID=1609 | MENU=8 | ITEM=7 | RQUERY=1 | NAME=Daftar Produksi (PD) | FILE=ListProduction_2
SELECT pd.pdid , pd.pdnotransaksi , pd.pdtgl, wo.wonotransaksi, pd.pdtgldipakai, pc.pcnama AS pdjenis , pd.pduraian , st.nama AS pdstatus FROM m6_pd pd JOIN m1_production_category pc ON pd.pdjenis = pc.pckode JOIN m0_status st ON pd.pdstatus = st.kode LEFT JOIN m6_wo wo ON pd.pdidwo = wo.woid ORDER BY pd.pdtgl , pd.pdid , pd.pdnotransaksi;

-- RID=1992 | MENU=8 | ITEM=8 | RQUERY=1 | NAME=Daftar Produksi (PD) | FILE=ListProduction2
SELECT pd.pdid , pd.pdnotransaksi , pd.pdtgl, wo.wonotransaksi, pd.pdtgldipakai, pc.pcnama AS pdjenis , pd.pduraian , st.nama AS pdstatus FROM m6_pd pd JOIN m1_production_category pc ON pd.pdjenis = pc.pckode JOIN m0_status st ON pd.pdstatus = st.kode LEFT JOIN m6_wo wo ON pd.pdidwo = wo.woid ORDER BY pd.pdtgl , pd.pdid , pd.pdnotransaksi;

-- RID=1993 | MENU=8 | ITEM=9 | RQUERY=1 | NAME=Produksi (PD) | FILE=ProductionDetail3
SELECT pd.pdid , pd.pdnotransaksi , pd.pdtgl, wo.wonotransaksi, pd.pdtgldipakai, pc.pcnama AS pdjenis , pd.pduraian , st.nama AS pdstatus FROM m6_pd pd JOIN m1_production_category pc ON pd.pdjenis = pc.pckode JOIN m0_status st ON pd.pdstatus = st.kode LEFT JOIN m6_wo wo ON pd.pdidwo = wo.woid ORDER BY pd.pdtgl , pd.pdid , pd.pdnotransaksi;

-- RID=1994 | MENU=8 | ITEM=10 | RQUERY=1 | NAME=Produksi (PD) | FILE=ProductionDetail4
SELECT pd.pdid , pd.pdnotransaksi , pd.pdtgl, wo.wonotransaksi, pd.pdtgldipakai, pc.pcnama AS pdjenis , pd.pduraian , st.nama AS pdstatus FROM m6_pd pd JOIN m1_production_category pc ON pd.pdjenis = pc.pckode JOIN m0_status st ON pd.pdstatus = st.kode LEFT JOIN m6_wo wo ON pd.pdidwo = wo.woid ORDER BY pd.pdtgl , pd.pdid , pd.pdnotransaksi;

-- RID=1880 | MENU=8 | ITEM=11 | RQUERY=1 | NAME=Produksi (PD) | FILE=ProductionDetail5
SELECT pd.pdid , pd.pdnotransaksi , pd.pdtgl, wo.wonotransaksi, pd.pdtgldipakai, pc.pcnama AS pdjenis , pd.pduraian , st.nama AS pdstatus FROM m6_pd pd JOIN m1_production_category pc ON pd.pdjenis = pc.pckode JOIN m0_status st ON pd.pdstatus = st.kode LEFT JOIN m6_wo wo ON pd.pdidwo = wo.woid ORDER BY pd.pdtgl , pd.pdid , pd.pdnotransaksi;

-- RID=1881 | MENU=8 | ITEM=12 | RQUERY=1 | NAME=Produksi (PD) | FILE=ProductionDetail6
SELECT pd.pdid , pd.pdnotransaksi , pd.pdtgl, wo.wonotransaksi, pd.pdtgldipakai, pc.pcnama AS pdjenis , pd.pduraian , st.nama AS pdstatus FROM m6_pd pd JOIN m1_production_category pc ON pd.pdjenis = pc.pckode JOIN m0_status st ON pd.pdstatus = st.kode LEFT JOIN m6_wo wo ON pd.pdidwo = wo.woid ORDER BY pd.pdtgl , pd.pdid , pd.pdnotransaksi;

-- RID=1882 | MENU=8 | ITEM=13 | RQUERY=1 | NAME=Produksi (PD) Batch | FILE=ProductionDetail1_batch
SELECT pd.pdid , pd.pdnotransaksi , pd.pdtgl, wo.wonotransaksi, pd.pdtgldipakai, pc.pcnama AS pdjenis , pd.pduraian , st.nama AS pdstatus FROM m6_pd pd JOIN m1_production_category pc ON pd.pdjenis = pc.pckode JOIN m0_status st ON pd.pdstatus = st.kode LEFT JOIN m6_wo wo ON pd.pdidwo = wo.woid ORDER BY pd.pdtgl , pd.pdid , pd.pdnotransaksi;

-- RID=1883 | MENU=8 | ITEM=14 | RQUERY=1 | NAME=Daftar Produksi | FILE=ListProduction4
SELECT pd.pdid , pd.pdnotransaksi , pd.pdtgl, wo.wonotransaksi, pd.pdtgldipakai, pc.pcnama AS pdjenis , pd.pduraian , st.nama AS pdstatus FROM m6_pd pd JOIN m1_production_category pc ON pd.pdjenis = pc.pckode JOIN m0_status st ON pd.pdstatus = st.kode LEFT JOIN m6_wo wo ON pd.pdidwo = wo.woid ORDER BY pd.pdtgl , pd.pdid , pd.pdnotransaksi;

-- RID=50000567 | MENU=8 | ITEM=15 | RQUERY=1 | NAME=Laporan Jasa Produksi Per Transaksi | FILE=jasa_produksi_pertransaksi
SELECT pd.pdid , pd.pdnotransaksi , pdo.idbarang, b.bkode , b.bnama , pdo.jml, pdo.satuan , pdo.harga , (pdo.jml * pdo.harga) AS total FROM m6_pd pd JOIN m6_pd_out pdo ON pd.pdid = pdo.idpd JOIN m1_item b ON pdo.idbarang = b.bid WHERE b.bjenis = "J" ORDER BY pd.pdtgl ASC , pd.pdnotransaksi ASC , pdo.urutan ASC;

-- RID=50000568 | MENU=8 | ITEM=16 | RQUERY=1 | NAME=Laporan Jasa Produksi Per Tanggal | FILE=jasa_produksi_rekap_pertgl
SELECT pd.pdid , pd.pdnotransaksi , pd.pdtgl , pdo.idbarang, b.bkode , b.bnama , SUM(pdo.jml) AS jml, pdo.satuan , pdo.harga , Sum(pdo.jml * pdo.harga) AS total FROM m6_pd pd JOIN m6_pd_out pdo ON pd.pdid = pdo.idpd JOIN m1_item b ON pdo.idbarang = b.bid WHERE b.bjenis = "J" GROUP BY pdo.idbarang ASC , pd.pdtgl ASC ORDER BY pdo.idbarang ASC , pd.pdtgl ASC;

-- RID=50000577 | MENU=8 | ITEM=17 | RQUERY=1 | NAME=Laporan Hasil Produksi | FILE=hasil_produksi2
SELECT pd.pduraian , pd.pdcatatan , pd.pdid , pdi.urutan , b.bnama AS namabarang , pdi.jmlbarang , pdi.satuanbarang, pd.pdtgl , pdi.hpp , (SELECT SUM(pdo.jmlbarang) AS jmlbarang FROM m6_pd_out pdo JOIN m6_pd pdd ON pdo.idpd = pdd.pdid WHERE pd.pduraian = pdd.pduraian GROUP BY pdd.pduraian ORDER BY pdd.pduraian ASC ) AS a FROM m6_pd pd JOIN m6_pd_in pdi ON pd.pdid = pdi.idpd JOIN m1_item b ON pdi.idbarang = b.bid ORDER BY pd.pdcatatan ASC , pd.pdtgl ASC , pd.pdnotransaksi ASC , pd.pdid ASC , pdi.urutan ASC , pdi.idpdin ASC;

-- RID=50001630 | MENU=8 | ITEM=19 | RQUERY=1 | NAME=Standart dan Realisasi Pemakaian Bahan | FILE=Standart dan Realisasi Pemakaian Bahan
SELECT pd.pdid , pd.pdnotransaksi , pd.pdtgl, pd.pdtgldipakai, pc.pcnama AS pdjenis , pd.pduraian , st.nama AS pdstatus FROM m6_pd pd JOIN m1_production_category pc ON pd.pdjenis = pc.pckode JOIN m0_status st ON pd.pdstatus = st.kode ORDER BY pd.pdtgl , pd.pdid , pd.pdnotransaksi;

-- RID=50001761 | MENU=8 | ITEM=20 | RQUERY=1 | NAME=Laporan Produksi Per Produk | FILE=pd_perbarang_jadi
SELECT b.bkode, b.bnama , pd.pdtgl , pd.pdnotransaksi , pdin.jml , pdin.satuan FROM m6_pd pd JOIN m6_pd_in pdin ON pd.pdid = pdin.idpd JOIN m1_item b ON pdin.idbarang = b.bid WHERE pd.pdstatus IN (2,3,4,7) ORDER BY b.bkode ASC , b.bnama ASC , pd.pdtgl ASC , pd.pdnotransaksi ASC;

-- RID=50003807 | MENU=8 | ITEM=21 | RQUERY=1 | NAME=Production Backorder Report Global | FILE=pd_backorderglobal
SELECT c.kkode, c.knama, so.soid, so.sonotransaksi, so.sotgl, so.sotglkirim, sod.idbarang, sod.jmlbarang, sod.satuan, pdp.mesin, pdp.tgl, MIN(pdp.tgl) as prodstartdate, MAX(pdp.tgl) as prodcompletedate, pdp.customtext10, SUM(CASE WHEN pd.pdcustomtext2 <> 'FG' THEN pdi.jmlbarang ELSE 0 END) as jmlpdwip, SUM(CASE pd.pdcustomtext2 WHEN 'FG' THEN pdi.jmlbarang ELSE 0 END) as jmlpdfg, sod.jmlbarang - SUM(CASE WHEN pd.pdcustomtext2 <> 'FG' THEN pdi.jmlbarang ELSE 0 END) as bowip, sod.jmlbarang - SUM(CASE pd.pdcustomtext2 WHEN 'FG' THEN pdi.jmlbarang ELSE 0 END) as bofg, c.kcatatan, i.bsatuan, i.bkode, i.bnama, i.bkelasproduk, cp.cpnama as bkelasproduknama, IFNULL(dttgl.jmlplan,0) as jmlplan, sod.jmlbarang - IFNULL(dttgl.jmlplan,0) as blmplan FROM m5_so so JOIN m1_contact c ON so.socustomer = c.kid JOIN m1_contact c2 ON so.sobagianpenjualan = c2.kid JOIN m5_so_production sod ON so.soid = sod.idso AND so.sostatus IN(2,3) JOIN m1_item i ON sod.idbarang = i.bid JOIN (SELECT idso, idbarang, SUM(jmlbarang - jmlrealisasi) as sisa FROM m5_so_detail GROUP BY idso, idbarang HAVING sisa > 0) as sodet ON sod.idso = sodet.idso AND sod.idbarang = sodet.idbarang LEFT JOIN m6_production_planning pdp ON so.soid = pdp.idsodetail AND sod.idbarang = pdp.idbarang LEFT JOIN m6_pd pd ON pdp.customtext10 = pd.pdcustomtext1 AND pd.pdstatus IN(2,3,4,7) LEFT JOIN m6_pd_in pdi ON pd.pdid = pdi.idpd LEFT JOIN m5_sf sf on so.socustomdbl1 = sf.sfid LEFT JOIN m1_class_product cp ON i.bkelasproduk = cp.cpkode LEFT JOIN (SELECT idsodetail, idbarang, max(tgl) as maxtgl, min(tgl) as mintgl, SUM(jmlbarang) as jmlplan FROM m6_production_planning GROUP BY idsodetail, idbarang ) as dttgl ON so.soid = dttgl.idsodetail AND sod.idbarang = dttgl.idbarang GROUP BY c.kkode, so.sotgl, so.soid, i.bkode ORDER BY c.kkode, so.sotgl, so.soid, i.bkode;

-- RID=50003808 | MENU=8 | ITEM=22 | RQUERY=1 | NAME=Production Backorder Report Detail | FILE=pd_backorderdetail
SELECT c.kkode, c.knama, c.kcatatan, so.soid, so.sonotransaksi, so.sotgl, so.sotglkirim, sod.idbarang, i.bkode, i.bnama, i.bsatuan, sod.jmlbarang, sod.satuan, pdp.mesin, pdp.tgl, dttgl.mintgl as prodstardate, dttgl.maxtgl as prodcompletedate, pdp.jml, pdp.customtext10 as routecard, SUM(CASE WHEN pd.pdcustomtext2 <> 'FG' THEN pdi.jmlbarang ELSE 0 END) as jmlpdwip, SUM(CASE pd.pdcustomtext2 WHEN 'FG' THEN pdi.jmlbarang ELSE 0 END) as jmlpdfg, pdp.jml - SUM(CASE WHEN pd.pdcustomtext2 <> 'FG' THEN pdi.jmlbarang ELSE 0 END) as bowip, pdp.jml - SUM(CASE pd.pdcustomtext2 WHEN 'FG' THEN pdi.jmlbarang ELSE 0 END) as bofg, IFNULL(dttgl.jmlplan,0) as jmlplan, sod.jmlbarang - IFNULL(dttgl.jmlplan,0) as blmplan FROM m5_so so JOIN m1_contact c ON so.socustomer = c.kid JOIN m5_so_production sod ON so.soid = sod.idso AND so.sostatus IN(2,3) JOIN m1_item i ON sod.idbarang = i.bid JOIN (SELECT idso, idbarang, SUM(jmlbarang - jmlrealisasi) as sisa FROM m5_so_detail GROUP BY idso, idbarang HAVING sisa > 0) as sodet ON sod.idso = sodet.idso AND sod.idbarang = sodet.idbarang LEFT JOIN m6_production_planning pdp ON so.soid = pdp.idsodetail AND sod.idbarang = pdp.idbarang LEFT JOIN m6_pd pd ON pdp.customtext10 = pd.pdcustomtext1 AND pd.pdstatus IN(2,3,4,7) LEFT JOIN m6_pd_in pdi ON pd.pdid = pdi.idpd LEFT JOIN (SELECT idsodetail, idbarang, max(tgl) as maxtgl, min(tgl) as mintgl, SUM(jmlbarang) as jmlplan FROM m6_production_planning GROUP BY idsodetail, idbarang ) as dttgl ON so.soid = dttgl.idsodetail AND sod.idbarang = dttgl.idbarang GROUP BY c.kkode, so.sotgl, so.soid, i.bkode, pdp.idpdpdetail ORDER BY c.kkode, so.sotgl, so.soid, i.bkode, pdp.idpdpdetail;

-- RID=50003809 | MENU=8 | ITEM=23 | RQUERY=1 | NAME=Daily Production Report | FILE=pd_dailyreport
SELECT c.kkode, IFNULL(c.knama, pd.pdcustomtext4) as knama, c.kcatatan, so.soid, IFNULL(so.sonotransaksi,pd.pdnoref) as sonotransaksi, so.sotgl, so.sotglkirim, sod.idbarang, i.bkode as kodebarangSO, i.bnama as namabarangSO, i.bsatuan as satuanbarangSO, sod.jmlbarang as jmlso, sod.satuan as satuanso, pdp.mesin as pdpmesin, pdp.tgl as pdptgl, dttgl.mintgl as pdpstartdate, dttgl.maxtgl as pdpcompletedate, pdp.jml as pdpjml, IFNULL(pdp.customtext10, pd.pdcustomtext1) as pdproutecard, pd.pdtgl AS pdtgl, pd.pdnotransaksi AS pdnotransaksi, pd.pdcustomtext2 AS pdjenis, pd.pdcustomtext1 as pdroutecard, pd.pdcustomtext3 as tungku, ip.bid AS pdidbarang, ip.bkode AS pdkodebarang, ip.bnama AS pdnamabarang, pdi.jmlbarang as pdjml, pdout.jmlbarang as jmlbahan, ROUND(100 - (pdi.jmlbarang / pdout.jmlbarang* 100), 5) AS persentasesusut FROM m6_pd pd JOIN m6_pd_in pdi ON pd.pdid = pdi.idpd AND pd.pdstatus IN(2,3,4,7) JOIN m1_item ip ON pdi.idbarang = ip.bid JOIN m6_pd_out pdout ON pd.pdid = pdout.idpd AND pdout.jmlbarang > 0 JOIN m1_item ib ON pdout.idbarang = ib.bid AND ib.bjenis = 'P' LEFT JOIN m6_production_planning pdp ON pd.pdcustomtext1 = pdp.customtext10 LEFT JOIN m5_so_production sod ON pdp.idsodetail = sod.idso AND pdp.idbarang = sod.idbarang LEFT JOIN m5_so so ON sod.idso = so.soid LEFT JOIN m1_contact c ON so.socustomer = c.kid LEFT JOIN m1_item i ON sod.idbarang = i.bid LEFT JOIN (SELECT idsodetail, idbarang, max(tgl) as maxtgl, min(tgl) as mintgl FROM m6_production_planning GROUP BY idsodetail, idbarang ) as dttgl ON so.soid = dttgl.idsodetail AND sod.idbarang = dttgl.idbarang GROUP BY pd.pdcustomtext3, pd.pdtgl, pd.pdnotransaksi, c.kkode, so.sotgl, i.bkode, pdp.idpdpdetail, pd.pdid, pdi.idpdin ORDER BY pd.pdcustomtext3, pd.pdtgl, pd.pdnotransaksi, c.kkode, so.sotgl, i.bkode, pdp.idpdpdetail, pd.pdid, pdi.idpdin;

-- RID=50003811 | MENU=8 | ITEM=24 | RQUERY=2 | NAME=Laporan Abu | FILE=Laporan_Abu
SELECT * FROM m2r_abunew ORDER BY tanggal DESC;

-- RID=50003820 | MENU=8 | ITEM=25 | RQUERY=2 | NAME=Production Backorder Report Detail | FILE=pd_backorderdetailnew
SELECT bo.idlogin, bo.kkode, bo.knama, bo.kcatatan, bo.soid, bo.sonotransaksi, bo.sotgl, bo.sotglkirim, bo.idbarang, bo.bkode, bo.bnama, bo.bsatuan, bo.jmlbarang, bo.satuan, bo.mesin, bo.tgl, bo.prodstardate, bo.prodcompletedate, bo.jml, bo.routecard, bo.jmlpdwip, bo.jmlpdfg, bo.bowip, bo.bofg, bo.jmlplan, bo.blmplan, bo.idmsmq, bo.userid FROM m2r_bo_production bo ORDER BY bo.kkode, bo.sotgl, bo.soid, bo.bkode, bo.tgl, bo.routecard;

-- RID=50003821 | MENU=8 | ITEM=26 | RQUERY=2 | NAME=Production Backorder Report Global | FILE=pd_backorderglobalnew
SELECT bo.idlogin, bo.kkode, bo.knama, bo.kcatatan, bo.soid, bo.sonotransaksi, bo.sotgl, bo.sotglkirim, bo.idbarang, bo.bkode, bo.bnama, bo.bsatuan, bo.jmlbarang, bo.satuan, bo.mesin, bo.tgl, bo.prodstardate as prodstartdate, bo.prodcompletedate, SUM(bo.jml) as jml, bo.routecard, SUM(bo.jmlpdwip) as jmlpdwip, SUM(bo.jmlpdfg) as jmlpdfg, (bo.bowip) as bowip, (bo.bofg) as bofg, bo.jmlplan, bo.blmplan, bo.idmsmq, bo.userid, i.bkelasproduk FROM m2r_bo_production_global bo JOIN m1_item i ON bo.idbarang = i.bid GROUP BY bo.kkode, bo.sotgl, bo.soid, bo.bkode ORDER BY bo.kkode, bo.sotgl, bo.soid, bo.bkode;

-- RID=50003830 | MENU=8 | ITEM=27 | RQUERY=1 | NAME=Daftar Produksi (PD) | FILE=-
SELECT pd.pdid , pd.pdnotransaksi , pd.pdtgl, wo.wonotransaksi, pd.pdtgldipakai, pc.pcnama AS pdjenis , pd.pduraian , st.nama AS pdstatus, b.bkode as kodehasil, pdin.namabarang as namahasil, pdin.jmlbarang as jmlhasil, pdin.satuanbarang as satuanhasil, pdin.customdbl1 as jmlbatang, pdin.hpppersen, pdin.hpp as hargahasil, (pdin.jmlbarang * pdin.hpp) as totalhasil, b2.bkode as kodebahan, pdout.namabarang as namabahan, pdout.jmlbarang as jmlbahan, pdout.satuanbarang as satuanbahan, pdout.hpp as hargabahan, (pdout.jmlbarang * pdout.hpp) as totalbahan FROM m6_pd pd JOIN m1_production_category pc ON pd.pdjenis = pc.pckode JOIN m0_status st ON pd.pdstatus = st.kode JOIN m6_pd_in pdin ON pd.pdid = pdin.idpd JOIN m1_item b ON pdin.idbarang = b.bid JOIN m6_pd_out pdout ON pd.pdid = pdout.idpd JOIN m1_item b2 ON pdout.idbarang = b2.bid LEFT JOIN m6_wo wo ON pd.pdidwo = wo.woid ORDER BY pd.pdtgl , pd.pdid , pd.pdnotransaksi, pdin.urutan, pdin.idpdin, pdout.urutan, pdout.idpdout;

-- RID=1604 | MENU=25 | ITEM=1 | RQUERY=2 | NAME=Stok Cover Day | FILE=StokCoverDay_2
SELECT * FROM m2r_stok_coverday ORDER BY scidbarang;

-- RID=1611 | MENU=25 | ITEM=2 | RQUERY=2 | NAME=Stok Cover Day | FILE=StokCoverDay_2
SELECT * FROM m2r_stok_coverday ORDER BY scidbarang;

-- RID=1668 | MENU=26 | ITEM=1 | RQUERY=1 | NAME=Laporan Produksi Dan Penjualan Dalam Berat Ton | FILE=produksidanpenjualan_dlmton
SELECT it.tgl , it.idbarang , b.bkode , b.bnama, CASE it.sumber WHEN "PD" THEN "Produksi" WHEN "SI" THEN "Penjualan" END AS sumber , it.jenismutasi , IFNULL(SUM(it.jmlbarang * b.baberat) / 1000,0) as jmlbarang , YEAR(it.tgl) as tahun , MONTH(it.tgl) as bulan FROM m1_item_transaction it JOIN m1_item b ON it.idbarang = b.bid WHERE ((it.sumber = "PD" AND it.jenismutasi = 1) OR (it.sumber = "SI" AND it.jenismutasi = 0 )) GROUP BY it.idbarang ASC, it.sumber ASC, MONTH(it.tgl) ASC ORDER BY it.idbarang ASC, it.sumber ASC, MONTH(it.tgl) ASC;

-- RID=2001 | MENU=26 | ITEM=2 | RQUERY=2 | NAME=Laporan Produksi VS Penjualan VS Stok | FILE=produksivspenjualanvsstok
SELECT pvp.idlogin, pvp.pvptahun, pvp.pvpidbarang, CONCAT(i.bnamaalias1, '') as pvpkodebarang, pvp.pvpurutan, pvp.pvpketerangan, (CASE WHEN pvp.pvptahun < YEAR(NOW()) THEN pvp.pvpjan WHEN pvp.pvptahun = YEAR(NOW()) AND 1 <= MONTH(NOW()) THEN pvp.pvpjan ELSE 0 END) as pvpjan, (CASE WHEN pvp.pvptahun < YEAR(NOW()) THEN pvp.pvpfeb WHEN pvp.pvptahun = YEAR(NOW()) AND 2 <= MONTH(NOW()) THEN pvp.pvpfeb ELSE 0 END) as pvpfeb, (CASE WHEN pvp.pvptahun < YEAR(NOW()) THEN pvp.pvpmar WHEN pvp.pvptahun = YEAR(NOW()) AND 3 <= MONTH(NOW()) THEN pvp.pvpmar ELSE 0 END) as pvpmar, (CASE WHEN pvp.pvptahun < YEAR(NOW()) THEN pvp.pvpapr WHEN pvp.pvptahun = YEAR(NOW()) AND 4 <= MONTH(NOW()) THEN pvp.pvpapr ELSE 0 END) as pvpapr, (CASE WHEN pvp.pvptahun < YEAR(NOW()) THEN pvp.pvpmei WHEN pvp.pvptahun = YEAR(NOW()) AND 5 <= MONTH(NOW()) THEN pvp.pvpmei ELSE 0 END) as pvpmei, (CASE WHEN pvp.pvptahun < YEAR(NOW()) THEN pvp.pvpjun WHEN pvp.pvptahun = YEAR(NOW()) AND 6 <= MONTH(NOW()) THEN pvp.pvpjun ELSE 0 END) as pvpjun, (CASE WHEN pvp.pvptahun < YEAR(NOW()) THEN pvp.pvpjul WHEN pvp.pvptahun = YEAR(NOW()) AND 7 <= MONTH(NOW()) THEN pvp.pvpjul ELSE 0 END) as pvpjul, (CASE WHEN pvp.pvptahun < YEAR(NOW()) THEN pvp.pvpagu WHEN pvp.pvptahun = YEAR(NOW()) AND 8 <= MONTH(NOW()) THEN pvp.pvpagu ELSE 0 END) as pvpagu, (CASE WHEN pvp.pvptahun < YEAR(NOW()) THEN pvp.pvpsep WHEN pvp.pvptahun = YEAR(NOW()) AND 9 <= MONTH(NOW()) THEN pvp.pvpsep ELSE 0 END) as pvpsep, (CASE WHEN pvp.pvptahun < YEAR(NOW()) THEN pvp.pvpokt WHEN pvp.pvptahun = YEAR(NOW()) AND 10 <= MONTH(NOW()) THEN pvp.pvpokt ELSE 0 END) as pvpokt, (CASE WHEN pvp.pvptahun < YEAR(NOW()) THEN pvp.pvpnov WHEN pvp.pvptahun = YEAR(NOW()) AND 11 <= MONTH(NOW()) THEN pvp.pvpnov ELSE 0 END) as pvpnov, (CASE WHEN pvp.pvptahun < YEAR(NOW()) THEN pvp.pvpdes WHEN pvp.pvptahun = YEAR(NOW()) AND 12 <= MONTH(NOW()) THEN pvp.pvpdes ELSE 0 END) as pvpdes, pvp.idmsmq, pvp.pvpuserid FROM M2r_Produksi_Vs_Penjualan pvp JOIN m1_item i ON pvp.pvpidbarang = i.bid ORDER BY pvp.pvpkodebarang, pvp.pvpurutan;

-- RID=50003799 | MENU=90 | ITEM=1 | RQUERY=1 | NAME=Machine Plotting | FILE=MachinePlotting
SELECT mp.mesin, m.mnama, mp.tgl, mp.kelas, c.cnama, mp.subkelas, sc.scnama, sc.sccatatan FROM m6_machine_plotting mp JOIN m1_machine m ON mp.mesin = m.mkode JOIN m1_class c ON mp.kelas = c.ckode JOIN m1_subclass sc ON mp.subkelas = sc.sckode ORDER BY mp.mesin, mp.tgl, mp.kelas, mp.subkelas;

-- RID=50003797 | MENU=91 | ITEM=1 | RQUERY=1 | NAME=Daily Production Plan and Realization Per Machine | FILE=pdp_machine
SELECT pp.mesin, m.mnama AS mesinnama, pp.tgl, pp.kelas, cl.cnama AS kelasnama, pp.subkelas, sc.scnama AS subkelasnama, pp.customtext10 AS norc, so.sonotransaksi, so.sotgl, so.sotglkirim, so.socustomer, c.kkode AS socustomerkode, c.knama AS socustomernama, i.bkode, i.bnama, pp.jml, CEIL(pp.jml/i.bjmllapangan) as jmlpcs, pp.satuan, pp.jmljam, i.baoem AS kadar, i.baukuran AS ukuran, i.bapanjang AS panjang, IFNULL(pd.jmlbarang,0) as jmlbr1, IFNULL(pd.customdbl1,0) as jmlpcsbr1, IFNULL(fg.jmlbarang,0) + IFNULL(fs.jmlbarang,0) as jmlfg, IFNULL(fg.customdbl1,0) + IFNULL(fs.customdbl1,0) as jmlpcsfg, 0 as jmlfs, 0 as jmlpcsfs FROM m6_production_planning pp JOIN m1_machine m ON pp.mesin = m.mkode JOIN m1_class cl ON pp.kelas = cl.ckode JOIN m1_subclass sc ON pp.subkelas = sc.sckode JOIN m1_item i ON pp.idbarang = i.bid LEFT JOIN m5_so so ON pp.idsodetail = so.soid LEFT JOIN m1_contact c ON so.socustomer = c.kid LEFT JOIN (SELECT pd.pdcustomtext1, pdi.jmlbarang, pdi.customdbl1 FROM m6_pd pd JOIN m6_pd_in pdi ON pd.pdid = pdi.idpd AND pd.pdstatus IN(2,3,4,7) AND pd.pdcustomtext2 = 'WIP1' ) as pd ON pp.customtext10 = pd.pdcustomtext1 LEFT JOIN (SELECT pd.pdcustomtext1, pdi.jmlbarang, pdi.customdbl1 FROM m6_pd pd JOIN m6_pd_in pdi ON pd.pdid = pdi.idpd AND pd.pdstatus IN(2,3,4,7) AND pd.pdcustomtext2 = 'FG' ) as fg ON pp.customtext10 = fg.pdcustomtext1 LEFT JOIN (SELECT pd.pdcustomtext1, pdi.jmlbarang, pdi.customdbl1 FROM m6_pd pd JOIN m6_pd_in pdi ON pd.pdid = pdi.idpd AND pd.pdstatus IN(2,3,4,7) AND pd.pdcustomtext2 = 'FS' ) as fs ON pp.customtext10 = fs.pdcustomtext1 GROUP BY pp.mesin, pp.tgl, pp.urutan, pp.kelas, pp.subkelas, so.sonotransaksi, i.bkode, pp.idplan ORDER BY pp.mesin, pp.tgl, pp.urutan, pp.kelas, pp.subkelas, so.sonotransaksi, i.bkode;

-- RID=50003798 | MENU=91 | ITEM=2 | RQUERY=1 | NAME=Route Card | FILE=pdp_routecard
SELECT pp.mesin, m.mnama AS mesinnama, pp.tgl, pp.kelas, cl.cnama AS kelasnama, pp.subkelas, sc.scnama AS subkelasnama, pp.customtext10 AS norc, so.sonotransaksi, so.sotgl, so.sotglkirim, so.socustomer, c.kkode AS socustomerkode, c.knama AS socustomernama, i.bkode, i.bnama, pp.jml, CEIL(pp.jml/i.bjmllapangan) as jmlpcs, pp.satuan, pp.jmljam, i.baoem AS kadar, i.baukuran AS ukuran, i.bapanjang AS panjang, i.bamodel as model, i.bavolume as volume, i.bnamaalias5 FROM m6_production_planning pp JOIN m1_machine m ON pp.mesin = m.mkode JOIN m1_class cl ON pp.kelas = cl.ckode JOIN m1_subclass sc ON pp.subkelas = sc.sckode JOIN m1_item i ON pp.idbarang = i.bid LEFT JOIN m5_so so ON pp.idsodetail = so.soid LEFT JOIN m1_contact c ON so.socustomer = c.kid ORDER BY pp.mesin, pp.tgl, pp.urutan, pp.kelas, pp.subkelas, so.sonotransaksi, i.bkode;

-- RID=50003818 | MENU=91 | ITEM=3 | RQUERY=1 | NAME=Route Card | FILE=pdp_routecard_BW1
SELECT pp.mesin, m.mnama AS mesinnama, pp.tgl, pp.kelas, cl.cnama AS kelasnama, pp.subkelas, sc.scnama AS subkelasnama, pp.customtext10 AS norc, so.sonotransaksi, so.sotgl, so.sotglkirim, so.socustomer, c.kkode AS socustomerkode, c.knama AS socustomernama, i.bkode, i.bnama, pp.jml, CEIL(pp.jml/i.bjmllapangan) as jmlpcs, pp.satuan, pp.jmljam, i.baoem AS kadar, i.baukuran AS ukuran, i.bapanjang AS panjang, i.bamodel as model, i.bavolume as volume FROM m6_production_planning pp JOIN m1_machine m ON pp.mesin = m.mkode JOIN m1_class cl ON pp.kelas = cl.ckode JOIN m1_subclass sc ON pp.subkelas = sc.sckode JOIN m1_item i ON pp.idbarang = i.bid LEFT JOIN m5_so so ON pp.idsodetail = so.soid LEFT JOIN m1_contact c ON so.socustomer = c.kid ORDER BY pp.mesin, pp.tgl, pp.urutan, pp.kelas, pp.subkelas, so.sonotransaksi, i.bkode;

-- RID=50003819 | MENU=91 | ITEM=4 | RQUERY=1 | NAME=Route Card | FILE=pdp_routecard_BW2
SELECT pp.mesin, m.mnama AS mesinnama, pp.tgl, pp.kelas, cl.cnama AS kelasnama, pp.subkelas, sc.scnama AS subkelasnama, pp.customtext10 AS norc, so.sonotransaksi, so.sotgl, so.sotglkirim, so.socustomer, c.kkode AS socustomerkode, c.knama AS socustomernama, i.bkode, i.bnama, pp.jml, CEIL(pp.jml/i.bjmllapangan) as jmlpcs, pp.satuan, pp.jmljam, i.baoem AS kadar, i.baukuran AS ukuran, i.bapanjang AS panjang, i.bamodel as model, i.bavolume as volume FROM m6_production_planning pp JOIN m1_machine m ON pp.mesin = m.mkode JOIN m1_class cl ON pp.kelas = cl.ckode JOIN m1_subclass sc ON pp.subkelas = sc.sckode JOIN m1_item i ON pp.idbarang = i.bid LEFT JOIN m5_so so ON pp.idsodetail = so.soid LEFT JOIN m1_contact c ON so.socustomer = c.kid ORDER BY pp.mesin, pp.tgl, pp.urutan, pp.kelas, pp.subkelas, so.sonotransaksi, i.bkode;

