import type { Entity } from './types';
import { FIELD_PERAN, FILTER_KATEGORI_ORANG, daftarkanPeran, selaraskanPeran } from './peran-orang';
import { FIELD_ORANG_DASAR } from './orang-fields';
import { ENTITAS_PERSONA } from './persona';
import { FILTER_JK_SANTRI, FILTER_LENGKAP_SANTRI } from './santri-filter';

const text = (name: string, label: string, required = true) => ({ name, label, type: 'text' as const, required });
const number = (name: string, label: string, required = false) => ({ name, label, type: 'number' as const, required, step: 1 });
const date = (name: string, label: string, required = true) => ({ name, label, type: 'date' as const, required });
const columns = (...items: Array<[string, string]>) => items.map(([name, label]) => ({ name, label }));

export const ENTITIES: Entity[] = [
  {
    key: 'orang',
    menu: 'induk',
    model: 'orang',
    label: 'Identitas orang',
    // Satu identitas dipakai ulang oleh modul lain; jelaskan agar operator tidak
    // membuat baris ganda untuk orang yang sama.
    formLebar: true,
    idType: 'bigint',
    fields: [
      ...FIELD_ORANG_DASAR,
      ...FIELD_PERAN,
      FILTER_KATEGORI_ORANG,
    ],
    columns: columns(['nama', 'Nama'], ['jk', 'JK'], ['hp', 'HP'], ['email', 'Email'], ['aktif', 'Aktif']),
    orderBy: { nama: 'asc' },
    sesudahBuat: daftarkanPeran,
    sesudahUbah: selaraskanPeran,
  },
  {
    key: 'santri',
    menu: 'induk',
    model: 'santri',
    label: 'Santri (detail akademik)',
    deskripsi: 'Data akademik per santri: unit, kelas, kamar, program, tahun masuk. Untuk menambah santri baru beserta identitas dan walinya, pakai pintasan persona "Santri".',
    idType: 'bigint',
    // Nama hidup di tabel `orang`, jadi tanpa ini kotak Cari tak pernah
    // menemukan siapa pun kecuali yang hafal NIS.
    cariPath: ['orang.nama'],
    include: { orang: true },
    fields: [
      { ...number('orangId', 'ID Orang (buat dulu di menu Identitas Orang)', true), hanyaBaru: true },
      text('nis', 'NIS', false),
      text('nisn', 'NISN', false),
      { ...number('unitId', 'Unit'), ref: { model: 'unit', label: 'nama', orderBy: { nama: 'asc' } } },
      { ...number('kelasId', 'Kelas'), ref: { model: 'kelas', label: 'nama', orderBy: { nama: 'asc' } } },
      { ...number('kamarId', 'Kamar'), ref: { model: 'kamar', label: 'kode', labelTambahan: 'asrama.nama', include: { asrama: true }, orderBy: { kode: 'asc' } } },
      { name: 'status', label: 'Status', type: 'select', options: ['Mukim', 'Alumni', 'Keluar'], required: true, filterDefault: 'Mukim' },
      text('program', 'Program', false),
      text('tahunMasuk', 'Tahun masuk', false),
      FILTER_JK_SANTRI,
      FILTER_LENGKAP_SANTRI,
    ],
    columns: [
      { name: 'orang.nama', label: 'Nama', subName: 'nis' },
      { name: 'orang.jk', label: 'JK' },
      ...columns(['unitId', 'Unit'], ['kelasId', 'Kelas'], ['kamarId', 'Kamar']),
      { name: 'status', label: 'Status', badge: { Mukim: 'hijau', Alumni: 'netral', Keluar: 'merah' } },
      { name: 'tahunMasuk', label: 'Tahun masuk' },
    ],
    orderBy: { createdAt: 'desc' },
  },
  {
    key: 'unit',
    menu: 'pengaturan',
    model: 'unit',
    label: 'Unit pendidikan',
    deskripsi: 'Identitas tiap unit di bawah yayasan (SMP, MA, Pondok, Poskestren): nama resmi, logo, kepala unit, kontak, serta visi & misi. Dipakai halaman Pengaturan → Unit.',
    formLebar: true,
    idType: 'int',
    fields: [
      text('key', 'Kode'),
      text('nama', 'Nama pendek'),
      { ...text('namaResmi', 'Nama resmi', false), span: 2, placeholder: 'SMP Nurul Huda Mergosono', hint: 'Dipakai untuk kop surat & halaman publik.' },
      text('jenjang', 'Jenjang', false),
      text('npsn', 'NPSN / NSM', false),
      text('akreditasi', 'Akreditasi', false),
      number('tahunBerdiri', 'Tahun berdiri', false),
      { ...text('deskripsi', 'Deskripsi singkat', false), span: 2 },
      { ...text('logoPath', 'Logo', false), span: 2, placeholder: '/assets/logo-nuha.webp', hint: 'Path berkas di folder public/, bukan unggahan.' },
      { name: 'aktif', label: 'Aktif', type: 'boolean', labelYa: 'Aktif' },
      { ...text('kepalaNama', 'Nama kepala unit', false), group: 'Pimpinan', hint: 'Dipakai bila kepala belum terdaftar sebagai pegawai.' },
      { ...text('kepalaJabatan', 'Sebutan jabatan', false), group: 'Pimpinan', placeholder: 'Kepala Sekolah / Kepala Madrasah / Pengasuh' },
      { ...number('kepalaPegawaiId', 'Kepala (dari pegawai)', false), group: 'Pimpinan', hint: 'Bila diisi, nama ini yang dipakai dan menggantikan teks di atas.', ref: { model: 'pegawai', label: 'orang.nama', include: { orang: true }, orderBy: { nip: 'asc' }, idType: 'bigint' } },
      { ...text('alamat', 'Jalan / alamat detail', false), group: 'Kontak', span: 3 },
      { name: 'desaId', label: 'Desa / kelurahan', type: 'wilayah', group: 'Kontak', span: 3, hint: 'Pilih desa atau kelurahan aktif untuk lokasi unit.' },
      { name: 'latitude', label: 'Latitude', type: 'number', step: 0.0000001, group: 'Kontak', placeholder: '-7.9839080' },
      { name: 'longitude', label: 'Longitude', type: 'number', step: 0.0000001, group: 'Kontak', placeholder: '112.6213910' },
      { ...text('telepon', 'Telepon', false), group: 'Kontak' },
      { ...text('email', 'Email', false), group: 'Kontak' },
      { ...text('website', 'Website', false), group: 'Kontak' },
      { name: 'visi', label: 'Visi', type: 'textarea', required: false, group: 'Visi & misi', span: 3 },
      { name: 'misi', label: 'Misi', type: 'textarea', required: false, group: 'Visi & misi', span: 3 },
    ],
    columns: columns(['key', 'Kode'], ['namaResmi', 'Nama resmi'], ['kepalaNama', 'Kepala unit'], ['npsn', 'NPSN / NSM'], ['aktif', 'Aktif']),
    orderBy: { nama: 'asc' },
  },
  {
    key: 'profil-lembaga',
    menu: 'pengaturan',
    model: 'profilLembaga',
    label: 'Profil yayasan',
    deskripsi: 'Identitas yayasan induk: ketua yayasan, pengasuh, akta, rekening resmi, dan kontak. Cukup satu baris (kode "yayasan").',
    formLebar: true,
    idType: 'int',
    fields: [
      { ...text('key', 'Kode'), hint: 'Gunakan "yayasan" — dibaca halaman Pengaturan → Unit.' },
      { ...text('nama', 'Nama yayasan'), span: 2 },
      text('namaArab', 'Nama Arab', false),
      text('singkatan', 'Singkatan', false),
      number('tahunBerdiri', 'Tahun berdiri', false),
      { ...text('logoPath', 'Logo', false), span: 2, placeholder: '/assets/logo-nuha.webp', hint: 'Path berkas di folder public/, bukan unggahan.' },
      text('aktaNotaris', 'Akta notaris', false),
      { ...text('ketuaNama', 'Ketua yayasan', false), group: 'Pimpinan' },
      { ...text('pengasuhNama', 'Pengasuh', false), group: 'Pimpinan' },
      { ...text('alamat', 'Jalan / alamat detail', false), group: 'Kontak', span: 3 },
      { name: 'desaId', label: 'Desa / kelurahan', type: 'wilayah', group: 'Kontak', span: 3, hint: 'Pilih desa atau kelurahan aktif untuk lokasi yayasan.' },
      { name: 'latitude', label: 'Latitude', type: 'number', step: 0.0000001, group: 'Kontak', placeholder: '-7.9839080' },
      { name: 'longitude', label: 'Longitude', type: 'number', step: 0.0000001, group: 'Kontak', placeholder: '112.6213910' },
      { ...text('telepon', 'Telepon', false), group: 'Kontak' },
      { ...text('email', 'Email', false), group: 'Kontak' },
      { ...text('website', 'Website', false), group: 'Kontak' },
      { ...text('rekening', 'Rekening resmi', false), group: 'Kontak', span: 3, placeholder: 'BSI 7011-2345-6789 a.n. PPSS Nurul Huda Mergosono' },
      { name: 'visi', label: 'Visi', type: 'textarea', required: false, group: 'Visi & misi', span: 3 },
      { name: 'misi', label: 'Misi', type: 'textarea', required: false, group: 'Visi & misi', span: 3 },
    ],
    columns: columns(['nama', 'Nama'], ['ketuaNama', 'Ketua yayasan'], ['pengasuhNama', 'Pengasuh'], ['tahunBerdiri', 'Berdiri']),
    orderBy: { nama: 'asc' },
  },
  { key: 'asrama', menu: 'pesantren', model: 'asrama', label: 'Asrama', idType: 'int', fields: [text('nama', 'Nama'), { name: 'jk', label: 'Jenis kelamin', type: 'select', options: ['L', 'P'], required: true }, number('kapasitas', 'Kapasitas'), text('musyrif', 'Musyrif', false)], columns: columns(['nama', 'Nama'], ['jk', 'JK'], ['kapasitas', 'Kapasitas'], ['musyrif', 'Musyrif']), orderBy: { nama: 'asc' } },
  { key: 'halaqah', menu: 'pesantren', model: 'halaqah', label: 'Halaqah', idType: 'int', fields: [text('nama', 'Nama'), text('ustadz', 'Ustadz'), text('waktu', 'Waktu'), text('tempat', 'Tempat'), text('jenjang', 'Jenjang'), number('anggota', 'Anggota')], columns: columns(['nama', 'Nama'], ['ustadz', 'Ustadz'], ['waktu', 'Waktu'], ['tempat', 'Tempat'], ['anggota', 'Anggota']), orderBy: { nama: 'asc' } },
  { key: 'kegiatan', menu: 'pesantren', model: 'kegiatanHarian', label: 'Kegiatan harian', idType: 'int', fields: [text('jam', 'Jam'), text('nama', 'Nama'), text('ket', 'Keterangan', false), number('urutan', 'Urutan')], columns: columns(['jam', 'Jam'], ['nama', 'Nama'], ['ket', 'Keterangan'], ['urutan', 'Urutan']), orderBy: { urutan: 'asc' } },
  { key: 'mapel', menu: 'akademik', model: 'mataPelajaran', label: 'Mata pelajaran', idType: 'int', fields: [text('kode', 'Kode'), text('nama', 'Nama'), number('jp', 'Jam pelajaran'), text('kelompok', 'Kelompok'), text('guru', 'Guru', false), number('kkm', 'KKM'), text('kurikulum', 'Kurikulum', false)], columns: columns(['kode', 'Kode'], ['nama', 'Nama'], ['kelompok', 'Kelompok'], ['guru', 'Guru'], ['kkm', 'KKM']), orderBy: { nama: 'asc' } },
  { key: 'perangkat', menu: 'kurikulum', model: 'perangkatAjar', label: 'Perangkat ajar', idType: 'int', fields: [text('kode', 'Kode'), text('mapel', 'Mapel'), text('kelas', 'Kelas'), text('jenis', 'Jenis'), text('topik', 'Topik'), number('pertemuan', 'Pertemuan'), text('guru', 'Guru'), text('status', 'Status')], columns: columns(['kode', 'Kode'], ['mapel', 'Mapel'], ['kelas', 'Kelas'], ['jenis', 'Jenis'], ['status', 'Status']), orderBy: { kode: 'asc' } },
  { key: 'bank-soal', menu: 'kurikulum', model: 'bankSoal', label: 'Bank soal', idType: 'int', fields: [text('kode', 'Kode'), text('mapel', 'Mapel'), text('topik', 'Topik'), text('tipe', 'Tipe'), text('level', 'Level'), number('butir', 'Butir'), number('dipakai', 'Dipakai'), text('penulis', 'Penulis')], columns: columns(['kode', 'Kode'], ['mapel', 'Mapel'], ['topik', 'Topik'], ['tipe', 'Tipe'], ['butir', 'Butir']), orderBy: { kode: 'asc' } },
  { key: 'obat', menu: 'poskestren', model: 'obat', label: 'Obat', idType: 'int', fields: [text('nama', 'Nama'), text('satuan', 'Satuan'), text('kategori', 'Kategori', false), number('stok', 'Stok'), number('stokMin', 'Stok minimum'), text('kadaluarsa', 'Kadaluarsa', false)], columns: columns(['nama', 'Nama'], ['satuan', 'Satuan'], ['kategori', 'Kategori'], ['stok', 'Stok'], ['stokMin', 'Min. stok']), orderBy: { nama: 'asc' } },
  {
    key: 'profil-kesehatan',
    menu: 'poskestren',
    model: 'profilKesehatan',
    label: 'Profil kesehatan santri',
    // Master data sekali-isi per santri; berbeda dari Rekam medis yang dicatat
    // per kunjungan poskestren.
    deskripsi: 'Data kesehatan dasar tiap santri: berat & tinggi badan, golongan darah, riwayat penyakit, alergi, dan kebutuhan khusus. Satu baris per santri — pemeriksaan harian dicatat di Rekam medis, bukan di sini.',
    idType: 'bigint',
    fields: [
      {
        ...number('santriId', 'Santri', true),
        group: 'Santri',
        span: 3,
        ref: { model: 'santri', label: 'orang.nama', include: { orang: true }, orderBy: { nis: 'asc' }, idType: 'bigint' },
        hint: 'Satu santri hanya boleh punya satu profil kesehatan.',
      },
      { name: 'beratKg', label: 'Berat badan (kg)', type: 'number', step: 0.1, group: 'Antropometri', placeholder: '42.5' },
      { name: 'tinggiCm', label: 'Tinggi badan (cm)', type: 'number', step: 0.1, group: 'Antropometri', placeholder: '155' },
      { name: 'golDarah', label: 'Golongan darah', type: 'select', options: ['A', 'B', 'AB', 'O'], group: 'Antropometri' },
      { ...text('riwayatPenyakit', 'Penyakit yang pernah diderita', false), group: 'Riwayat', span: 3, placeholder: 'Asma, tifus (2024)', hint: 'Pisahkan dengan koma bila lebih dari satu.' },
      { ...text('alergi', 'Alergi', false), group: 'Riwayat', span: 3, placeholder: 'Udang, debu, antibiotik golongan penisilin' },
      { ...text('kebutuhanKhusus', 'Kebutuhan khusus', false), group: 'Riwayat', span: 3, placeholder: 'Kacamata minus, diet rendah gula' },
      { name: 'catatan', label: 'Catatan tambahan', type: 'textarea', group: 'Riwayat', span: 3, placeholder: 'Kontrol rutin tiap 3 bulan di RS Saiful Anwar.' },
    ],
    columns: columns(['santriId', 'Santri'], ['beratKg', 'BB (kg)'], ['tinggiCm', 'TB (cm)'], ['golDarah', 'Gol. darah'], ['riwayatPenyakit', 'Riwayat penyakit'], ['kebutuhanKhusus', 'Kebutuhan khusus']),
    orderBy: { santriId: 'asc' },
  },
  { key: 'kas', menu: 'keuangan', model: 'transaksiKas', label: 'Transaksi kas', idType: 'bigint', fields: [text('kode', 'Kode'), date('tgl', 'Tanggal'), text('uraian', 'Uraian'), text('kategori', 'Kategori'), text('metode', 'Metode'), { name: 'arah', label: 'Arah', type: 'select', options: ['Masuk', 'Keluar'], required: true }, number('nominal', 'Nominal', true)], columns: columns(['kode', 'Kode'], ['tgl', 'Tanggal'], ['uraian', 'Uraian'], ['arah', 'Arah'], ['nominal', 'Nominal']), orderBy: { tgl: 'desc' } },
  { key: 'pendaftar', menu: 'ppdb', model: 'applicant', label: 'Pendaftar PPDB', idType: 'bigint', fields: [text('registrationNumber', 'No. registrasi'), text('fullName', 'Nama'), text('choice', 'Pilihan'), text('previousSchool', 'Asal sekolah', false), text('guardianPhone', 'HP wali', false), date('registeredAt', 'Tanggal daftar'), number('score', 'Nilai', false), { name: 'status', label: 'Status', type: 'select', options: ['New', 'Verification', 'Selection', 'Passed', 'Failed', 'Reenrollment'], required: true }], columns: columns(['registrationNumber', 'No. Reg'], ['fullName', 'Nama'], ['choice', 'Pilihan'], ['previousSchool', 'Asal sekolah'], ['status', 'Status']), orderBy: { createdAt: 'desc' } },
  { key: 'template-wa', menu: 'wa', model: 'waTemplate', label: 'Template WhatsApp', idType: 'int', fields: [text('code', 'Kode'), text('role', 'Penerima'), text('title', 'Judul'), text('trigger', 'Pemicu'), text('schedule', 'Waktu', false), { name: 'content', label: 'Isi pesan', type: 'textarea', required: true }, { name: 'isActive', label: 'Aktif', type: 'boolean' }], columns: columns(['code', 'Kode'], ['role', 'Penerima'], ['title', 'Judul'], ['trigger', 'Pemicu'], ['isActive', 'Aktif']), orderBy: { code: 'asc' } },
  { key: 'pengumuman', menu: 'dashboard', model: 'announcement', label: 'Pengumuman', idType: 'bigint', fields: [date('date', 'Tanggal'), text('title', 'Judul'), { name: 'content', label: 'Isi', type: 'textarea', required: true }, text('target', 'Target')], columns: columns(['date', 'Tanggal'], ['title', 'Judul'], ['target', 'Target']), orderBy: { date: 'desc' } },
  { key: 'agenda', menu: 'dashboard', model: 'agenda', label: 'Agenda', idType: 'bigint', fields: [date('date', 'Tanggal'), text('time', 'Jam', false), text('title', 'Judul'), text('unit', 'Unit', false)], columns: columns(['date', 'Tanggal'], ['time', 'Jam'], ['title', 'Judul'], ['unit', 'Unit']), orderBy: { date: 'desc' } },
  { key: 'pegawai', menu: 'kepegawaian', model: 'pegawai', label: 'Kepegawaian (detail)', deskripsi: 'Data kepegawaian per orang: unit, rekening, mapel diampu, jam mengajar. Untuk menambah guru atau staf baru beserta identitasnya, pakai pintasan persona "Guru" / "Staf".', idType: 'bigint', fields: [number('orangId', 'ID Orang (buat dulu di menu Identitas Orang)', true), text('nip', 'NIP'), { ...number('unitId', 'Unit', false), ref: { model: 'unit', label: 'nama', orderBy: { nama: 'asc' } } }, text('jabatan', 'Jabatan'), text('status', 'Status'), text('rekening', 'Rekening', false), text('pendidikanTerakhir', 'Pendidikan terakhir', false), text('mapelDiampu', 'Mapel diampu', false), text('tugasTambahan', 'Tugas tambahan', false), number('jamMengajar', 'Jam mengajar', false), text('tmpTglLahir', 'Tempat/tgl lahir', false)], columns: columns(['nip', 'NIP'], ['jabatan', 'Jabatan'], ['status', 'Status'], ['mapelDiampu', 'Mapel diampu'], ['jamMengajar', 'Jam mengajar']), orderBy: { nip: 'asc' } },
  { key: 'tahun-ajaran', menu: 'pengaturan', model: 'academicYear', label: 'Tahun pelajaran', idType: 'int', fields: [text('code', 'Kode (mis. 2026/2027)'), text('semester', 'Semester (Gasal/Genap)'), { name: 'isActive', label: 'Aktif', type: 'boolean' }], columns: columns(['code', 'Kode'], ['semester', 'Semester'], ['isActive', 'Aktif']), orderBy: { code: 'desc' } },
  { key: 'kelas', menu: 'kurikulum', model: 'kelas', label: 'Kelas', idType: 'int', fields: [{ ...number('unitId', 'Unit', true), ref: { model: 'unit', label: 'nama', orderBy: { nama: 'asc' } } }, text('nama', 'Nama kelas'), text('tingkat', 'Tingkat'), { ...number('waliKelasId', 'Wali kelas', false), ref: { model: 'pegawai', label: 'orang.nama', include: { orang: true }, orderBy: { nip: 'asc' }, idType: 'bigint' } }, { ...number('academicYearId', 'Tahun pelajaran', false), ref: { model: 'academicYear', label: 'code', labelTambahan: 'semester', orderBy: { code: 'desc' } } }], columns: columns(['nama', 'Nama'], ['tingkat', 'Tingkat'], ['unitId', 'Unit'], ['waliKelasId', 'Wali kelas'], ['academicYearId', 'Tahun pelajaran']), orderBy: { nama: 'asc' } },
  ...ENTITAS_PERSONA,
];

export const getEntity = (key: string) => ENTITIES.find((entity) => entity.key === key);
