import type { Entity } from './types';

const text = (name: string, label: string, required = true) => ({ name, label, type: 'text' as const, required });
const number = (name: string, label: string, required = false) => ({ name, label, type: 'number' as const, required, step: 1 });
const date = (name: string, label: string, required = true) => ({ name, label, type: 'date' as const, required });
const columns = (...items: Array<[string, string]>) => items.map(([name, label]) => ({ name, label }));

export const ENTITIES: Entity[] = [
  { key: 'orang', menu: 'induk', model: 'orang', label: 'Identitas orang', idType: 'bigint', fields: [text('nama', 'Nama'), { name: 'jk', label: 'Jenis kelamin', type: 'select', options: ['L', 'P'], required: true }, text('nik', 'NIK', false), text('hp', 'No. HP', false), text('email', 'Email', false), text('alamat', 'Alamat', false), { name: 'aktif', label: 'Aktif', type: 'boolean' }], columns: columns(['nama', 'Nama'], ['jk', 'JK'], ['hp', 'HP'], ['email', 'Email'], ['aktif', 'Aktif']), orderBy: { nama: 'asc' } },
  { key: 'unit', menu: 'pengaturan', model: 'unit', label: 'Unit pendidikan', idType: 'int', fields: [text('key', 'Kode'), text('nama', 'Nama'), text('deskripsi', 'Deskripsi', false), { name: 'aktif', label: 'Aktif', type: 'boolean' }], columns: columns(['key', 'Kode'], ['nama', 'Nama'], ['deskripsi', 'Deskripsi'], ['aktif', 'Aktif']), orderBy: { nama: 'asc' } },
  { key: 'asrama', menu: 'pesantren', model: 'asrama', label: 'Asrama', idType: 'int', fields: [text('nama', 'Nama'), { name: 'jk', label: 'Jenis kelamin', type: 'select', options: ['L', 'P'], required: true }, number('kapasitas', 'Kapasitas'), text('musyrif', 'Musyrif', false)], columns: columns(['nama', 'Nama'], ['jk', 'JK'], ['kapasitas', 'Kapasitas'], ['musyrif', 'Musyrif']), orderBy: { nama: 'asc' } },
  { key: 'halaqah', menu: 'pesantren', model: 'halaqah', label: 'Halaqah', idType: 'int', fields: [text('nama', 'Nama'), text('ustadz', 'Ustadz'), text('waktu', 'Waktu'), text('tempat', 'Tempat'), text('jenjang', 'Jenjang'), number('anggota', 'Anggota')], columns: columns(['nama', 'Nama'], ['ustadz', 'Ustadz'], ['waktu', 'Waktu'], ['tempat', 'Tempat'], ['anggota', 'Anggota']), orderBy: { nama: 'asc' } },
  { key: 'kegiatan', menu: 'pesantren', model: 'kegiatanHarian', label: 'Kegiatan harian', idType: 'int', fields: [text('jam', 'Jam'), text('nama', 'Nama'), text('ket', 'Keterangan', false), number('urutan', 'Urutan')], columns: columns(['jam', 'Jam'], ['nama', 'Nama'], ['ket', 'Keterangan'], ['urutan', 'Urutan']), orderBy: { urutan: 'asc' } },
  { key: 'mapel', menu: 'akademik', model: 'mataPelajaran', label: 'Mata pelajaran', idType: 'int', fields: [text('kode', 'Kode'), text('nama', 'Nama'), number('jp', 'Jam pelajaran'), text('kelompok', 'Kelompok'), text('guru', 'Guru', false), number('kkm', 'KKM'), text('kurikulum', 'Kurikulum', false)], columns: columns(['kode', 'Kode'], ['nama', 'Nama'], ['kelompok', 'Kelompok'], ['guru', 'Guru'], ['kkm', 'KKM']), orderBy: { nama: 'asc' } },
  { key: 'perangkat', menu: 'kurikulum', model: 'perangkatAjar', label: 'Perangkat ajar', idType: 'int', fields: [text('kode', 'Kode'), text('mapel', 'Mapel'), text('kelas', 'Kelas'), text('jenis', 'Jenis'), text('topik', 'Topik'), number('pertemuan', 'Pertemuan'), text('guru', 'Guru'), text('status', 'Status')], columns: columns(['kode', 'Kode'], ['mapel', 'Mapel'], ['kelas', 'Kelas'], ['jenis', 'Jenis'], ['status', 'Status']), orderBy: { kode: 'asc' } },
  { key: 'bank-soal', menu: 'kurikulum', model: 'bankSoal', label: 'Bank soal', idType: 'int', fields: [text('kode', 'Kode'), text('mapel', 'Mapel'), text('topik', 'Topik'), text('tipe', 'Tipe'), text('level', 'Level'), number('butir', 'Butir'), number('dipakai', 'Dipakai'), text('penulis', 'Penulis')], columns: columns(['kode', 'Kode'], ['mapel', 'Mapel'], ['topik', 'Topik'], ['tipe', 'Tipe'], ['butir', 'Butir']), orderBy: { kode: 'asc' } },
  { key: 'obat', menu: 'poskestren', model: 'obat', label: 'Obat', idType: 'int', fields: [text('nama', 'Nama'), text('satuan', 'Satuan'), text('kategori', 'Kategori', false), number('stok', 'Stok'), number('stokMin', 'Stok minimum'), text('kadaluarsa', 'Kadaluarsa', false)], columns: columns(['nama', 'Nama'], ['satuan', 'Satuan'], ['kategori', 'Kategori'], ['stok', 'Stok'], ['stokMin', 'Min. stok']), orderBy: { nama: 'asc' } },
  { key: 'kas', menu: 'keuangan', model: 'transaksiKas', label: 'Transaksi kas', idType: 'bigint', fields: [text('kode', 'Kode'), date('tgl', 'Tanggal'), text('uraian', 'Uraian'), text('kategori', 'Kategori'), text('metode', 'Metode'), { name: 'arah', label: 'Arah', type: 'select', options: ['Masuk', 'Keluar'], required: true }, number('nominal', 'Nominal', true)], columns: columns(['kode', 'Kode'], ['tgl', 'Tanggal'], ['uraian', 'Uraian'], ['arah', 'Arah'], ['nominal', 'Nominal']), orderBy: { tgl: 'desc' } },
  { key: 'pendaftar', menu: 'ppdb', model: 'pendaftar', label: 'Pendaftar PPDB', idType: 'bigint', fields: [text('noReg', 'No. registrasi'), text('nama', 'Nama'), text('pilihan', 'Pilihan'), text('asalSekolah', 'Asal sekolah', false), text('hpWali', 'HP wali', false), date('tglDaftar', 'Tanggal daftar'), number('nilai', 'Nilai', false), { name: 'status', label: 'Status', type: 'select', options: ['Baru', 'Verifikasi', 'Seleksi', 'Lulus', 'TidakLulus', 'DaftarUlang'], required: true }], columns: columns(['noReg', 'No. Reg'], ['nama', 'Nama'], ['pilihan', 'Pilihan'], ['asalSekolah', 'Asal sekolah'], ['status', 'Status']), orderBy: { createdAt: 'desc' } },
  { key: 'template-wa', menu: 'wa', model: 'templateWa', label: 'Template WhatsApp', idType: 'int', fields: [text('kode', 'Kode'), text('role', 'Penerima'), text('judul', 'Judul'), text('pemicu', 'Pemicu'), text('waktu', 'Waktu', false), { name: 'isi', label: 'Isi pesan', type: 'textarea', required: true }, { name: 'aktif', label: 'Aktif', type: 'boolean' }], columns: columns(['kode', 'Kode'], ['role', 'Penerima'], ['judul', 'Judul'], ['pemicu', 'Pemicu'], ['aktif', 'Aktif']), orderBy: { kode: 'asc' } },
  { key: 'pengumuman', menu: 'dashboard', model: 'pengumuman', label: 'Pengumuman', idType: 'bigint', fields: [date('tgl', 'Tanggal'), text('judul', 'Judul'), { name: 'isi', label: 'Isi', type: 'textarea', required: true }, text('target', 'Target')], columns: columns(['tgl', 'Tanggal'], ['judul', 'Judul'], ['target', 'Target']), orderBy: { tgl: 'desc' } },
  { key: 'agenda', menu: 'dashboard', model: 'agenda', label: 'Agenda', idType: 'bigint', fields: [date('tgl', 'Tanggal'), text('jam', 'Jam', false), text('judul', 'Judul'), text('unit', 'Unit', false)], columns: columns(['tgl', 'Tanggal'], ['jam', 'Jam'], ['judul', 'Judul'], ['unit', 'Unit']), orderBy: { tgl: 'desc' } },
];

export const getEntity = (key: string) => ENTITIES.find((entity) => entity.key === key);
