CREATE TABLE IF NOT EXISTS myerpplus_landing.m3_ts_history (
    tsidhistory bigint PRIMARY KEY,
    tsid bigint,
    tscabang text,
    tslokasi text,
    tsgudangasal text,
    tsgudangtransit text,
    tsgudangtujuan text,
    tsnotransaksi text,
    tstgl timestamptz,
    tsuraian text,
    tscatatan text,
    tsnoref text,
    tstglnoref timestamptz,
    tsstatus text,
    tsstatussebelumnya text,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m3_ts_detail_history (
    idhistorydetail bigint PRIMARY KEY,
    idhistory bigint,
    idtsdetail bigint,
    idts bigint,
    idbarang bigint,
    namabarang text,
    jml numeric(20,6),
    jmlbarang numeric(20,6),
    satuan text,
    satuanbarang text,
    nilaisatuan numeric(20,6),
    cabang text,
    lokasi text,
    gudangasal text,
    gudangtransit text,
    gudangtujuan text,
    costcenter text,
    divisi text,
    subdivisi text,
    proyek text,
    catatan text,
    urutan bigint,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m3_sa_history (
    saidhistory bigint PRIMARY KEY,
    said bigint,
    sacabang text,
    salokasi text,
    sagudang text,
    sanotransaksi text,
    satgl timestamptz,
    sauraian text,
    sacatatan text,
    sanoref text,
    satglnoref timestamptz,
    sastatus text,
    sastatussebelumnya text,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m3_sa_detail_history (
    idhistorydetail bigint PRIMARY KEY,
    idhistory bigint,
    idsadetail bigint,
    idsa bigint,
    idbarang bigint,
    namabarang text,
    jmlmasuk numeric(20,6),
    jmlkeluar numeric(20,6),
    jmlbarangmasuk numeric(20,6),
    jmlbarangkeluar numeric(20,6),
    satuan text,
    satuanbarang text,
    nilaisatuan numeric(20,6),
    hpplama numeric(20,6),
    hpp numeric(20,6),
    rekpersediaan text,
    reklawan text,
    idspdetail bigint,
    cabang text,
    lokasi text,
    gudang text,
    costcenter text,
    divisi text,
    subdivisi text,
    proyek text,
    catatan text,
    urutan bigint,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m3_sp_history (
    spidhistory bigint PRIMARY KEY,
    spid bigint,
    spcabang text,
    splokasi text,
    spgudang text,
    spnotransaksi text,
    sptgl timestamptz,
    spuraian text,
    spcatatan text,
    spnoref text,
    sptglnoref timestamptz,
    spstatussa text,
    spstatus text,
    spstatussebelumnya text,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m3_sp_detail_history (
    idhistorydetail bigint PRIMARY KEY,
    idhistory bigint,
    idspdetail bigint,
    idsp bigint,
    idbarang bigint,
    namabarang text,
    jmlsistem numeric(20,6),
    jmlfisik numeric(20,6),
    jmlbagus numeric(20,6),
    jmlrusak numeric(20,6),
    selisih numeric(20,6),
    satuan text,
    satuanbarang text,
    nilaisatuan numeric(20,6),
    jmlbarangsistem numeric(20,6),
    jmlbarangfisik numeric(20,6),
    jmlbarangbagus numeric(20,6),
    jmlbarangrusak numeric(20,6),
    selisihbarang numeric(20,6),
    cabang text,
    lokasi text,
    gudang text,
    lokasibarang text,
    jmlsa numeric(20,6),
    statussa text,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m3_ib (
    ibid bigint PRIMARY KEY,
    ibcabang text,
    iblokasi text,
    ibgudang text,
    ibnotransaksi text,
    ibtgl timestamptz,
    ibmatauang text,
    ibkurs numeric(20,6),
    iburaian text,
    ibcatatan text,
    ibnoref text,
    ibtglnoref timestamptz,
    ibstatus text,
    ibstatussebelumnya text,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m3_ib_detail (
    idibdetail bigint PRIMARY KEY,
    idib bigint,
    idbarang bigint,
    namabarang text,
    jml numeric(20,6),
    jmlbarang numeric(20,6),
    satuan text,
    satuanbarang text,
    nilaisatuan numeric(20,6),
    matauang text,
    kurs numeric(20,6),
    hpplama numeric(20,6),
    hpp numeric(20,6),
    rekpersediaan text,
    cabang text,
    lokasi text,
    gudang text,
    costcenter text,
    divisi text,
    subdivisi text,
    proyek text,
    catatan text,
    urutan bigint,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m3_ib_history (
    ibidhistory bigint PRIMARY KEY,
    ibid bigint,
    ibcabang text,
    iblokasi text,
    ibgudang text,
    ibnotransaksi text,
    ibtgl timestamptz,
    ibmatauang text,
    ibkurs numeric(20,6),
    iburaian text,
    ibcatatan text,
    ibnoref text,
    ibtglnoref timestamptz,
    ibstatus text,
    ibstatussebelumnya text,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m3_ib_detail_history (
    idhistorydetail bigint PRIMARY KEY,
    idhistory bigint,
    idibdetail bigint,
    idib bigint,
    idbarang bigint,
    namabarang text,
    jml numeric(20,6),
    jmlbarang numeric(20,6),
    satuan text,
    satuanbarang text,
    nilaisatuan numeric(20,6),
    matauang text,
    kurs numeric(20,6),
    hpplama numeric(20,6),
    hpp numeric(20,6),
    rekpersediaan text,
    cabang text,
    lokasi text,
    gudang text,
    costcenter text,
    divisi text,
    subdivisi text,
    proyek text,
    catatan text,
    urutan bigint,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m3_notes (
    nid bigint PRIMARY KEY,
    sumber text,
    idtransaksi text,
    kode text,
    catatan text,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m3_files (
    fsumber text,
    fidtransaksi text,
    fnamafile text,
    finputtgl timestamptz,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb,
    CONSTRAINT pk_m3_files PRIMARY KEY (fsumber, fidtransaksi, fnamafile, finputtgl)
);
