CREATE TABLE IF NOT EXISTS myerpplus_landing.m2_aj_history (
    ajidhistory bigint PRIMARY KEY,
    ajid bigint,
    ajcabang text,
    ajlokasi text,
    ajsumber text,
    ajnotransaksi text,
    ajtgl timestamptz,
    ajkodepa bigint,
    ajkontak text,
    ajuraian text,
    ajcatatan text,
    ajmatauang text,
    ajkurs numeric(20,6),
    ajdebit numeric(20,6),
    ajdebitvalas numeric(20,6),
    ajkredit numeric(20,6),
    ajkreditvalas numeric(20,6),
    ajjumlahbayar numeric(20,6),
    ajjumlahbayarvalas numeric(20,6),
    ajstatus text,
    ajstatussebelumnya text,
    ajinputtgl timestamptz,
    ajmodifikasitgl timestamptz,
    ajpostingtgl timestamptz,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m2_aj_detail_history (
    idhistorydetail bigint PRIMARY KEY,
    idhistory bigint,
    idajdetail bigint,
    idaj bigint,
    norek text,
    matauang text,
    kurs numeric(20,6),
    debit numeric(20,6),
    debitvalas numeric(20,6),
    kredit numeric(20,6),
    kreditvalas numeric(20,6),
    catatan text,
    costcenter text,
    divisi text,
    subdivisi text,
    proyek text,
    urutan bigint,
    isclose bigint,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m2_bd_history (
    bdidhistory bigint PRIMARY KEY,
    bdid bigint,
    bdcabang text,
    bdlokasi text,
    bdsumber text,
    bdnotransaksi text,
    bdtgl timestamptz,
    bdtglanggaran timestamptz,
    bdkodepa bigint,
    bdkontak text,
    bdanggarankategori text,
    bdanggarancabang text,
    bdanggaranlokasi text,
    bdanggarancostcenter text,
    bdanggarandivisi text,
    bdanggaransubdivisi text,
    bdanggaranproyek text,
    bduraian text,
    bdcatatan text,
    bdmatauang text,
    bdkurs numeric(20,6),
    bdstatus text,
    bdstatussebelumnya text,
    bdinputtgl timestamptz,
    bdmodifikasitgl timestamptz,
    bdpostingtgl timestamptz,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m2_bd_detail_history (
    idhistorydetail bigint PRIMARY KEY,
    idhistory bigint,
    idbddetail bigint,
    idbd bigint,
    norek text,
    matauang text,
    kurs numeric(20,6),
    jumlah numeric(20,6),
    jumlahvalas numeric(20,6),
    catatan text,
    costcenter text,
    divisi text,
    subdivisi text,
    proyek text,
    urutan bigint,
    isclose bigint,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m2_jm_history (
    jmidhistory bigint PRIMARY KEY,
    jmid bigint,
    jmcabang text,
    jmlokasi text,
    jmsumber text,
    jmnotransaksi text,
    jmtgl timestamptz,
    jmkodepa bigint,
    jmuraian text,
    jmcatatan text,
    jmmatauang text,
    jmkurs numeric(20,6),
    jmdebit numeric(20,6),
    jmdebitvalas numeric(20,6),
    jmkredit numeric(20,6),
    jmkreditvalas numeric(20,6),
    jmjumlahbayar numeric(20,6),
    jmjumlahbayarvalas numeric(20,6),
    jmstatus text,
    jmstatussebelumnya text,
    jminputtgl timestamptz,
    jmmodifikasitgl timestamptz,
    jmpostingtgl timestamptz,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m2_jm_detail_history (
    idhistorydetail bigint PRIMARY KEY,
    idhistory bigint,
    idjmdetail bigint,
    idjm bigint,
    kontak text,
    norek text,
    matauang text,
    kurs numeric(20,6),
    debit numeric(20,6),
    debitvalas numeric(20,6),
    kredit numeric(20,6),
    kreditvalas numeric(20,6),
    catatan text,
    costcenter text,
    divisi text,
    subdivisi text,
    proyek text,
    urutan bigint,
    isclose bigint,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m2_rg_history (
    rgidhistory bigint PRIMARY KEY,
    rgid bigint,
    rgcabang text,
    rglokasi text,
    rgsumber text,
    rgnotransaksi text,
    rgtgl timestamptz,
    rgkodepa bigint,
    rgkontak text,
    rguraian text,
    rgcatatan text,
    rgmatauang text,
    rgkurs numeric(20,6),
    rgjumlah numeric(20,6),
    rgjumlahvalas numeric(20,6),
    rgstatusrgc text,
    rgstatus text,
    rgstatussebelumnya text,
    rginputtgl timestamptz,
    rgmodifikasitgl timestamptz,
    rgpostingtgl timestamptz,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m2_rg_detail_history (
    idhistorydetail bigint PRIMARY KEY,
    idhistory bigint,
    idrgdetail bigint,
    idrg bigint,
    nogiro text,
    kontak text,
    matauang text,
    kurs numeric(20,6),
    jumlah numeric(20,6),
    jumlahvalas numeric(20,6),
    bank text,
    noacbank text,
    rekbank text,
    rekgiro text,
    tgljatuhtempo timestamptz,
    catatan text,
    urutan bigint,
    statusgiro text,
    statusrgc text,
    isclose bigint,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m2_rgc_history (
    rgcidhistory bigint PRIMARY KEY,
    rgcid bigint,
    rgccabang text,
    rgclokasi text,
    rgcsumber text,
    rgcjenis text,
    rgcnotransaksi text,
    rgctgl timestamptz,
    rgckodepa bigint,
    rgckontak text,
    rgcuraian text,
    rgccatatan text,
    rgcmatauang text,
    rgckurs numeric(20,6),
    rgcjumlah numeric(20,6),
    rgcjumlahvalas numeric(20,6),
    rgcidrg bigint,
    rgcstatus text,
    rgcstatussebelumnya text,
    rgcinputtgl timestamptz,
    rgcmodifikasitgl timestamptz,
    rgcpostingtgl timestamptz,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m2_rgc_detail_history (
    idhistorydetail bigint PRIMARY KEY,
    idhistory bigint,
    idrgcdetail bigint,
    idrgc bigint,
    nogiro text,
    kontak text,
    matauang text,
    kurs numeric(20,6),
    jumlah numeric(20,6),
    jumlahvalas numeric(20,6),
    bank text,
    noacbank text,
    rekbank text,
    rekgiro text,
    tgljatuhtempo timestamptz,
    catatan text,
    urutan bigint,
    statusgiro text,
    idrgdetail bigint,
    isclose bigint,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m2_sg_history (
    sgidhistory bigint PRIMARY KEY,
    sgid bigint,
    sgcabang text,
    sglokasi text,
    sgsumber text,
    sgnotransaksi text,
    sgtgl timestamptz,
    sgkodepa bigint,
    sgkontak text,
    sguraian text,
    sgcatatan text,
    sgmatauang text,
    sgkurs numeric(20,6),
    sgjumlah numeric(20,6),
    sgjumlahvalas numeric(20,6),
    sgstatussgc text,
    sgstatus text,
    sgstatussebelumnya text,
    sginputtgl timestamptz,
    sgmodifikasitgl timestamptz,
    sgpostingtgl timestamptz,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m2_sg_detail_history (
    idhistorydetail bigint PRIMARY KEY,
    idhistory bigint,
    idsgdetail bigint,
    idsg bigint,
    nogiro text,
    kontak text,
    matauang text,
    kurs numeric(20,6),
    jumlah numeric(20,6),
    jumlahvalas numeric(20,6),
    bank text,
    noacbank text,
    rekbank text,
    rekgiro text,
    tgljatuhtempo timestamptz,
    catatan text,
    urutan bigint,
    statusgiro text,
    statussgc text,
    isclose bigint,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m2_sgc_history (
    sgcidhistory bigint PRIMARY KEY,
    sgcid bigint,
    sgccabang text,
    sgclokasi text,
    sgcsumber text,
    sgcjenis text,
    sgcnotransaksi text,
    sgctgl timestamptz,
    sgckodepa bigint,
    sgckontak text,
    sgcuraian text,
    sgccatatan text,
    sgcmatauang text,
    sgckurs numeric(20,6),
    sgcjumlah numeric(20,6),
    sgcjumlahvalas numeric(20,6),
    sgcidsg bigint,
    sgcstatus text,
    sgcstatussebelumnya text,
    sgcinputtgl timestamptz,
    sgcmodifikasitgl timestamptz,
    sgcpostingtgl timestamptz,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);

CREATE TABLE IF NOT EXISTS myerpplus_landing.m2_sgc_detail_history (
    idhistorydetail bigint PRIMARY KEY,
    idhistory bigint,
    idsgcdetail bigint,
    idsgc bigint,
    nogiro text,
    kontak text,
    matauang text,
    kurs numeric(20,6),
    jumlah numeric(20,6),
    jumlahvalas numeric(20,6),
    bank text,
    noacbank text,
    rekbank text,
    rekgiro text,
    tgljatuhtempo timestamptz,
    catatan text,
    urutan bigint,
    statusgiro text,
    idsgdetail bigint,
    isclose bigint,
    _cdc_record_key text,
    _cdc_source_table text,
    _cdc_updated_at timestamptz,
    _cdc_deleted boolean,
    _cdc_payload jsonb
);
