#!/usr/bin/env python3
"""Render PostgreSQL landing-table SQL from semantic schemas for OBT prerequisites."""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path("/opt/sentient-factory/apps/myerpplus-db-mapping")
DB_ROOT = ROOT / "db"
OUT_DIR = DB_ROOT / "obt-physical-sql" / "pgsql-landing"


SEMANTIC_FILES = {
    "m0": DB_ROOT / "m0 - administrator" / "semantic-schema-m0.json",
    "m1": DB_ROOT / "m1-master data" / "semantic-schema-m1.json",
    "m2": DB_ROOT / "m2-finance" / "semantic-schema-m2.json",
    "m3": DB_ROOT / "m3-inventory" / "semantic-schema-m3.json",
    "m4": DB_ROOT / "m4-purchasing" / "semantic-schema-m4.json",
    "m5": DB_ROOT / "m5-sales" / "semantic-schema-m5.json",
    "m12": DB_ROOT / "m12-pos" / "semantic-schema-m12.json",
}

TABLE_ORDER = [
    "m0_user",
    "m0_menu",
    "m0_nomor",
    "m0_role",
    "m0_role_menu",
    "m0_user_role",
    "m0_userlog",
    "m1_branch",
    "m1_class_product",
    "m1_coa",
    "m1_contact",
    "m1_contact_category",
    "m1_cost_center",
    "m1_currency",
    "m1_customer_category",
    "m1_division",
    "m1_expedition",
    "m1_bank",
    "m1_city",
    "m1_item",
    "m1_department",
    "m1_country",
    "m1_item_category",
    "m1_item_permission",
    "m1_item_stock_warehouse",
    "m1_item_transaction",
    "m1_item_type",
    "m1_location",
    "m1_material",
    "m1_merk",
    "m1_model",
    "m1_project",
    "m1_salesman_category",
    "m1_section",
    "m1_size",
    "m1_subdepartment",
    "m1_subdivision",
    "m1_supplier_category",
    "m1_tax",
    "m1_terms",
    "m1_transaction_note",
    "m1_transaction_note_detail",
    "m1_type_sa",
    "m1_unit",
    "m1_warehouse",
    "m1_province",
    "m1_other_cost",
    "m2_cd",
    "m2_cd_detail",
    "m2_cd_detail_history",
    "m2_cd_history",
    "m2_bd",
    "m2_bd_detail",
    "m2_bd_detail_history",
    "m2_bd_history",
    "m2_cr",
    "m2_cr_detail",
    "m2_cr_detail_history",
    "m2_cr_history",
    "m2_aj",
    "m2_aj_detail",
    "m2_aj_detail_history",
    "m2_aj_history",
    "m2_cb",
    "m2_cb_detail",
    "m2_cb_detail_history",
    "m2_cb_pay",
    "m2_cb_pay_history",
    "m2_cb_history",
    "m2_files",
    "m2_gj",
    "m2_gj_detail",
    "m2_gj_detail_history",
    "m2_gj_history",
    "m2_giro_list",
    "m2_jm",
    "m2_jm_detail",
    "m2_jm_detail_history",
    "m2_jm_history",
    "m2_notes",
    "m2_realization",
    "m2_rm",
    "m2_rm_pay",
    "m2_rm_pay_history",
    "m2_rm_detail",
    "m2_rm_detail_history",
    "m2_rm_history",
    "m2_rg",
    "m2_rg_detail",
    "m2_rg_detail_history",
    "m2_rg_history",
    "m2_rgc",
    "m2_rgc_detail",
    "m2_rgc_detail_history",
    "m2_rgc_history",
    "m2_sg",
    "m2_sg_detail",
    "m2_sg_detail_history",
    "m2_sg_history",
    "m2_sgc",
    "m2_sgc_detail",
    "m2_sgc_detail_history",
    "m2_sgc_history",
    "m2_sm",
    "m2_sm_detail",
    "m2_sm_detail_history",
    "m2_sm_pay",
    "m2_sm_pay_history",
    "m2_sm_history",
    "m2_transaction_journal",
    "m3_sa",
    "m3_sa_detail",
    "m3_mr",
    "m3_mr_detail",
    "m3_rs",
    "m3_rs_detail",
    "m3_sp",
    "m3_sp_detail",
    "m3_ts",
    "m3_ts_detail",
    "m4_po",
    "m4_po_detail",
    "m4_ap",
    "m4_ap_pay",
    "m4_grn",
    "m4_grn_detail",
    "m4_ri",
    "m4_ri_detail",
    "m4_dnr",
    "m4_dnr_detail",
    "m4_prt",
    "m4_prt_detail",
    "m4_vp",
    "m4_vp_detail",
    "m4_vpp",
    "m4_vpp_detail",
    "m5_sq",
    "m5_sq_detail",
    "m5_so",
    "m5_so_detail",
    "m5_as",
    "m5_ip",
    "m5_pi",
    "m5_pi_detail",
    "m5_pl",
    "m5_pl_detail",
    "m5_do",
    "m5_do_detail",
    "m5_dr",
    "m5_dr_detail",
    "m5_ic",
    "m5_ic_detail",
    "m5_pv",
    "m5_pv_detail",
    "m5_rp",
    "m5_si",
    "m5_si_detail",
    "m5_rnr",
    "m5_rnr_detail",
    "m5_sr",
    "m5_sr_detail",
    "m_12_pos_category",
    "m_12_pos_voucher_in",
    "m_12_pos_voucher_out",
]

PRIMARY_KEYS = {
    "m0_user": "userid",
    "m0_menu": ["mnmoduleid", "mnid"],
    "m0_nomor": "kodetabel",
    "m0_role": "rkode",
    "m0_role_menu": ["rmrole", "rmmoduleid", "rmmenuid"],
    "m0_user_role": ["userid", "role"],
    "m0_userlog": ["uluserid", "ultgl", "ulidmodule", "ulidmenu", "uljenisaktivitas", "ulaktivitas"],
    "m1_branch": "bkode",
    "m1_class_product": "cpkode",
    "m1_coa": "cnomor",
    "m1_contact": "kid",
    "m1_contact_category": "cckode",
    "m1_cost_center": "cckode",
    "m1_currency": "ckode",
    "m1_customer_category": "cckode",
    "m1_division": "dkode",
    "m1_expedition": "ekode",
    "m1_bank": "bkode",
    "m1_city": "ckode",
    "m1_item": "bid",
    "m1_department": "dpkode",
    "m1_country": "ckode",
    "m1_item_category": "ickode",
    "m1_item_permission": "ipkode",
    "m1_item_stock_warehouse": ["idbarang", "kgudang"],
    "m1_item_transaction": "id",
    "m1_item_type": "itkode",
    "m1_location": "lkode",
    "m1_material": "mkode",
    "m1_merk": "mkode",
    "m1_model": "mkode",
    "m1_project": "pkode",
    "m1_salesman_category": "sckode",
    "m1_section": "skode",
    "m1_size": "skode",
    "m1_subdepartment": "sdpkode",
    "m1_subdivision": "sdkode",
    "m1_supplier_category": "sckode",
    "m1_tax": "tkode",
    "m1_terms": "trkode",
    "m1_transaction_note": ["tnsumber", "tnkode"],
    "m1_transaction_note_detail": ["tndsumber", "tndkode"],
    "m1_type_sa": "tsakode",
    "m1_unit": "ukode",
    "m1_warehouse": "wkode",
    "m1_province": "pkode",
    "m1_other_cost": "ockode",
    "m2_cd": "cdid",
    "m2_cd_detail": "idcddetail",
    "m2_cd_detail_history": "idhistorydetail",
    "m2_cd_history": "cdidhistory",
    "m2_bd": "bdid",
    "m2_bd_detail": "idbddetail",
    "m2_bd_detail_history": "idhistorydetail",
    "m2_bd_history": "bdidhistory",
    "m2_cr": "crid",
    "m2_cr_detail": "idcrdetail",
    "m2_cr_detail_history": "idhistorydetail",
    "m2_cr_history": "cridhistory",
    "m2_aj": "ajid",
    "m2_aj_detail": "idajdetail",
    "m2_aj_detail_history": "idhistorydetail",
    "m2_aj_history": "ajidhistory",
    "m2_cb": "cbid",
    "m2_cb_detail": "idcbdetail",
    "m2_cb_detail_history": "idhistorydetail",
    "m2_cb_pay": "idcbcarabayar",
    "m2_cb_pay_history": "idcarabayarhistory",
    "m2_cb_history": "cbidhistory",
    "m2_files": ["fsumber", "fidtransaksi", "fnamafile", "finputtgl"],
    "m2_gj": "gjid",
    "m2_gj_detail": "idgjdetail",
    "m2_gj_detail_history": "idhistorydetail",
    "m2_gj_history": "gjidhistory",
    "m2_giro_list": ["glsumber", "glidtransaksi", "glnogiro", "glurutan"],
    "m2_jm": "jmid",
    "m2_jm_detail": "idjmdetail",
    "m2_jm_detail_history": "idhistorydetail",
    "m2_jm_history": "jmidhistory",
    "m2_notes": "nid",
    "m2_realization": ["rtahun", "rbulan", "rnorek", "rkodepa"],
    "m2_rm": "rmid",
    "m2_rm_pay": "idrmcarabayar",
    "m2_rm_pay_history": "idrmcarabayarhistory",
    "m2_rm_detail": "idrmdetail",
    "m2_rm_detail_history": "idhistorydetail",
    "m2_rm_history": "rmidhistory",
    "m2_rg": "rgid",
    "m2_rg_detail": "idrgdetail",
    "m2_rg_detail_history": "idhistorydetail",
    "m2_rg_history": "rgidhistory",
    "m2_rgc": "rgcid",
    "m2_rgc_detail": "idrgcdetail",
    "m2_rgc_detail_history": "idhistorydetail",
    "m2_rgc_history": "rgcidhistory",
    "m2_sg": "sgid",
    "m2_sg_detail": "idsgdetail",
    "m2_sg_detail_history": "idhistorydetail",
    "m2_sg_history": "sgidhistory",
    "m2_sgc": "sgcid",
    "m2_sgc_detail": "idsgcdetail",
    "m2_sgc_detail_history": "idhistorydetail",
    "m2_sgc_history": "sgcidhistory",
    "m2_sm": "smid",
    "m2_sm_detail": "idsmdetail",
    "m2_sm_detail_history": "idhistorydetail",
    "m2_sm_pay": "idsmcarabayar",
    "m2_sm_pay_history": "idsmcarabayarhistory",
    "m2_sm_history": "smidhistory",
    "m2_transaction_journal": "tid",
    "m3_sa": "said",
    "m3_sa_detail": "idsadetail",
    "m3_mr": "mrid",
    "m3_mr_detail": "idmrdetail",
    "m3_rs": "rsid",
    "m3_rs_detail": "idrsdetail",
    "m3_sp": "spid",
    "m3_sp_detail": "idspdetail",
    "m3_ts": "tsid",
    "m3_ts_detail": "idtsdetail",
    "m4_po": "poid",
    "m4_po_detail": "idpodetail",
    "m4_ap": "apid",
    "m4_ap_pay": "idapcarabayar",
    "m4_grn": "grnid",
    "m4_grn_detail": "idgrndetail",
    "m4_ri": "riid",
    "m4_ri_detail": "idridetail",
    "m4_dnr": "dnrid",
    "m4_dnr_detail": "iddnrdetail",
    "m4_prt": "prtid",
    "m4_prt_detail": "idprtdetail",
    "m4_vp": "vpid",
    "m4_vp_detail": "idvpdetail",
    "m4_vpp": "vppid",
    "m4_vpp_detail": "idvppdetail",
    "m5_sq": "sqid",
    "m5_sq_detail": "idsqdetail",
    "m5_so": "soid",
    "m5_so_detail": "idsodetail",
    "m5_as": "asid",
    "m5_ip": "ipid",
    "m5_pi": "piid",
    "m5_pi_detail": "idpidetail",
    "m5_pl": "plid",
    "m5_pl_detail": "idpldetail",
    "m5_do": "doid",
    "m5_do_detail": "iddodetail",
    "m5_dr": "drid",
    "m5_dr_detail": "iddrdetail",
    "m5_ic": "icid",
    "m5_ic_detail": "idicdetail",
    "m5_pv": "pvid",
    "m5_pv_detail": "idpvdetail",
    "m5_rp": "rpid",
    "m5_si": "siid",
    "m5_si_detail": "idsidetail",
    "m5_rnr": "rnrid",
    "m5_rnr_detail": "idrnrdetail",
    "m5_sr": "srid",
    "m5_sr_detail": "idsrdetail",
    "m_12_pos_category": "pckode",
    "m_12_pos_voucher_in": "viid",
    "m_12_pos_voucher_out": "void",
}

TYPE_OVERRIDES: dict[tuple[str, str], str] = {
    ("m0_menu", "mnid"): "bigint",
    ("m0_menu", "mnidtransaksi"): "bigint",
    ("m0_menu", "mnlebar"): "bigint",
    ("m0_menu", "mnlevel"): "bigint",
    ("m0_menu", "mnmoduleid"): "bigint",
    ("m0_menu", "mnpopup"): "bigint",
    ("m0_menu", "mntinggi"): "bigint",
    ("m0_menu", "mntype"): "bigint",
    ("m0_menu", "mnurutan"): "bigint",
    ("m0_menu", "mnviewopening"): "bigint",
    ("m0_nomor", "jmldigit"): "bigint",
    ("m0_nomor", "menuid"): "bigint",
    ("m0_nomor", "moduleid"): "bigint",
    ("m0_role_menu", "rmmenuid"): "bigint",
    ("m0_role_menu", "rmmoduleid"): "bigint",
    ("m0_role_menu", "rmfavourite"): "bigint",
    ("m0_user_role", "userid"): "bigint",
    ("m0_userlog", "ulidmenu"): "bigint",
    ("m0_userlog", "ulidmodule"): "bigint",
    ("m0_userlog", "uljenisaktivitas"): "bigint",
    ("m0_userlog", "uluserid"): "bigint",
    ("m0_userlog", "ultgl"): "timestamptz",
    ("m4_po", "postatus"): "bigint",
    ("m4_po", "posupplier"): "bigint",
    ("m4_po", "pobagianpembelian"): "bigint",
    ("m4_po_detail", "urutan"): "bigint",
    ("m4_ap", "apcabang"): "text",
    ("m4_ap", "aplokasi"): "text",
    ("m4_ap", "apjenis"): "bigint",
    ("m4_ap", "apkodepa"): "bigint",
    ("m4_ap", "apkontak"): "bigint",
    ("m4_ap", "apkontakperson"): "bigint",
    ("m4_ap", "apbagianpembayaran"): "bigint",
    ("m4_ap", "aptgljatuhtempo"): "timestamptz",
    ("m4_ap", "apidpo"): "bigint",
    ("m4_ap", "apstatusbayar"): "bigint",
    ("m4_ap", "aptgllunas"): "timestamptz",
    ("m4_ap", "apcostcenter"): "text",
    ("m4_ap", "apdivisi"): "text",
    ("m4_ap", "apsubdivisi"): "text",
    ("m4_ap", "approyek"): "text",
    ("m4_ap", "apstatusvpp"): "bigint",
    ("m4_ap", "apstatus"): "bigint",
    ("m4_ap", "apstatussebelumnya"): "bigint",
    ("m4_ap", "apjmlrevisi"): "bigint",
    ("m4_ap", "apcetakanke"): "bigint",
    ("m4_ap", "appostingtgl"): "timestamptz",
    ("m4_ap_pay", "idap"): "bigint",
    ("m4_ap_pay", "carabayar"): "bigint",
    ("m4_ap_pay", "tgljt"): "timestamptz",
    ("m4_ap_pay", "urutan"): "bigint",
    ("m4_ri", "ristatuslunas"): "bigint",
    ("m4_ri", "ritgllunas"): "timestamptz",
    ("m4_ri", "rinofakturpajak"): "text",
    ("m4_ri", "risdhbayarpajak"): "bigint",
    ("m4_ri", "ritglbayarpajak"): "timestamptz",
    ("m4_ri", "rirekdiskon"): "text",
    ("m4_ri", "rirekpajak1"): "text",
    ("m4_ri", "rirekpajak2"): "text",
    ("m4_ri", "ribiayalain"): "numeric(20,6)",
    ("m4_ri", "rikodepa"): "bigint",
    ("m4_ri", "risupplier"): "bigint",
    ("m4_ri", "ribagianpembelian"): "bigint",
    ("m4_ri", "riidpr"): "bigint",
    ("m4_ri", "riidcs"): "bigint",
    ("m4_ri", "riidrq"): "bigint",
    ("m4_ri", "riidbs"): "bigint",
    ("m4_ri", "riidpo"): "bigint",
    ("m4_ri", "riidipc"): "bigint",
    ("m4_ri", "riidgrn"): "bigint",
    ("m4_ri", "ristatusdnr"): "bigint",
    ("m4_ri", "ristatusprt"): "bigint",
    ("m4_ri", "ristatusrealisasi"): "bigint",
    ("m4_ri", "ristatuspie"): "bigint",
    ("m4_ri", "ritglpie"): "timestamptz",
    ("m4_ri", "ristatusvpp"): "bigint",
    ("m4_ri", "ristatus"): "bigint",
    ("m4_ri", "ristatussebelumnya"): "bigint",
    ("m4_ri", "ricetakanke"): "bigint",
    ("m4_ri", "ritutupperiode"): "bigint",
    ("m4_ri", "riidap"): "bigint",
    ("m4_vp", "vpcabang"): "text",
    ("m4_vp", "vplokasi"): "text",
    ("m4_vp", "vpgudang"): "text",
    ("m4_vp", "vpkodepa"): "bigint",
    ("m4_vp", "vpsupplier"): "bigint",
    ("m4_vp", "vpsupplierkontak"): "bigint",
    ("m4_vp", "vpbagianpembayaran"): "bigint",
    ("m4_vp", "vptglnoref"): "timestamptz",
    ("m4_vp", "vpcarabayar"): "bigint",
    ("m4_vp", "vptglbayar"): "timestamptz",
    ("m4_vp", "vpidvpp"): "bigint",
    ("m4_vp", "vpstatus"): "bigint",
    ("m4_vp", "vpstatussebelumnya"): "bigint",
    ("m4_vp", "vpjmlrevisi"): "bigint",
    ("m4_vp", "vpcetakanke"): "bigint",
    ("m4_vp", "vppostingtgl"): "timestamptz",
    ("m4_vp_detail", "idvp"): "bigint",
    ("m4_vp_detail", "idtransaksi"): "bigint",
    ("m4_vp_detail", "rencana"): "timestamptz",
    ("m4_vp_detail", "rekhutangpiutang"): "text",
    ("m4_vp_detail", "costcenter"): "text",
    ("m4_vp_detail", "divisi"): "text",
    ("m4_vp_detail", "subdivisi"): "text",
    ("m4_vp_detail", "proyek"): "text",
    ("m4_vp_detail", "idvppdetail"): "bigint",
    ("m4_vp_detail", "urutan"): "bigint",
    ("m4_vpp", "vppcabang"): "text",
    ("m4_vpp", "vpplokasi"): "text",
    ("m4_vpp", "vppgudang"): "text",
    ("m4_vpp", "vppkodepa"): "bigint",
    ("m4_vpp", "vppsupplier"): "bigint",
    ("m4_vpp", "vppsupplierkontak"): "bigint",
    ("m4_vpp", "vppbagianpembayaran"): "bigint",
    ("m4_vpp", "vpptglnoref"): "timestamptz",
    ("m4_vpp", "vppcarabayar"): "bigint",
    ("m4_vpp", "vpptglbayar"): "timestamptz",
    ("m4_vpp", "vppstatusvp"): "bigint",
    ("m4_vpp", "vppstatus"): "bigint",
    ("m4_vpp", "vppstatussebelumnya"): "bigint",
    ("m4_vpp", "vppjmlrevisi"): "bigint",
    ("m4_vpp", "vppcetakanke"): "bigint",
    ("m4_vpp", "vpppostingtgl"): "timestamptz",
    ("m4_vpp_detail", "idvpp"): "bigint",
    ("m4_vpp_detail", "idtransaksi"): "bigint",
    ("m4_vpp_detail", "rencana"): "timestamptz",
    ("m4_vpp_detail", "rekhutangpiutang"): "text",
    ("m4_vpp_detail", "costcenter"): "text",
    ("m4_vpp_detail", "divisi"): "text",
    ("m4_vpp_detail", "subdivisi"): "text",
    ("m4_vpp_detail", "proyek"): "text",
    ("m4_vpp_detail", "statusvp"): "bigint",
    ("m4_vpp_detail", "urutan"): "bigint",
    ("m5_as", "askontak"): "bigint",
    ("m5_as", "askontakperson"): "bigint",
    ("m5_as", "asbagianterima"): "bigint",
    ("m5_as", "astgljatuhtempo"): "timestamptz",
    ("m5_as", "asidso"): "bigint",
    ("m5_as", "asidip"): "bigint",
    ("m5_as", "asstatusbayar"): "bigint",
    ("m5_as", "astgllunas"): "timestamptz",
    ("m5_as", "asstatus"): "bigint",
    ("m5_as", "asstatussebelumnya"): "bigint",
    ("m5_as", "asjmlrevisi"): "bigint",
    ("m5_as", "ascetakanke"): "bigint",
    ("m5_as", "asinputuser"): "bigint",
    ("m5_as", "asinputtgl"): "timestamptz",
    ("m5_as", "asmodifikasiuser"): "bigint",
    ("m5_as", "asmodifikasitgl"): "timestamptz",
    ("m5_as", "aspostingtgl"): "timestamptz",
    ("m5_ip", "ipkontak"): "bigint",
    ("m5_ip", "ipkontakperson"): "bigint",
    ("m5_ip", "ipbagianterima"): "bigint",
    ("m5_ip", "iptgljatuhtempo"): "timestamptz",
    ("m5_ip", "ipidso"): "bigint",
    ("m5_ip", "ipstatusbayar"): "bigint",
    ("m5_ip", "iptgllunas"): "timestamptz",
    ("m5_ip", "ipstatus"): "bigint",
    ("m5_ip", "ipstatussebelumnya"): "bigint",
    ("m5_ip", "ipjmlrevisi"): "bigint",
    ("m5_ip", "ipcetakanke"): "bigint",
    ("m5_ip", "ipinputuser"): "bigint",
    ("m5_ip", "ipinputtgl"): "timestamptz",
    ("m5_ip", "ipmodifikasiuser"): "bigint",
    ("m5_ip", "ipmodifikasitgl"): "timestamptz",
    ("m5_ip", "ippostingtgl"): "timestamptz",
    ("m5_ic", "iccustomer"): "bigint",
    ("m5_ic", "iccustomerkontak"): "bigint",
    ("m5_ic", "icbagianpenjualan"): "bigint",
    ("m5_ic", "icbagianpenagihan"): "bigint",
    ("m5_ic", "ictglnoref"): "timestamptz",
    ("m5_ic", "iccarabayar"): "bigint",
    ("m5_ic", "ictglbayar"): "timestamptz",
    ("m5_ic", "icstatuspv"): "bigint",
    ("m5_ic", "icstatus"): "bigint",
    ("m5_ic", "icstatussebelumnya"): "bigint",
    ("m5_ic", "icjmlrevisi"): "bigint",
    ("m5_ic", "iccetakanke"): "bigint",
    ("m5_ic", "icpostingtgl"): "timestamptz",
    ("m5_ic", "icmodifikasiuser"): "bigint",
    ("m5_ic", "icmodifikasitgl"): "timestamptz",
    ("m5_ic_detail", "idic"): "bigint",
    ("m5_ic_detail", "idtransaksi"): "bigint",
    ("m5_ic_detail", "rencana"): "timestamptz",
    ("m5_ic_detail", "rekhutangpiutang"): "text",
    ("m5_ic_detail", "costcenter"): "text",
    ("m5_ic_detail", "divisi"): "text",
    ("m5_ic_detail", "subdivisi"): "text",
    ("m5_ic_detail", "proyek"): "text",
    ("m5_ic_detail", "statuspv"): "bigint",
    ("m5_ic_detail", "urutan"): "bigint",
    ("m5_pv", "pvcustomer"): "bigint",
    ("m5_pv", "pvcustomerkontak"): "bigint",
    ("m5_pv", "pvbagianpenjualan"): "bigint",
    ("m5_pv", "pvbagianterima"): "bigint",
    ("m5_pv", "pvtglnoref"): "timestamptz",
    ("m5_pv", "pvcarabayar"): "bigint",
    ("m5_pv", "pvtglbayar"): "timestamptz",
    ("m5_pv", "pvidic"): "bigint",
    ("m5_pv", "pvstatus"): "bigint",
    ("m5_pv", "pvstatussebelumnya"): "bigint",
    ("m5_pv", "pvjmlrevisi"): "bigint",
    ("m5_pv", "pvcetakanke"): "bigint",
    ("m5_pv", "pvpostingtgl"): "timestamptz",
    ("m5_pv", "pvmodifikasiuser"): "bigint",
    ("m5_pv", "pvmodifikasitgl"): "timestamptz",
    ("m5_pv_detail", "idpv"): "bigint",
    ("m5_pv_detail", "idtransaksi"): "bigint",
    ("m5_pv_detail", "rencana"): "timestamptz",
    ("m5_pv_detail", "rekhutangpiutang"): "text",
    ("m5_pv_detail", "costcenter"): "text",
    ("m5_pv_detail", "divisi"): "text",
    ("m5_pv_detail", "subdivisi"): "text",
    ("m5_pv_detail", "proyek"): "text",
    ("m5_pv_detail", "idicdetail"): "bigint",
    ("m5_pv_detail", "urutan"): "bigint",
    ("m5_rp", "rpkontak"): "bigint",
    ("m5_rp", "rpkontakperson"): "bigint",
    ("m5_rp", "rpbagianterima"): "bigint",
    ("m5_rp", "rptgljatuhtempo"): "timestamptz",
    ("m5_rp", "rpidsi"): "bigint",
    ("m5_rp", "rpstatusbayar"): "bigint",
    ("m5_rp", "rptgllunas"): "timestamptz",
    ("m5_rp", "rpstatus"): "bigint",
    ("m5_rp", "rpstatussebelumnya"): "bigint",
    ("m5_rp", "rpjmlrevisi"): "bigint",
    ("m5_rp", "rpcetakanke"): "bigint",
    ("m5_rp", "rpinputuser"): "bigint",
    ("m5_rp", "rpinputtgl"): "timestamptz",
    ("m5_rp", "rpmodifikasiuser"): "bigint",
    ("m5_rp", "rpmodifikasitgl"): "timestamptz",
    ("m5_rp", "rppostingtgl"): "timestamptz",
    ("m5_si", "sicustomer"): "bigint",
    ("m5_si", "sibagianpenjualan"): "bigint",
    ("m5_si", "sitglkirim"): "timestamptz",
    ("m5_si", "sitgljatuhtempo"): "timestamptz",
    ("m5_si", "sitglnoref"): "timestamptz",
    ("m5_si", "sitglpenutupan"): "timestamptz",
    ("m5_si", "sibiayalain"): "numeric(20,6)",
    ("m5_si", "sibayartunai"): "numeric(20,6)",
    ("m5_si", "sibayarkkredit"): "numeric(20,6)",
    ("m5_si", "sibayarkdebit"): "numeric(20,6)",
    ("m5_si", "sibayarvoucher"): "numeric(20,6)",
    ("m5_si", "sibayarpoin"): "numeric(20,6)",
    ("m5_si", "sicharge"): "numeric(20,6)",
    ("m5_si", "sipoinsebelumnya"): "numeric(20,6)",
    ("m5_si", "sipoindidapat"): "numeric(20,6)",
    ("m5_si", "sistatuslunas"): "bigint",
    ("m5_si", "sitgllunas"): "timestamptz",
    ("m5_si", "sinofakturpajak"): "text",
    ("m5_si", "sisdhbayarpajak"): "bigint",
    ("m5_si", "sitglbayarpajak"): "timestamptz",
    ("m5_si", "sirekdiskon"): "text",
    ("m5_si", "sirekpajak1"): "text",
    ("m5_si", "sirekpajak2"): "text",
    ("m5_si", "siidsq"): "bigint",
    ("m5_si", "siidso"): "bigint",
    ("m5_si", "siidas"): "bigint",
    ("m5_si", "siidpi"): "bigint",
    ("m5_si", "siidpl"): "bigint",
    ("m5_si", "siiddo"): "bigint",
    ("m5_si", "siiddr"): "bigint",
    ("m5_si", "sistatusrnr"): "bigint",
    ("m5_si", "sistatussr"): "bigint",
    ("m5_si", "sistatusrealisasi"): "bigint",
    ("m5_si", "sistatussie"): "bigint",
    ("m5_si", "sitglsie"): "timestamptz",
    ("m5_si", "sistatus"): "bigint",
    ("m5_si", "sistatussebelumnya"): "bigint",
    ("m5_si", "sicetakanke"): "bigint",
    ("m5_si", "siuploaded"): "bigint",
    ("m5_si", "simodifikasiuser"): "bigint",
    ("m5_si_detail", "urutan"): "bigint",
    ("m5_sr", "srcustomer"): "bigint",
    ("m5_sr", "srbagianpenjualan"): "bigint",
    ("m5_sr", "srtglkirim"): "timestamptz",
    ("m5_sr", "srtgljatuhtempo"): "timestamptz",
    ("m5_sr", "srtglnoref"): "timestamptz",
    ("m5_sr", "srtglpenutupan"): "timestamptz",
    ("m5_sr", "srbiayalain"): "numeric(20,6)",
    ("m5_sr", "srsisatransaksi"): "numeric(20,6)",
    ("m5_sr", "srstatuslunas"): "bigint",
    ("m5_sr", "srtgllunas"): "timestamptz",
    ("m5_sr", "srnofakturpajak"): "text",
    ("m5_sr", "srsdhbayarpajak"): "bigint",
    ("m5_sr", "srtglbayarpajak"): "timestamptz",
    ("m5_sr", "srrekdiskon"): "text",
    ("m5_sr", "srrekpajak1"): "text",
    ("m5_sr", "srrekpajak2"): "text",
    ("m5_sr", "sridsq"): "bigint",
    ("m5_sr", "sridso"): "bigint",
    ("m5_sr", "sridpi"): "bigint",
    ("m5_sr", "sridpl"): "bigint",
    ("m5_sr", "sriddo"): "bigint",
    ("m5_sr", "sriddr"): "bigint",
    ("m5_sr", "sridsi"): "bigint",
    ("m5_sr", "sridrnr"): "bigint",
    ("m5_sr", "srstatussie"): "bigint",
    ("m5_sr", "srtglsie"): "timestamptz",
    ("m5_sr", "srstatus"): "bigint",
    ("m5_sr", "srstatussebelumnya"): "bigint",
    ("m5_sr", "srcetakanke"): "bigint",
}


def infer_type(table_name: str, column: str) -> str:
    override = TYPE_OVERRIDES.get((table_name, column))
    if override:
        return override
    if column in {"userid"} or column.endswith("id") or column.startswith("id"):
        return "bigint"
    if "tgl" in column or "date" in column or "expired" in column:
        return "timestamptz"
    if re.match(r"^[a-z]{1,4}id[a-z0-9_]+$", column):
        return "bigint"
    numeric_tokens = (
        "jml",
        "harga",
        "kurs",
        "diskon",
        "pajak",
        "total",
        "saldo",
        "batas",
        "denda",
        "qty",
        "rate",
        "nilai",
        "point",
        "persen",
        "luas",
        "berat",
        "volume",
        "komisi",
    )
    if any(token in column for token in numeric_tokens):
        return "numeric(20,6)"
    if column.endswith("aktif") or column.startswith("is") or column.startswith("status") or column.endswith("close") or column.endswith("posting"):
        return "bigint"
    return "text"


def cast_expr(table_name: str, payload: str, column: str) -> str:
    expr = f"{payload} ->> '{column}'"
    pg_type = infer_type(table_name, column)
    if pg_type == "bigint":
        return f"NULLIF({expr}, '')::bigint"
    if pg_type == "numeric(20,6)":
        return f"NULLIF({expr}, '')::numeric(20,6)"
    if pg_type == "timestamptz":
        return f"NULLIF({expr}, '')::timestamptz"
    return expr


def load_tables() -> dict[str, list[str]]:
    out: dict[str, list[str]] = {}
    for path in SEMANTIC_FILES.values():
        obj = json.loads(path.read_text())
        for table in obj["tables"]:
            name = table["table_name"]
            if name in TABLE_ORDER:
                out[name] = list(table["columns"].keys())
    missing = [name for name in TABLE_ORDER if name not in out]
    if missing:
        raise KeyError(f"Missing semantic tables: {', '.join(missing)}")
    return out


def pk_columns(table_name: str) -> list[str]:
    pk = PRIMARY_KEYS[table_name]
    return pk if isinstance(pk, list) else [pk]


def render_create(table_name: str, columns: list[str]) -> str:
    pk = pk_columns(table_name)
    lines = [f"    {col} {infer_type(table_name, col)}" for col in columns]
    lines.extend(
        [
            "    _cdc_record_key text",
            "    _cdc_source_table text",
            "    _cdc_updated_at timestamptz",
            "    _cdc_deleted boolean not null default false",
            "    _cdc_payload jsonb",
        ]
    )
    cols = ",\n".join(lines)
    pk_clause = ", ".join(pk)
    return f"""-- Auto-generated landing table for {table_name}
CREATE TABLE IF NOT EXISTS {table_name} (
{cols},
    CONSTRAINT pk_{table_name} PRIMARY KEY ({pk_clause})
);
"""


def render_upsert(table_name: str, columns: list[str]) -> str:
    pk = pk_columns(table_name)
    target_cols = columns + [
        "_cdc_record_key",
        "_cdc_source_table",
        "_cdc_updated_at",
        "_cdc_deleted",
        "_cdc_payload",
    ]
    select_cols = [cast_expr(table_name, "row_payload", col) + f" AS {col}" for col in columns]
    select_cols.extend(
        [
            "record_key AS _cdc_record_key",
            "source_table AS _cdc_source_table",
            "updated_at AS _cdc_updated_at",
            "COALESCE(LOWER(row_payload ->> '__deleted') = 'true', false) AS _cdc_deleted",
            "row_payload AS _cdc_payload",
        ]
    )
    updates = ",\n    ".join(
        [f"{col} = EXCLUDED.{col}" for col in target_cols if col not in pk]
    )
    pk_not_null = " AND ".join([f"(row_payload ->> '{col}') IS NOT NULL" for col in pk])
    pk_clause = ", ".join(pk)
    return f"""-- Auto-generated upsert from cdc_current_state into {table_name}
WITH normalized AS (
    SELECT
        record_key,
        source_table,
        updated_at,
        COALESCE(payload -> 'payload', payload) AS row_payload
    FROM cdc_current_state
    WHERE source_table = 'myerpplus.{table_name}'
)
INSERT INTO {table_name} (
    {", ".join(target_cols)}
)
SELECT
    {", ".join(target_cols)}
FROM (
    SELECT
        {",\n        ".join(select_cols)}
    FROM normalized
    WHERE {pk_not_null}
) AS prepared
ON CONFLICT ({pk_clause}) DO UPDATE
SET
    {updates};
"""


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    tables = load_tables()

    create_parts = []
    upsert_parts = []

    for table_name in TABLE_ORDER:
        cols = tables[table_name]
        create_parts.append(render_create(table_name, cols))
        upsert_parts.append(render_upsert(table_name, cols))

    (OUT_DIR / "pg_create_myerpplus_landing_tables.sql").write_text(
        "\n".join(create_parts)
    )
    (OUT_DIR / "pg_upsert_myerpplus_landing_tables_from_cdc.sql").write_text(
        "\n".join(upsert_parts)
    )
    print("rendered db/obt-physical-sql/pgsql-landing/pg_create_myerpplus_landing_tables.sql")
    print("rendered db/obt-physical-sql/pgsql-landing/pg_upsert_myerpplus_landing_tables_from_cdc.sql")


if __name__ == "__main__":
    main()
