#!/usr/bin/env python3
"""Render canonical OBT agent mapping JSON with live PostgreSQL row counts."""

from __future__ import annotations

import importlib.util
import json
from copy import deepcopy
from pathlib import Path


ROOT = Path("/home/rania/apps/sentient-factory")
PG_RUNNER_PATH = ROOT / "apps" / "myerpplus-db-mapping" / "scripts" / "run-pg-obt-table-sql.py"
OUT_PATH = ROOT / "apps" / "myerpplus-db-mapping" / "db" / "obt-agent-mapping.json"


TEMPLATE = {
    "artifact": "obt-agent-mapping",
    "version": 1,
    "purpose": "Machine-readable canonical OBT mapping for AI agents, including business grain, source families, safe join hints, physical targets, and rollout status.",
    "scope": "canonical obt portfolio plus active physical outputs that currently back the rollout",
    "status_labels": ["bootstrapped", "source-empty", "blocked", "queued"],
    "generated_from": [
        "docs/docs/08-obt/konsep-obt-m0-m12.md",
        "docs/docs/08-obt/semantic-to-physical-obt-mapping.md",
        "docs/docs/08-obt/obt-portfolio-rollout-status.md",
    ],
    "shared_output_contract": {
        "source_identity": [
            "source_module",
            "source_doc_type",
            "source_header_id",
            "source_detail_id",
            "source_allocation_id",
        ],
        "business_document": ["doc_no", "doc_date", "doc_status_code", "doc_status_name"],
        "organizational_scope": ["branch_code", "branch_name", "location_code", "location_name"],
        "party_scope": ["contact_id", "contact_code", "contact_name"],
        "item_scope": ["item_id", "item_code", "item_name", "uom_code"],
        "process_scope": ["upstream_doc_no", "downstream_doc_no", "lineage_path"],
        "measures": ["qty", "amount", "currency_code", "exchange_rate"],
        "governance": [
            "input_user_id",
            "input_user_name",
            "modified_user_id",
            "modified_user_name",
            "source_payload",
            "etl_batch_id",
        ],
    },
    "canonical_obts": [
        {
            "name": "obt_admin_access",
            "domain": "m0",
            "business_grain": "one row per user-role-menu access combination or activity event",
            "source_tables": ["m0_user", "m0_user_role", "m0_role", "m0_role_menu", "m0_menu", "m0_userlog"],
            "safe_join_path": [
                "m0_user_role.userid -> m0_user.userid",
                "m0_user_role.role -> m0_role.rkode",
                "m0_role.rkode -> m0_role_menu.rmrole",
                "m0_role_menu.rmmoduleid + rmmenuid -> m0_menu.mnmoduleid + mnid",
            ],
            "physical_targets": ["obt_admin_access"],
            "status": "bootstrapped",
            "notes": "Built from landed administrator baseline.",
        },
        {
            "name": "obt_menu_authorization",
            "domain": "m0",
            "business_grain": "one row per role-menu authorization relation",
            "source_tables": ["m0_role", "m0_role_menu", "m0_menu"],
            "safe_join_path": [
                "m0_role.rkode -> m0_role_menu.rmrole",
                "m0_role_menu.rmmoduleid + rmmenuid -> m0_menu.mnmoduleid + mnid",
            ],
            "physical_targets": ["obt_menu_authorization"],
            "status": "bootstrapped",
            "notes": "Role-menu authorization matrix.",
        },
        {
            "name": "obt_system_configuration",
            "domain": "m0",
            "business_grain": "one row per system numbering or configuration entry",
            "source_tables": ["m0_nomor"],
            "safe_join_path": ["m0_nomor.kodetabel is the stable numbering anchor"],
            "physical_targets": ["obt_system_configuration"],
            "status": "bootstrapped",
            "notes": "Numbering and system configuration baseline.",
        },
        {
            "name": "obt_queue_activity",
            "domain": "m0",
            "business_grain": "one row per queue activity or queue execution event",
            "source_tables": ["m0_queue", "m0_queue_log", "m0_queue_activity"],
            "safe_join_path": ["queue header -> queue log -> queue activity"],
            "physical_targets": ["obt_queue_activity"],
            "status": "blocked",
            "notes": "Source queue tables were not found in source MySQL.",
        },
        {
            "name": "dim_item",
            "domain": "m1",
            "business_grain": "one row per item master",
            "source_tables": ["m1_item"],
            "safe_join_path": ["anchor on m1_item only; enrich cautiously with master references"],
            "physical_targets": ["dim_item"],
            "status": "bootstrapped",
            "notes": "Conformed item dimension.",
        },
        {
            "name": "dim_item_warehouse_stock",
            "domain": "m1",
            "business_grain": "one row per item per warehouse stock position",
            "source_tables": ["m1_item_stock_warehouse", "m1_item", "m1_warehouse", "m1_location", "m1_branch"],
            "safe_join_path": [
                "m1_item_stock_warehouse.idbarang -> m1_item.bid",
                "m1_item_stock_warehouse.kgudang -> m1_warehouse.wkode",
                "m1_warehouse.wlokasi -> m1_location.lkode",
                "m1_location.lcabang -> m1_branch.bkode",
            ],
            "physical_targets": ["dim_item_warehouse_stock"],
            "status": "bootstrapped",
            "notes": "Warehouse-grain stock position for item availability checks.",
        },
        {
            "name": "dim_contact",
            "domain": "m1",
            "business_grain": "one row per contact master",
            "source_tables": ["m1_contact"],
            "safe_join_path": ["anchor on m1_contact only; enrich cautiously with category, terms, and salesman references"],
            "physical_targets": ["dim_contact"],
            "status": "bootstrapped",
            "notes": "Conformed contact dimension.",
        },
        {
            "name": "dim_branch",
            "domain": "m1",
            "business_grain": "one row per branch master",
            "source_tables": ["m1_branch"],
            "safe_join_path": ["anchor on m1_branch only"],
            "physical_targets": ["dim_branch"],
            "status": "bootstrapped",
            "notes": "Organizational branch dimension.",
        },
        {
            "name": "dim_location",
            "domain": "m1",
            "business_grain": "one row per location master",
            "source_tables": ["m1_location", "m1_branch"],
            "safe_join_path": ["m1_location.lcabang -> m1_branch.bkode"],
            "physical_targets": ["dim_location"],
            "status": "bootstrapped",
            "notes": "Organizational location dimension.",
        },
        {
            "name": "dim_warehouse",
            "domain": "m1",
            "business_grain": "one row per warehouse master",
            "source_tables": ["m1_warehouse", "m1_location", "m1_branch"],
            "safe_join_path": ["m1_warehouse.wlokasi -> m1_location.lkode", "m1_location.lcabang -> m1_branch.bkode"],
            "physical_targets": ["dim_warehouse"],
            "status": "bootstrapped",
            "notes": "Warehouse dimension for stock and movement drilldown.",
        },
        {
            "name": "dim_coa",
            "domain": "m1",
            "business_grain": "one row per chart of account",
            "source_tables": ["m1_coa"],
            "safe_join_path": ["anchor on m1_coa only"],
            "physical_targets": ["dim_coa"],
            "status": "bootstrapped",
            "notes": "Finance reference dimension.",
        },
        {
            "name": "dim_terms",
            "domain": "m1",
            "business_grain": "one row per payment terms master",
            "source_tables": ["m1_terms"],
            "safe_join_path": ["anchor on m1_terms only"],
            "physical_targets": ["dim_terms"],
            "status": "bootstrapped",
            "notes": "Payment terms dimension.",
        },
        {
            "name": "dim_division",
            "domain": "m1",
            "business_grain": "one row per division master",
            "source_tables": ["m1_division"],
            "safe_join_path": ["anchor on m1_division only"],
            "physical_targets": ["dim_division"],
            "status": "bootstrapped",
            "notes": "Organization division dimension.",
        },
        {
            "name": "dim_project",
            "domain": "m1",
            "business_grain": "one row per project master",
            "source_tables": ["m1_project", "m1_division"],
            "safe_join_path": ["m1_project.divisi -> m1_division.dkode"],
            "physical_targets": ["dim_project"],
            "status": "bootstrapped",
            "notes": "Project reference dimension.",
        },
        {
            "name": "dim_cost_center",
            "domain": "m1",
            "business_grain": "one row per cost center master",
            "source_tables": ["m1_cost_center", "m1_division", "m1_coa"],
            "safe_join_path": ["m1_cost_center.ccdivisi -> m1_division.dkode", "m1_cost_center.cccoa -> m1_coa.cnomor"],
            "physical_targets": ["dim_cost_center"],
            "status": "bootstrapped",
            "notes": "Cost center reference dimension.",
        },
        {
            "name": "dim_contact_terms",
            "domain": "m1",
            "business_grain": "one row per contact and invoice type terms override",
            "source_tables": ["m1_contact_terms"],
            "safe_join_path": ["m1_contact_terms.contact_id -> m1_contact.kid", "m1_contact_terms.terms_code -> m1_terms.tkode"],
            "physical_targets": ["dim_contact_terms"],
            "status": "source-empty",
            "notes": "Physical dimension exists but source is currently empty.",
        },
        {
            "name": "dim_contact_price",
            "domain": "m1",
            "business_grain": "one row per contact-item-uom price override",
            "source_tables": ["m1_contact_price", "m1_contact", "m1_item"],
            "safe_join_path": ["contact-price anchor -> contact master", "contact-price anchor -> item master"],
            "physical_targets": ["dim_contact_price"],
            "status": "source-empty",
            "notes": "Physical dimension exists but source is currently empty.",
        },
        {
            "name": "dim_contact_category",
            "domain": "m1",
            "business_grain": "one row per contact category master",
            "source_tables": ["m1_contact_category"],
            "safe_join_path": ["anchor on m1_contact_category only"],
            "physical_targets": ["dim_contact_category"],
            "status": "bootstrapped",
            "notes": "Contact category dimension.",
        },
        {
            "name": "dim_customer_category",
            "domain": "m1",
            "business_grain": "one row per customer category master",
            "source_tables": ["m1_customer_category"],
            "safe_join_path": ["anchor on m1_customer_category only"],
            "physical_targets": ["dim_customer_category"],
            "status": "bootstrapped",
            "notes": "Customer category dimension.",
        },
        {
            "name": "dim_supplier_category",
            "domain": "m1",
            "business_grain": "one row per supplier category master",
            "source_tables": ["m1_supplier_category"],
            "safe_join_path": ["anchor on m1_supplier_category only"],
            "physical_targets": ["dim_supplier_category"],
            "status": "bootstrapped",
            "notes": "Supplier category dimension.",
        },
        {
            "name": "dim_salesman_category",
            "domain": "m1",
            "business_grain": "one row per salesman category master",
            "source_tables": ["m1_salesman_category"],
            "safe_join_path": ["anchor on m1_salesman_category only"],
            "physical_targets": ["dim_salesman_category"],
            "status": "bootstrapped",
            "notes": "Salesman category dimension.",
        },
        {
            "name": "dim_item_category",
            "domain": "m1",
            "business_grain": "one row per item category master",
            "source_tables": ["m1_item_category"],
            "safe_join_path": ["anchor on m1_item_category only"],
            "physical_targets": ["dim_item_category"],
            "status": "bootstrapped",
            "notes": "Item category dimension.",
        },
        {
            "name": "dim_item_location",
            "domain": "m1",
            "business_grain": "one row per item location master",
            "source_tables": ["m1_item_location"],
            "safe_join_path": ["anchor on m1_item_location only"],
            "physical_targets": ["dim_item_location"],
            "status": "source-empty",
            "notes": "Physical dimension exists but source is currently empty.",
        },
        {
            "name": "dim_item_location_warehouse",
            "domain": "m1",
            "business_grain": "one row per item, warehouse, and item-location mapping",
            "source_tables": ["m1_item_location_warehouse", "m1_item_location", "m1_warehouse"],
            "safe_join_path": ["mapping -> item location", "mapping -> warehouse"],
            "physical_targets": ["dim_item_location_warehouse"],
            "status": "source-empty",
            "notes": "Physical dimension exists but source is currently empty.",
        },
        {
            "name": "dim_item_price",
            "domain": "m1",
            "business_grain": "one row per item and currency price",
            "source_tables": ["m1_item_price", "m1_item"],
            "safe_join_path": ["item-price anchor -> item master"],
            "physical_targets": ["dim_item_price"],
            "status": "source-empty",
            "notes": "Physical dimension exists but source is currently empty.",
        },
        {
            "name": "dim_item_supplier",
            "domain": "m1",
            "business_grain": "one row per item-supplier relation",
            "source_tables": ["m1_item_supplier", "m1_item", "m1_contact"],
            "safe_join_path": ["item-supplier anchor -> item master", "item-supplier anchor -> contact master"],
            "physical_targets": ["dim_item_supplier"],
            "status": "source-empty",
            "notes": "Physical dimension exists but source is currently empty.",
        },
        {
            "name": "dim_item_type",
            "domain": "m1",
            "business_grain": "one row per item type master",
            "source_tables": ["m1_item_type"],
            "safe_join_path": ["anchor on m1_item_type only"],
            "physical_targets": ["dim_item_type"],
            "status": "bootstrapped",
            "notes": "Item type dimension.",
        },
        {
            "name": "dim_unit",
            "domain": "m1",
            "business_grain": "one row per unit of measure master",
            "source_tables": ["m1_unit"],
            "safe_join_path": ["anchor on m1_unit only"],
            "physical_targets": ["dim_unit"],
            "status": "bootstrapped",
            "notes": "Unit of measure dimension.",
        },
        {
            "name": "dim_expedition",
            "domain": "m1",
            "business_grain": "one row per expedition master",
            "source_tables": ["m1_expedition"],
            "safe_join_path": ["anchor on m1_expedition only"],
            "physical_targets": ["dim_expedition"],
            "status": "bootstrapped",
            "notes": "Expedition reference dimension.",
        },
        {
            "name": "dim_tax",
            "domain": "m1",
            "business_grain": "one row per tax master",
            "source_tables": ["m1_tax"],
            "safe_join_path": ["anchor on m1_tax only"],
            "physical_targets": ["dim_tax"],
            "status": "bootstrapped",
            "notes": "Tax reference dimension.",
        },
        {
            "name": "dim_currency",
            "domain": "m1",
            "business_grain": "one row per currency master",
            "source_tables": ["m1_currency"],
            "safe_join_path": ["anchor on m1_currency only"],
            "physical_targets": ["dim_currency"],
            "status": "bootstrapped",
            "notes": "Currency reference dimension.",
        },
        {
            "name": "dim_bank",
            "domain": "m1",
            "business_grain": "one row per bank master",
            "source_tables": ["m1_bank"],
            "safe_join_path": ["anchor on m1_bank only"],
            "physical_targets": ["dim_bank"],
            "status": "bootstrapped",
            "notes": "Bank reference dimension.",
        },
        {
            "name": "dim_price_category",
            "domain": "m1",
            "business_grain": "one row per price category master",
            "source_tables": ["m1_price_category"],
            "safe_join_path": ["anchor on m1_price_category only"],
            "physical_targets": ["dim_price_category"],
            "status": "source-empty",
            "notes": "Physical dimension exists but source is currently empty.",
        },
        {
            "name": "dim_price_category_detail",
            "domain": "m1",
            "business_grain": "one row per price category detail relation",
            "source_tables": ["m1_price_category_detail", "m1_price_category", "m1_item"],
            "safe_join_path": ["detail -> price category header", "detail -> item master"],
            "physical_targets": ["dim_price_category_detail"],
            "status": "source-empty",
            "notes": "Physical dimension exists but source is currently empty.",
        },
        {
            "name": "dim_department",
            "domain": "m1",
            "business_grain": "one row per department master",
            "source_tables": ["m1_department"],
            "safe_join_path": ["anchor on m1_department only"],
            "physical_targets": ["dim_department"],
            "status": "bootstrapped",
            "notes": "Department dimension.",
        },
        {
            "name": "dim_subdepartment",
            "domain": "m1",
            "business_grain": "one row per subdepartment master",
            "source_tables": ["m1_subdepartment"],
            "safe_join_path": ["anchor on m1_subdepartment only"],
            "physical_targets": ["dim_subdepartment"],
            "status": "source-empty",
            "notes": "Physical dimension exists; source currently has no rows.",
        },
        {
            "name": "dim_section",
            "domain": "m1",
            "business_grain": "one row per section master",
            "source_tables": ["m1_section", "m1_department"],
            "safe_join_path": ["m1_section.department_code -> m1_department.department_code"],
            "physical_targets": ["dim_section"],
            "status": "bootstrapped",
            "notes": "Section dimension.",
        },
        {
            "name": "dim_country",
            "domain": "m1",
            "business_grain": "one row per country master",
            "source_tables": ["m1_country"],
            "safe_join_path": ["anchor on m1_country only"],
            "physical_targets": ["dim_country"],
            "status": "bootstrapped",
            "notes": "Country geography dimension.",
        },
        {
            "name": "dim_province",
            "domain": "m1",
            "business_grain": "one row per province master",
            "source_tables": ["m1_province", "m1_country"],
            "safe_join_path": ["m1_province.country_code -> m1_country.country_code"],
            "physical_targets": ["dim_province"],
            "status": "bootstrapped",
            "notes": "Province geography dimension.",
        },
        {
            "name": "dim_city",
            "domain": "m1",
            "business_grain": "one row per city master",
            "source_tables": ["m1_city", "m1_province", "m1_country"],
            "safe_join_path": ["m1_city.province_code -> m1_province.province_code", "m1_province.country_code -> m1_country.country_code"],
            "physical_targets": ["dim_city"],
            "status": "bootstrapped",
            "notes": "City geography dimension.",
        },
        {
            "name": "dim_class_product",
            "domain": "m1",
            "business_grain": "one row per product class master",
            "source_tables": ["m1_class_product"],
            "safe_join_path": ["anchor on m1_class_product only"],
            "physical_targets": ["dim_class_product"],
            "status": "bootstrapped",
            "notes": "Product classification dimension.",
        },
        {
            "name": "dim_material",
            "domain": "m1",
            "business_grain": "one row per material master",
            "source_tables": ["m1_material"],
            "safe_join_path": ["anchor on m1_material only"],
            "physical_targets": ["dim_material"],
            "status": "bootstrapped",
            "notes": "Material attribute dimension.",
        },
        {
            "name": "dim_merk",
            "domain": "m1",
            "business_grain": "one row per merk master",
            "source_tables": ["m1_merk"],
            "safe_join_path": ["anchor on m1_merk only"],
            "physical_targets": ["dim_merk"],
            "status": "bootstrapped",
            "notes": "Brand/merk dimension.",
        },
        {
            "name": "dim_model",
            "domain": "m1",
            "business_grain": "one row per model master",
            "source_tables": ["m1_model", "m1_merk"],
            "safe_join_path": ["m1_model.merk_code -> m1_merk.merk_code"],
            "physical_targets": ["dim_model"],
            "status": "bootstrapped",
            "notes": "Product model dimension.",
        },
        {
            "name": "dim_size",
            "domain": "m1",
            "business_grain": "one row per size master",
            "source_tables": ["m1_size"],
            "safe_join_path": ["anchor on m1_size only"],
            "physical_targets": ["dim_size"],
            "status": "bootstrapped",
            "notes": "Product size dimension.",
        },
        {
            "name": "dim_type_sa",
            "domain": "m1",
            "business_grain": "one row per service or adjustment type master",
            "source_tables": ["m1_type_sa"],
            "safe_join_path": ["anchor on m1_type_sa only"],
            "physical_targets": ["dim_type_sa"],
            "status": "bootstrapped",
            "notes": "Type-SA reference dimension.",
        },
        {
            "name": "dim_other_cost",
            "domain": "m1",
            "business_grain": "one row per other-cost master",
            "source_tables": ["m1_other_cost"],
            "safe_join_path": ["anchor on m1_other_cost only"],
            "physical_targets": ["dim_other_cost"],
            "status": "bootstrapped",
            "notes": "Other-cost reference dimension.",
        },
        {
            "name": "dim_item_permission",
            "domain": "m1",
            "business_grain": "one row per item permission profile",
            "source_tables": ["m1_item_permission"],
            "safe_join_path": ["anchor on m1_item_permission only"],
            "physical_targets": ["dim_item_permission"],
            "status": "bootstrapped",
            "notes": "Item permission profile dimension.",
        },
        {
            "name": "dim_transaction_note",
            "domain": "m1",
            "business_grain": "one row per transaction source and note code",
            "source_tables": ["m1_transaction_note"],
            "safe_join_path": ["anchor on m1_transaction_note only"],
            "physical_targets": ["dim_transaction_note"],
            "status": "bootstrapped",
            "notes": "Transaction note vocabulary dimension.",
        },
        {
            "name": "dim_transaction_note_detail",
            "domain": "m1",
            "business_grain": "one row per transaction source, note code, and note detail payload",
            "source_tables": ["m1_transaction_note_detail", "m1_transaction_note"],
            "safe_join_path": ["detail -> transaction note header"],
            "physical_targets": ["dim_transaction_note_detail"],
            "status": "source-empty",
            "notes": "Physical dimension exists; source currently has no rows.",
        },
        {
            "name": "dim_item_transaction",
            "domain": "m1",
            "business_grain": "one row per item transaction snapshot event",
            "source_tables": ["m1_item_transaction", "m1_item", "m1_warehouse", "m1_location", "m1_branch"],
            "safe_join_path": [
                "m1_item_transaction.idbarang -> m1_item.bid",
                "m1_item_transaction.kgudang -> m1_warehouse.wkode",
                "m1_warehouse.wlokasi -> m1_location.lkode",
                "m1_location.lcabang -> m1_branch.bkode"
            ],
            "physical_targets": ["dim_item_transaction"],
            "status": "bootstrapped",
            "notes": "Stock-card style item transaction snapshot dimension.",
        },
        {
            "name": "obt_finance_document",
            "domain": "m2",
            "business_grain": "one row per finance document header or finance document line",
            "source_tables": [
                "m2_cr", "m2_cr_detail", "m2_cd", "m2_cd_detail", "m2_rm", "m2_rm_detail",
                "m2_sm", "m2_sm_detail", "m2_cb", "m2_cb_detail", "m2_gj", "m2_gj_detail",
            ],
            "safe_join_path": ["header table -> detail table", "detail coa/contact references only when semantically required"],
            "physical_targets": ["obt_finance_document", "obt_finance_document_line"],
            "status": "bootstrapped",
            "notes": "Current baseline covers CR, CD, RM, SM, CB, and GJ families.",
        },
        {
            "name": "obt_finance_allocation",
            "domain": "m2",
            "business_grain": "one row per finance allocation or payment distribution",
            "source_tables": ["m2_rm_pay", "m2_sm_pay", "m2_cb_pay"],
            "safe_join_path": ["_pay table -> owning header table"],
            "physical_targets": ["obt_finance_allocation"],
            "status": "source-empty",
            "notes": "Allocation source families are currently empty in source MySQL.",
        },
        {
            "name": "obt_cash_bank_movement",
            "domain": "m2",
            "business_grain": "one row per posted cash or bank journal line",
            "source_tables": ["m2_transaction_journal"],
            "safe_join_path": [
                "m2_transaction_journal.tid is the stable journal line id",
                "m2_transaction_journal.tidtransaksi + tsumber identifies the owning finance document",
            ],
            "physical_targets": ["obt_cash_bank_movement"],
            "status": "bootstrapped",
            "notes": "Posted journal movement baseline built from transaction journal rows.",
        },
        {
            "name": "obt_finance_budget_realization",
            "domain": "m2",
            "business_grain": "one row per period, account, and budget-authority realization snapshot",
            "source_tables": ["m2_realization"],
            "safe_join_path": [
                "m2_realization.rtahun + rbulan + rnorek + rkodepa identifies a realization snapshot row",
            ],
            "physical_targets": ["obt_finance_budget_realization"],
            "status": "bootstrapped",
            "notes": "Budget realization baseline currently covers the base m2_realization aggregate table.",
        },
        {
            "name": "obt_profit_loss_line",
            "domain": "m2",
            "business_grain": "one row per journal line classified into profit and loss categories",
            "source_tables": ["m2_transaction_journal", "m1_coa"],
            "safe_join_path": [
                "m2_transaction_journal.tnorek -> dim_coa.account_code",
                "P&L classification uses dim_coa.account_type 11/12/13/14/15",
            ],
            "physical_targets": ["obt_profit_loss_line"],
            "status": "bootstrapped",
            "notes": "Profit and loss line baseline is derived from journal rows joined to COA classification.",
        },
        {
            "name": "obt_finance_document_history_event",
            "domain": "m2",
            "business_grain": "one row per historical snapshot of a finance document header",
            "source_tables": [
                "m2_cr_history", "m2_cd_history", "m2_rm_history",
                "m2_sm_history", "m2_cb_history", "m2_gj_history",
                "m2_aj_history", "m2_bd_history", "m2_jm_history",
                "m2_rg_history", "m2_rgc_history", "m2_sg_history", "m2_sgc_history",
            ],
            "safe_join_path": [
                "history header row is the anchor grain",
                "history header -> branch/location/contact references",
                "history header -> coa only when a stable account code exists on the header",
            ],
            "physical_targets": ["obt_finance_document_history_event"],
            "status": "bootstrapped",
            "notes": "Historical event stream for finance headers. Current populated baseline covers CR, CD, RM, SM, CB, and GJ; AJ, BD, JM, RG, RGC, SG, and SGC are wired but currently source-empty.",
        },
        {
            "name": "obt_finance_document_history_line_event",
            "domain": "m2",
            "business_grain": "one row per historical snapshot of a finance document detail line",
            "source_tables": [
                "m2_cr_detail_history", "m2_cd_detail_history", "m2_rm_detail_history",
                "m2_sm_detail_history", "m2_cb_detail_history", "m2_gj_detail_history",
                "m2_aj_detail_history", "m2_bd_detail_history", "m2_jm_detail_history",
                "m2_rg_detail_history", "m2_rgc_detail_history", "m2_sg_detail_history", "m2_sgc_detail_history",
            ],
            "safe_join_path": [
                "history detail row is the anchor grain",
                "history detail -> owning history header via idhistory",
                "detail and header -> coa, cost center, division, and project references",
            ],
            "physical_targets": ["obt_finance_document_history_line_event"],
            "status": "bootstrapped",
            "notes": "Historical event stream for finance detail lines. Current populated baseline covers CR, CD, RM, SM, CB, and GJ; AJ, BD, JM, RG, RGC, SG, and SGC are wired but currently source-empty.",
        },
        {
            "name": "obt_finance_payment_history_event",
            "domain": "m2",
            "business_grain": "one row per historical snapshot of a finance payment or giro allocation row",
            "source_tables": [
                "m2_rm_pay_history", "m2_sm_pay_history", "m2_cb_pay_history",
                "m2_rm_history", "m2_sm_history", "m2_cb_history",
            ],
            "safe_join_path": [
                "pay-history row is the anchor grain",
                "pay-history -> owning history header row",
                "header -> branch/location/contact; pay row -> bank reference",
            ],
            "physical_targets": ["obt_finance_payment_history_event"],
            "status": "source-empty",
            "notes": "Physical history payment event table exists and is ready, but current _pay_history source families are empty.",
        },
        {
            "name": "dim_finance_giro_list",
            "domain": "m2",
            "business_grain": "one row per giro register entry",
            "source_tables": ["m2_giro_list"],
            "safe_join_path": [
                "m2_giro_list.glsumber + glidtransaksi + glnogiro + glurutan is the natural giro row identity",
            ],
            "physical_targets": ["dim_finance_giro_list"],
            "status": "bootstrapped",
            "notes": "Auxiliary giro register dimension.",
        },
        {
            "name": "dim_finance_attachment",
            "domain": "m2",
            "business_grain": "one row per finance attachment file entry",
            "source_tables": ["m2_files"],
            "safe_join_path": [
                "m2_files.fsumber + fidtransaksi + fnamafile + finputtgl is the natural attachment identity",
            ],
            "physical_targets": ["dim_finance_attachment"],
            "status": "bootstrapped",
            "notes": "Auxiliary finance attachment dimension.",
        },
        {
            "name": "dim_finance_note",
            "domain": "m2",
            "business_grain": "one row per finance note entry",
            "source_tables": ["m2_notes"],
            "safe_join_path": [
                "m2_notes.nid is the stable finance note id",
            ],
            "physical_targets": ["dim_finance_note"],
            "status": "source-empty",
            "notes": "Auxiliary finance note dimension exists but source is currently empty.",
        },
        {
            "name": "obt_inventory_movement_line",
            "domain": "m3",
            "business_grain": "one row per stock movement line",
            "source_tables": ["m3_mr_detail", "m3_ts_detail", "m3_rs_detail", "m3_sp_detail", "m3_sa_detail"],
            "safe_join_path": [
                "anchor on movement detail row",
                "detail -> parent header",
                "detail/header -> m1 item and warehouse references",
            ],
            "physical_targets": ["obt_inventory_movement_line"],
            "status": "bootstrapped",
            "notes": "Current baseline covers TS_LINE, SP_LINE, and SA_LINE. MR and RS source families are currently empty.",
        },
        {
            "name": "obt_inventory_request_event",
            "domain": "m3",
            "business_grain": "one row per material request or receiving slip header event",
            "source_tables": ["m3_mr", "m3_rs", "m3_mr_history", "m3_rs_history"],
            "safe_join_path": [
                "request header row is the anchor grain",
                "header -> branch/location/warehouse references",
            ],
            "physical_targets": ["obt_inventory_request_event"],
            "status": "source-empty",
            "notes": "Physical event table exists for MR and RS families, but current source is empty.",
        },
        {
            "name": "obt_inventory_document_event",
            "domain": "m3",
            "business_grain": "one row per inventory document header event",
            "source_tables": ["m3_ts", "m3_sa", "m3_sp", "m3_ib", "m3_mr", "m3_rs", "m3_pa", "m3_rf", "m3_dc", "m3_rw"],
            "safe_join_path": [
                "inventory header row is the anchor grain",
                "header -> branch/location/warehouse references",
            ],
            "physical_targets": ["obt_inventory_document_event"],
            "status": "bootstrapped",
            "notes": "Current populated baseline covers TS, SA, SP, and IB. Other document families remain source-empty.",
        },
        {
            "name": "obt_inventory_document_history_event",
            "domain": "m3",
            "business_grain": "one row per inventory document history header snapshot",
            "source_tables": ["m3_ts_history", "m3_sa_history", "m3_sp_history", "m3_ib_history", "m3_mr_history", "m3_rs_history"],
            "safe_join_path": [
                "inventory history header row is the anchor grain",
                "history header -> branch/location/warehouse references",
            ],
            "physical_targets": ["obt_inventory_document_history_event"],
            "status": "bootstrapped",
            "notes": "Current populated baseline covers TS, SA, SP, and IB history headers.",
        },
        {
            "name": "obt_inventory_document_history_line_event",
            "domain": "m3",
            "business_grain": "one row per inventory document history detail snapshot",
            "source_tables": ["m3_ts_detail_history", "m3_sa_detail_history", "m3_sp_detail_history", "m3_ib_detail_history", "m3_mr_detail_history", "m3_rs_detail_history"],
            "safe_join_path": [
                "inventory history detail row is the anchor grain",
                "history detail -> history header -> item and warehouse references",
            ],
            "physical_targets": ["obt_inventory_document_history_line_event"],
            "status": "bootstrapped",
            "notes": "Current populated baseline covers TS, SA, SP, and IB history lines.",
        },
        {
            "name": "dim_inventory_price_setup",
            "domain": "m3",
            "business_grain": "one row per inventory price setup document or detail record",
            "source_tables": ["m3_pa", "m3_pa_detail"],
            "safe_join_path": [
                "m3_pa paid is the price setup header anchor",
                "m3_pa_detail.idpa -> m3_pa.paid",
            ],
            "physical_targets": ["dim_inventory_price_setup"],
            "status": "source-empty",
            "notes": "Physical dimension exists but current PA source family is empty.",
        },
        {
            "name": "dim_inventory_refuel_event",
            "domain": "m3",
            "business_grain": "one row per inventory refuel document or detail record",
            "source_tables": ["m3_rf", "m3_rf_detail"],
            "safe_join_path": [
                "m3_rf rfid is the refuel header anchor",
                "m3_rf_detail.idrf -> m3_rf.rfid",
            ],
            "physical_targets": ["dim_inventory_refuel_event"],
            "status": "source-empty",
            "notes": "Physical dimension exists but current RF source family is empty.",
        },
        {
            "name": "dim_inventory_daily_check",
            "domain": "m3",
            "business_grain": "one row per daily check document, detail, or check item",
            "source_tables": ["m3_dc", "m3_dc_detail", "m3_dc_check", "m3_dc_history", "m3_dc_detail_history", "m3_dc_check_history"],
            "safe_join_path": [
                "m3_dc dcid is the daily check header anchor",
                "detail and check rows link back through dc header identity",
            ],
            "physical_targets": ["dim_inventory_daily_check"],
            "status": "source-empty",
            "notes": "Physical dimension exists but current DC source family is empty.",
        },
        {
            "name": "dim_inventory_rw",
            "domain": "m3",
            "business_grain": "one row per inventory RW document",
            "source_tables": ["m3_rw"],
            "safe_join_path": ["m3_rw rwid is the stable RW document id"],
            "physical_targets": ["dim_inventory_rw"],
            "status": "source-empty",
            "notes": "Physical dimension exists but current RW source family is empty.",
        },
        {
            "name": "dim_inventory_note",
            "domain": "m3",
            "business_grain": "one row per inventory note entry",
            "source_tables": ["m3_notes"],
            "safe_join_path": ["m3_notes note id or source tuple is the natural note identity"],
            "physical_targets": ["dim_inventory_note"],
            "status": "source-empty",
            "notes": "Physical dimension exists but current source is empty.",
        },
        {
            "name": "dim_inventory_attachment",
            "domain": "m3",
            "business_grain": "one row per inventory attachment file entry",
            "source_tables": ["m3_files"],
            "safe_join_path": ["m3_files source and file tuple is the natural attachment identity"],
            "physical_targets": ["dim_inventory_attachment"],
            "status": "source-empty",
            "notes": "Physical dimension exists but current source is empty.",
        },
        {
            "name": "obt_purchase_line_flow",
            "domain": "m4",
            "business_grain": "one row per purchasing line traced across lifecycle documents",
            "source_tables": [
                "m4_pr_detail", "m4_rq_detail", "m4_bs_detail", "m4_po_detail",
                "m4_grn_detail", "m4_ri_detail", "m4_dnr_detail", "m4_prt_detail",
            ],
            "safe_join_path": [
                "detail anchor first",
                "walk upstream or downstream through explicit detail foreign keys",
                "lift to parent headers after line lineage is resolved",
            ],
            "physical_targets": ["obt_purchase_line_flow", "obt_purchase_document_line_event"],
            "status": "bootstrapped",
            "notes": "Current anchor is purchase line flow baseline.",
        },
        {
            "name": "obt_purchase_payment",
            "domain": "m4",
            "business_grain": "one row per payable target or vendor payment allocation",
            "source_tables": ["m4_ap", "m4_ap_pay", "m4_vpp_detail", "m4_vp_detail", "m4_ri"],
            "safe_join_path": [
                "m4_ap_pay.idap -> m4_ap.apid",
                "m4_vp_detail.idvp -> m4_vp.vpid",
                "m4_vpp_detail.idvpp -> m4_vpp.vppid",
                "polymorphic target: sumber AP/RI/PRT -> target header",
            ],
            "physical_targets": ["obt_purchase_payment"],
            "status": "bootstrapped",
            "notes": "Current baseline covers AP_PAY and VP_DETAIL. VPP_DETAIL source is currently empty.",
        },
        {
            "name": "dim_purchase_note",
            "domain": "m4",
            "business_grain": "one row per purchasing note entry",
            "source_tables": ["m4_notes"],
            "safe_join_path": ["m4_notes.nid is the stable purchasing note id"],
            "physical_targets": ["dim_purchase_note"],
            "status": "source-empty",
            "notes": "Purchasing note dimension is modeled explicitly for M4 note coverage.",
        },
        {
            "name": "dim_purchase_attachment",
            "domain": "m4",
            "business_grain": "one row per purchasing attachment entry",
            "source_tables": ["m4_files"],
            "safe_join_path": ["m4_files source and file tuple is the natural purchasing attachment identity"],
            "physical_targets": ["dim_purchase_attachment"],
            "status": "source-empty",
            "notes": "Purchasing attachment dimension is modeled explicitly for M4 attachment coverage.",
        },
        {
            "name": "obt_purchase_comparative_event",
            "domain": "m4",
            "business_grain": "one row per comparative-sheet supplier-item line",
            "source_tables": ["m4_cs", "m4_cs_detail"],
            "safe_join_path": ["m4_cs_detail.idcs -> m4_cs.csid", "m4_cs_detail.idbarang -> m1_item.bid"],
            "physical_targets": ["obt_purchase_comparative_event"],
            "status": "source-empty",
            "notes": "Comparative-sheet family coverage exists physically, but current landed source is empty.",
        },
        {
            "name": "obt_purchase_invoice_exchange_event",
            "domain": "m4",
            "business_grain": "one row per purchase invoice exchange detail relation",
            "source_tables": ["m4_pie", "m4_pie_detail"],
            "safe_join_path": ["m4_pie_detail.idpie -> m4_pie.pieid", "m4_pie_detail.idtransaksi follows sumber discriminator"],
            "physical_targets": ["obt_purchase_invoice_exchange_event"],
            "status": "source-empty",
            "notes": "Purchase invoice exchange family coverage exists physically, but current landed source is empty.",
        },
        {
            "name": "obt_sales_line_flow",
            "domain": "m5",
            "business_grain": "one row per sales line traced across quotation, order, delivery, invoice, and return",
            "source_tables": [
                "m5_sq_detail", "m5_so_detail", "m5_pi_detail", "m5_pl_detail", "m5_do_detail",
                "m5_dr_detail", "m5_si_detail", "m5_rnr_detail", "m5_sr_detail",
            ],
            "safe_join_path": [
                "detail anchor first",
                "walk across explicit line lineage ids",
                "lift to headers after line lineage is resolved",
            ],
            "physical_targets": ["obt_sales_line_flow", "obt_sales_order_line_flow"],
            "status": "bootstrapped",
            "notes": "Current anchor is sales invoice line flow baseline.",
        },
        {
            "name": "obt_sales_receivable",
            "domain": "m5",
            "business_grain": "one row per invoice, receivable target, or collection allocation",
            "source_tables": ["m5_si", "m5_ic_detail", "m5_pv_detail", "m5_as", "m5_rp"],
            "safe_join_path": [
                "m5_ic_detail.idic -> m5_ic.icid",
                "m5_pv_detail.idpv -> m5_pv.pvid",
                "m5_pv_detail.idicdetail -> m5_ic_detail.idicdetail",
                "polymorphic target: sumber SI/SR/AS/IP/RP -> target header",
            ],
            "physical_targets": ["obt_sales_receivable"],
            "status": "bootstrapped",
            "notes": "Current baseline covers IC_DETAIL and PV_DETAIL. PV_DETAIL source mix currently includes SI, SR, AS, IP, and CA.",
        },
        {
            "name": "dim_sales_note",
            "domain": "m5",
            "business_grain": "one row per sales note entry",
            "source_tables": ["m5_notes"],
            "safe_join_path": ["m5_notes.nid is the stable sales note id"],
            "physical_targets": ["dim_sales_note"],
            "status": "bootstrapped",
            "notes": "Sales note dimension is modeled explicitly for M5 note coverage.",
        },
        {
            "name": "dim_sales_attachment",
            "domain": "m5",
            "business_grain": "one row per sales attachment entry",
            "source_tables": ["m5_files"],
            "safe_join_path": ["m5_files source and file tuple is the natural sales attachment identity"],
            "physical_targets": ["dim_sales_attachment"],
            "status": "source-empty",
            "notes": "Sales attachment dimension is modeled explicitly for M5 attachment coverage.",
        },
        {
            "name": "obt_sales_invoice_exchange_event",
            "domain": "m5",
            "business_grain": "one row per sales invoice exchange detail relation",
            "source_tables": ["m5_sie", "m5_sie_detail"],
            "safe_join_path": ["m5_sie_detail.idsie -> m5_sie.sieid", "m5_sie_detail.idtransaksi follows sumber discriminator"],
            "physical_targets": ["obt_sales_invoice_exchange_event"],
            "status": "source-empty",
            "notes": "Sales invoice exchange family coverage exists physically, but current landed source is empty.",
        },
        {
            "name": "obt_sales_point_adjustment_event",
            "domain": "m5",
            "business_grain": "one row per sales point adjustment detail",
            "source_tables": ["m5_spa", "m5_spa_detail"],
            "safe_join_path": ["m5_spa_detail.idspa -> m5_spa.spaid", "m5_spa_detail.kontak -> m1_contact.kid"],
            "physical_targets": ["obt_sales_point_adjustment_event"],
            "status": "source-empty",
            "notes": "Sales point adjustment family coverage exists physically, but current landed source is empty.",
        },
        {
            "name": "obt_sales_closing_snapshot",
            "domain": "m5",
            "business_grain": "one row per closing-sales header snapshot",
            "source_tables": ["m5_cl"],
            "safe_join_path": ["m5_cl.clid is the stable closing snapshot id"],
            "physical_targets": ["obt_sales_closing_snapshot"],
            "status": "source-empty",
            "notes": "Sales closing family coverage exists physically, but current landed source is empty.",
        },
        {
            "name": "obt_sales_forecast_event",
            "domain": "m5",
            "business_grain": "one row per sales forecast detail line",
            "source_tables": ["m5_sf", "m5_sf_detail"],
            "safe_join_path": ["m5_sf_detail.idsf -> m5_sf.sfid", "m5_sf_detail.idbarang -> m1_item.bid"],
            "physical_targets": ["obt_sales_forecast_event"],
            "status": "bootstrapped",
            "notes": "Sales forecast family coverage is materialized from landed M5 forecast data.",
        },
        {
            "name": "obt_bom_route_snapshot",
            "domain": "m6",
            "business_grain": "one row per BOM input or output component snapshot",
            "source_tables": ["m6_bom", "m6_bom_in", "m6_bom_out"],
            "safe_join_path": ["m6_bom_in.idbom -> m6_bom.bomid", "m6_bom_out.idbom -> m6_bom.bomid"],
            "physical_targets": ["obt_bom_route_snapshot"],
            "status": "bootstrapped",
            "notes": "Canonical BOM structure snapshot is materialized from landed manufacturing BOM data.",
        },
        {
            "name": "obt_manufacturing_execution",
            "domain": "m6",
            "business_grain": "one row per work-order material line, output line, or activity line",
            "source_tables": ["m6_wo_in", "m6_wo_out", "m6_wo_activity", "m6_wo_route_card", "m6_wo"],
            "safe_join_path": ["anchor on material, output, or activity detail row", "detail -> work-order header"],
            "physical_targets": ["obt_manufacturing_execution"],
            "status": "bootstrapped",
            "notes": "Canonical manufacturing execution output is materialized from landed PD and work-order execution families.",
        },
        {
            "name": "dim_manufacturing_note",
            "domain": "m6",
            "business_grain": "one row per manufacturing note entry",
            "source_tables": ["m6_notes"],
            "safe_join_path": ["m6_notes.nid is the stable manufacturing note id"],
            "physical_targets": ["dim_manufacturing_note"],
            "status": "source-empty",
            "notes": "Manufacturing note dimension exists physically, but current source is empty.",
        },
        {
            "name": "dim_manufacturing_attachment",
            "domain": "m6",
            "business_grain": "one row per manufacturing attachment entry",
            "source_tables": ["m6_files"],
            "safe_join_path": ["m6_files.fsumber + fidtransaksi + fnamafile is the natural attachment identity"],
            "physical_targets": ["dim_manufacturing_attachment"],
            "status": "source-empty",
            "notes": "Manufacturing attachment dimension exists physically, but current source is empty.",
        },
        {
            "name": "obt_asset_lifecycle",
            "domain": "m7",
            "business_grain": "one row per asset event",
            "source_tables": ["m7_asset", "m7_ar_detail", "m7_aq_detail", "m7_ao_detail", "m7_ae_detail", "m7_at_detail", "m7_ag_detail", "m7_da_detail"],
            "safe_join_path": ["anchor on asset event detail row", "detail -> parent header -> asset master"],
            "physical_targets": ["obt_asset_lifecycle"],
            "status": "source-empty",
            "notes": "Canonical asset lifecycle output exists physically, but current landed source family is empty.",
        },
        {
            "name": "obt_asset_depreciation_event",
            "domain": "m7",
            "business_grain": "one row per asset depreciation detail event",
            "source_tables": ["m7_da", "m7_da_detail"],
            "safe_join_path": ["m7_da_detail.idda -> m7_da.daid"],
            "physical_targets": ["obt_asset_depreciation_event"],
            "status": "source-empty",
            "notes": "Canonical depreciation event output exists physically, but current landed source family is empty.",
        },
        {
            "name": "obt_asset_mutation",
            "domain": "m7",
            "business_grain": "one row per asset transfer or disposal event",
            "source_tables": ["m7_at", "m7_at_detail", "m7_ag", "m7_ag_detail"],
            "safe_join_path": ["m7_at_detail.idat -> m7_at.atid", "m7_ag_detail.idag -> m7_ag.agid"],
            "physical_targets": ["obt_asset_mutation"],
            "status": "source-empty",
            "notes": "Canonical mutation output exists physically, but current landed source family is empty.",
        },
        {
            "name": "dim_asset_note",
            "domain": "m7",
            "business_grain": "one row per asset note entry",
            "source_tables": ["m7_notes"],
            "safe_join_path": ["m7_notes.nid is the stable asset note id"],
            "physical_targets": ["dim_asset_note"],
            "status": "source-empty",
            "notes": "Asset note dimension exists physically, but current source is empty.",
        },
        {
            "name": "dim_asset_attachment",
            "domain": "m7",
            "business_grain": "one row per asset attachment entry",
            "source_tables": ["m7_files"],
            "safe_join_path": ["m7_files.fsumber + fidtransaksi + fnamafile is the natural attachment identity"],
            "physical_targets": ["dim_asset_attachment"],
            "status": "source-empty",
            "notes": "Asset attachment dimension exists physically, but current source is empty.",
        },
        {
            "name": "obt_metric_snapshot",
            "domain": "m8",
            "business_grain": "one row per metric, chart, content, or indicator snapshot",
            "source_tables": ["active m8 content and metric tables"],
            "safe_join_path": ["keep within m8 metric/content boundary unless ownership metadata is explicitly requested"],
            "physical_targets": ["obt_metric_snapshot"],
            "status": "queued",
            "notes": "Canonical definition exists, but current rollout has not materialized it yet.",
        },
        {
            "name": "obt_patient_visit_billing",
            "domain": "m11",
            "business_grain": "one row per patient visit line or billing line",
            "source_tables": ["m_11_kj", "m_11_ak_detail", "m_11_lu_detail", "m_11_lb_detail", "m_11_ro_detail", "m_11_kw_detail"],
            "safe_join_path": ["visit or billing detail anchor first", "detail -> visit-linked header"],
            "physical_targets": ["obt_patient_visit_billing"],
            "status": "queued",
            "notes": "Canonical definition exists, but current rollout has not materialized it yet.",
        },
        {
            "name": "obt_pos_transaction_line",
            "domain": "m12",
            "business_grain": "one row per POS cashier transaction item",
            "source_tables": ["m_12_st_detail", "m_12_st"],
            "safe_join_path": ["m_12_st_detail.idst -> m_12_st.stid"],
            "physical_targets": ["obt_pos_transaction_line"],
            "status": "source-empty",
            "notes": "Source m_12_st and m_12_st_detail are currently empty.",
        },
        {
            "name": "obt_pos_promo_application",
            "domain": "m12",
            "business_grain": "one row per promo or voucher application line",
            "source_tables": ["m_12_ai_detail", "m_12_ai_additional", "m_12_bi_detail", "m_12_bi_bonus", "m_12_ppv_detail", "m_12_ppv_pay", "m_12_pos_voucher_out"],
            "safe_join_path": [
                "promo or voucher application detail -> owning POS or voucher header",
                "formal voucher-to-invoice path only when explicit linkage exists",
            ],
            "physical_targets": ["obt_pos_promo_application"],
            "status": "queued",
            "notes": "Canonical definition exists, but current rollout has not materialized it yet.",
        },
    ],
    "active_physical_outputs": [
        {"name": "dim_finance_note", "domain": "m2", "canonical_parent": "dim_finance_note"},
        {"name": "dim_finance_attachment", "domain": "m2", "canonical_parent": "dim_finance_attachment"},
        {"name": "dim_finance_giro_list", "domain": "m2", "canonical_parent": "dim_finance_giro_list"},
        {"name": "obt_cash_bank_movement", "domain": "m2", "canonical_parent": "obt_cash_bank_movement"},
        {"name": "obt_profit_loss_line", "domain": "m2", "canonical_parent": "obt_profit_loss_line"},
        {"name": "dim_item_warehouse_stock", "domain": "m1", "canonical_parent": "dim_item_warehouse_stock"},
        {"name": "obt_finance_budget_realization", "domain": "m2", "canonical_parent": "obt_finance_budget_realization"},
        {"name": "obt_finance_payment_history_event", "domain": "m2", "canonical_parent": "obt_finance_payment_history_event"},
        {"name": "obt_finance_document_history_event", "domain": "m2", "canonical_parent": "obt_finance_document_history_event"},
        {"name": "obt_finance_document_history_line_event", "domain": "m2", "canonical_parent": "obt_finance_document_history_line_event"},
        {"name": "obt_inventory_request_event", "domain": "m3", "canonical_parent": "obt_inventory_request_event"},
        {"name": "dim_inventory_price_setup", "domain": "m3", "canonical_parent": "dim_inventory_price_setup"},
        {"name": "dim_inventory_refuel_event", "domain": "m3", "canonical_parent": "dim_inventory_refuel_event"},
        {"name": "dim_inventory_daily_check", "domain": "m3", "canonical_parent": "dim_inventory_daily_check"},
        {"name": "dim_inventory_rw", "domain": "m3", "canonical_parent": "dim_inventory_rw"},
        {"name": "dim_inventory_note", "domain": "m3", "canonical_parent": "dim_inventory_note"},
        {"name": "dim_inventory_attachment", "domain": "m3", "canonical_parent": "dim_inventory_attachment"},
        {"name": "obt_inventory_document_event", "domain": "m3", "canonical_parent": "obt_inventory_document_event"},
        {"name": "obt_inventory_document_history_event", "domain": "m3", "canonical_parent": "obt_inventory_document_history_event"},
        {"name": "obt_inventory_document_history_line_event", "domain": "m3", "canonical_parent": "obt_inventory_document_history_line_event"},
        {"name": "dim_manufacturing_note", "domain": "m6", "canonical_parent": "dim_manufacturing_note"},
        {"name": "dim_manufacturing_attachment", "domain": "m6", "canonical_parent": "dim_manufacturing_attachment"},
        {"name": "obt_bom_route_snapshot", "domain": "m6", "canonical_parent": "obt_bom_route_snapshot"},
        {"name": "obt_manufacturing_execution", "domain": "m6", "canonical_parent": "obt_manufacturing_execution"},
        {"name": "dim_asset_note", "domain": "m7", "canonical_parent": "dim_asset_note"},
        {"name": "dim_asset_attachment", "domain": "m7", "canonical_parent": "dim_asset_attachment"},
        {"name": "obt_asset_lifecycle", "domain": "m7", "canonical_parent": "obt_asset_lifecycle"},
        {"name": "obt_asset_depreciation_event", "domain": "m7", "canonical_parent": "obt_asset_depreciation_event"},
        {"name": "obt_asset_mutation", "domain": "m7", "canonical_parent": "obt_asset_mutation"},
        {"name": "obt_cash_disbursement_line_flow", "domain": "m2", "canonical_parent": "obt_finance_document"},
        {"name": "obt_cash_receipt_line_flow", "domain": "m2", "canonical_parent": "obt_finance_document"},
        {"name": "obt_receipt_money_line_flow", "domain": "m2", "canonical_parent": "obt_finance_document"},
        {"name": "obt_finance_document_line", "domain": "m2", "canonical_parent": "obt_finance_document"},
        {"name": "dim_purchase_note", "domain": "m4", "canonical_parent": "dim_purchase_note"},
        {"name": "dim_purchase_attachment", "domain": "m4", "canonical_parent": "dim_purchase_attachment"},
        {"name": "obt_purchase_comparative_event", "domain": "m4", "canonical_parent": "obt_purchase_comparative_event"},
        {"name": "obt_purchase_invoice_exchange_event", "domain": "m4", "canonical_parent": "obt_purchase_invoice_exchange_event"},
        {"name": "obt_purchase_document_line_event", "domain": "m4", "canonical_parent": "obt_purchase_line_flow"},
        {"name": "dim_sales_note", "domain": "m5", "canonical_parent": "dim_sales_note"},
        {"name": "dim_sales_attachment", "domain": "m5", "canonical_parent": "dim_sales_attachment"},
        {"name": "obt_sales_invoice_exchange_event", "domain": "m5", "canonical_parent": "obt_sales_invoice_exchange_event"},
        {"name": "obt_sales_point_adjustment_event", "domain": "m5", "canonical_parent": "obt_sales_point_adjustment_event"},
        {"name": "obt_sales_closing_snapshot", "domain": "m5", "canonical_parent": "obt_sales_closing_snapshot"},
        {"name": "obt_sales_forecast_event", "domain": "m5", "canonical_parent": "obt_sales_forecast_event"},
        {"name": "obt_sales_order_line_flow", "domain": "m5", "canonical_parent": "obt_sales_line_flow"},
        {"name": "obt_pos_to_sales", "domain": "m12", "canonical_parent": "obt_pos_promo_application"},
    ],
    "operational_notes": {
        "batch_state": "All currently populated outputs are baseline batch results loaded from MySQL into PostgreSQL landing and then materialized into OBT tables.",
        "cdc_state": "Transactional CDC is not yet live for m2, m4, m5, and m12 because source CDC events are not yet flowing into cdc_events and cdc_current_state.",
        "agent_usage_hint": [
            "Prefer canonical_obts for semantic intent classification.",
            "Use physical_targets to decide which physical PostgreSQL table to query.",
            "If status is source-empty or blocked, the agent should explain that the semantic target exists but is not currently populated.",
            "If a canonical OBT maps to multiple physical targets, choose the more specific output when the user intent is narrow and line- or event-oriented.",
        ],
    },
}


def load_pg_runner():
    spec = importlib.util.spec_from_file_location("pg_runner", PG_RUNNER_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load PostgreSQL runner from {PG_RUNNER_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def table_count(client, table_name: str) -> int:
    try:
        _, rows = client.query(f"SELECT COUNT(*) FROM public.{table_name}")
        return int(rows[0][0]) if rows else 0
    except RuntimeError as error:
        if "does not exist" in str(error):
            return 0
        raise


def canonical_row_count(client, entry: dict) -> int:
    targets = entry.get("physical_targets", [])
    if not targets:
        return 0
    return table_count(client, targets[0])


def build_document() -> dict:
    doc = deepcopy(TEMPLATE)
    pg_runner = load_pg_runner()
    pg_runner.load_env_files()
    client = pg_runner.SimplePgClient(pg_runner.resolve_database_url())
    client.connect()
    try:
        for entry in doc["canonical_obts"]:
            entry["current_row_count"] = canonical_row_count(client, entry)
        for entry in doc["active_physical_outputs"]:
            entry["current_row_count"] = table_count(client, entry["name"])
    finally:
        client.close()
    return doc


def main() -> int:
    document = build_document()
    OUT_PATH.write_text(json.dumps(document, indent=2) + "\n")
    print(f"rendered {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
