-- Auto-generated from vw_obt_purchase_line_flow.sql
-- Purpose:
--   create the OBT table structure directly in PostgreSQL
--   do not create a view on the source/client database
--   keep the table empty for the first controlled load step

CREATE TABLE IF NOT EXISTS obt_purchase_line_flow (
    source_module text,
    obt_name text,
    source_doc_type text,
    source_header_id bigint,
    source_detail_id bigint,
    doc_no text,
    doc_date timestamp without time zone,
    doc_status_code bigint,
    doc_status_name text,
    branch_code text,
    branch_name text,
    location_code text,
    location_name text,
    contact_id bigint,
    contact_code text,
    contact_name text,
    buyer_contact_id bigint,
    buyer_contact_code text,
    buyer_contact_name text,
    terms_code text,
    terms_name text,
    item_id bigint,
    item_code text,
    item_name text,
    line_no bigint,
    uom_code text,
    qty numeric(20,6),
    qty_base numeric(20,6),
    qty_realized numeric(20,6),
    qty_realized_base numeric(20,6),
    unit_price numeric(20,6),
    discount_percent numeric(20,6),
    discount_amount numeric(20,6),
    amount numeric(20,6),
    currency_code text,
    exchange_rate numeric(20,6),
    input_user_id bigint,
    input_user_name text,
    modified_user_id bigint,
    modified_user_name text,
    grn_doc_count bigint,
    grn_doc_nos text,
    grn_status_names text,
    first_grn_date timestamp without time zone,
    last_grn_date timestamp without time zone,
    qty_grn numeric(20,6),
    qty_grn_base numeric(20,6),
    qty_realized_grn numeric(20,6),
    qty_realized_grn_base numeric(20,6),
    amount_grn numeric(20,6),
    ri_doc_count bigint,
    ri_doc_nos text,
    ri_status_names text,
    source_grn_doc_nos text,
    first_ri_date timestamp without time zone,
    last_ri_date timestamp without time zone,
    qty_ri numeric(20,6),
    qty_ri_base numeric(20,6),
    qty_realized_ri numeric(20,6),
    qty_realized_ri_base numeric(20,6),
    amount_ri numeric(20,6),
    dnr_doc_count bigint,
    dnr_doc_nos text,
    dnr_status_names text,
    source_ri_doc_nos text,
    first_dnr_date timestamp without time zone,
    last_dnr_date timestamp without time zone,
    qty_dnr numeric(20,6),
    qty_dnr_base numeric(20,6),
    qty_realized_dnr numeric(20,6),
    qty_realized_dnr_base numeric(20,6),
    amount_dnr numeric(20,6),
    prt_doc_count bigint,
    prt_doc_nos text,
    prt_status_names text,
    source_dnr_doc_nos text,
    first_prt_date timestamp without time zone,
    last_prt_date timestamp without time zone,
    qty_prt numeric(20,6),
    qty_prt_base numeric(20,6),
    amount_prt numeric(20,6),
    upstream_doc_no text,
    downstream_doc_no text,
    lineage_path text,
    etl_loaded_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_obt_purchase_line_flow_source_detail
    ON obt_purchase_line_flow (source_module, source_detail_id);

CREATE INDEX IF NOT EXISTS ix_obt_purchase_line_flow_doc_date
    ON obt_purchase_line_flow (doc_date);
