CREATE TABLE IF NOT EXISTS public.obt_sales_forecast_event (
    obt_id bigserial PRIMARY KEY,
    obt_name text NOT NULL,
    source_module text,
    source_doc_type text,
    source_header_id text,
    source_detail_id text,
    source_allocation_id text,
    doc_no text,
    doc_date timestamptz,
    doc_status_code text,
    doc_status_name text,
    branch_code text,
    branch_name text,
    location_code text,
    location_name text,
    contact_id text,
    contact_code text,
    contact_name text,
    item_id text,
    item_code text,
    item_name text,
    uom_code text,
    upstream_doc_no text,
    downstream_doc_no text,
    lineage_path text,
    qty numeric(20,6),
    amount numeric(20,6),
    currency_code text,
    exchange_rate numeric(20,6),
    input_user_id text,
    input_user_name text,
    modified_user_id text,
    modified_user_name text,
    source_payload jsonb,
    etl_batch_id text,
    etl_loaded_at timestamptz NOT NULL DEFAULT now(),
    etl_updated_at timestamptz NOT NULL DEFAULT now()
);
