CREATE TABLE IF NOT EXISTS public.dim_finance_giro_list (
    source_code text NOT NULL,
    source_header_id text NOT NULL,
    giro_no text NOT NULL,
    line_no bigint NOT NULL,
    doc_no text,
    contact_id text,
    contact_code text,
    contact_name text,
    bank_account_code text,
    giro_account_code text,
    giro_type bigint,
    bank_name text,
    bank_account_no text,
    currency_code text,
    exchange_rate numeric(20,6),
    amount numeric(20,6),
    amount_foreign numeric(20,6),
    due_date timestamptz,
    cleared_date timestamptz,
    status_code bigint,
    previous_status_code bigint,
    source_payload jsonb,
    etl_batch_id text,
    etl_loaded_at timestamptz NOT NULL DEFAULT now(),
    etl_updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (source_code, source_header_id, giro_no, line_no)
);
