-- System metric registry.
-- Purpose:
--   1. Menjadi registry metric teknis/internal yang dipakai backend engine.
--   2. Menjadi mapping target untuk business metric dan advanced alert builder.
--   3. Menyimpan level metric yang lebih dekat ke OBT / query resolver / aggregation engine.
--
-- Design choice:
--   1. MVP cukup 1 tabel.
--   2. Fokus pada metric registry, bukan full expression engine.

CREATE OR REPLACE FUNCTION public.set_row_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.metric_system_registry (
  system_metric_id bigserial PRIMARY KEY,
  metric_key varchar(160) NOT NULL,
  label varchar(220) NOT NULL,
  module_key varchar(60) NOT NULL,
  description text,
  source_table varchar(160),
  source_type varchar(40) NOT NULL DEFAULT 'obt_metric',
  resolver_key varchar(160),
  sql_template text,
  aggregation_type varchar(40),
  value_type varchar(40) NOT NULL DEFAULT 'number',
  supported_dimensions jsonb NOT NULL DEFAULT '[]'::jsonb,
  supported_filters jsonb NOT NULL DEFAULT '[]'::jsonb,
  default_filters jsonb NOT NULL DEFAULT '{}'::jsonb,
  tags jsonb NOT NULL DEFAULT '[]'::jsonb,
  owner_name varchar(120),
  review_status varchar(30) NOT NULL DEFAULT 'draft',
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_by text,
  updated_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT uq_metric_system_registry_key UNIQUE (metric_key),
  CONSTRAINT chk_metric_system_source_type CHECK (
    source_type IN ('obt_metric', 'semantic_metric', 'saved_query', 'ai_query', 'manual_rule_source')
  ),
  CONSTRAINT chk_metric_system_value_type CHECK (
    value_type IN ('number', 'currency', 'percent', 'count', 'days', 'duration', 'ratio', 'boolean', 'text')
  ),
  CONSTRAINT chk_metric_system_aggregation_type CHECK (
    aggregation_type IS NULL OR aggregation_type IN ('sum', 'avg', 'count', 'count_distinct', 'min', 'max', 'ratio', 'custom')
  ),
  CONSTRAINT chk_metric_system_review_status CHECK (
    review_status IN ('draft', 'reviewed', 'approved', 'archived')
  )
);

CREATE INDEX IF NOT EXISTS idx_metric_system_registry_module
  ON public.metric_system_registry (module_key, is_active, sort_order)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_metric_system_registry_source
  ON public.metric_system_registry (source_type, source_table)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_metric_system_registry_tags
  ON public.metric_system_registry USING gin (tags);

CREATE INDEX IF NOT EXISTS idx_metric_system_registry_dimensions
  ON public.metric_system_registry USING gin (supported_dimensions);

DROP TRIGGER IF EXISTS trg_metric_system_registry_updated_at ON public.metric_system_registry;
CREATE TRIGGER trg_metric_system_registry_updated_at
BEFORE UPDATE ON public.metric_system_registry
FOR EACH ROW
EXECUTE FUNCTION public.set_row_updated_at();

INSERT INTO public.metric_system_registry (
  metric_key,
  label,
  module_key,
  description,
  source_table,
  source_type,
  resolver_key,
  aggregation_type,
  value_type,
  supported_dimensions,
  supported_filters,
  default_filters,
  tags,
  owner_name,
  review_status,
  is_active,
  sort_order,
  created_by,
  updated_by
)
VALUES
  (
    'sales_invoice_amount_daily_sum',
    'Sales Invoice Amount Daily Sum',
    'sales',
    'Total invoice amount per day from sales receivable OBT.',
    'public.obt_sales_receivable',
    'obt_metric',
    'sales_invoice_amount_daily_sum',
    'sum',
    'currency',
    '["branch","customer","salesman","invoice_date"]'::jsonb,
    '["period","branch","customer","salesman"]'::jsonb,
    '{"period":"today"}'::jsonb,
    '["sales","invoice","amount","daily"]'::jsonb,
    'Sales Analyst',
    'approved',
    true,
    10,
    'seed',
    'seed'
  ),
  (
    'sales_target_vs_actual_pct',
    'Sales Target Vs Actual Percentage',
    'sales',
    'Actual sales dibanding target sales pada grain bulanan.',
    'public.obt_sales_forecast_event',
    'obt_metric',
    'sales_target_vs_actual_pct',
    'ratio',
    'percent',
    '["branch","salesman","period"]'::jsonb,
    '["period","branch","salesman"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["sales","target","achievement"]'::jsonb,
    'Sales Manager',
    'reviewed',
    true,
    20,
    'seed',
    'seed'
  ),
  (
    'receivable_overdue_amount_30_plus',
    'Receivable Overdue Amount 30+ Days',
    'finance',
    'Outstanding receivable amount for invoices overdue more than 30 days.',
    'public.obt_sales_receivable',
    'obt_metric',
    'receivable_overdue_amount_30_plus',
    'sum',
    'currency',
    '["branch","customer","salesman","aging_bucket"]'::jsonb,
    '["period","branch","customer","salesman","aging_bucket"]'::jsonb,
    '{"aging_bucket":"30_plus"}'::jsonb,
    '["finance","receivable","overdue"]'::jsonb,
    'Finance Lead',
    'approved',
    true,
    30,
    'seed',
    'seed'
  ),
  (
    'cash_in_vs_cash_out_total',
    'Cash In Vs Cash Out Total',
    'finance',
    'Net and gross cash in and cash out across selected period.',
    'public.obt_cash_receipt_line_flow',
    'obt_metric',
    'cash_in_vs_cash_out_total',
    'custom',
    'currency',
    '["branch","bank_account","period"]'::jsonb,
    '["period","branch","bank_account"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","cashflow"]'::jsonb,
    'Finance Manager',
    'reviewed',
    true,
    40,
    'seed',
    'seed'
  ),
  (
    'receivable_overdue_customer_count',
    'Receivable Overdue Customer Count',
    'finance',
    'Distinct customer count with overdue receivable exposure.',
    'public.obt_sales_receivable',
    'obt_metric',
    'receivable_overdue_customer_count',
    'count_distinct',
    'count',
    '["branch","customer","salesman","aging_bucket"]'::jsonb,
    '["period","branch","customer","salesman","aging_bucket"]'::jsonb,
    '{"aging_bucket":"30_plus"}'::jsonb,
    '["finance","receivable","overdue","customer"]'::jsonb,
    'Finance Lead',
    'approved',
    true,
    41,
    'seed',
    'seed'
  ),
  (
    'receivable_overdue_invoice_count',
    'Receivable Overdue Invoice Count',
    'finance',
    'Count overdue receivable invoices that passed due date.',
    'public.obt_sales_receivable',
    'obt_metric',
    'receivable_overdue_invoice_count',
    'count',
    'count',
    '["branch","customer","salesman","aging_bucket"]'::jsonb,
    '["period","branch","customer","salesman","aging_bucket"]'::jsonb,
    '{"aging_bucket":"30_plus"}'::jsonb,
    '["finance","receivable","overdue","invoice"]'::jsonb,
    'Finance Lead',
    'approved',
    true,
    42,
    'seed',
    'seed'
  ),
  (
    'cash_receipt_total_amount',
    'Cash Receipt Total Amount',
    'finance',
    'Total incoming cash amount from cash receipt flow.',
    'public.obt_cash_receipt_line_flow',
    'obt_metric',
    'cash_receipt_total_amount',
    'sum',
    'currency',
    '["branch","location","contact","cash_account_code","cost_center_code","project_code"]'::jsonb,
    '["period","branch","location","contact","cash_account_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","cash","receipt","inflow"]'::jsonb,
    'Finance Manager',
    'approved',
    true,
    43,
    'seed',
    'seed'
  ),
  (
    'cash_disbursement_total_amount',
    'Cash Disbursement Total Amount',
    'finance',
    'Total outgoing cash amount from cash disbursement flow.',
    'public.obt_cash_disbursement_line_flow',
    'obt_metric',
    'cash_disbursement_total_amount',
    'sum',
    'currency',
    '["branch","location","contact","cash_account_code","cost_center_code","project_code"]'::jsonb,
    '["period","branch","location","contact","cash_account_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","cash","disbursement","outflow"]'::jsonb,
    'Finance Manager',
    'approved',
    true,
    44,
    'seed',
    'seed'
  ),
  (
    'receipt_money_total_amount',
    'Receipt Money Total Amount',
    'finance',
    'Total amount from receipt money flow.',
    'public.obt_receipt_money_line_flow',
    'obt_metric',
    'receipt_money_total_amount',
    'sum',
    'currency',
    '["branch","location","contact","cash_account_code","payment_method_code","cost_center_code","project_code"]'::jsonb,
    '["period","branch","location","contact","payment_method_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","receipt_money","collection"]'::jsonb,
    'Finance Lead',
    'reviewed',
    true,
    45,
    'seed',
    'seed'
  ),
  (
    'receipt_money_transaction_count',
    'Receipt Money Transaction Count',
    'finance',
    'Count of receipt money detail transactions.',
    'public.obt_receipt_money_line_flow',
    'obt_metric',
    'receipt_money_transaction_count',
    'count',
    'count',
    '["branch","location","contact","payment_method_code"]'::jsonb,
    '["period","branch","location","contact","payment_method_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","receipt_money","count"]'::jsonb,
    'Finance Lead',
    'reviewed',
    true,
    46,
    'seed',
    'seed'
  ),
  (
    'finance_payment_history_total_amount',
    'Finance Payment History Total Amount',
    'finance',
    'Total payment amount recorded in finance payment history events.',
    'public.obt_finance_payment_history_event',
    'obt_metric',
    'finance_payment_history_total_amount',
    'sum',
    'currency',
    '["branch","location","contact","payment_method_code","bank_code","giro_type_code"]'::jsonb,
    '["period","branch","location","contact","payment_method_code","bank_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","payment_history","amount"]'::jsonb,
    'Finance Manager',
    'reviewed',
    true,
    47,
    'seed',
    'seed'
  ),
  (
    'finance_payment_history_event_count',
    'Finance Payment History Event Count',
    'finance',
    'Count of finance payment history events.',
    'public.obt_finance_payment_history_event',
    'obt_metric',
    'finance_payment_history_event_count',
    'count',
    'count',
    '["branch","location","contact","payment_method_code","bank_code","giro_type_code"]'::jsonb,
    '["period","branch","location","contact","payment_method_code","bank_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","payment_history","count"]'::jsonb,
    'Finance Manager',
    'reviewed',
    true,
    48,
    'seed',
    'seed'
  ),
  (
    'finance_budget_realization_total_amount',
    'Finance Budget Realization Total Amount',
    'finance',
    'Total realized amount from finance budget realization OBT.',
    'public.obt_finance_budget_realization',
    'obt_metric',
    'finance_budget_realization_total_amount',
    'sum',
    'currency',
    '["branch","location","contact","item_code"]'::jsonb,
    '["period","branch","location","contact","item_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","budget","realization"]'::jsonb,
    'Finance Controller',
    'approved',
    true,
    49,
    'seed',
    'seed'
  ),
  (
    'finance_budget_variance_amount',
    'Finance Budget Variance Amount',
    'finance',
    'Variance amount between budget and realization at finance planning grain.',
    'public.obt_finance_budget_realization',
    'obt_metric',
    'finance_budget_variance_amount',
    'custom',
    'currency',
    '["branch","location","contact","item_code"]'::jsonb,
    '["period","branch","location","contact","item_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","budget","variance"]'::jsonb,
    'Finance Controller',
    'reviewed',
    true,
    50,
    'seed',
    'seed'
  ),
  (
    'finance_open_document_count',
    'Finance Open Document Count',
    'finance',
    'Count of finance documents in open or active status.',
    'public.obt_finance_document',
    'obt_metric',
    'finance_open_document_count',
    'count',
    'count',
    '["branch","location","contact","source_doc_type","doc_status_name"]'::jsonb,
    '["period","branch","location","contact","source_doc_type","doc_status_name"]'::jsonb,
    '{"doc_status_name":"open"}'::jsonb,
    '["finance","document","open"]'::jsonb,
    'Finance Operations',
    'approved',
    true,
    51,
    'seed',
    'seed'
  ),
  (
    'bank_position_total_amount',
    'Bank Position Total Amount',
    'finance',
    'Total finance document amount grouped by bank/cash account position.',
    'public.obt_finance_document',
    'obt_metric',
    'bank_position_total_amount',
    'sum',
    'currency',
    '["branch","location","contact","source_doc_type","bank_code","bank_name"]'::jsonb,
    '["period","branch","location","source_doc_type","bank_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","bank","position"]'::jsonb,
    'Treasury Lead',
    'reviewed',
    true,
    52,
    'seed',
    'seed'
  ),
  (
    'finance_allocation_total_amount',
    'Finance Allocation Total Amount',
    'finance',
    'Total amount allocated through finance allocation OBT.',
    'public.obt_finance_allocation',
    'obt_metric',
    'finance_allocation_total_amount',
    'sum',
    'currency',
    '["branch","location","contact","cost_center_code","project_code"]'::jsonb,
    '["period","branch","location","contact","cost_center_code","project_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","allocation"]'::jsonb,
    'Finance Controller',
    'reviewed',
    true,
    53,
    'seed',
    'seed'
  ),
  (
    'accounting_journal_line_amount_total',
    'Accounting Journal Line Amount Total',
    'accounting',
    'Total nominal across accounting journal lines.',
    'public.obt_finance_document_line',
    'obt_metric',
    'accounting_journal_line_amount_total',
    'sum',
    'currency',
    '["branch","location","contact","source_doc_type","line_account_code"]'::jsonb,
    '["period","branch","location","contact","source_doc_type","line_account_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["accounting","journal","line","amount"]'::jsonb,
    'Accounting Lead',
    'approved',
    true,
    54,
    'seed',
    'seed'
  ),
  (
    'accounting_journal_line_count',
    'Accounting Journal Line Count',
    'accounting',
    'Count accounting journal lines.',
    'public.obt_finance_document_line',
    'obt_metric',
    'accounting_journal_line_count',
    'count',
    'count',
    '["branch","location","contact","source_doc_type","line_account_code"]'::jsonb,
    '["period","branch","location","contact","source_doc_type","line_account_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["accounting","journal","line","count"]'::jsonb,
    'Accounting Lead',
    'approved',
    true,
    55,
    'seed',
    'seed'
  ),
  (
    'accounting_distinct_account_count',
    'Accounting Distinct Account Count',
    'accounting',
    'Distinct COA account count used by accounting journal lines.',
    'public.obt_finance_document_line',
    'obt_metric',
    'accounting_distinct_account_count',
    'count_distinct',
    'count',
    '["branch","location","source_doc_type","line_account_code"]'::jsonb,
    '["period","branch","location","source_doc_type","line_account_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["accounting","coa","account","count"]'::jsonb,
    'Accounting Lead',
    'reviewed',
    true,
    56,
    'seed',
    'seed'
  ),
  (
    'accounting_document_lifecycle_event_count',
    'Accounting Document Lifecycle Event Count',
    'accounting',
    'Count lifecycle events recorded for accounting documents.',
    'public.obt_finance_document_history_event',
    'obt_metric',
    'accounting_document_lifecycle_event_count',
    'count',
    'count',
    '["branch","location","contact","source_doc_type","doc_status_code","previous_status_code"]'::jsonb,
    '["period","branch","location","contact","source_doc_type","doc_status_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["accounting","document","lifecycle","event"]'::jsonb,
    'Accounting Operations',
    'reviewed',
    true,
    57,
    'seed',
    'seed'
  ),
  (
    'accounting_document_revision_total',
    'Accounting Document Revision Total',
    'accounting',
    'Total revision count recorded on accounting document lifecycle events.',
    'public.obt_finance_document_history_event',
    'obt_metric',
    'accounting_document_revision_total',
    'sum',
    'count',
    '["branch","location","contact","source_doc_type","doc_status_code"]'::jsonb,
    '["period","branch","location","contact","source_doc_type"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["accounting","document","revision"]'::jsonb,
    'Accounting Operations',
    'reviewed',
    true,
    58,
    'seed',
    'seed'
  ),
  (
    'accounting_active_coa_count',
    'Accounting Active COA Count',
    'accounting',
    'Count active chart of accounts records.',
    'public.dim_coa',
    'obt_metric',
    'accounting_active_coa_count',
    'count',
    'count',
    '["branch","location","account_type","parent_account_code"]'::jsonb,
    '["branch","location","account_type","parent_account_code"]'::jsonb,
    '{"is_active":1}'::jsonb,
    '["accounting","coa","active"]'::jsonb,
    'Accounting Master Data',
    'approved',
    true,
    59,
    'seed',
    'seed'
  ),
  (
    'accounting_revenue_total',
    'Accounting Revenue Total',
    'accounting',
    'Total revenue based on profit and loss journal classification.',
    'public.obt_profit_loss_line',
    'obt_metric',
    'accounting_revenue_total',
    'sum',
    'currency',
    '["branch","location","contact","account_code","pnl_category","fiscal_year","fiscal_month"]'::jsonb,
    '["period","branch","location","contact","account_code","fiscal_year","fiscal_month"]'::jsonb,
    '{"pnl_category":"REVENUE"}'::jsonb,
    '["accounting","profit_loss","revenue"]'::jsonb,
    'Accounting Controller',
    'approved',
    true,
    60,
    'seed',
    'seed'
  ),
  (
    'accounting_cogs_total',
    'Accounting COGS Total',
    'accounting',
    'Total cost of goods sold based on profit and loss journal classification.',
    'public.obt_profit_loss_line',
    'obt_metric',
    'accounting_cogs_total',
    'sum',
    'currency',
    '["branch","location","contact","account_code","pnl_category","fiscal_year","fiscal_month"]'::jsonb,
    '["period","branch","location","contact","account_code","fiscal_year","fiscal_month"]'::jsonb,
    '{"pnl_category":"COGS"}'::jsonb,
    '["accounting","profit_loss","cogs"]'::jsonb,
    'Accounting Controller',
    'approved',
    true,
    61,
    'seed',
    'seed'
  ),
  (
    'accounting_operating_expense_total',
    'Accounting Operating Expense Total',
    'accounting',
    'Total operating expense based on profit and loss journal classification.',
    'public.obt_profit_loss_line',
    'obt_metric',
    'accounting_operating_expense_total',
    'sum',
    'currency',
    '["branch","location","contact","account_code","pnl_category","fiscal_year","fiscal_month"]'::jsonb,
    '["period","branch","location","contact","account_code","fiscal_year","fiscal_month"]'::jsonb,
    '{"pnl_category":"OPERATING_EXPENSE"}'::jsonb,
    '["accounting","profit_loss","opex"]'::jsonb,
    'Accounting Controller',
    'approved',
    true,
    62,
    'seed',
    'seed'
  ),
  (
    'accounting_net_profit_total',
    'Accounting Net Profit Total',
    'accounting',
    'Net profit derived from profit and loss journal classification.',
    'public.obt_profit_loss_line',
    'obt_metric',
    'accounting_net_profit_total',
    'custom',
    'currency',
    '["branch","location","contact","fiscal_year","fiscal_month"]'::jsonb,
    '["period","branch","location","contact","fiscal_year","fiscal_month"]'::jsonb,
    '{"pnl_scope":"net_profit"}'::jsonb,
    '["accounting","profit_loss","net_profit"]'::jsonb,
    'Accounting Controller',
    'approved',
    true,
    63,
    'seed',
    'seed'
  ),
  (
    'inventory_stock_on_hand_total',
    'Inventory Stock On Hand Total',
    'inventory',
    'Total current stock quantity across item and warehouse rows.',
    'public.dim_item_warehouse_stock',
    'obt_metric',
    'inventory_stock_on_hand_total',
    'sum',
    'number',
    '["branch","location","warehouse_code","item_code","item_category_code","supplier_id"]'::jsonb,
    '["branch","location","warehouse_code","item_code","item_category_code","supplier_id"]'::jsonb,
    '{"include_zero":false}'::jsonb,
    '["inventory","stock","on_hand"]'::jsonb,
    'Inventory Control',
    'approved',
    true,
    64,
    'seed',
    'seed'
  ),
  (
    'inventory_item_with_stock_count',
    'Inventory Item With Stock Count',
    'inventory',
    'Count item-warehouse rows with positive stock balance.',
    'public.dim_item_warehouse_stock',
    'obt_metric',
    'inventory_item_with_stock_count',
    'count',
    'count',
    '["branch","location","warehouse_code","item_code","item_category_code","supplier_id"]'::jsonb,
    '["branch","location","warehouse_code","item_code","item_category_code","supplier_id"]'::jsonb,
    '{"stock_gt":0}'::jsonb,
    '["inventory","stock","positive","count"]'::jsonb,
    'Inventory Control',
    'reviewed',
    true,
    65,
    'seed',
    'seed'
  ),
  (
    'inventory_stock_value_total',
    'Inventory Stock Value Total',
    'inventory',
    'Estimated stock value based on current stock multiplied by average cost.',
    'public.dim_item_warehouse_stock',
    'obt_metric',
    'inventory_stock_value_total',
    'custom',
    'currency',
    '["branch","location","warehouse_code","item_code","item_category_code","supplier_id"]'::jsonb,
    '["branch","location","warehouse_code","item_code","item_category_code","supplier_id"]'::jsonb,
    '{"formula":"current_stock*average_cost","include_zero":false}'::jsonb,
    '["inventory","stock","value"]'::jsonb,
    'Inventory Control',
    'approved',
    true,
    66,
    'seed',
    'seed'
  ),
  (
    'inventory_active_item_stock_count',
    'Inventory Active Item Stock Count',
    'inventory',
    'Count active item-warehouse stock rows.',
    'public.dim_item_warehouse_stock',
    'obt_metric',
    'inventory_active_item_stock_count',
    'count',
    'count',
    '["branch","location","warehouse_code","item_code","item_category_code"]'::jsonb,
    '["branch","location","warehouse_code","item_code","item_category_code"]'::jsonb,
    '{"is_active":1}'::jsonb,
    '["inventory","stock","active"]'::jsonb,
    'Inventory Master Data',
    'reviewed',
    true,
    67,
    'seed',
    'seed'
  ),
  (
    'inventory_document_history_event_count',
    'Inventory Document History Event Count',
    'inventory',
    'Count lifecycle events across inventory document history.',
    'public.obt_inventory_document_history_event',
    'obt_metric',
    'inventory_document_history_event_count',
    'count',
    'count',
    '["branch_code","location_code","warehouse_from_code","warehouse_to_code","source_doc_type","doc_status_code"]'::jsonb,
    '["period","branch_code","location_code","source_doc_type","doc_status_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["inventory","document","history","event"]'::jsonb,
    'Inventory Operations',
    'reviewed',
    true,
    68,
    'seed',
    'seed'
  ),
  (
    'inventory_transfer_event_count',
    'Inventory Transfer Event Count',
    'inventory',
    'Count inventory document history events for transfer stock documents.',
    'public.obt_inventory_document_history_event',
    'obt_metric',
    'inventory_transfer_event_count',
    'count',
    'count',
    '["branch_code","location_code","warehouse_from_code","warehouse_transit_code","warehouse_to_code","doc_status_code"]'::jsonb,
    '["period","branch_code","location_code","warehouse_from_code","warehouse_to_code","doc_status_code"]'::jsonb,
    '{"period":"current_month","source_doc_type":"TS"}'::jsonb,
    '["inventory","transfer","event"]'::jsonb,
    'Inventory Operations',
    'approved',
    true,
    69,
    'seed',
    'seed'
  ),
  (
    'inventory_receive_event_count',
    'Inventory Receive Event Count',
    'inventory',
    'Count inventory document history events for receive stock documents.',
    'public.obt_inventory_document_history_event',
    'obt_metric',
    'inventory_receive_event_count',
    'count',
    'count',
    '["branch_code","location_code","warehouse_from_code","warehouse_to_code","doc_status_code"]'::jsonb,
    '["period","branch_code","location_code","warehouse_to_code","doc_status_code"]'::jsonb,
    '{"period":"current_month","source_doc_type":"RS"}'::jsonb,
    '["inventory","receive","event"]'::jsonb,
    'Inventory Operations',
    'approved',
    true,
    70,
    'seed',
    'seed'
  ),
  (
    'inventory_daily_check_count',
    'Inventory Daily Check Count',
    'inventory',
    'Count inventory daily check records.',
    'public.dim_inventory_daily_check',
    'obt_metric',
    'inventory_daily_check_count',
    'count',
    'count',
    '["branch_code","location_code","shift_code","item_id","check_category_id","check_status"]'::jsonb,
    '["period","branch_code","location_code","shift_code","check_category_id","check_status"]'::jsonb,
    '{"period":"current_day"}'::jsonb,
    '["inventory","daily_check","count"]'::jsonb,
    'Inventory Supervisor',
    'reviewed',
    true,
    71,
    'seed',
    'seed'
  ),
  (
    'inventory_daily_check_issue_count',
    'Inventory Daily Check Issue Count',
    'inventory',
    'Count inventory daily check rows flagged as issue or failed status.',
    'public.dim_inventory_daily_check',
    'obt_metric',
    'inventory_daily_check_issue_count',
    'count',
    'count',
    '["branch_code","location_code","shift_code","item_id","check_category_id","check_status"]'::jsonb,
    '["period","branch_code","location_code","shift_code","check_category_id","check_status"]'::jsonb,
    '{"period":"current_day","issue_only":true}'::jsonb,
    '["inventory","daily_check","issue"]'::jsonb,
    'Inventory Supervisor',
    'approved',
    true,
    72,
    'seed',
    'seed'
  ),
  (
    'inventory_inactive_item_stock_count',
    'Inventory Inactive Item Stock Count',
    'inventory',
    'Count inactive item-warehouse stock rows still present in stock dimension.',
    'public.dim_item_warehouse_stock',
    'obt_metric',
    'inventory_inactive_item_stock_count',
    'count',
    'count',
    '["branch","location","warehouse_code","item_code","item_category_code"]'::jsonb,
    '["branch","location","warehouse_code","item_code","item_category_code"]'::jsonb,
    '{"is_active":0}'::jsonb,
    '["inventory","stock","inactive"]'::jsonb,
    'Inventory Master Data',
    'reviewed',
    true,
    73,
    'seed',
    'seed'
  ),
  (
    'negative_stock_row_count',
    'Negative Stock Row Count',
    'warehouse',
    'Count rows where item warehouse balance is below zero.',
    'public.dim_item_warehouse_stock',
    'obt_metric',
    'negative_stock_row_count',
    'count',
    'count',
    '["warehouse","item","category"]'::jsonb,
    '["warehouse","item","category"]'::jsonb,
    '{}'::jsonb,
    '["warehouse","negative_stock"]'::jsonb,
    'Warehouse Supervisor',
    'approved',
    true,
    50,
    'seed',
    'seed'
  ),
  (
    'inventory_aging_value_90_plus',
    'Inventory Aging Value 90+ Days',
    'warehouse',
    'Inventory value where stock age is greater than 90 days.',
    'public.obt_inventory_document_event',
    'obt_metric',
    'inventory_aging_value_90_plus',
    'sum',
    'currency',
    '["warehouse","item","category","aging_bucket"]'::jsonb,
    '["warehouse","item","category","aging_bucket"]'::jsonb,
    '{"aging_bucket":"90_plus"}'::jsonb,
    '["warehouse","aging","inventory"]'::jsonb,
    'Inventory Analyst',
    'reviewed',
    true,
    60,
    'seed',
    'seed'
  ),
  (
    'purchase_price_variance_pct',
    'Purchase Price Variance Percentage',
    'purchasing',
    'Percentage variance of purchase price versus baseline.',
    'public.obt_purchase_comparative_event',
    'obt_metric',
    'purchase_price_variance_pct',
    'ratio',
    'percent',
    '["supplier","item","branch"]'::jsonb,
    '["supplier","item","branch","period"]'::jsonb,
    '{"baseline":"previous_purchase"}'::jsonb,
    '["purchasing","price","variance"]'::jsonb,
    'Procurement Lead',
    'reviewed',
    true,
    70,
    'seed',
    'seed'
  ),
  (
    'purchase_order_open_total_amount',
    'Purchase Order Open Total Amount',
    'purchasing',
    'Total open amount across purchase orders not yet completed.',
    'public.obt_purchase_document_line_event',
    'obt_metric',
    'purchase_order_open_total_amount',
    'sum',
    'currency',
    '["supplier","branch","buyer"]'::jsonb,
    '["supplier","branch","buyer","period"]'::jsonb,
    '{"status":"open"}'::jsonb,
    '["purchasing","po","open"]'::jsonb,
    'Procurement Analyst',
    'approved',
    true,
    80,
    'seed',
    'seed'
  )
ON CONFLICT (metric_key) DO UPDATE SET
  label = EXCLUDED.label,
  module_key = EXCLUDED.module_key,
  description = EXCLUDED.description,
  source_table = EXCLUDED.source_table,
  source_type = EXCLUDED.source_type,
  resolver_key = EXCLUDED.resolver_key,
  aggregation_type = EXCLUDED.aggregation_type,
  value_type = EXCLUDED.value_type,
  supported_dimensions = EXCLUDED.supported_dimensions,
  supported_filters = EXCLUDED.supported_filters,
  default_filters = EXCLUDED.default_filters,
  tags = EXCLUDED.tags,
  owner_name = EXCLUDED.owner_name,
  review_status = EXCLUDED.review_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order,
  updated_by = EXCLUDED.updated_by,
  updated_at = now(),
  deleted_at = NULL;
