-- Auto-generated from vw_obt_pos_to_sales.sql
-- Purpose:
--   create the OBT table structure directly in PostgreSQL
--   do not create a view on the source/client database
--   keep the table empty for the first controlled load step

CREATE TABLE IF NOT EXISTS obt_pos_to_sales (
    source_module text,
    obt_name text,
    source_doc_type text,
    source_header_id bigint,
    source_detail_id bigint,
    doc_no text,
    doc_date timestamp without time zone,
    doc_status_code bigint,
    doc_status_name text,
    branch_code text,
    branch_name text,
    location_code text,
    location_name text,
    contact_id bigint,
    contact_code text,
    contact_name text,
    item_id bigint,
    item_code text,
    item_name text,
    uom_code text,
    qty numeric(20,6),
    amount numeric(20,6),
    currency_code text,
    exchange_rate numeric(20,6),
    voucher_source text,
    pos_category_code text,
    pos_category_name text,
    voucher_issue_date timestamp without time zone,
    voucher_expiry_date timestamp without time zone,
    voucher_paid_off_date timestamp without time zone,
    voucher_master_closed bigint,
    voucher_usage_closed bigint,
    voucher_nominal_amount numeric(20,6),
    voucher_nominal_amount_foreign numeric(20,6),
    voucher_paid_amount numeric(20,6),
    voucher_paid_amount_foreign numeric(20,6),
    voucher_remaining_amount numeric(20,6),
    voucher_remaining_amount_foreign numeric(20,6),
    voucher_usage_amount numeric(20,6),
    voucher_usage_amount_foreign numeric(20,6),
    sales_invoice_id bigint,
    invoice_no text,
    invoice_date timestamp without time zone,
    invoice_status_code bigint,
    invoice_status_name text,
    invoice_branch_code text,
    invoice_branch_name text,
    invoice_location_code text,
    invoice_location_name text,
    sales_contact_customer_id bigint,
    sales_contact_customer_code text,
    sales_contact_customer_name text,
    sales_contact_id bigint,
    sales_contact_code text,
    sales_contact_name text,
    terms_code text,
    terms_name text,
    invoice_total numeric(20,6),
    invoice_currency_code text,
    invoice_exchange_rate numeric(20,6),
    input_user_id bigint,
    input_user_name text,
    modified_user_id bigint,
    modified_user_name text,
    invoice_line_count bigint,
    invoice_detail_subtotal numeric(20,6),
    invoice_qty numeric(20,6),
    invoice_qty_base numeric(20,6),
    downstream_doc_no text,
    lineage_path text,
    etl_loaded_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_obt_pos_to_sales_source_detail
    ON obt_pos_to_sales (source_module, source_detail_id);

CREATE INDEX IF NOT EXISTS ix_obt_pos_to_sales_doc_date
    ON obt_pos_to_sales (doc_date);
