-- Semantic metric registry.
-- Purpose:
--   1. Menjadi catalog resmi semantic metric yang direferensikan oleh semantic_ref.
--   2. Menjembatani business metric dengan semantic concept yang lebih stabil dan reusable.
--   3. Menyimpan canonical key untuk menangani alias / variasi naming yang sudah terlanjur dipakai.

CREATE OR REPLACE FUNCTION public.set_row_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.metric_semantic_registry (
  semantic_id bigserial PRIMARY KEY,
  semantic_key varchar(160) NOT NULL,
  canonical_semantic_key varchar(160),
  label varchar(220) NOT NULL,
  short_label varchar(120),
  module_key varchar(60) NOT NULL,
  entity_key varchar(120),
  measure_key varchar(120),
  definition text,
  calculation_summary text,
  value_type varchar(40) NOT NULL DEFAULT 'number',
  unit varchar(40),
  supported_dimensions jsonb NOT NULL DEFAULT '[]'::jsonb,
  default_filters jsonb NOT NULL DEFAULT '{}'::jsonb,
  tags jsonb NOT NULL DEFAULT '[]'::jsonb,
  owner_name varchar(120),
  review_status varchar(30) NOT NULL DEFAULT 'draft',
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by text,
  updated_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT uq_metric_semantic_registry_key UNIQUE (semantic_key),
  CONSTRAINT chk_metric_semantic_registry_value_type CHECK (
    value_type IN ('number', 'currency', 'percent', 'count', 'days', 'duration', 'ratio', 'boolean', 'text')
  ),
  CONSTRAINT chk_metric_semantic_registry_review_status CHECK (
    review_status IN ('draft', 'reviewed', 'approved', 'archived')
  )
);

CREATE INDEX IF NOT EXISTS idx_metric_semantic_registry_module
  ON public.metric_semantic_registry (module_key, is_active, sort_order)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_metric_semantic_registry_canonical
  ON public.metric_semantic_registry (canonical_semantic_key, is_active)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_metric_semantic_registry_tags
  ON public.metric_semantic_registry USING gin (tags);

CREATE INDEX IF NOT EXISTS idx_metric_semantic_registry_dimensions
  ON public.metric_semantic_registry USING gin (supported_dimensions);

DROP TRIGGER IF EXISTS trg_metric_semantic_registry_updated_at ON public.metric_semantic_registry;
CREATE TRIGGER trg_metric_semantic_registry_updated_at
BEFORE UPDATE ON public.metric_semantic_registry
FOR EACH ROW
EXECUTE FUNCTION public.set_row_updated_at();

INSERT INTO public.metric_semantic_registry (
  semantic_key,
  canonical_semantic_key,
  label,
  short_label,
  module_key,
  entity_key,
  measure_key,
  definition,
  calculation_summary,
  value_type,
  unit,
  supported_dimensions,
  default_filters,
  tags,
  owner_name,
  review_status,
  is_active,
  sort_order,
  metadata,
  created_by,
  updated_by
)
VALUES
  (
    'daily_sales_revenue',
    'daily_sales_revenue',
    'Daily Sales Revenue',
    'Sales Revenue',
    'sales',
    'sales_invoice',
    'revenue_amount',
    'Total revenue from valid sales invoices at daily grain.',
    'Sum invoice amount from valid sales invoices grouped by day.',
    'currency',
    'idr',
    '["branch","customer","salesman"]'::jsonb,
    '{"period":"today"}'::jsonb,
    '["sales","revenue","daily"]'::jsonb,
    'Sales Analyst',
    'approved',
    true,
    10,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'sales_daily_revenue',
    'daily_sales_revenue',
    'Sales Daily Revenue',
    'Sales Revenue',
    'sales',
    'sales_invoice',
    'revenue_amount',
    'Alias semantic key for daily sales revenue concept.',
    'Same concept as daily_sales_revenue; retained for compatibility.',
    'currency',
    'idr',
    '["branch","customer","salesman"]'::jsonb,
    '{"period":"today"}'::jsonb,
    '["sales","revenue","daily","alias"]'::jsonb,
    'Sales Analyst',
    'reviewed',
    true,
    20,
    '{"alias":true}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'monthly_sales_achievement',
    'monthly_sales_achievement',
    'Monthly Sales Achievement',
    'Achievement',
    'sales',
    'sales_target',
    'achievement_pct',
    'Sales performance versus target at monthly grain.',
    'Actual sales divided by target sales for the selected month.',
    'percent',
    'percent',
    '["branch","salesman"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["sales","target","achievement"]'::jsonb,
    'Sales Manager',
    'approved',
    true,
    30,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'sales_monthly_achievement',
    'monthly_sales_achievement',
    'Sales Monthly Achievement',
    'Achievement',
    'sales',
    'sales_target',
    'achievement_pct',
    'Alias semantic key for monthly sales achievement.',
    'Same concept as monthly_sales_achievement; retained for compatibility.',
    'percent',
    'percent',
    '["branch","salesman"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["sales","target","achievement","alias"]'::jsonb,
    'Sales Manager',
    'reviewed',
    true,
    40,
    '{"alias":true}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'overdue_receivable_total',
    'overdue_receivable_total',
    'Overdue Receivable Total',
    'Overdue AR',
    'finance',
    'receivable',
    'overdue_amount',
    'Total outstanding receivable that has passed due date.',
    'Sum outstanding receivable where due date is exceeded.',
    'currency',
    'idr',
    '["branch","customer","salesman","aging_bucket"]'::jsonb,
    '{"aging_bucket":"30_plus"}'::jsonb,
    '["finance","receivable","overdue"]'::jsonb,
    'Finance Lead',
    'approved',
    true,
    50,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'receivable_overdue_total',
    'overdue_receivable_total',
    'Receivable Overdue Total',
    'Overdue AR',
    'finance',
    'receivable',
    'overdue_amount',
    'Alias semantic key for overdue receivable total.',
    'Same concept as overdue_receivable_total; retained for compatibility.',
    'currency',
    'idr',
    '["branch","customer","salesman","aging_bucket"]'::jsonb,
    '{"aging_bucket":"30_plus"}'::jsonb,
    '["finance","receivable","overdue","alias"]'::jsonb,
    'Finance Lead',
    'reviewed',
    true,
    60,
    '{"alias":true}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'cash_in_vs_cash_out',
    'cash_in_vs_cash_out',
    'Cash In vs Cash Out',
    'Cashflow',
    'finance',
    'cashflow',
    'net_cash_variance',
    'Comparison between incoming and outgoing cash for a selected period.',
    'Net cash inflow versus cash outflow over the chosen period.',
    'currency',
    'idr',
    '["branch","bank_account"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","cashflow"]'::jsonb,
    'Finance Manager',
    'approved',
    true,
    70,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'overdue_receivable_customer_count',
    'overdue_receivable_customer_count',
    'Overdue Receivable Customer Count',
    'Overdue Customers',
    'finance',
    'receivable',
    'overdue_customer_count',
    'Distinct customer count with overdue receivable balance.',
    'Count distinct customers that still carry overdue receivable balance.',
    'count',
    'customer',
    '["branch","customer","salesman","aging_bucket"]'::jsonb,
    '{"aging_bucket":"30_plus"}'::jsonb,
    '["finance","receivable","overdue","customer"]'::jsonb,
    'Finance Lead',
    'approved',
    true,
    71,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'overdue_receivable_invoice_count',
    'overdue_receivable_invoice_count',
    'Overdue Receivable Invoice Count',
    'Overdue Invoices',
    'finance',
    'receivable',
    'overdue_invoice_count',
    'Count of overdue receivable invoices.',
    'Count invoices whose due date has passed and remain outstanding.',
    'count',
    'invoice',
    '["branch","customer","salesman","aging_bucket"]'::jsonb,
    '{"aging_bucket":"30_plus"}'::jsonb,
    '["finance","receivable","overdue","invoice"]'::jsonb,
    'Finance Lead',
    'approved',
    true,
    72,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'cash_in_total',
    'cash_in_total',
    'Cash In Total',
    'Cash In',
    'finance',
    'cashflow',
    'cash_in_amount',
    'Total cash inflow for the selected period.',
    'Sum incoming cash receipt amount for the selected period.',
    'currency',
    'idr',
    '["branch","location","contact","bank_account","cost_center","project"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","cashflow","cash_in"]'::jsonb,
    'Finance Manager',
    'approved',
    true,
    73,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'cash_out_total',
    'cash_out_total',
    'Cash Out Total',
    'Cash Out',
    'finance',
    'cashflow',
    'cash_out_amount',
    'Total cash outflow for the selected period.',
    'Sum outgoing cash disbursement amount for the selected period.',
    'currency',
    'idr',
    '["branch","location","contact","bank_account","cost_center","project"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","cashflow","cash_out"]'::jsonb,
    'Finance Manager',
    'approved',
    true,
    74,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'net_cash_movement',
    'net_cash_movement',
    'Net Cash Movement',
    'Net Cash',
    'finance',
    'cashflow',
    'net_cash_amount',
    'Net cash movement from cash in minus cash out.',
    'Cash inflow less cash outflow over the selected period.',
    'currency',
    'idr',
    '["branch","location","bank_account"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","cashflow","net"]'::jsonb,
    'Finance Manager',
    'reviewed',
    true,
    75,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'receipt_money_total',
    'receipt_money_total',
    'Receipt Money Total',
    'Receipt Money',
    'finance',
    'receipt_money',
    'receipt_money_amount',
    'Total receipt money collected in the selected period.',
    'Sum receipt money line flow amount for the selected period.',
    'currency',
    'idr',
    '["branch","location","contact","payment_method","bank_account"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","receipt_money"]'::jsonb,
    'Finance Lead',
    'reviewed',
    true,
    76,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'receipt_money_transaction_count',
    'receipt_money_transaction_count',
    'Receipt Money Transaction Count',
    'Receipt Count',
    'finance',
    'receipt_money',
    'receipt_money_transaction_count',
    'Count of receipt money transactions in the selected period.',
    'Count receipt money detail rows for the selected period.',
    'count',
    'transaction',
    '["branch","location","contact","payment_method"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","receipt_money","count"]'::jsonb,
    'Finance Lead',
    'reviewed',
    true,
    77,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'payment_history_total',
    'payment_history_total',
    'Payment History Total',
    'Payment Total',
    'finance',
    'payment_history',
    'payment_amount',
    'Total payment amount recorded in finance payment history.',
    'Sum payment history event amount for the selected period.',
    'currency',
    'idr',
    '["branch","location","contact","payment_method","bank"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","payment_history","amount"]'::jsonb,
    'Finance Manager',
    'reviewed',
    true,
    78,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'payment_history_event_count',
    'payment_history_event_count',
    'Payment History Event Count',
    'Payment Events',
    'finance',
    'payment_history',
    'payment_event_count',
    'Count of payment history events.',
    'Count payment history records over the selected period.',
    'count',
    'event',
    '["branch","location","contact","payment_method","bank"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","payment_history","count"]'::jsonb,
    'Finance Manager',
    'reviewed',
    true,
    79,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'budget_realization_total',
    'budget_realization_total',
    'Budget Realization Total',
    'Realization',
    'finance',
    'budget_realization',
    'realization_amount',
    'Total realized finance amount for the selected period.',
    'Sum realized budget amount recorded in finance budget realization OBT.',
    'currency',
    'idr',
    '["branch","location","contact","item_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","budget","realization"]'::jsonb,
    'Finance Controller',
    'approved',
    true,
    80,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'budget_vs_realization_variance',
    'budget_vs_realization_variance',
    'Budget vs Realization Variance',
    'Budget Variance',
    'finance',
    'budget_realization',
    'variance_amount',
    'Variance between finance budget and realization.',
    'Derived difference between planned budget and realized amount.',
    'currency',
    'idr',
    '["branch","location","contact","item_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","budget","variance"]'::jsonb,
    'Finance Controller',
    'reviewed',
    true,
    81,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'finance_open_document_count',
    'finance_open_document_count',
    'Finance Open Document Count',
    'Open Documents',
    'finance',
    'finance_document',
    'open_document_count',
    'Count of finance documents still open.',
    'Count finance documents whose workflow or payment status remains open.',
    'count',
    'document',
    '["branch","location","contact","source_doc_type","doc_status_name"]'::jsonb,
    '{"doc_status_name":"open"}'::jsonb,
    '["finance","document","open"]'::jsonb,
    'Finance Operations',
    'approved',
    true,
    82,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'bank_position_total',
    'bank_position_total',
    'Bank Position Total',
    'Bank Position',
    'finance',
    'bank_position',
    'bank_position_amount',
    'Total finance amount grouped by bank position.',
    'Sum finance document amount associated with bank or cash position.',
    'currency',
    'idr',
    '["branch","location","bank_account","source_doc_type"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","bank","position"]'::jsonb,
    'Treasury Lead',
    'reviewed',
    true,
    83,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'allocation_total',
    'allocation_total',
    'Allocation Total',
    'Allocation',
    'finance',
    'allocation',
    'allocation_amount',
    'Total allocated amount across finance allocation records.',
    'Sum allocation amount across cost center and project dimensions.',
    'currency',
    'idr',
    '["branch","location","contact","cost_center","project"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","allocation"]'::jsonb,
    'Finance Controller',
    'reviewed',
    true,
    84,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'accounting_journal_line_amount_total',
    'accounting_journal_line_amount_total',
    'Accounting Journal Line Amount Total',
    'Journal Amount',
    'accounting',
    'journal_line',
    'journal_line_amount',
    'Total journal line nominal across accounting document lines.',
    'Sum journal line amount across accounting document lines for the selected period.',
    'currency',
    'idr',
    '["branch","location","contact","source_doc_type","line_account_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["accounting","journal","amount"]'::jsonb,
    'Accounting Lead',
    'approved',
    true,
    85,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'accounting_journal_line_count',
    'accounting_journal_line_count',
    'Accounting Journal Line Count',
    'Journal Count',
    'accounting',
    'journal_line',
    'journal_line_count',
    'Count accounting journal lines.',
    'Count journal line rows across accounting document lines for the selected period.',
    'count',
    'line',
    '["branch","location","contact","source_doc_type","line_account_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["accounting","journal","count"]'::jsonb,
    'Accounting Lead',
    'approved',
    true,
    86,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'accounting_distinct_account_count',
    'accounting_distinct_account_count',
    'Accounting Distinct Account Count',
    'Distinct Accounts',
    'accounting',
    'coa_usage',
    'distinct_account_count',
    'Distinct COA account count used in accounting journal lines.',
    'Count distinct accounts referenced by accounting journal lines.',
    'count',
    'account',
    '["branch","location","source_doc_type","line_account_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["accounting","coa","count"]'::jsonb,
    'Accounting Lead',
    'reviewed',
    true,
    87,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'accounting_document_lifecycle_event_count',
    'accounting_document_lifecycle_event_count',
    'Accounting Document Lifecycle Event Count',
    'Lifecycle Events',
    'accounting',
    'finance_document',
    'document_lifecycle_event_count',
    'Count lifecycle events across accounting documents.',
    'Count status/history events recorded for accounting documents.',
    'count',
    'event',
    '["branch","location","contact","source_doc_type","doc_status_code","previous_status_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["accounting","document","lifecycle"]'::jsonb,
    'Accounting Operations',
    'reviewed',
    true,
    88,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'accounting_document_revision_total',
    'accounting_document_revision_total',
    'Accounting Document Revision Total',
    'Revision Total',
    'accounting',
    'finance_document',
    'document_revision_total',
    'Total revision count across accounting document lifecycle.',
    'Sum revision count recorded in accounting document lifecycle history.',
    'count',
    'revision',
    '["branch","location","contact","source_doc_type"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["accounting","document","revision"]'::jsonb,
    'Accounting Operations',
    'reviewed',
    true,
    89,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'accounting_active_coa_count',
    'accounting_active_coa_count',
    'Accounting Active COA Count',
    'Active COA',
    'accounting',
    'coa',
    'active_coa_count',
    'Count active COA records.',
    'Count active chart of accounts available for accounting.',
    'count',
    'account',
    '["branch","location","account_type","parent_account_code"]'::jsonb,
    '{"is_active":1}'::jsonb,
    '["accounting","coa","active"]'::jsonb,
    'Accounting Master Data',
    'approved',
    true,
    90,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'accounting_revenue_total',
    'accounting_revenue_total',
    'Accounting Revenue Total',
    'Revenue',
    'accounting',
    'profit_loss',
    'revenue_total',
    'Total revenue from profit and loss journal classification.',
    'Sum net amount from profit and loss lines classified as REVENUE.',
    'currency',
    'idr',
    '["branch","location","contact","account_code","fiscal_year","fiscal_month"]'::jsonb,
    '{"pnl_category":"REVENUE"}'::jsonb,
    '["accounting","profit_loss","revenue"]'::jsonb,
    'Accounting Controller',
    'approved',
    true,
    91,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'accounting_cogs_total',
    'accounting_cogs_total',
    'Accounting COGS Total',
    'COGS',
    'accounting',
    'profit_loss',
    'cogs_total',
    'Total cost of goods sold from profit and loss journal classification.',
    'Sum net amount from profit and loss lines classified as COGS.',
    'currency',
    'idr',
    '["branch","location","contact","account_code","fiscal_year","fiscal_month"]'::jsonb,
    '{"pnl_category":"COGS"}'::jsonb,
    '["accounting","profit_loss","cogs"]'::jsonb,
    'Accounting Controller',
    'approved',
    true,
    92,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'accounting_operating_expense_total',
    'accounting_operating_expense_total',
    'Accounting Operating Expense Total',
    'Opex',
    'accounting',
    'profit_loss',
    'operating_expense_total',
    'Total operating expense from profit and loss journal classification.',
    'Sum net amount from profit and loss lines classified as OPERATING_EXPENSE.',
    'currency',
    'idr',
    '["branch","location","contact","account_code","fiscal_year","fiscal_month"]'::jsonb,
    '{"pnl_category":"OPERATING_EXPENSE"}'::jsonb,
    '["accounting","profit_loss","opex"]'::jsonb,
    'Accounting Controller',
    'approved',
    true,
    93,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'accounting_net_profit_total',
    'accounting_net_profit_total',
    'Accounting Net Profit Total',
    'Net Profit',
    'accounting',
    'profit_loss',
    'net_profit_total',
    'Net profit derived from profit and loss journal classification.',
    'Derived net profit from revenue, cogs, operating expense, and other result categories.',
    'currency',
    'idr',
    '["branch","location","contact","fiscal_year","fiscal_month"]'::jsonb,
    '{"pnl_scope":"net_profit"}'::jsonb,
    '["accounting","profit_loss","net_profit"]'::jsonb,
    'Accounting Controller',
    'approved',
    true,
    94,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'inventory_stock_on_hand_total',
    'inventory_stock_on_hand_total',
    'Inventory Stock On Hand Total',
    'Stock On Hand',
    'inventory',
    'inventory_balance',
    'stock_on_hand_total',
    'Total current stock quantity across inventory item-warehouse rows.',
    'Sum current stock quantity from inventory stock by warehouse dimension.',
    'number',
    'qty',
    '["branch","location","warehouse_code","item_code","item_category_code","supplier_id"]'::jsonb,
    '{"include_zero":false}'::jsonb,
    '["inventory","stock","on_hand"]'::jsonb,
    'Inventory Control',
    'approved',
    true,
    95,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'inventory_item_with_stock_count',
    'inventory_item_with_stock_count',
    'Inventory Item With Stock Count',
    'Items With Stock',
    'inventory',
    'inventory_balance',
    'item_with_stock_count',
    'Count item-warehouse rows with stock greater than zero.',
    'Count inventory item rows where current stock is positive.',
    'count',
    'item',
    '["branch","location","warehouse_code","item_code","item_category_code","supplier_id"]'::jsonb,
    '{"stock_gt":0}'::jsonb,
    '["inventory","stock","positive","count"]'::jsonb,
    'Inventory Control',
    'reviewed',
    true,
    96,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'inventory_stock_value_total',
    'inventory_stock_value_total',
    'Inventory Stock Value Total',
    'Stock Value',
    'inventory',
    'inventory_balance',
    'stock_value_total',
    'Estimated inventory stock value using stock quantity and average cost.',
    'Derived value from current stock multiplied by average cost.',
    'currency',
    'idr',
    '["branch","location","warehouse_code","item_code","item_category_code","supplier_id"]'::jsonb,
    '{"include_zero":false}'::jsonb,
    '["inventory","stock","value"]'::jsonb,
    'Inventory Control',
    'approved',
    true,
    97,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'inventory_active_item_stock_count',
    'inventory_active_item_stock_count',
    'Inventory Active Item Stock Count',
    'Active Stock Items',
    'inventory',
    'inventory_balance',
    'active_item_stock_count',
    'Count active item-warehouse stock rows.',
    'Count stock rows where the inventory item is marked active.',
    'count',
    'item',
    '["branch","location","warehouse_code","item_code","item_category_code"]'::jsonb,
    '{"is_active":1}'::jsonb,
    '["inventory","stock","active"]'::jsonb,
    'Inventory Master Data',
    'reviewed',
    true,
    98,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'inventory_document_history_event_count',
    'inventory_document_history_event_count',
    'Inventory Document History Event Count',
    'Document Events',
    'inventory',
    'inventory_document',
    'document_history_event_count',
    'Count lifecycle events across inventory document history.',
    'Count history events for inventory material request, transfer, receive, and related documents.',
    'count',
    'event',
    '["branch_code","location_code","warehouse_from_code","warehouse_to_code","source_doc_type","doc_status_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["inventory","document","history","event"]'::jsonb,
    'Inventory Operations',
    'reviewed',
    true,
    99,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'inventory_transfer_event_count',
    'inventory_transfer_event_count',
    'Inventory Transfer Event Count',
    'Transfer Events',
    'inventory',
    'inventory_transfer',
    'transfer_event_count',
    'Count inventory transfer stock events.',
    'Count inventory history events for transfer stock documents.',
    'count',
    'event',
    '["branch_code","location_code","warehouse_from_code","warehouse_transit_code","warehouse_to_code","doc_status_code"]'::jsonb,
    '{"period":"current_month","source_doc_type":"TS"}'::jsonb,
    '["inventory","transfer","event"]'::jsonb,
    'Inventory Operations',
    'approved',
    true,
    100,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'inventory_receive_event_count',
    'inventory_receive_event_count',
    'Inventory Receive Event Count',
    'Receive Events',
    'inventory',
    'inventory_receipt',
    'receive_event_count',
    'Count inventory receive stock events.',
    'Count inventory history events for receive stock documents.',
    'count',
    'event',
    '["branch_code","location_code","warehouse_from_code","warehouse_to_code","doc_status_code"]'::jsonb,
    '{"period":"current_month","source_doc_type":"RS"}'::jsonb,
    '["inventory","receive","event"]'::jsonb,
    'Inventory Operations',
    'approved',
    true,
    101,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'inventory_daily_check_count',
    'inventory_daily_check_count',
    'Inventory Daily Check Count',
    'Daily Check Count',
    'inventory',
    'inventory_daily_check',
    'daily_check_count',
    'Count inventory daily check rows.',
    'Count daily check records across shift, item, and check category.',
    'count',
    'check',
    '["branch_code","location_code","shift_code","item_id","check_category_id","check_status"]'::jsonb,
    '{"period":"current_day"}'::jsonb,
    '["inventory","daily_check","count"]'::jsonb,
    'Inventory Supervisor',
    'reviewed',
    true,
    102,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'inventory_daily_check_issue_count',
    'inventory_daily_check_issue_count',
    'Inventory Daily Check Issue Count',
    'Daily Check Issues',
    'inventory',
    'inventory_daily_check',
    'daily_check_issue_count',
    'Count inventory daily check rows flagged as issue.',
    'Count daily check records where status indicates issue, fail, or exception.',
    'count',
    'issue',
    '["branch_code","location_code","shift_code","item_id","check_category_id","check_status"]'::jsonb,
    '{"period":"current_day","issue_only":true}'::jsonb,
    '["inventory","daily_check","issue"]'::jsonb,
    'Inventory Supervisor',
    'approved',
    true,
    103,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'inventory_inactive_item_stock_count',
    'inventory_inactive_item_stock_count',
    'Inventory Inactive Item Stock Count',
    'Inactive Stock Items',
    'inventory',
    'inventory_balance',
    'inactive_item_stock_count',
    'Count inactive item-warehouse stock rows.',
    'Count stock rows where item or stock row is marked inactive.',
    'count',
    'item',
    '["branch","location","warehouse_code","item_code","item_category_code"]'::jsonb,
    '{"is_active":0}'::jsonb,
    '["inventory","stock","inactive"]'::jsonb,
    'Inventory Master Data',
    'reviewed',
    true,
    104,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'negative_stock_count',
    'negative_stock_count',
    'Negative Stock Count',
    'Negative Stock',
    'warehouse',
    'inventory_balance',
    'negative_stock_count',
    'Count of item-warehouse combinations with stock below zero.',
    'Count rows where stock balance is negative.',
    'count',
    'item',
    '["warehouse","item","category"]'::jsonb,
    '{}'::jsonb,
    '["warehouse","negative_stock"]'::jsonb,
    'Warehouse Supervisor',
    'approved',
    true,
    80,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'inventory_negative_stock_count',
    'negative_stock_count',
    'Inventory Negative Stock Count',
    'Negative Stock',
    'warehouse',
    'inventory_balance',
    'negative_stock_count',
    'Alias semantic key for negative stock count.',
    'Same concept as negative_stock_count; retained for compatibility.',
    'count',
    'item',
    '["warehouse","item","category"]'::jsonb,
    '{}'::jsonb,
    '["warehouse","negative_stock","alias"]'::jsonb,
    'Warehouse Supervisor',
    'reviewed',
    true,
    90,
    '{"alias":true}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'inventory_aging_90_plus',
    'inventory_aging_90_plus',
    'Inventory Aging 90+ Days',
    'Aging 90+',
    'warehouse',
    'inventory_aging',
    'aging_value',
    'Inventory value where aging exceeds 90 days.',
    'Sum inventory value for stock older than 90 days.',
    'currency',
    'idr',
    '["warehouse","item","category","aging_bucket"]'::jsonb,
    '{"aging_bucket":"90_plus"}'::jsonb,
    '["warehouse","aging","inventory"]'::jsonb,
    'Inventory Analyst',
    'approved',
    true,
    100,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'inventory_coverage_days',
    'inventory_coverage_days',
    'Inventory Coverage Days',
    'Coverage Days',
    'warehouse',
    'inventory_balance',
    'coverage_days',
    'Estimated days of stock coverage based on current balance and consumption rate.',
    'Current stock divided by expected outbound or consumption rate.',
    'days',
    'day',
    '["warehouse","item","category"]'::jsonb,
    '{}'::jsonb,
    '["warehouse","coverage"]'::jsonb,
    'Inventory Analyst',
    'reviewed',
    true,
    110,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'purchase_price_variance',
    'purchase_price_variance',
    'Purchase Price Variance',
    'Price Variance',
    'purchasing',
    'purchase_order',
    'price_variance_pct',
    'Variance of purchase price versus baseline or historical benchmark.',
    'Current purchase price compared with baseline purchase price.',
    'percent',
    'percent',
    '["supplier","item","buyer"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["purchasing","variance","price"]'::jsonb,
    'Procurement Lead',
    'approved',
    true,
    120,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'purchase_price_variance_pct',
    'purchase_price_variance',
    'Purchase Price Variance Percentage',
    'Price Variance',
    'purchasing',
    'purchase_order',
    'price_variance_pct',
    'Alias semantic key for purchase price variance percentage.',
    'Same concept as purchase_price_variance; retained for compatibility.',
    'percent',
    'percent',
    '["supplier","item","buyer"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["purchasing","variance","price","alias"]'::jsonb,
    'Procurement Lead',
    'reviewed',
    true,
    130,
    '{"alias":true}'::jsonb,
    'seed',
    'seed'
  ),
  (
    'open_purchase_order_total',
    'open_purchase_order_total',
    'Open Purchase Order Total',
    'Open PO',
    'purchasing',
    'purchase_order',
    'open_po_amount',
    'Total value of purchase orders that are still open.',
    'Sum value of purchase orders not yet fully received or closed.',
    'currency',
    'idr',
    '["supplier","branch","buyer"]'::jsonb,
    '{"status":"open"}'::jsonb,
    '["purchasing","open_po"]'::jsonb,
    'Procurement Manager',
    'approved',
    true,
    140,
    '{"alias":false}'::jsonb,
    'seed',
    'seed'
  )
ON CONFLICT (semantic_key)
DO UPDATE SET
  canonical_semantic_key = EXCLUDED.canonical_semantic_key,
  label = EXCLUDED.label,
  short_label = EXCLUDED.short_label,
  module_key = EXCLUDED.module_key,
  entity_key = EXCLUDED.entity_key,
  measure_key = EXCLUDED.measure_key,
  definition = EXCLUDED.definition,
  calculation_summary = EXCLUDED.calculation_summary,
  value_type = EXCLUDED.value_type,
  unit = EXCLUDED.unit,
  supported_dimensions = EXCLUDED.supported_dimensions,
  default_filters = EXCLUDED.default_filters,
  tags = EXCLUDED.tags,
  owner_name = EXCLUDED.owner_name,
  review_status = EXCLUDED.review_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order,
  metadata = EXCLUDED.metadata,
  updated_by = EXCLUDED.updated_by,
  deleted_at = NULL;
