-- Business metric registry.
-- Purpose:
--   1. Menjadi source of truth metric bisnis yang user-facing.
--   2. Dipakai oleh alert rule, dashboard, dan AI context retrieval.
--   3. Menjembatani istilah bisnis dengan source semantic/system/query di backend.
--
-- Design choice:
--   1. MVP cukup 1 tabel.
--   2. Gunakan JSONB untuk dimensions, filters, tags, dan metadata ringan.
--   3. Child table baru diperlukan nanti kalau versioning / filter-definition / mapping menjadi kompleks.

CREATE OR REPLACE FUNCTION public.set_row_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.metric_business_registry (
  metric_id bigserial PRIMARY KEY,
  metric_key varchar(120) NOT NULL,
  label varchar(200) NOT NULL,
  short_label varchar(100),
  module_key varchar(60) NOT NULL,
  description text,
  business_definition text,
  unit varchar(40),
  value_type varchar(40) NOT NULL DEFAULT 'number',
  comparison_type varchar(40),
  semantic_ref varchar(120),
  system_metric_ref varchar(120),
  source_type varchar(40) NOT NULL DEFAULT 'semantic_metric',
  source_ref varchar(120),
  supported_dimensions jsonb NOT NULL DEFAULT '[]'::jsonb,
  default_filters jsonb NOT NULL DEFAULT '{}'::jsonb,
  tags jsonb NOT NULL DEFAULT '[]'::jsonb,
  owner_name varchar(120),
  review_status varchar(30) NOT NULL DEFAULT 'draft',
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_by text,
  updated_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT uq_metric_business_registry_key UNIQUE (metric_key),
  CONSTRAINT chk_metric_business_value_type CHECK (
    value_type IN ('number', 'currency', 'percent', 'count', 'days', 'duration', 'ratio', 'boolean', 'text')
  ),
  CONSTRAINT chk_metric_business_comparison_type CHECK (
    comparison_type IS NULL OR comparison_type IN (
      'threshold',
      'day_over_day',
      'week_over_week',
      'month_over_month',
      'year_over_year',
      'target_vs_actual',
      'trend_anomaly'
    )
  ),
  CONSTRAINT chk_metric_business_source_type CHECK (
    source_type IN (
      'semantic_metric',
      'system_metric',
      'saved_query',
      'ai_query',
      'manual_rule_source'
    )
  ),
  CONSTRAINT chk_metric_business_review_status CHECK (
    review_status IN ('draft', 'reviewed', 'approved', 'archived')
  )
);

CREATE INDEX IF NOT EXISTS idx_metric_business_registry_module
  ON public.metric_business_registry (module_key, is_active, sort_order)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_metric_business_registry_status
  ON public.metric_business_registry (review_status, is_active)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_metric_business_registry_source
  ON public.metric_business_registry (source_type, source_ref)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_metric_business_registry_tags
  ON public.metric_business_registry
  USING gin (tags);

CREATE INDEX IF NOT EXISTS idx_metric_business_registry_dimensions
  ON public.metric_business_registry
  USING gin (supported_dimensions);

-- Normalize semantic_ref to canonical semantic key before enforcing FK.
UPDATE public.metric_business_registry b
SET semantic_ref = s.canonical_semantic_key
FROM public.metric_semantic_registry s
WHERE b.semantic_ref = s.semantic_key
  AND s.canonical_semantic_key IS NOT NULL
  AND b.semantic_ref IS DISTINCT FROM s.canonical_semantic_key;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_metric_business_registry_semantic_ref'
      AND conrelid = 'public.metric_business_registry'::regclass
  ) THEN
    ALTER TABLE public.metric_business_registry
      ADD CONSTRAINT fk_metric_business_registry_semantic_ref
      FOREIGN KEY (semantic_ref)
      REFERENCES public.metric_semantic_registry(semantic_key);
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_metric_business_registry_system_metric_ref'
      AND conrelid = 'public.metric_business_registry'::regclass
  ) THEN
    ALTER TABLE public.metric_business_registry
      ADD CONSTRAINT fk_metric_business_registry_system_metric_ref
      FOREIGN KEY (system_metric_ref)
      REFERENCES public.metric_system_registry(metric_key);
  END IF;
END;
$$;

DROP TRIGGER IF EXISTS trg_metric_business_registry_updated_at ON public.metric_business_registry;
CREATE TRIGGER trg_metric_business_registry_updated_at
BEFORE UPDATE ON public.metric_business_registry
FOR EACH ROW
EXECUTE FUNCTION public.set_row_updated_at();

-- Seed awal metric bisnis inti lintas modul.
INSERT INTO public.metric_business_registry (
  metric_key,
  label,
  short_label,
  module_key,
  description,
  business_definition,
  unit,
  value_type,
  comparison_type,
  semantic_ref,
  system_metric_ref,
  source_type,
  source_ref,
  supported_dimensions,
  default_filters,
  tags,
  owner_name,
  review_status,
  is_active,
  sort_order,
  created_by,
  updated_by
)
VALUES
  (
    'daily_sales_revenue',
    'Daily Sales Revenue',
    'Sales Revenue',
    'sales',
    'Total nilai penjualan per hari.',
    'Menunjukkan total nilai invoice penjualan yang valid pada hari berjalan atau periode harian yang dipilih.',
    'idr',
    'currency',
    'day_over_day',
    'daily_sales_revenue',
    'sales_invoice_amount_daily_sum',
    'semantic_metric',
    'daily_sales_revenue',
    '["branch","customer","salesman"]'::jsonb,
    '{"period":"today"}'::jsonb,
    '["sales","revenue","daily"]'::jsonb,
    'Sales Analyst',
    'approved',
    true,
    10,
    'seed',
    'seed'
  ),
  (
    'monthly_sales_achievement',
    'Monthly Sales Achievement',
    'Sales Achievement',
    'sales',
    'Persentase pencapaian sales terhadap target bulanan.',
    'Membandingkan actual sales bulan berjalan dengan target sales yang sudah ditetapkan.',
    'percent',
    'percent',
    'target_vs_actual',
    'monthly_sales_achievement',
    'sales_target_vs_actual_pct',
    'semantic_metric',
    'monthly_sales_achievement',
    '["branch","salesman"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["sales","target","achievement"]'::jsonb,
    'Sales Manager',
    'reviewed',
    true,
    20,
    'seed',
    'seed'
  ),
  (
    'overdue_receivable_total',
    'Overdue Receivable Total',
    'Overdue AR',
    'finance',
    'Total outstanding receivable yang sudah melewati jatuh tempo.',
    'Menunjukkan total piutang yang overdue sesuai definisi aging perusahaan.',
    'idr',
    'currency',
    'threshold',
    'overdue_receivable_total',
    'receivable_overdue_amount_30_plus',
    'semantic_metric',
    'overdue_receivable_total',
    '["branch","customer","salesman","aging_bucket"]'::jsonb,
    '{"aging_bucket":"30_plus"}'::jsonb,
    '["finance","receivable","overdue"]'::jsonb,
    'Finance Lead',
    'approved',
    true,
    30,
    'seed',
    'seed'
  ),
  (
    'cash_in_vs_cash_out',
    'Cash In vs Cash Out',
    'Cashflow',
    'finance',
    'Perbandingan cash in dan cash out pada periode terpilih.',
    'Mengukur keseimbangan arus kas masuk dan keluar untuk periode yang dipilih.',
    'idr',
    'currency',
    'month_over_month',
    'cash_in_vs_cash_out',
    'cash_in_vs_cash_out_total',
    'semantic_metric',
    'cash_in_vs_cash_out',
    '["branch","bank_account"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","cashflow"]'::jsonb,
    'Finance Manager',
    'reviewed',
    true,
    40,
    'seed',
    'seed'
  ),
  (
    'overdue_receivable_customer_count',
    'Overdue Receivable Customer Count',
    'Overdue Customers',
    'finance',
    'Jumlah customer yang masih memiliki piutang overdue.',
    'Menghitung jumlah customer unik dengan saldo piutang yang sudah melewati jatuh tempo.',
    'customer',
    'count',
    'threshold',
    'overdue_receivable_customer_count',
    'receivable_overdue_customer_count',
    'semantic_metric',
    'overdue_receivable_customer_count',
    '["branch","customer","salesman","aging_bucket"]'::jsonb,
    '{"aging_bucket":"30_plus"}'::jsonb,
    '["finance","receivable","overdue","customer"]'::jsonb,
    'Finance Lead',
    'approved',
    true,
    41,
    'seed',
    'seed'
  ),
  (
    'overdue_receivable_invoice_count',
    'Overdue Receivable Invoice Count',
    'Overdue Invoices',
    'finance',
    'Jumlah invoice piutang yang overdue.',
    'Menghitung jumlah invoice dengan due date terlewati dan outstanding masih tersisa.',
    'invoice',
    'count',
    'threshold',
    'overdue_receivable_invoice_count',
    'receivable_overdue_invoice_count',
    'semantic_metric',
    'overdue_receivable_invoice_count',
    '["branch","customer","salesman","aging_bucket"]'::jsonb,
    '{"aging_bucket":"30_plus"}'::jsonb,
    '["finance","receivable","overdue","invoice"]'::jsonb,
    'Finance Lead',
    'approved',
    true,
    42,
    'seed',
    'seed'
  ),
  (
    'cash_in_total',
    'Cash In Total',
    'Cash In',
    'finance',
    'Total kas masuk pada periode terpilih.',
    'Menunjukkan total nilai kas masuk dari transaksi cash receipt pada periode terpilih.',
    'idr',
    'currency',
    'month_over_month',
    'cash_in_total',
    'cash_receipt_total_amount',
    'semantic_metric',
    'cash_in_total',
    '["branch","location","contact","bank_account","cost_center","project"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","cashflow","cash_in"]'::jsonb,
    'Finance Manager',
    'approved',
    true,
    43,
    'seed',
    'seed'
  ),
  (
    'cash_out_total',
    'Cash Out Total',
    'Cash Out',
    'finance',
    'Total kas keluar pada periode terpilih.',
    'Menunjukkan total nilai kas keluar dari transaksi cash disbursement pada periode terpilih.',
    'idr',
    'currency',
    'month_over_month',
    'cash_out_total',
    'cash_disbursement_total_amount',
    'semantic_metric',
    'cash_out_total',
    '["branch","location","contact","bank_account","cost_center","project"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","cashflow","cash_out"]'::jsonb,
    'Finance Manager',
    'approved',
    true,
    44,
    'seed',
    'seed'
  ),
  (
    'net_cash_movement',
    'Net Cash Movement',
    'Net Cash',
    'finance',
    'Selisih bersih antara kas masuk dan kas keluar.',
    'Mengukur net cash movement setelah mengurangkan cash out dari cash in.',
    'idr',
    'currency',
    'month_over_month',
    'net_cash_movement',
    'cash_in_vs_cash_out_total',
    'semantic_metric',
    'net_cash_movement',
    '["branch","location","bank_account"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","cashflow","net"]'::jsonb,
    'Finance Manager',
    'reviewed',
    true,
    45,
    'seed',
    'seed'
  ),
  (
    'receipt_money_total',
    'Receipt Money Total',
    'Receipt Money',
    'finance',
    'Total penerimaan uang dari receipt money flow.',
    'Menunjukkan total nilai penerimaan uang yang tercatat pada receipt money line flow.',
    'idr',
    'currency',
    'month_over_month',
    'receipt_money_total',
    'receipt_money_total_amount',
    'semantic_metric',
    'receipt_money_total',
    '["branch","location","contact","payment_method","bank_account"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","receipt_money"]'::jsonb,
    'Finance Lead',
    'reviewed',
    true,
    46,
    'seed',
    'seed'
  ),
  (
    'receipt_money_transaction_count',
    'Receipt Money Transaction Count',
    'Receipt Count',
    'finance',
    'Jumlah transaksi receipt money pada periode terpilih.',
    'Menghitung jumlah transaksi detail receipt money untuk memonitor volume collection.',
    'transaction',
    'count',
    'threshold',
    'receipt_money_transaction_count',
    'receipt_money_transaction_count',
    'semantic_metric',
    'receipt_money_transaction_count',
    '["branch","location","contact","payment_method"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","receipt_money","count"]'::jsonb,
    'Finance Lead',
    'reviewed',
    true,
    47,
    'seed',
    'seed'
  ),
  (
    'payment_history_total',
    'Payment History Total',
    'Payment Total',
    'finance',
    'Total nilai payment history event pada periode terpilih.',
    'Menunjukkan total nilai pembayaran yang tercatat di event histori pembayaran finance.',
    'idr',
    'currency',
    'month_over_month',
    'payment_history_total',
    'finance_payment_history_total_amount',
    'semantic_metric',
    'payment_history_total',
    '["branch","location","contact","payment_method","bank"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","payment_history","amount"]'::jsonb,
    'Finance Manager',
    'reviewed',
    true,
    48,
    'seed',
    'seed'
  ),
  (
    'payment_history_event_count',
    'Payment History Event Count',
    'Payment Events',
    'finance',
    'Jumlah event payment history pada periode terpilih.',
    'Menghitung volume event pembayaran finance untuk monitoring aktivitas payment.',
    'event',
    'count',
    'threshold',
    'payment_history_event_count',
    'finance_payment_history_event_count',
    'semantic_metric',
    'payment_history_event_count',
    '["branch","location","contact","payment_method","bank"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","payment_history","count"]'::jsonb,
    'Finance Manager',
    'reviewed',
    true,
    49,
    'seed',
    'seed'
  ),
  (
    'budget_realization_total',
    'Budget Realization Total',
    'Realization',
    'finance',
    'Total realisasi budget pada periode terpilih.',
    'Menunjukkan total nilai realisasi yang tercatat di finance budget realization.',
    'idr',
    'currency',
    'target_vs_actual',
    'budget_realization_total',
    'finance_budget_realization_total_amount',
    'semantic_metric',
    'budget_realization_total',
    '["branch","location","contact","item_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","budget","realization"]'::jsonb,
    'Finance Controller',
    'approved',
    true,
    50,
    'seed',
    'seed'
  ),
  (
    'budget_vs_realization_variance',
    'Budget vs Realization Variance',
    'Budget Variance',
    'finance',
    'Selisih antara budget dan realization.',
    'Mengukur variance nominal antara anggaran yang direncanakan dan realisasi aktual.',
    'idr',
    'currency',
    'target_vs_actual',
    'budget_vs_realization_variance',
    'finance_budget_variance_amount',
    'semantic_metric',
    'budget_vs_realization_variance',
    '["branch","location","contact","item_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","budget","variance"]'::jsonb,
    'Finance Controller',
    'reviewed',
    true,
    51,
    'seed',
    'seed'
  ),
  (
    'finance_open_document_count',
    'Finance Open Document Count',
    'Open Documents',
    'finance',
    'Jumlah dokumen finance yang masih open.',
    'Menghitung jumlah dokumen finance yang status workflow atau payment status-nya masih terbuka.',
    'document',
    'count',
    'threshold',
    'finance_open_document_count',
    'finance_open_document_count',
    'semantic_metric',
    'finance_open_document_count',
    '["branch","location","contact","source_doc_type","doc_status_name"]'::jsonb,
    '{"doc_status_name":"open"}'::jsonb,
    '["finance","document","open"]'::jsonb,
    'Finance Operations',
    'approved',
    true,
    52,
    'seed',
    'seed'
  ),
  (
    'bank_position_total',
    'Bank Position Total',
    'Bank Position',
    'finance',
    'Total nominal transaksi finance per posisi bank.',
    'Menunjukkan total nominal dokumen finance yang terkait posisi bank atau cash account.',
    'idr',
    'currency',
    'month_over_month',
    'bank_position_total',
    'bank_position_total_amount',
    'semantic_metric',
    'bank_position_total',
    '["branch","location","bank_account","source_doc_type"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","bank","position"]'::jsonb,
    'Treasury Lead',
    'reviewed',
    true,
    53,
    'seed',
    'seed'
  ),
  (
    'allocation_total',
    'Allocation Total',
    'Allocation',
    'finance',
    'Total nominal allocation pada periode terpilih.',
    'Menunjukkan total nominal alokasi biaya atau dana lintas cost center dan project.',
    'idr',
    'currency',
    'threshold',
    'allocation_total',
    'finance_allocation_total_amount',
    'semantic_metric',
    'allocation_total',
    '["branch","location","contact","cost_center","project"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["finance","allocation"]'::jsonb,
    'Finance Controller',
    'reviewed',
    true,
    54,
    'seed',
    'seed'
  ),
  (
    'accounting_journal_line_amount_total',
    'Accounting Journal Line Amount Total',
    'Journal Amount',
    'accounting',
    'Total nominal line jurnal accounting.',
    'Menunjukkan total nominal line jurnal pada dokumen accounting di periode terpilih.',
    'idr',
    'currency',
    'month_over_month',
    'accounting_journal_line_amount_total',
    'accounting_journal_line_amount_total',
    'semantic_metric',
    'accounting_journal_line_amount_total',
    '["branch","location","contact","source_doc_type","line_account_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["accounting","journal","amount"]'::jsonb,
    'Accounting Lead',
    'approved',
    true,
    55,
    'seed',
    'seed'
  ),
  (
    'accounting_journal_line_count',
    'Accounting Journal Line Count',
    'Journal Count',
    'accounting',
    'Jumlah line jurnal accounting.',
    'Menghitung jumlah line jurnal accounting untuk memonitor volume posting.',
    'line',
    'count',
    'threshold',
    'accounting_journal_line_count',
    'accounting_journal_line_count',
    'semantic_metric',
    'accounting_journal_line_count',
    '["branch","location","contact","source_doc_type","line_account_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["accounting","journal","count"]'::jsonb,
    'Accounting Lead',
    'approved',
    true,
    56,
    'seed',
    'seed'
  ),
  (
    'accounting_distinct_account_count',
    'Accounting Distinct Account Count',
    'Distinct Accounts',
    'accounting',
    'Jumlah akun COA unik yang dipakai pada jurnal accounting.',
    'Menghitung berapa banyak akun COA berbeda yang dipakai oleh line jurnal accounting.',
    'account',
    'count',
    'threshold',
    'accounting_distinct_account_count',
    'accounting_distinct_account_count',
    'semantic_metric',
    'accounting_distinct_account_count',
    '["branch","location","source_doc_type","line_account_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["accounting","coa","count"]'::jsonb,
    'Accounting Lead',
    'reviewed',
    true,
    57,
    'seed',
    'seed'
  ),
  (
    'accounting_document_lifecycle_event_count',
    'Accounting Document Lifecycle Event Count',
    'Lifecycle Events',
    'accounting',
    'Jumlah event lifecycle dokumen accounting.',
    'Menghitung berapa banyak perubahan status atau history event pada dokumen accounting.',
    'event',
    'count',
    'threshold',
    'accounting_document_lifecycle_event_count',
    'accounting_document_lifecycle_event_count',
    'semantic_metric',
    'accounting_document_lifecycle_event_count',
    '["branch","location","contact","source_doc_type","doc_status_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["accounting","document","lifecycle"]'::jsonb,
    'Accounting Operations',
    'reviewed',
    true,
    58,
    'seed',
    'seed'
  ),
  (
    'accounting_document_revision_total',
    'Accounting Document Revision Total',
    'Revision Total',
    'accounting',
    'Total revisi dokumen accounting.',
    'Menunjukkan total jumlah revisi yang tercatat pada lifecycle dokumen accounting.',
    'revision',
    'count',
    'threshold',
    'accounting_document_revision_total',
    'accounting_document_revision_total',
    'semantic_metric',
    'accounting_document_revision_total',
    '["branch","location","contact","source_doc_type"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["accounting","document","revision"]'::jsonb,
    'Accounting Operations',
    'reviewed',
    true,
    59,
    'seed',
    'seed'
  ),
  (
    'accounting_active_coa_count',
    'Accounting Active COA Count',
    'Active COA',
    'accounting',
    'Jumlah akun COA aktif.',
    'Menghitung jumlah akun chart of accounts yang aktif dan siap dipakai.',
    'account',
    'count',
    'threshold',
    'accounting_active_coa_count',
    'accounting_active_coa_count',
    'semantic_metric',
    'accounting_active_coa_count',
    '["branch","location","account_type","parent_account_code"]'::jsonb,
    '{"is_active":1}'::jsonb,
    '["accounting","coa","active"]'::jsonb,
    'Accounting Master Data',
    'approved',
    true,
    60,
    'seed',
    'seed'
  ),
  (
    'accounting_revenue_total',
    'Accounting Revenue Total',
    'Revenue',
    'accounting',
    'Total revenue dari klasifikasi laba rugi accounting.',
    'Menunjukkan total revenue berdasarkan line profit and loss yang diklasifikasikan sebagai REVENUE.',
    'idr',
    'currency',
    'month_over_month',
    'accounting_revenue_total',
    'accounting_revenue_total',
    'semantic_metric',
    'accounting_revenue_total',
    '["branch","location","contact","account_code","fiscal_year","fiscal_month"]'::jsonb,
    '{"pnl_category":"REVENUE"}'::jsonb,
    '["accounting","profit_loss","revenue"]'::jsonb,
    'Accounting Controller',
    'approved',
    true,
    61,
    'seed',
    'seed'
  ),
  (
    'accounting_cogs_total',
    'Accounting COGS Total',
    'COGS',
    'accounting',
    'Total cost of goods sold dari klasifikasi laba rugi accounting.',
    'Menunjukkan total COGS berdasarkan line profit and loss yang diklasifikasikan sebagai COGS.',
    'idr',
    'currency',
    'month_over_month',
    'accounting_cogs_total',
    'accounting_cogs_total',
    'semantic_metric',
    'accounting_cogs_total',
    '["branch","location","contact","account_code","fiscal_year","fiscal_month"]'::jsonb,
    '{"pnl_category":"COGS"}'::jsonb,
    '["accounting","profit_loss","cogs"]'::jsonb,
    'Accounting Controller',
    'approved',
    true,
    62,
    'seed',
    'seed'
  ),
  (
    'accounting_operating_expense_total',
    'Accounting Operating Expense Total',
    'Opex',
    'accounting',
    'Total operating expense dari klasifikasi laba rugi accounting.',
    'Menunjukkan total operating expense berdasarkan line profit and loss yang diklasifikasikan sebagai OPERATING_EXPENSE.',
    'idr',
    'currency',
    'month_over_month',
    'accounting_operating_expense_total',
    'accounting_operating_expense_total',
    'semantic_metric',
    'accounting_operating_expense_total',
    '["branch","location","contact","account_code","fiscal_year","fiscal_month"]'::jsonb,
    '{"pnl_category":"OPERATING_EXPENSE"}'::jsonb,
    '["accounting","profit_loss","opex"]'::jsonb,
    'Accounting Controller',
    'approved',
    true,
    63,
    'seed',
    'seed'
  ),
  (
    'accounting_net_profit_total',
    'Accounting Net Profit Total',
    'Net Profit',
    'accounting',
    'Net profit accounting hasil derivasi laba rugi.',
    'Mengukur net profit berdasarkan kombinasi revenue, cogs, operating expense, dan komponen other result.',
    'idr',
    'currency',
    'month_over_month',
    'accounting_net_profit_total',
    'accounting_net_profit_total',
    'semantic_metric',
    'accounting_net_profit_total',
    '["branch","location","contact","fiscal_year","fiscal_month"]'::jsonb,
    '{"pnl_scope":"net_profit"}'::jsonb,
    '["accounting","profit_loss","net_profit"]'::jsonb,
    'Accounting Controller',
    'approved',
    true,
    64,
    'seed',
    'seed'
  ),
  (
    'inventory_stock_on_hand_total',
    'Inventory Stock On Hand Total',
    'Stock On Hand',
    'inventory',
    'Total stok berjalan pada item dan gudang inventory.',
    'Menunjukkan total kuantitas stok yang masih tersedia pada dimensi inventory item-warehouse.',
    'qty',
    'number',
    'threshold',
    'inventory_stock_on_hand_total',
    'inventory_stock_on_hand_total',
    'semantic_metric',
    'inventory_stock_on_hand_total',
    '["branch","location","warehouse_code","item_code","item_category_code","supplier_id"]'::jsonb,
    '{"include_zero":false}'::jsonb,
    '["inventory","stock","on_hand"]'::jsonb,
    'Inventory Control',
    'approved',
    true,
    65,
    'seed',
    'seed'
  ),
  (
    'inventory_item_with_stock_count',
    'Inventory Item With Stock Count',
    'Items With Stock',
    'inventory',
    'Jumlah row item-gudang yang masih memiliki stok positif.',
    'Menghitung berapa banyak kombinasi item dan gudang yang current stock-nya lebih besar dari nol.',
    'item',
    'count',
    'threshold',
    'inventory_item_with_stock_count',
    'inventory_item_with_stock_count',
    'semantic_metric',
    'inventory_item_with_stock_count',
    '["branch","location","warehouse_code","item_code","item_category_code","supplier_id"]'::jsonb,
    '{"stock_gt":0}'::jsonb,
    '["inventory","stock","positive","count"]'::jsonb,
    'Inventory Control',
    'reviewed',
    true,
    66,
    'seed',
    'seed'
  ),
  (
    'inventory_stock_value_total',
    'Inventory Stock Value Total',
    'Stock Value',
    'inventory',
    'Estimasi total nilai inventory berdasarkan stock dan average cost.',
    'Mengukur total nilai stok inventory dari current stock dikalikan average cost.',
    'idr',
    'currency',
    'threshold',
    'inventory_stock_value_total',
    'inventory_stock_value_total',
    'semantic_metric',
    'inventory_stock_value_total',
    '["branch","location","warehouse_code","item_code","item_category_code","supplier_id"]'::jsonb,
    '{"include_zero":false,"formula":"current_stock*average_cost"}'::jsonb,
    '["inventory","stock","value"]'::jsonb,
    'Inventory Control',
    'approved',
    true,
    67,
    'seed',
    'seed'
  ),
  (
    'inventory_active_item_stock_count',
    'Inventory Active Item Stock Count',
    'Active Stock Items',
    'inventory',
    'Jumlah row stock inventory untuk item yang aktif.',
    'Menghitung row inventory stock yang masih aktif untuk keperluan pengendalian master data dan stock.',
    'item',
    'count',
    'threshold',
    'inventory_active_item_stock_count',
    'inventory_active_item_stock_count',
    'semantic_metric',
    'inventory_active_item_stock_count',
    '["branch","location","warehouse_code","item_code","item_category_code"]'::jsonb,
    '{"is_active":1}'::jsonb,
    '["inventory","stock","active"]'::jsonb,
    'Inventory Master Data',
    'reviewed',
    true,
    68,
    'seed',
    'seed'
  ),
  (
    'inventory_document_history_event_count',
    'Inventory Document History Event Count',
    'Document Events',
    'inventory',
    'Jumlah event history dokumen inventory.',
    'Menghitung berapa banyak perubahan status dan history event pada dokumen inventory.',
    'event',
    'count',
    'threshold',
    'inventory_document_history_event_count',
    'inventory_document_history_event_count',
    'semantic_metric',
    'inventory_document_history_event_count',
    '["branch_code","location_code","warehouse_from_code","warehouse_to_code","source_doc_type","doc_status_code"]'::jsonb,
    '{"period":"current_month"}'::jsonb,
    '["inventory","document","history","event"]'::jsonb,
    'Inventory Operations',
    'reviewed',
    true,
    69,
    'seed',
    'seed'
  ),
  (
    'inventory_transfer_event_count',
    'Inventory Transfer Event Count',
    'Transfer Events',
    'inventory',
    'Jumlah event history untuk dokumen transfer stock inventory.',
    'Menghitung event inventory yang terkait dengan dokumen transfer stock.',
    'event',
    'count',
    'threshold',
    'inventory_transfer_event_count',
    'inventory_transfer_event_count',
    'semantic_metric',
    'inventory_transfer_event_count',
    '["branch_code","location_code","warehouse_from_code","warehouse_transit_code","warehouse_to_code","doc_status_code"]'::jsonb,
    '{"period":"current_month","source_doc_type":"TS"}'::jsonb,
    '["inventory","transfer","event"]'::jsonb,
    'Inventory Operations',
    'approved',
    true,
    70,
    'seed',
    'seed'
  ),
  (
    'inventory_receive_event_count',
    'Inventory Receive Event Count',
    'Receive Events',
    'inventory',
    'Jumlah event history untuk dokumen receive stock inventory.',
    'Menghitung event inventory yang terkait dengan dokumen receive stock.',
    'event',
    'count',
    'threshold',
    'inventory_receive_event_count',
    'inventory_receive_event_count',
    'semantic_metric',
    'inventory_receive_event_count',
    '["branch_code","location_code","warehouse_from_code","warehouse_to_code","doc_status_code"]'::jsonb,
    '{"period":"current_month","source_doc_type":"RS"}'::jsonb,
    '["inventory","receive","event"]'::jsonb,
    'Inventory Operations',
    'approved',
    true,
    71,
    'seed',
    'seed'
  ),
  (
    'inventory_daily_check_count',
    'Inventory Daily Check Count',
    'Daily Check Count',
    'inventory',
    'Jumlah row daily check inventory.',
    'Menghitung total daily check inventory berdasarkan shift, item, dan kategori pengecekan.',
    'check',
    'count',
    'threshold',
    'inventory_daily_check_count',
    'inventory_daily_check_count',
    'semantic_metric',
    'inventory_daily_check_count',
    '["branch_code","location_code","shift_code","item_id","check_category_id","check_status"]'::jsonb,
    '{"period":"current_day"}'::jsonb,
    '["inventory","daily_check","count"]'::jsonb,
    'Inventory Supervisor',
    'reviewed',
    true,
    72,
    'seed',
    'seed'
  ),
  (
    'inventory_daily_check_issue_count',
    'Inventory Daily Check Issue Count',
    'Daily Check Issues',
    'inventory',
    'Jumlah daily check inventory yang berstatus issue, fail, atau exception.',
    'Menghitung row daily check inventory yang mengindikasikan masalah operasional.',
    'issue',
    'count',
    'threshold',
    'inventory_daily_check_issue_count',
    'inventory_daily_check_issue_count',
    'semantic_metric',
    'inventory_daily_check_issue_count',
    '["branch_code","location_code","shift_code","item_id","check_category_id","check_status"]'::jsonb,
    '{"period":"current_day","issue_only":true}'::jsonb,
    '["inventory","daily_check","issue"]'::jsonb,
    'Inventory Supervisor',
    'approved',
    true,
    73,
    'seed',
    'seed'
  ),
  (
    'inventory_inactive_item_stock_count',
    'Inventory Inactive Item Stock Count',
    'Inactive Stock Items',
    'inventory',
    'Jumlah row stock inventory untuk item yang sudah tidak aktif.',
    'Menghitung stock row yang masih ada walaupun item atau row inventory-nya sudah inactive.',
    'item',
    'count',
    'threshold',
    'inventory_inactive_item_stock_count',
    'inventory_inactive_item_stock_count',
    'semantic_metric',
    'inventory_inactive_item_stock_count',
    '["branch","location","warehouse_code","item_code","item_category_code"]'::jsonb,
    '{"is_active":0}'::jsonb,
    '["inventory","stock","inactive"]'::jsonb,
    'Inventory Master Data',
    'reviewed',
    true,
    74,
    'seed',
    'seed'
  ),
  (
    'negative_stock_count',
    'Negative Stock Count',
    'Negative Stock',
    'warehouse',
    'Jumlah item-lokasi dengan stock balance negatif.',
    'Menghitung berapa banyak kombinasi item dan warehouse yang memiliki stock balance di bawah nol.',
    'count',
    'count',
    'threshold',
    'negative_stock_count',
    'negative_stock_row_count',
    'semantic_metric',
    'negative_stock_count',
    '["warehouse","item","category"]'::jsonb,
    '{"include_zero":false}'::jsonb,
    '["warehouse","stock","negative"]'::jsonb,
    'Warehouse Supervisor',
    'approved',
    true,
    50,
    'seed',
    'seed'
  ),
  (
    'inventory_aging_90_plus',
    'Inventory Aging 90+ Days',
    'Aging 90+',
    'warehouse',
    'Jumlah atau nilai inventory yang berumur lebih dari 90 hari.',
    'Menunjukkan inventory slow-moving dengan umur stock di atas 90 hari.',
    'idr',
    'currency',
    'threshold',
    'inventory_aging_90_plus',
    'inventory_aging_value_90_plus',
    'semantic_metric',
    'inventory_aging_90_plus',
    '["warehouse","item","category"]'::jsonb,
    '{"aging_days":90}'::jsonb,
    '["warehouse","inventory","aging","slow_moving"]'::jsonb,
    'Inventory Analyst',
    'reviewed',
    true,
    60,
    'seed',
    'seed'
  ),
  (
    'inventory_coverage_days',
    'Inventory Coverage Days',
    'Coverage Days',
    'warehouse',
    'Estimasi daya tahan stok berdasarkan saldo saat ini dan laju konsumsi atau outbound.',
    'Menunjukkan berapa hari stok masih cukup sebelum perlu replenishment atau intervensi pembelian.',
    'day',
    'days',
    'threshold',
    'inventory_coverage_days',
    NULL,
    'semantic_metric',
    'inventory_coverage_days',
    '["warehouse","item","category"]'::jsonb,
    '{}'::jsonb,
    '["warehouse","coverage"]'::jsonb,
    'Inventory Analyst',
    'reviewed',
    true,
    65,
    'seed',
    'seed'
  ),
  (
    'purchase_price_variance',
    'Purchase Price Variance',
    'Price Variance',
    'purchasing',
    'Selisih harga beli terhadap baseline atau pembelian sebelumnya.',
    'Mengukur kenaikan atau penurunan harga beli dibanding referensi yang disetujui.',
    'percent',
    'percent',
    'threshold',
    'purchase_price_variance',
    'purchase_price_variance_pct',
    'semantic_metric',
    'purchase_price_variance',
    '["supplier","item","branch"]'::jsonb,
    '{"baseline":"previous_purchase"}'::jsonb,
    '["purchasing","price","variance"]'::jsonb,
    'Procurement Lead',
    'reviewed',
    true,
    70,
    'seed',
    'seed'
  ),
  (
    'open_purchase_order_total',
    'Open Purchase Order Total',
    'Open PO',
    'purchasing',
    'Nilai total purchase order yang masih open.',
    'Menunjukkan exposure open purchase order yang belum selesai diproses.',
    'idr',
    'currency',
    'threshold',
    'open_purchase_order_total',
    'purchase_order_open_total_amount',
    'semantic_metric',
    'open_purchase_order_total',
    '["supplier","branch","buyer"]'::jsonb,
    '{"status":"open"}'::jsonb,
    '["purchasing","po","open"]'::jsonb,
    'Procurement Analyst',
    'approved',
    true,
    80,
    'seed',
    'seed'
  )
ON CONFLICT (metric_key) DO UPDATE SET
  label = EXCLUDED.label,
  short_label = EXCLUDED.short_label,
  module_key = EXCLUDED.module_key,
  description = EXCLUDED.description,
  business_definition = EXCLUDED.business_definition,
  unit = EXCLUDED.unit,
  value_type = EXCLUDED.value_type,
  comparison_type = EXCLUDED.comparison_type,
  semantic_ref = EXCLUDED.semantic_ref,
  system_metric_ref = EXCLUDED.system_metric_ref,
  source_type = EXCLUDED.source_type,
  source_ref = EXCLUDED.source_ref,
  supported_dimensions = EXCLUDED.supported_dimensions,
  default_filters = EXCLUDED.default_filters,
  tags = EXCLUDED.tags,
  owner_name = EXCLUDED.owner_name,
  review_status = EXCLUDED.review_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order,
  updated_by = EXCLUDED.updated_by,
  updated_at = now(),
  deleted_at = NULL;
