CREATE TABLE IF NOT EXISTS public.obt_inventory_document_history_line_event (
    inventory_history_line_key text PRIMARY KEY,
    obt_name text NOT NULL DEFAULT 'obt_inventory_document_history_line_event',
    source_module text NOT NULL,
    source_doc_type text NOT NULL,
    source_history_id text NOT NULL,
    source_header_id text NOT NULL,
    source_detail_id text NOT NULL,
    doc_no text,
    doc_date timestamptz,
    branch_code text,
    branch_name text,
    location_code text,
    location_name text,
    warehouse_from_code text,
    warehouse_from_name text,
    warehouse_transit_code text,
    warehouse_transit_name text,
    warehouse_to_code text,
    warehouse_to_name text,
    item_id text,
    item_code text,
    item_name text,
    uom_code text,
    qty_in numeric(20,6),
    qty_out numeric(20,6),
    qty_balance numeric(20,6),
    unit_value numeric(20,6),
    amount numeric(20,6),
    inventory_account_code text,
    offset_account_code text,
    cost_center_code text,
    division_code text,
    subdivision_code text,
    project_code text,
    notes text,
    line_order bigint,
    source_payload jsonb,
    etl_batch_id text,
    etl_loaded_at timestamptz NOT NULL DEFAULT now(),
    etl_updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_obt_inventory_document_history_line_doc
    ON public.obt_inventory_document_history_line_event (source_doc_type, doc_no, doc_date);
