-- Physical OBT table for MyERPPlus sales order line flow.
-- Grain:
--   one row per m5_so_detail.idsodetail
-- Purpose:
--   make sales-order-level transactions visible immediately in PostgreSQL OBT
--   without waiting for invoice-line anchored OBT materialization

CREATE TABLE IF NOT EXISTS obt_sales_order_line_flow (
    source_module text,
    obt_name text,
    source_doc_type text,
    source_header_id bigint,
    source_detail_id bigint,
    doc_no text,
    doc_date timestamp without time zone,
    doc_status_code bigint,
    doc_status_name text,
    doc_notes text,
    branch_code text,
    branch_name text,
    location_code text,
    location_name text,
    contact_id bigint,
    contact_code text,
    contact_name text,
    sales_contact_id bigint,
    sales_contact_code text,
    sales_contact_name text,
    item_id bigint,
    item_code text,
    item_name text,
    line_no bigint,
    uom_code text,
    qty numeric(20,6),
    qty_base numeric(20,6),
    qty_realized numeric(20,6),
    unit_price numeric(20,6),
    discount_percent numeric(20,6),
    discount_amount numeric(20,6),
    amount numeric(20,6),
    currency_code text,
    exchange_rate numeric(20,6),
    input_user_id bigint,
    input_user_name text,
    modified_user_id bigint,
    modified_user_name text,
    sq_header_id bigint,
    sq_detail_id bigint,
    sq_no text,
    sq_date timestamp without time zone,
    sq_status_code bigint,
    sq_status_name text,
    qty_sq numeric(20,6),
    qty_sq_base numeric(20,6),
    qty_realized_sq numeric(20,6),
    pi_doc_count bigint,
    pi_doc_nos text,
    first_pi_date timestamp without time zone,
    last_pi_date timestamp without time zone,
    qty_pi numeric(20,6),
    qty_pi_base numeric(20,6),
    qty_realized_pi numeric(20,6),
    pl_doc_count bigint,
    pl_doc_nos text,
    first_pl_date timestamp without time zone,
    last_pl_date timestamp without time zone,
    qty_pl numeric(20,6),
    qty_pl_base numeric(20,6),
    qty_realized_pl numeric(20,6),
    do_doc_count bigint,
    do_doc_nos text,
    first_do_date timestamp without time zone,
    last_do_date timestamp without time zone,
    qty_do numeric(20,6),
    qty_do_base numeric(20,6),
    qty_realized_do numeric(20,6),
    si_doc_count bigint,
    si_doc_nos text,
    first_si_date timestamp without time zone,
    last_si_date timestamp without time zone,
    qty_si numeric(20,6),
    qty_si_base numeric(20,6),
    amount_si numeric(20,6),
    dr_doc_count bigint,
    dr_doc_nos text,
    first_dr_date timestamp without time zone,
    last_dr_date timestamp without time zone,
    qty_dr numeric(20,6),
    qty_dr_base numeric(20,6),
    qty_returned_dr numeric(20,6),
    rnr_doc_count bigint,
    rnr_doc_nos text,
    first_rnr_date timestamp without time zone,
    last_rnr_date timestamp without time zone,
    qty_rnr numeric(20,6),
    qty_rnr_base numeric(20,6),
    sr_doc_count bigint,
    sr_doc_nos text,
    first_sr_date timestamp without time zone,
    last_sr_date timestamp without time zone,
    qty_sr numeric(20,6),
    qty_sr_base numeric(20,6),
    upstream_doc_no text,
    downstream_doc_no text,
    lineage_path text,
    etl_loaded_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_obt_sales_order_line_flow_source_detail
    ON obt_sales_order_line_flow (source_module, source_detail_id);

CREATE INDEX IF NOT EXISTS ix_obt_sales_order_line_flow_doc_date
    ON obt_sales_order_line_flow (doc_date);
