INSERT INTO public.dim_finance_giro_list (
    source_code,
    source_header_id,
    giro_no,
    line_no,
    doc_no,
    contact_id,
    contact_code,
    contact_name,
    bank_account_code,
    giro_account_code,
    giro_type,
    bank_name,
    bank_account_no,
    currency_code,
    exchange_rate,
    amount,
    amount_foreign,
    due_date,
    cleared_date,
    status_code,
    previous_status_code,
    source_payload,
    etl_batch_id,
    etl_loaded_at,
    etl_updated_at
)
SELECT
    gl.glsumber AS source_code,
    gl.glidtransaksi::text AS source_header_id,
    gl.glnogiro AS giro_no,
    COALESCE(NULLIF(BTRIM(gl.glurutan::text), '')::bigint, 0::bigint) AS line_no,
    gl.glnotransaksi AS doc_no,
    NULLIF(BTRIM(gl.glkontak::text), '') AS contact_id,
    ct.kkode AS contact_code,
    ct.knama AS contact_name,
    gl.glrekbank AS bank_account_code,
    gl.glrekgiro AS giro_account_code,
    NULLIF(BTRIM(gl.gljenis::text), '')::bigint AS giro_type,
    gl.glbank AS bank_name,
    gl.glnoacbank AS bank_account_no,
    gl.glmatauang AS currency_code,
    NULLIF(BTRIM(gl.glkurs::text), '')::numeric(20,6) AS exchange_rate,
    NULLIF(BTRIM(gl.gljumlah::text), '')::numeric(20,6) AS amount,
    NULLIF(BTRIM(gl.gljumlahvalas::text), '')::numeric(20,6) AS amount_foreign,
    gl.gltgljthtempo::timestamp without time zone AS due_date,
    gl.gltglcair::timestamp without time zone AS cleared_date,
    NULLIF(BTRIM(gl.glstatus::text), '')::bigint AS status_code,
    NULLIF(BTRIM(gl.glstatussebelumnya::text), '')::bigint AS previous_status_code,
    gl._cdc_payload AS source_payload,
    'baseline-dim-finance-giro-list-v1' AS etl_batch_id,
    clock_timestamp() AS etl_loaded_at,
    clock_timestamp() AS etl_updated_at
FROM myerpplus_landing.m2_giro_list gl
LEFT JOIN myerpplus_landing.m1_contact ct
    ON ct.kid = NULLIF(BTRIM(gl.glkontak::text), '')::bigint
WHERE COALESCE(gl._cdc_deleted, false) = false
ON CONFLICT (source_code, source_header_id, giro_no, line_no) DO UPDATE SET
    doc_no = EXCLUDED.doc_no,
    contact_id = EXCLUDED.contact_id,
    contact_code = EXCLUDED.contact_code,
    contact_name = EXCLUDED.contact_name,
    bank_account_code = EXCLUDED.bank_account_code,
    giro_account_code = EXCLUDED.giro_account_code,
    giro_type = EXCLUDED.giro_type,
    bank_name = EXCLUDED.bank_name,
    bank_account_no = EXCLUDED.bank_account_no,
    currency_code = EXCLUDED.currency_code,
    exchange_rate = EXCLUDED.exchange_rate,
    amount = EXCLUDED.amount,
    amount_foreign = EXCLUDED.amount_foreign,
    due_date = EXCLUDED.due_date,
    cleared_date = EXCLUDED.cleared_date,
    status_code = EXCLUDED.status_code,
    previous_status_code = EXCLUDED.previous_status_code,
    source_payload = EXCLUDED.source_payload,
    etl_batch_id = EXCLUDED.etl_batch_id,
    etl_updated_at = clock_timestamp();
