INSERT INTO public.dim_item (
    item_id,
    item_code,
    item_name,
    item_type,
    item_category_code,
    class_product_code,
    default_uom_code,
    sales_uom_code,
    branch_code,
    location_code,
    warehouse_code,
    supplier_id,
    inventory_account_code,
    sales_account_code,
    is_active,
    active_at,
    current_stock,
    average_cost,
    notes,
    source_payload,
    etl_batch_id,
    etl_loaded_at,
    etl_updated_at
)
SELECT
    bid,
    bkode,
    bnama,
    btipe,
    bkategori,
    bkelasproduk,
    bsatuandefault,
    bsatuan,
    bcabang,
    blokasi,
    bgudang,
    bsuplier,
    brekpersediaan,
    brekpenjualan,
    baktif,
    baktiftgl,
    NULLIF(bstok, '')::numeric(30,6),
    NULLIF(bhppaverage, '')::numeric(30,6),
    bcatatan,
    _cdc_payload,
    'baseline-dim-item-v1',
    clock_timestamp(),
    clock_timestamp()
FROM myerpplus_landing.m1_item
WHERE COALESCE(_cdc_deleted, false) = false;
