INSERT INTO public.obt_finance_budget_realization (
    obt_name,
    source_module,
    source_doc_type,
    source_header_id,
    source_detail_id,
    source_allocation_id,
    doc_no,
    doc_date,
    doc_status_code,
    doc_status_name,
    branch_code,
    branch_name,
    location_code,
    location_name,
    contact_id,
    contact_code,
    contact_name,
    item_id,
    item_code,
    item_name,
    uom_code,
    upstream_doc_no,
    downstream_doc_no,
    lineage_path,
    qty,
    amount,
    currency_code,
    exchange_rate,
    input_user_id,
    input_user_name,
    modified_user_id,
    modified_user_name,
    source_payload,
    etl_batch_id,
    etl_loaded_at,
    etl_updated_at
)
SELECT
    'obt_finance_budget_realization' AS obt_name,
    'm2' AS source_module,
    'REALIZATION' AS source_doc_type,
    (r.rtahun::text || '-' || LPAD(r.rbulan::text, 2, '0') || '-' || r.rnorek || '-' || r.rkodepa::text) AS source_header_id,
    NULL::text AS source_detail_id,
    NULL::text AS source_allocation_id,
    ('REAL-' || r.rtahun::text || LPAD(r.rbulan::text, 2, '0') || '-' || r.rnorek) AS doc_no,
    make_timestamp(r.rtahun::int, r.rbulan::int, 1, 0, 0, 0) AT TIME ZONE 'UTC' AS doc_date,
    NULL::text AS doc_status_code,
    'REALIZED' AS doc_status_name,
    NULL::text AS branch_code,
    NULL::text AS branch_name,
    NULL::text AS location_code,
    NULL::text AS location_name,
    NULL::text AS contact_id,
    NULL::text AS contact_code,
    NULL::text AS contact_name,
    NULL::text AS item_id,
    NULL::text AS item_code,
    NULL::text AS item_name,
    NULL::text AS uom_code,
    r.rkodepa::text AS upstream_doc_no,
    NULL::text AS downstream_doc_no,
    'REALIZATION->COA' AS lineage_path,
    NULL::numeric(20,6) AS qty,
    (
        COALESCE(NULLIF(r.rjmldebit::text, '')::numeric(20,6), 0::numeric(20,6))
        - COALESCE(NULLIF(r.rjmlkredit::text, '')::numeric(20,6), 0::numeric(20,6))
    ) AS amount,
    'IDR' AS currency_code,
    1::numeric(20,6) AS exchange_rate,
    NULL::text AS input_user_id,
    NULL::text AS input_user_name,
    NULL::text AS modified_user_id,
    NULL::text AS modified_user_name,
    r._cdc_payload AS source_payload,
    'baseline-finance-budget-realization-v1' AS etl_batch_id,
    clock_timestamp() AS etl_loaded_at,
    clock_timestamp() AS etl_updated_at
FROM myerpplus_landing.m2_realization r
WHERE COALESCE(r._cdc_deleted, false) = false;
