INSERT INTO public.obt_inventory_document_history_line_event (
    inventory_history_line_key, source_module, source_doc_type, source_history_id, source_header_id, source_detail_id, doc_no, doc_date, branch_code, branch_name, location_code, location_name, warehouse_from_code, warehouse_from_name, warehouse_transit_code, warehouse_transit_name, warehouse_to_code, warehouse_to_name, item_id, item_code, item_name, uom_code, qty_in, qty_out, qty_balance, unit_value, amount, inventory_account_code, offset_account_code, cost_center_code, division_code, subdivision_code, project_code, notes, line_order, source_payload, etl_batch_id, etl_loaded_at, etl_updated_at
)
SELECT
    q.inventory_history_line_key, 'm3', q.source_doc_type, q.source_history_id, q.source_header_id, q.source_detail_id, q.doc_no, q.doc_date, q.branch_code, q.branch_name, q.location_code, q.location_name, q.warehouse_from_code, wf.wnama, q.warehouse_transit_code, wt.wnama, q.warehouse_to_code, wto.wnama, q.item_id, itm.bkode, q.item_name, q.uom_code, q.qty_in, q.qty_out, q.qty_balance, q.unit_value, q.amount, q.inventory_account_code, q.offset_account_code, q.cost_center_code, q.division_code, q.subdivision_code, q.project_code, q.notes, q.line_order, q.source_payload, 'baseline-inventory-history-line-v1', clock_timestamp(), clock_timestamp()
FROM (
    SELECT 'TSD:' || idhistorydetail::text AS inventory_history_line_key, 'TS_HISTORY_LINE'::text AS source_doc_type, idhistory::text AS source_history_id, idts::text AS source_header_id, idtsdetail::text AS source_detail_id, h.tsnotransaksi AS doc_no, h.tstgl AS doc_date, h.tscabang AS branch_code, br.bnama AS branch_name, h.tslokasi AS location_code, lc.lnama AS location_name, gudangasal AS warehouse_from_code, gudangtransit AS warehouse_transit_code, gudangtujuan AS warehouse_to_code, idbarang::text AS item_id, namabarang AS item_name, COALESCE(satuanbarang, satuan) AS uom_code, NULL::numeric(20,6) AS qty_in, NULL::numeric(20,6) AS qty_out, COALESCE(jmlbarang, jml) AS qty_balance, nilaisatuan AS unit_value, COALESCE(jmlbarang, jml) * COALESCE(nilaisatuan,0) AS amount, NULL::text AS inventory_account_code, NULL::text AS offset_account_code, costcenter AS cost_center_code, divisi AS division_code, subdivisi AS subdivision_code, proyek AS project_code, catatan AS notes, urutan::bigint AS line_order, d._cdc_payload AS source_payload FROM m3_ts_detail_history d JOIN m3_ts_history h ON h.tsidhistory = d.idhistory LEFT JOIN m1_branch br ON br.bkode = h.tscabang LEFT JOIN m1_location lc ON lc.lkode = h.tslokasi WHERE COALESCE(d._cdc_deleted, false) = false
    UNION ALL
    SELECT 'SAD:' || idhistorydetail::text, 'SA_HISTORY_LINE', idhistory::text, idsa::text, idsadetail::text, h.sanotransaksi, h.satgl, h.sacabang, br.bnama, h.salokasi, lc.lnama, gudang, NULL::text, gudang, idbarang::text, namabarang, COALESCE(satuanbarang, satuan), COALESCE(jmlbarangmasuk, jmlmasuk), COALESCE(jmlbarangkeluar, jmlkeluar), COALESCE(jmlbarangmasuk,0)-COALESCE(jmlbarangkeluar,0), COALESCE(hpp,nilaisatuan), (COALESCE(jmlbarangmasuk,0)-COALESCE(jmlbarangkeluar,0))*COALESCE(hpp,nilaisatuan,0), rekpersediaan, reklawan, costcenter, divisi, subdivisi, proyek, catatan, urutan::bigint, d._cdc_payload FROM m3_sa_detail_history d JOIN m3_sa_history h ON h.saidhistory = d.idhistory LEFT JOIN m1_branch br ON br.bkode = h.sacabang LEFT JOIN m1_location lc ON lc.lkode = h.salokasi WHERE COALESCE(d._cdc_deleted, false) = false
    UNION ALL
    SELECT 'SPD:' || idhistorydetail::text, 'SP_HISTORY_LINE', idhistory::text, idsp::text, idspdetail::text, h.spnotransaksi, h.sptgl, h.spcabang, br.bnama, h.splokasi, lc.lnama, gudang, NULL::text, gudang, idbarang::text, namabarang, COALESCE(satuanbarang, satuan), NULL::numeric(20,6), NULL::numeric(20,6), selisihbarang, nilaisatuan, COALESCE(selisihbarang,0)*COALESCE(nilaisatuan,0), NULL::text, NULL::text, NULL::text, NULL::text, NULL::text, NULL::text, NULL::text, NULL::bigint, d._cdc_payload FROM m3_sp_detail_history d JOIN m3_sp_history h ON h.spidhistory = d.idhistory LEFT JOIN m1_branch br ON br.bkode = h.spcabang LEFT JOIN m1_location lc ON lc.lkode = h.splokasi WHERE COALESCE(d._cdc_deleted, false) = false
    UNION ALL
    SELECT 'IBD:' || idhistorydetail::text, 'IB_HISTORY_LINE', idhistory::text, idib::text, idibdetail::text, h.ibnotransaksi, h.ibtgl, h.ibcabang, br.bnama, h.iblokasi, lc.lnama, gudang, NULL::text, gudang, idbarang::text, namabarang, COALESCE(satuanbarang, satuan), COALESCE(jmlbarang, jml), NULL::numeric(20,6), COALESCE(jmlbarang, jml), COALESCE(hpp,nilaisatuan), COALESCE(jmlbarang, jml)*COALESCE(hpp,nilaisatuan,0), rekpersediaan, NULL::text, costcenter, divisi, subdivisi, proyek, catatan, urutan::bigint, d._cdc_payload FROM m3_ib_detail_history d JOIN m3_ib_history h ON h.ibidhistory = d.idhistory LEFT JOIN m1_branch br ON br.bkode = h.ibcabang LEFT JOIN m1_location lc ON lc.lkode = h.iblokasi WHERE COALESCE(d._cdc_deleted, false) = false
) q
LEFT JOIN m1_item itm ON itm.bid = NULLIF(q.item_id, '')::bigint
LEFT JOIN m1_warehouse wf ON wf.wkode = q.warehouse_from_code
LEFT JOIN m1_warehouse wt ON wt.wkode = q.warehouse_transit_code
LEFT JOIN m1_warehouse wto ON wto.wkode = q.warehouse_to_code;
