INSERT INTO public.dim_item_transaction (
    transaction_id, branch_code, location_code, warehouse_code, mutation_type, source_code,
    source_header_id, source_detail_id, doc_no, doc_date, contact_id, item_id, item_name, item_type,
    qty, uom_code, qty_item, amount, currency_code, exchange_rate, notes, source_payload,
    etl_batch_id, etl_loaded_at, etl_updated_at
)
SELECT
    id,
    cabang,
    lokasi,
    gudang,
    jenismutasi,
    sumber,
    idutama,
    iddetail,
    notransaksi,
    tgl,
    kontak,
    idbarang,
    namabarang,
    tipebarang,
    NULLIF(BTRIM(CAST(jml AS text)), '')::numeric(30,6),
    satuan,
    NULLIF(BTRIM(CAST(jmlbarang AS text)), '')::numeric(30,6),
    NULLIF(BTRIM(CAST(harga AS text)), '')::numeric(30,6),
    matauang,
    NULLIF(BTRIM(CAST(kurs AS text)), '')::numeric(30,6),
    catatan,
    _cdc_payload,
    'baseline-dim-item-transaction-v1',
    clock_timestamp(),
    clock_timestamp()
FROM myerpplus_landing.m1_item_transaction
WHERE COALESCE(_cdc_deleted, false) = false
ON CONFLICT (transaction_id) DO UPDATE SET
    branch_code = EXCLUDED.branch_code,
    location_code = EXCLUDED.location_code,
    warehouse_code = EXCLUDED.warehouse_code,
    mutation_type = EXCLUDED.mutation_type,
    source_code = EXCLUDED.source_code,
    source_header_id = EXCLUDED.source_header_id,
    source_detail_id = EXCLUDED.source_detail_id,
    doc_no = EXCLUDED.doc_no,
    doc_date = EXCLUDED.doc_date,
    contact_id = EXCLUDED.contact_id,
    item_id = EXCLUDED.item_id,
    item_name = EXCLUDED.item_name,
    item_type = EXCLUDED.item_type,
    qty = EXCLUDED.qty,
    uom_code = EXCLUDED.uom_code,
    qty_item = EXCLUDED.qty_item,
    amount = EXCLUDED.amount,
    currency_code = EXCLUDED.currency_code,
    exchange_rate = EXCLUDED.exchange_rate,
    notes = EXCLUDED.notes,
    source_payload = EXCLUDED.source_payload,
    etl_batch_id = EXCLUDED.etl_batch_id,
    etl_updated_at = clock_timestamp();
