import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Sidebar Senti ERP — autogenerated dari struktur folder docs/erp/.
// Urutan diatur via prefix angka folder / front matter sidebar_position.
const sidebars: SidebarsConfig = {
  erpSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
