import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Sidebar Senti MDP — autogenerated dari struktur folder docs/mdp/.
// Urutan diatur via prefix angka folder / front matter sidebar_position.
const sidebars: SidebarsConfig = {
  mdpSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
