import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'contributing',
    {
      type: 'category',
      label: 'Marketing',
      link: {
        type: 'generated-index',
        title: 'Marketing',
        description: 'Marketing documentation and ticket references.',
        slug: '/marketing',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '06-marketing',
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorial MyERPPlus',
      link: {
        type: 'generated-index',
        title: 'Tutorial MyERPPlus',
        description: 'Panduan penggunaan dan pengembangan MyERPPlus.',
        slug: '/tutorial-myerpplus',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '07-tutorial-myerpplus',
        },
      ],
    },
  ],
};

export default sidebars;
