import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Sidebar Senti HR — autogenerated dari struktur folder docs/hr/.
// Urutan diatur via prefix angka folder / front matter sidebar_position.
const sidebars: SidebarsConfig = {
  hrSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
