import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'contributing',
    {
      type: 'category',
      label: 'Marketing',
      link: {
        type: 'generated-index',
        title: 'Marketing',
        description: 'Marketing documentation and ticket references.',
        slug: '/marketing',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '06-marketing',
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorial MyERPPlus',
      link: {
        type: 'doc',
        id: 'tutorial-myerpplus/getting-started',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '07-tutorial-myerpplus',
        },
      ],
    },
    {
      type: 'category',
      label: 'OBT',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'OBT',
        description: 'Cross-module semantic OBT concepts and blueprint for MyERPPlus.',
        slug: '/obt',
      },
      items: [
        'obt/konsep-obt-m0-m12',
        'obt/semantic-obt-blueprint',
        'obt/semantic-cross-module-lineage',
      ],
    },
  ],
};

export default sidebars;
