/**
 * Konsolidasi semua FEATURE_COPY entries untuk dashboard m2_*.
 *
 * Setiap m2_* page punya entry sendiri di sini — di-lookup oleh `M2Dashboard`
 * via prop `feature`. Sebelumnya tiap page punya FEATURE_COPY map sendiri
 * (duplikasi ~30 baris × 7 file).
 */
export type M2FeatureCopy = {
  description: string;
  kpi1: string;
  kpi2: string;
  kpi3: string;
  kpi4: string;
  trendTitle: string;
  flowTitle: string;
  sourceTitle: string;
  branchTitle: string;
  statusTitle: string;
  tableTitle: string;
  insightTitle: string;
  insightHighlights: string;
  insightAnomalies: string;
  insightRecommendations: string;
  totalBranchTitle: string;
  totalSourceTitle: string;
  emptyStatusText: string;
  emptyInsightText: string;
  emptyAnomalyText: string;
  emptyRecommendationText: string;
  emptyTableText: string;
};

export const M2_FEATURE_LABELS: Record<string, string> = {
  m2_aj: 'Jurnal Penyesuaian (AJ)',
  m2_bd: 'Anggaran (BD)',
  m2_cb: 'Saldo Awal COA (CB)',
  m2_cr: 'Kas Masuk (CR)',
  m2_cd: 'Kas Keluar (CD)',
  m2_gj: 'Jurnal Umum (GJ)',
  m2_jm: 'Jurnal Memorial (JM)',
  m2_rg: 'Giro Masuk (RG)',
  m2_rgc: 'Giro Masuk Batal (RGC)',
  m2_rm: 'Bank Receipt (RM)',
  m2_sg: 'Giro Keluar (SG)',
  m2_sgc: 'Giro Keluar Batal (SGC)',
  m2_sm: 'Bank Payment (SM)',
  m2_template: 'Template Jurnal (TJ)',
};

export const M2_FEATURE_COPY: Record<string, M2FeatureCopy> = {
  default: {
    description:
      'Dashboard Finance & Accounting dengan KPI, chart, breakdown, dan list transaksi.',
    kpi1: 'Total Jurnal',
    kpi2: 'Total Debit',
    kpi3: 'Total Kredit',
    kpi4: 'Net Cashflow',
    trendTitle: 'Trend Debit vs Kredit',
    flowTitle: 'Cash In vs Cash Out',
    sourceTitle: 'Komposisi Sumber',
    branchTitle: 'Top Cabang',
    statusTitle: 'Ringkasan Status',
    tableTitle: 'List Transaksi (Sample)',
    insightTitle: 'AI Insight',
    insightHighlights: 'Highlights',
    insightAnomalies: 'Anomaly Alerts',
    insightRecommendations: 'Recommendations',
    totalBranchTitle: 'Total Cabang',
    totalSourceTitle: 'Total Sumber',
    emptyStatusText: 'No status data.',
    emptyInsightText: 'No insight generated.',
    emptyAnomalyText: 'No anomaly detected.',
    emptyRecommendationText: 'No recommendation.',
    emptyTableText: 'Tidak ada data tabel.',
  },
  m2_bd: {
    description:
      'Dashboard Anggaran (BD) untuk memantau nilai anggaran, realisasi pergerakan, dan status dokumen.',
    kpi1: 'Total Dokumen Anggaran',
    kpi2: 'Total Nilai Anggaran',
    kpi3: 'Total Realisasi Anggaran',
    kpi4: 'Selisih Anggaran',
    trendTitle: 'Trend Nilai Anggaran vs Realisasi',
    flowTitle: 'Alokasi Anggaran vs Realisasi',
    sourceTitle: 'Komposisi Sumber Anggaran',
    branchTitle: 'Top Cabang Berdasarkan Anggaran',
    statusTitle: 'Ringkasan Status Anggaran',
    tableTitle: 'List Dokumen Anggaran (Sample)',
    insightTitle: 'AI Insight Anggaran',
    insightHighlights: 'Sorotan Anggaran',
    insightAnomalies: 'Anomali Anggaran',
    insightRecommendations: 'Rekomendasi Anggaran',
    totalBranchTitle: 'Total Cabang Anggaran',
    totalSourceTitle: 'Total Sumber Anggaran',
    emptyStatusText: 'Tidak ada data status anggaran.',
    emptyInsightText: 'Belum ada insight anggaran.',
    emptyAnomalyText: 'Belum ada anomali anggaran.',
    emptyRecommendationText: 'Belum ada rekomendasi anggaran.',
    emptyTableText: 'Tidak ada data dokumen anggaran.',
  },
  m2_sg: {
    description:
      'Dashboard Giro Keluar (SG) untuk memantau pengeluaran via giro, nilai pembayaran, dan distribusi transaksi.',
    kpi1: 'Total Transaksi Giro Keluar',
    kpi2: 'Total Nilai Giro Keluar',
    kpi3: 'Total Terbayar',
    kpi4: 'Outstanding Giro',
    trendTitle: 'Trend Giro Keluar vs Terbayar',
    flowTitle: 'Arus Pembayaran Giro',
    sourceTitle: 'Komposisi Sumber Giro Keluar',
    branchTitle: 'Top Cabang Pembayaran Giro',
    statusTitle: 'Ringkasan Status Giro Keluar',
    tableTitle: 'List Transaksi Giro Keluar (Sample)',
    insightTitle: 'AI Insight Giro Keluar',
    insightHighlights: 'Ringkasan',
    insightAnomalies: 'Anomali',
    insightRecommendations: 'Rekomendasi',
    totalBranchTitle: 'Total Cabang',
    totalSourceTitle: 'Total Sumber',
    emptyStatusText: 'Belum ada data status giro keluar.',
    emptyInsightText: 'Belum ada insight giro keluar.',
    emptyAnomalyText: 'Belum ada anomali giro keluar.',
    emptyRecommendationText: 'Belum ada rekomendasi giro keluar.',
    emptyTableText: 'Tidak ada data transaksi giro keluar.',
  },
  m2_sgc: {
    description:
      'Dashboard Giro Keluar Batal (SGC) untuk memantau pembatalan giro keluar, tren nilai pembatalan, dan distribusi transaksi.',
    kpi1: 'Total Transaksi Batal',
    kpi2: 'Total Nilai Giro Batal',
    kpi3: 'Total Nilai Reversal',
    kpi4: 'Net Pembatalan',
    trendTitle: 'Trend Giro Batal vs Reversal',
    flowTitle: 'Arus Nilai Pembatalan',
    sourceTitle: 'Komposisi Sumber Giro Batal',
    branchTitle: 'Top Cabang Pembatalan',
    statusTitle: 'Ringkasan Status Giro Batal',
    tableTitle: 'List Transaksi Giro Keluar Batal (Sample)',
    insightTitle: 'AI Insight Giro Keluar Batal',
    insightHighlights: 'Ringkasan',
    insightAnomalies: 'Anomali',
    insightRecommendations: 'Rekomendasi',
    totalBranchTitle: 'Total Cabang',
    totalSourceTitle: 'Total Sumber',
    emptyStatusText: 'Belum ada data status giro keluar batal.',
    emptyInsightText: 'Belum ada insight giro keluar batal.',
    emptyAnomalyText: 'Belum ada anomali giro keluar batal.',
    emptyRecommendationText: 'Belum ada rekomendasi giro keluar batal.',
    emptyTableText: 'Tidak ada data transaksi giro keluar batal.',
  },
  m2_rm: {
    description:
      'Dashboard Bank Receipt (RM) untuk memantau penerimaan bank, tren realisasi, dan distribusi transaksi.',
    kpi1: 'Total Transaksi Bank Receipt',
    kpi2: 'Total Nilai Receipt',
    kpi3: 'Total Terealisasi',
    kpi4: 'Outstanding Receipt',
    trendTitle: 'Trend Receipt vs Realisasi',
    flowTitle: 'Arus Penerimaan Bank',
    sourceTitle: 'Komposisi Sumber Receipt',
    branchTitle: 'Top Cabang Receipt',
    statusTitle: 'Ringkasan Status Bank Receipt',
    tableTitle: 'List Transaksi Bank Receipt (Sample)',
    insightTitle: 'AI Insight Bank Receipt',
    insightHighlights: 'Ringkasan',
    insightAnomalies: 'Anomali',
    insightRecommendations: 'Rekomendasi',
    totalBranchTitle: 'Total Cabang',
    totalSourceTitle: 'Total Sumber',
    emptyStatusText: 'Belum ada data status bank receipt.',
    emptyInsightText: 'Belum ada insight bank receipt.',
    emptyAnomalyText: 'Belum ada anomali bank receipt.',
    emptyRecommendationText: 'Belum ada rekomendasi bank receipt.',
    emptyTableText: 'Tidak ada data transaksi bank receipt.',
  },
  m2_rg: {
    description:
      'Dashboard Giro Masuk (RG) untuk memantau penerimaan giro, tren pencairan, dan distribusi transaksi.',
    kpi1: 'Total Transaksi Giro Masuk',
    kpi2: 'Total Nilai Giro Masuk',
    kpi3: 'Total Tercairkan',
    kpi4: 'Outstanding Giro',
    trendTitle: 'Trend Giro Masuk vs Tercairkan',
    flowTitle: 'Arus Penerimaan Giro',
    sourceTitle: 'Komposisi Sumber Giro Masuk',
    branchTitle: 'Top Cabang Giro Masuk',
    statusTitle: 'Ringkasan Status Giro Masuk',
    tableTitle: 'List Transaksi Giro Masuk (Sample)',
    insightTitle: 'AI Insight Giro Masuk',
    insightHighlights: 'Ringkasan',
    insightAnomalies: 'Anomali',
    insightRecommendations: 'Rekomendasi',
    totalBranchTitle: 'Total Cabang',
    totalSourceTitle: 'Total Sumber',
    emptyStatusText: 'Belum ada data status giro masuk.',
    emptyInsightText: 'Belum ada insight giro masuk.',
    emptyAnomalyText: 'Belum ada anomali giro masuk.',
    emptyRecommendationText: 'Belum ada rekomendasi giro masuk.',
    emptyTableText: 'Tidak ada data transaksi giro masuk.',
  },
  m2_rgc: {
    description:
      'Dashboard Giro Masuk Batal (RGC) untuk memantau pembatalan giro masuk, tren reversal, dan distribusi transaksi.',
    kpi1: 'Total Transaksi Giro Batal',
    kpi2: 'Total Nilai Giro Batal',
    kpi3: 'Total Nilai Reversal',
    kpi4: 'Net Pembatalan',
    trendTitle: 'Trend Giro Batal vs Reversal',
    flowTitle: 'Arus Pembatalan Giro',
    sourceTitle: 'Komposisi Sumber Giro Batal',
    branchTitle: 'Top Cabang Giro Batal',
    statusTitle: 'Ringkasan Status Giro Masuk Batal',
    tableTitle: 'List Transaksi Giro Masuk Batal (Sample)',
    insightTitle: 'AI Insight Giro Masuk Batal',
    insightHighlights: 'Ringkasan',
    insightAnomalies: 'Anomali',
    insightRecommendations: 'Rekomendasi',
    totalBranchTitle: 'Total Cabang',
    totalSourceTitle: 'Total Sumber',
    emptyStatusText: 'Belum ada data status giro masuk batal.',
    emptyInsightText: 'Belum ada insight giro masuk batal.',
    emptyAnomalyText: 'Belum ada anomali giro masuk batal.',
    emptyRecommendationText: 'Belum ada rekomendasi giro masuk batal.',
    emptyTableText: 'Tidak ada data transaksi giro masuk batal.',
  },
  m2_cd: {
    description:
      'Dashboard Kas Keluar (CD) untuk memantau pengeluaran kas, tren pembayaran, dan status transaksi.',
    kpi1: 'Total Transaksi Kas Keluar',
    kpi2: 'Total Kas Keluar',
    kpi3: 'Total Terbayar',
    kpi4: 'Outstanding Pengeluaran',
    trendTitle: 'Trend Kas Keluar vs Terbayar',
    flowTitle: 'Arus Pengeluaran Kas',
    sourceTitle: 'Komposisi Sumber Kas Keluar',
    branchTitle: 'Top Cabang Pengeluaran',
    statusTitle: 'Ringkasan Status Kas Keluar',
    tableTitle: 'List Transaksi Kas Keluar (Sample)',
    insightTitle: 'AI Insight Kas Keluar',
    insightHighlights: 'Ringkasan',
    insightAnomalies: 'Anomali',
    insightRecommendations: 'Rekomendasi',
    totalBranchTitle: 'Total Cabang',
    totalSourceTitle: 'Total Sumber',
    emptyStatusText: 'Belum ada data status kas keluar.',
    emptyInsightText: 'Belum ada insight kas keluar.',
    emptyAnomalyText: 'Belum ada anomali kas keluar.',
    emptyRecommendationText: 'Belum ada rekomendasi kas keluar.',
    emptyTableText: 'Tidak ada data transaksi kas keluar.',
  },
  m2_cb: {
    description:
      'Dashboard Saldo Awal COA (CB) untuk memantau nominal opening balance, status posting, dan konsistensi saldo awal.',
    kpi1: 'Total Dokumen Saldo Awal',
    kpi2: 'Total Debit Saldo Awal',
    kpi3: 'Total Kredit Saldo Awal',
    kpi4: 'Net Opening Balance',
    trendTitle: 'Trend Debit vs Kredit Saldo Awal',
    flowTitle: 'Debit vs Kredit per Periode',
    sourceTitle: 'Komposisi Sumber Saldo Awal',
    branchTitle: 'Top Cabang Berdasarkan Saldo Awal',
    statusTitle: 'Ringkasan Status Saldo Awal',
    tableTitle: 'List Dokumen Saldo Awal (Sample)',
    insightTitle: 'AI Insight Saldo Awal COA',
    insightHighlights: 'Sorotan Saldo Awal',
    insightAnomalies: 'Anomali Saldo Awal',
    insightRecommendations: 'Rekomendasi Saldo Awal',
    totalBranchTitle: 'Total Cabang',
    totalSourceTitle: 'Total Sumber',
    emptyStatusText: 'Tidak ada data status saldo awal.',
    emptyInsightText: 'Belum ada insight saldo awal.',
    emptyAnomalyText: 'Belum ada anomali saldo awal.',
    emptyRecommendationText: 'Belum ada rekomendasi saldo awal.',
    emptyTableText: 'Tidak ada data dokumen saldo awal.',
  },
  m2_sm: {
    description:
      'Dashboard Bank Payment (SM) untuk memantau pembayaran bank, tren pengeluaran, dan kualitas transaksi.',
    kpi1: 'Total Transaksi Bank Payment',
    kpi2: 'Total Nilai Pembayaran',
    kpi3: 'Total Terealisasi',
    kpi4: 'Outstanding Payment',
    trendTitle: 'Trend Payment vs Realisasi',
    flowTitle: 'Arus Payment Bank',
    sourceTitle: 'Komposisi Sumber Payment',
    branchTitle: 'Top Cabang Payment',
    statusTitle: 'Ringkasan Status Bank Payment',
    tableTitle: 'List Transaksi Bank Payment (Sample)',
    insightTitle: 'AI Insight Bank Payment',
    insightHighlights: 'Ringkasan',
    insightAnomalies: 'Anomali',
    insightRecommendations: 'Rekomendasi',
    totalBranchTitle: 'Total Cabang',
    totalSourceTitle: 'Total Sumber',
    emptyStatusText: 'Belum ada data status bank payment.',
    emptyInsightText: 'Belum ada insight bank payment.',
    emptyAnomalyText: 'Belum ada anomali bank payment.',
    emptyRecommendationText: 'Belum ada rekomendasi bank payment.',
    emptyTableText: 'Tidak ada data transaksi bank payment.',
  },
};
